### ISSUE TITLE
Kernel config still prompts for P6_NOPS

### ISSUE THREAD

**Issue by Sukid** [Tk-Glitch/PKGBUILDS#100]
Just letting you know, the kernel customization config file is missing an option for X86_P6_NOPS and it still asks if you want to use P6_NOPS before it starts compiling. That's the only thing stopping it from being totally automatic though!
Thanks for that update by the way, now I can run the kernel compile automated after a bunch of other stuff I like to compile overnight.

**Comment by Tk-Glitch** [comment]
This will only happen if you set CONFIG_MNATIVE=y
I can't think of an elegant solution to that, except removing that mostly undesirable option maybe :smile: Maybe I should add some kind of warning about it.
Selecting your architecture instead will fix that :wink:

**Comment by Sukid** [comment]
Oh, ok! Will do that.

**Comment by ryanmusante** [comment]
Specifying architecture still causes the build to prompt me with selection, how do I force haswell?
``
_processor_opt="MHASWELL"
```

**Comment by Tk-Glitch** [comment]
Right now you can't automate that, that's the main reason @Sukid 's ticket was valid. Either you keep the default generic and don't get prompted, or set native and get prompted on top of having a possibly non-optimal optimization, or leave empty and get prompted with the ability to select the right optimization.
I'll make some kind of fix for that asap, I'm still thinking about my options.
