### ISSUE TITLE
PBA and DXUP are incompatible!

### ISSUE THREAD

**Issue by Kerrung** [Tk-Glitch/PKGBUILDS#101]
Compilation cannot be completed successfully and will end only with error messages if PBA and DXUP are enabled at the same time. Is it possible to switch so that when you turn on one of them, it would automatically turn off the other? Or at least write a warning about this in the description for both PBA and DXUP.
![screenshot from 2019-01-24 12-03-33](https://user-images.githubusercontent.com/36989404/51660608-1eafb100-1fd0-11e9-9e41-b5509a0db384.png)
![screenshot from 2019-01-24 12-02-48](https://user-images.githubusercontent.com/36989404/51660609-1eafb100-1fd0-11e9-8091-49d637d0a852.png)

Thank you!

**Comment by Tk-Glitch** [comment]
This is completely unrelated to PBA.
Here : https://github.com/Tk-Glitch/PKGBUILDS/issues/93

**Comment by Tk-Glitch** [comment]
The patch has been upstreamed
