### ISSUE TITLE
[Request/Discussion] proton-tkg

### ISSUE THREAD

**Issue by clapbr** [Tk-Glitch/PKGBUILDS#102]
Would be awesome to have a wine-tkg-like build for proton, main advantage is not needing the terrible Steam wine and using native Steam instead. I have been using this great fork (https://github.com/popsUlfr/Proton/releases/tag/proton-3.16-6-gne-0.1.1) for a few games and it works great so this idea came to mind. It looks very doable to port tkg improvements to a package and put it in ~/.local/share/Steam/compatibilitytools.d/ but I might be wrong.
It might be not worth the trouble or interesting for you so I'm opening this just to ask for your opinion.

**Comment by clapbr** [comment]
I hacked together wine-tkg directly into above project's proton folder and it works great. Being free of wine steam and using only native for everything is totally worth it. It's probably pretty straightforward to make a script to build it properly. I used these instructions https://github.com/ValveSoftware/Proton/issues/22#issuecomment-416060018 as reference.

**Comment by Tk-Glitch** [comment]
I didn't find the time to dive into it at this point, but adding such functionality has been on my list for some time now, just not a priority. Thanks for your findings and experimentation! I'll be working on implementing an option for it soon.

**Comment by Tk-Glitch** [comment]
Fixed in https://github.com/Tk-Glitch/PKGBUILDS/commit/3a4499099e1e683f8905b66ff1f51e60b486217b
