### ISSUE TITLE
Mechwarrior Online patch suggestion

### ISSUE THREAD

**Issue by ronoverdrive** [Tk-Glitch/PKGBUILDS#104]
Mechwarrior Online currently is using an outdated version of Boost that causes the game to crash at the login screen. This is a known issue on both WINE and Proton, however, ohartenstein23 on the MWO forums has come up with a [hack](https://mwomercs.com/forums/topic/268847-running-the-game-on-ubuntu-steam-play/page__view__findpost__p__6195387) to get the game to work. I have made a [patch](https://pastebin.com/nJP3cLkc) that works for me with your PKGBUILD and should be easy to implement if you care to do so.

**Comment by Tk-Glitch** [comment]
Thanks for your suggestion!
I have added the patch in https://github.com/Tk-Glitch/PKGBUILDS/commit/4e74aaf518d976429cdcb03254082425b13e8550
