### ISSUE TITLE
A request for MF

### ISSUE THREAD

**Issue by ahmed-elsayed2017** [Tk-Glitch/PKGBUILDS#106]
I found a fork from Proton/Wine that added some workarounds to run some games that need Windows Media Foundation. Could you consider adding it to your next releases or patches?

https://github.com/jzengc/wine/tree/proton_3.16_mf

**Comment by Tk-Glitch** [comment]
I've been made aware of this indeed. It's on my list :)

**Comment by ahmed-elsayed2017** [comment]
Thanks man, and sorry for wasting your time.

**Comment by ahmed-elsayed2017** [comment]
One more thing I forgot to mention, and I hope that you can help me with if you want to, but I don't know if it is appropriate to mention here!

I found a script for an application that can unpack all the files of re_chunk_000.pak of the game RE7 Biohazard, and I found all the videos that cause the problem.

The application gives the ability to unpack the files to be able to modify them and reimport them again instead of the original files, so I made files with the same name of the video files but with no data (0B), and I tried to import them again, but that didn't work!

**Comment by Tk-Glitch** [comment]
Considering deleting the videos didn't fix Shadows either, and that they were actually playable outside of the game, I have high doubts it's that simple.

**Comment by ahmed-elsayed2017** [comment]
If the files are deleted, it will give an error, and may not continue, but if the files are exist and the same size, but filled with zeros(empty). What will happen?!

**Comment by Tk-Glitch** [comment]
Depends on what the game is actually doing. This is out of my scope anyway :D

**Comment by ahmed-elsayed2017** [comment]
Ok thanks any way. I will try to figure it out.

**Comment by Tk-Glitch** [comment]
Good luck ! :)

**Comment by ahmed-elsayed2017** [comment]
Some people managed to run Resident Evil 2 Remake which has the same problem as Resident Evil 7 Biohazard, but they didn't mention what they did exactly

https://www.reddit.com/r/linux_gaming/comments/ajyx51/resident_evil_2_playable_with_the_latest_dxvk_and/

**Comment by Tk-Glitch** [comment]
Looks like jzengc is working on it. It's simply not there yet. We have to wait for the implementation to get more complete.

**Comment by ahmed-elsayed2017** [comment]
He did a lot of changes since last time I checked. Did you try the last changes?

I can't try it myself, because building always fails with me.
`fatal error: gnutls26/gnutls.h: No such file or directory`

**Comment by Tk-Glitch** [comment]
I did check. If it had been any different I'd have told you :wink:

**Comment by ahmed-elsayed2017** [comment]
Resident Evil 7 Biohazard works now

![screenshot_20190130_014143](https://user-images.githubusercontent.com/29783425/51948501-710a2b00-2431-11e9-9a71-11a2d5807430.png)

The modified script + mfplate:
[python-installcab-master.zip](https://github.com/Tk-Glitch/PKGBUILDS/files/2810218/python-installcab-master.zip)

**Comment by Tk-Glitch** [comment]
Nice!

**Comment by ahmed-elsayed2017** [comment]
I got banned from https://github.com/ValveSoftware/Proton for posting this fix! Should I deleted from here?!

**Comment by ahmed-elsayed2017** [comment]
I removed the dlls from the compressed file. It is legal now :D

**Comment by ahmed-elsayed2017** [comment]
Could you please change Winetricks PKGBUILD from `https://github.com/Winetricks/winetricks.git ` to more updated branch `https://github.com/austin987/winetricks.git`

I can't do it myself because it will fail in md5sums check.

**Comment by clapbr** [comment]
> Could you please change Winetricks PKGBUILD from `https://github.com/Winetricks/winetricks.git` to more updated branch `https://github.com/austin987/winetricks.git`
> 
> I can't do it myself but it will fail in md5sums, so could you change it and send me the modified file.

change it yourself and run updpkgsums in PKGBUILDs folder

**Comment by ahmed-elsayed2017** [comment]
> > Could you please change Winetricks PKGBUILD from `https://github.com/Winetricks/winetricks.git` to more updated branch `https://github.com/austin987/winetricks.git`
> > I can't do it myself but it will fail in md5sums, so could you change it and send me the modified file.
> 
> change it yourself and run updpkgsums in PKGBUILDs folder

Now, I get this error

> patching file src/winetricks
> Unreversed patch detected!  Skipping patch.
> 1 out of 1 hunk ignored -- saving rejects to file src/winetricks.rej
> ==> ERROR: A failure occurred in package().
>     Aborting...
>

**Comment by Tk-Glitch** [comment]
@ahmed-elsayed2017 In what way is it more updated? It's mostly old and deprecated stuff..

**Comment by ahmed-elsayed2017** [comment]
A lot of branch switch to this old brach. I don't know why!

I want this commit https://github.com/austin987/winetricks/commit/5d653bfd9f2282a1d77edd3e4ed71205be1c4894

**Comment by clapbr** [comment]
> @ahmed-elsayed2017 In what way is it more updated? It's mostly old and deprecated stuff..

there's mf branch with an extra patch, not sure if he's referring to it. btw @ahmed-elsayed2017 you also need to specify branch in PKGBUILD if thats the case. add #branch=mf to the end of the link

> Now, I get this error
> 
> > patching file src/winetricks
> > Unreversed patch detected!  Skipping patch.
> > 1 out of 1 hunk ignored -- saving rejects to file src/winetricks.rej
> > ==> ERROR: A failure occurred in package().
> > Aborting...

usually gets this when reapplying patches, check which one is it and comment the line. (line starts with patch -Np1)

**Comment by Tk-Glitch** [comment]
As @clapbr said :)
