### ISSUE TITLE
Nvidia prime faults on drivers in 400 series

### ISSUE THREAD

**Issue by ryanmusante** [Tk-Glitch/PKGBUILDS#112]
```
Asynchronous wait on fence NVIDIA:nvidia.prime:ce43 timed out (hint:intel_atomic_commit_ready+0x0/0x54 [i915])
````
It appears that there is a bug that plagues configurations with Prime/Prime Synchronization. I have encountered this trying each available 4XX driver. _The only way to avoid hard freezes is by reverting to what is the latest in 300 series,_ **396.54**. OR by disabling Prime Sync with:
```
xrandr --output eDP-1-1 --set 'PRIME Synchronization' '0'
```
I am not sure if it is only being triggered by vulkan applications or not. It seems to always occur when using DXVK+wine.

https://devtalk.nvidia.com/default/topic/1046736/linux/nvidia-415-27-nvidia-nvidia-prime-5ec2b-timed-out-issue-system-hang-/

https://devtalk.nvidia.com/default/topic/1046988/linux/asynchronous-wait-on-fence-nvidia-nvidia-prime/

My xorg is as follows:
```
~ >>> cat /etc/X11/xorg.conf.d/90-mhwd.conf                                                                          
Section "ServerLayout"
    Identifier "layout"
    Screen 0 "nvidia"
    Inactive "intel"
EndSection

Section "Screen"
    Identifier "nvidia"
    Device "nvidia"
EndSection

Section "Device"
    Identifier "nvidia"
    Driver "nvidia"
    BusID "PCI:1:0:0"
    Option "AllowEmptyInitialConfiguration" "1"
    Option "ConnectToAcpid" "0"
EndSection

Section "Screen"
    Identifier "intel"
    Device "intel"
EndSection

Section "Device"
    Identifier "intel"
    Driver "modesetting"
    BusID  "PCI:0:2:0"
    Option "AccelMethod" "none"
EndSection
```

**Comment by Leopard1907** [comment]
Yeah , i opened that timed out issue. That happens only when i quit from Witcher 3 and move my mouse cursor immediately.

If i wait for 10 seconds or so , that is not happening.

Though i don't understand what can TKG do about it? Clearly an Nvidia weirdness.

**Comment by ryanmusante** [comment]
Its not that TKG can do anything about it, this is more so to notify other users here of the immediate concern and see if they have come across possible workarounds.

**Comment by Leopard1907** [comment]
@ryanmusante

https://www.nvidia.com/Download/driverResults.aspx/145182/en-us

-Fixed a bug which could sometimes cause Vulkan applications to lock up the GPU when freeing large chunks of memory on systems with PRIME enabled.

**Comment by ryanmusante** [comment]
Testing 418.56.

**Comment by Tk-Glitch** [comment]
Definitely seems fixed on my side. What about you guys?

**Comment by Leopard1907** [comment]
Shamefully waiting for update to land in Graphics PPA 😂

**Comment by Tk-Glitch** [comment]
Harsh :smile:

**Comment by ryanmusante** [comment]
Civ5(wine) is running smooth now, no problems. I call it good.

**Comment by Leopard1907** [comment]
Also seems fixed on my end.
