### ISSUE TITLE
Unable to find dxvk patch

### ISSUE THREAD

**Issue by droidman** [Tk-Glitch/PKGBUILDS#113]
error
`~/PKGBUILDS/wine-tkg-git/PKGBUILD: line 919: ../dxvk-winelib.patch: No such file or directory`

**Comment by Tk-Glitch** [comment]
cd into `wine-tkg-git` before running makepkg ?

**Comment by droidman** [comment]
> cd into `wine-tkg-git` before running makepkg ?

I ended up using doing a git reset and it started working again.

**Comment by Tk-Glitch** [comment]
Weird. So that was just a failing git pull I guess?
