### ISSUE TITLE
Error when building Wine-TKG with Gallium-nine

### ISSUE THREAD

**Issue by ahmed-elsayed2017** [Tk-Glitch/PKGBUILDS#115]
I get this error when building Wine-TKG:

> 2019-02-10 18:40:50 (34.0 MB/s) - ‘~/PKGBUILDS/wine-tkg-git/staging-helper.patch’ saved [4288/4288]
> 
> patching file dlls/ntdll/loadorder.c
> Hunk #1 FAILED at 629.
> 1 out of 1 hunk FAILED -- saving rejects to file dlls/ntdll/loadorder.c.rej
> patching file programs/winecfg/resource.h
> patching file programs/winecfg/staging.c
> Hunk #1 succeeded at 133 with fuzz 1 (offset 12 lines).
> Hunk #2 succeeded at 157 (offset 12 lines).
> Hunk #3 succeeded at 165 (offset 12 lines).
> Hunk #4 succeeded at 213 (offset 12 lines).
> patching file programs/winecfg/winecfg.rc
> ==> ERROR: A failure occurred in prepare().
>     Aborting...

[customization.cfg.zip](https://github.com/Tk-Glitch/PKGBUILDS/files/2849131/customization.cfg.zip)

**Comment by Tk-Glitch** [comment]
Gallium nine patch needs a rebase against latest staging. Not my bug. Please leave this open until it's fixed for other people to be aware :)

**Comment by ahmed-elsayed2017** [comment]
There is another problem with latest wine build. Xbox 360 controller act so much weird with the latest wine build. When I move the right analog the camera moves sometimes to the right and sometimes to the left. This problem didn't exist with previous Wine versions. The game I tested was Neir Automata.

**Comment by ahmed-elsayed2017** [comment]
I want to build TKG version 4.0. What do I have to change in customization.cfg?

**Comment by Tk-Glitch** [comment]
First, I'm not responsible for upstream breaks :D I can fix or help fixing some stuff but I'm just a frog. I can only do so much. I'm providing a tool that can be used for debugging just as much as experimenting. If you want to help, check for open bugs on winehq and report your issue if needed with as much detail as possible.
For the second question, you want to touch either plain version (if you're planning to disable staging) or staging version. For example, in the case of staging, go there : https://github.com/wine-staging/wine-staging/releases and copy/paste the short commit of the release you want as staging version.

**Comment by ahmed-elsayed2017** [comment]
Thanks. I always report any problem that I encounter to Winehq whatever they answer it or not.

**Comment by Tk-Glitch** [comment]
Thank you :+1:

**Comment by ahmed-elsayed2017** [comment]
I hope they fix it in the next release.
https://bugs.winehq.org/show_bug.cgi?id=46623

**Comment by Tk-Glitch** [comment]
I've been sending a few patches around for testing purposes and, who knows.. I may have some temporary solution to provide in case it's not fixed before 4.2 release.

**Comment by ahmed-elsayed2017** [comment]
Nice work man.

I am sorry for asking some thing out of the topic, but every time I install something with Winetricks like dotnet or vcrun2017. It changes windows version to Windows XP instead of Windows 7, and when I try to install any 3rd part application, it refuse to install until I change Windows version to XP. Is there going to be any trouble using XP instead of 7 when running games?

**Comment by Tk-Glitch** [comment]
The switch was needed at some point at  least (not necessarily still the case, but winetricks is slow moving). Some games won't be okay with XP mode, some won't be okay without XP mode (Watch Dogs for example needs XP mode to output sound, and that makes little sense). In most cases however, you'll want to switch back to win7 after you're done winetricks'ing.

**Comment by ahmed-elsayed2017** [comment]
Thanks. I deleted my previous question to keep the comments relevant to the title.

**Comment by neVERberleRfellerER** [comment]
Another problem:
https://github.com/wine-staging/wine-staging/commit/c6aeba1397722b9ccb88f7c3bae68da84144bb35
. This means that Nine enabling has to be redone and unfortunately it seems, that per-app settings are no longer possible (with the exception of symlinking d3d9-nine.dll to game directory as d3d9.dll and settings d3d9 override to native, which is what I am doing).

**Comment by Tk-Glitch** [comment]
Sad day.
https://github.com/Tk-Glitch/PKGBUILDS/commit/1d9e75f2d0c44147b1c474c9cb3f0ca05e66b887

**Comment by ahmed-elsayed2017** [comment]
That is not good....

I will give dx912pxy a try.

**Comment by ahmed-elsayed2017** [comment]
Could you please leave it for the older releases?

**Comment by ahmed-elsayed2017** [comment]
They are trying to integrate DXVK into Wine https://github.com/doitsujin/dxvk/pull/926

And someone add building scripts for Fedora that build wine with Gallium Nine, VKD3D, and FAudio, and DXVK https://github.com/leonmaxx/wine-dxvk-rpm

**Comment by Tk-Glitch** [comment]
?

**Comment by ahmed-elsayed2017** [comment]
They are testing DXVK to be a part of future wine releases. I don't know if Fedora builds work or not because I don't use Fedora.

**Comment by Tk-Glitch** [comment]
We know each other with Guy1524, that wasn't my point. What does it have anything to do with that issue though?

**Comment by ahmed-elsayed2017** [comment]
It is wine 4.2 with Gallium Nine patches included. I didn't test it.

**Comment by Tk-Glitch** [comment]
If you are using the PKGBUILD you can test the patches, I did add userpatches support also for such cases.

**Comment by leonmaxx** [comment]
@ahmed-elsayed2017 If you're talking about Gallium-Nine in my build of Wine 4.2, I rebased patches myself, and tested them in `Star Wars: The Old Republic` and `AION`, and they are working with these games.

**Comment by ahmed-elsayed2017** [comment]
These patches don't work with TKG.
