### ISSUE TITLE
includes 🐸coin miner 

### ISSUE THREAD

**Issue by Joshua-Ashton** [Tk-Glitch/PKGBUILDS#116]
🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸

pls fix

it uses 100% of my physx dedicated card to mine frog coins

**Comment by Tk-Glitch** [comment]
Is your FROGPU overheating as a result?

**Comment by Joshua-Ashton** [comment]
yes it also has no thermal throttling so i used it to boil water and made tea

**Comment by Tk-Glitch** [comment]
So nice! Can I have some?

**Comment by Joshua-Ashton** [comment]
sure if u remove the frog miner from my pc 🐸🐸🐸🐸🐸🐸

**Comment by Tk-Glitch** [comment]
It's deleting itself on exit already, what more do you want? :frog: Wanna frog, is that it?

**Comment by Joshua-Ashton** [comment]
ok 😏  🐸
