### ISSUE TITLE
it make my benis smol

### ISSUE THREAD

**Issue by itmakesmybenisbigger** [Tk-Glitch/PKGBUILDS#118]
🐽🐽 oink of the morning to ya! 🐽🐽

🐷🐷🐷🐷🐷🐷🐷🐷

i tried to use it with simon cowell's latest instrument but it kept making my oinkers turn into iodine.

i poured turpentine on them but it only made them smell more. 💩

**Comment by Tk-Glitch** [comment]
omfg
