### ISSUE TITLE
Missing sims_2-fix-legacy.patch

### ISSUE THREAD

**Issue by neVERberleRfellerER** [Tk-Glitch/PKGBUILDS#119]
Build fails because sims_2-fix-legacy.patch is missing.

**Comment by julianovs** [comment]
same problem here

**Comment by openglfreak** [comment]
Temporary fix:
https://gist.github.com/openglfreak/f2b48eec12d4b04bbf334f4225650eea
Download to the PKGBUILDS folder, run it using a posix-compliant shell, build.
Works-On-My-Machine certified.

**Comment by Tk-Glitch** [comment]
The sims2 patch missing is fixed by 954a7ebbbffae693dea0a0c674009956d99e4e28
However staging builds will still fail because of upstream patches missing. I think it's the day of missing patches for everyone :smile:
