### ISSUE TITLE
Error when building latest Wine-TKG

### ISSUE THREAD

**Issue by ahmed-elsayed2017** [Tk-Glitch/PKGBUILDS#120]
Latest PKGBUILD gives me this error:
```
==> ERROR: sims_2-fix-legacy.patch was not found in the build directory and is not a URL.
  -> exit cleanup done
```
I removed **sims_2-fix-legacy.patch** manually from **PKGBUILD** then run **updpkgsums**, and it is building now.

**Comment by openglfreak** [comment]
duplicate of #119
