### ISSUE TITLE
Additional Kernel Optimizations?

### ISSUE THREAD

**Issue by ronoverdrive** [Tk-Glitch/PKGBUILDS#121]
[Phoronix posted an article today](https://www.phoronix.com/scan.php?page=news_item&px=Gentoo-CPU-Options-Kernel-2019) on a [patch that added additional CPU optimizations](https://github.com/graysky2/kernel_gcc_patch)  from Gentoo that are suppose to add small, but noticeable performance gains. Was wondering if these were already in your kernel or what you thought about them?

**Comment by clapbr** [comment]
It is used here already

**Comment by Tk-Glitch** [comment]
And it's been there for a long time :frog:
