### ISSUE TITLE
Winegcc can't build DXVK

### ISSUE THREAD

**Issue by Kerrung** [Tk-Glitch/PKGBUILDS#123]
![screenshot from 2019-02-26 22-54-06](https://user-images.githubusercontent.com/36989404/53435195-1658f480-3a1a-11e9-9280-1149640fdaa2.png)

**Comment by Tk-Glitch** [comment]
The issue is clang actually. If you build wine with clang or zapcc, winegcc will currently break.

**Comment by Kerrung** [comment]
@Tk-Glitch This started after I tried using clang. But as soon as I got this compilation error, I switched back to gcc, then I restarted the compilation, but unfortunately, this did not solve the issue.

**Comment by Tk-Glitch** [comment]
Because DXVK will build against your currently installed wine. So you'll have to first rebuild without DXVK, with GCC, to then be able to build with DXVK again. You could also install wine 4.2 from Arch repos instead of rebuilding without DXVK first. Hopefully I'm clear enough.

**Comment by Kerrung** [comment]
Your advice helped me, thank you.
