### ISSUE TITLE
[FEATURE REQUEST] D9VK support, please

### ISSUE THREAD

**Issue by Kerrung** [Tk-Glitch/PKGBUILDS#124]
[D9VK Forming As Direct3D 9 Over Vulkan Based On DXVK](https://www.phoronix.com/scan.php?page=news_item&px=D9VK-D3D9-Vulkan-From-DXVK).

Joshua Ashton, the developer who had been working on "DXUP" as a Direct3D 9/10 to D3D11 translation layer so that the output could be fed to DXVK for running on Vulkan is now developing the "D9VK" project. 

D9VK is a fork of the DXVK code-base adding Direct3D 9 to Vulkan support directly. Two days ago he began committing his work [to the D9VK repository on GitHub](https://www.phoronix.com/scan.php?page=news_item&px=D9VK-D3D9-Vulkan-From-DXVK) The DXVK code-base is based on the v1.0 state of the project with so far having a few dozen patches on top for working out the initial Direct3D 9 bits. It's unclear if this is intended as a temporary fork or if ultimately the plan will be to try to merge back with DXVK, assuming upstream is interested. 

Joshua's DXUP repository meanwhile hasn't been touched in about a month, so D9VK would seem to be his new primary focus. 

This all comes while CodeWeavers has expressed interest recently in adding Vulkan support to WineD3D albeit at least as of a few weeks ago not engaging with DXVK. 

It will be interesting to see where D9VK heads though at its stage today doesn't appear to be yet ready for primetime in handling Direct3D 9 Windows games though given the rate of these Direct3D-over-Vulkan translation layers I wouldn't be surprised if it's working well soon, especially with D9VK being based on the already mature DXVK code-base. Exciting times ahead for GNU/Linux gamers!

**Comment by Tk-Glitch** [comment]
Josh is part of the frog family, and actually one of my moderators. You can be sure D9VK will be part of wine-tkg as soon as it makes sense. It's not the case at this point.

**Comment by Joshua-Ashton** [comment]
^ this

**Comment by Kerrung** [comment]
Thank you!
Close because 5509baba9ac81e45adcbeadb6d56a9814574b60c, but my games don't working at this moment.
