### ISSUE TITLE
Build 4.3 FAudio with WMA support

### ISSUE THREAD

**Issue by t14462** [Tk-Glitch/PKGBUILDS#125]
Build 4.3 FAudio with WMA support, because in Fallout 4 I can't hear anything. All events just silent because of WMA, which unsupported without some building flags.

So I using winetricks --force faudio, insteasd of builtin faudio.

**Comment by Tk-Glitch** [comment]
You have to build Faudio (with or without WMA support is up to you). It's not builtin, it's an external lib.

**Comment by goldpaw** [comment]
Not to necro here, and I might have misunderstood something, but isn't Faudio builtin since wine development 4.3? 

https://www.winehq.org/announce/4.3 
"Reimplementation of XAudio2 using the FAudio library."

**Comment by Tk-Glitch** [comment]
@goldpaw  Well, it isn't. As an external library (and thus, an optional dependency), you'll need to either install the Faudio packages your distro provides (good luck with that right now) or build that by yourself. If you install Wine 4.3 as is without Faudio libs, you won't have sound on xaudio2-dependent apps anymore.

Wine-staging maintainers decided to instead revert Faudio support implementation altogether until most distros are providing Faudio packages: https://github.com/wine-staging/wine-staging/commit/f419a53698ed34dc12ad598d8bc342fc7840117f

**Comment by goldpaw** [comment]
Ah, I see! :)
