### ISSUE TITLE
Failed license link in lib32-nvidia-utils-tkg

### ISSUE THREAD

**Issue by Sporif** [Tk-Glitch/PKGBUILDS#126]
It's a very minor thing, but on line 611 of the `nvidia-all` PKGBUILD:

```
ln -s $_pkgbasename "${pkgdir}/usr/share/licenses/${pkgname}"
```
`$_pkgbasename` is not set, so the link is not made. It should be:

```
ln -s nvidia-utils "${pkgdir}/usr/share/licenses/${pkgname}"
```

like it is for `lib32-opencl-nvidia-tkg`

**Comment by Tk-Glitch** [comment]
Nice find!
