### ISSUE TITLE
Can't build with enabled faudio

### ISSUE THREAD

**Issue by soredake** [Tk-Glitch/PKGBUILDS#127]
```
checking for -lFAudio... not found
configure: error: libFAudio 32-bit development files not found, XAudio2 won't be supported.
This is an error since --with-faudio was requested.
```
Both lib32-faudio-git and faudio-git are installed.

**Comment by Tk-Glitch** [comment]
Some people are encountering that indeed.. And it's not limited to Faudio. lib32-x265 seems to be an issue as well. I'm glad I've used --with-faudio here so you guys are aware your libs are frogged. If you don't care about 32-bit support, you can comment out line #461 (`_configure_args+=(--with-faudio)`) to ignore the problem.
However this is not my bug and it just reveals that something in the lib32 chain (not necessarily the lib32-faudio package itself) is broken.

Please keep the issue open for now, thanks.

**Comment by soredake** [comment]
Interesting, configure can find library on 4.2 version, so something is broken on 4.3n

**Comment by Tk-Glitch** [comment]
I can't reproduce it for whatever reason. That's interestingly weird though.. I'll review the current 4.3 implementation.

**Comment by soredake** [comment]
4.3 has way more complicated code https://www.diffchecker.com/AkCR3rr3

**Comment by SveSop** [comment]
4.2 Used XAudio2 -> OpenAL, while 4.3 uses XAudio2 -> FAudio (libfaudio).
You must have libfaudio and libfaudio-dev to build wine-4.3

**Comment by Tk-Glitch** [comment]
@SveSop Yes but even with the libs installed, some people have been encountering issues to get them recognized on 4.3, and it's usually breaking only on the lib32 side for whatever reason. I'm still unable to reproduce it, sadly.

**Comment by SveSop** [comment]
@Tk-Glitch im on Ubuntu, so when building wine i use lxc for the 32-bit part, and have had no problems there. Possibly depends on distro i guess, as not many have libfaudio atm.
I made a PPA for libaudio and SDL2-2.0.9 backported to Bionic and Cosmic here: [https://launchpad.net/~cybermax-dexter/+archive/ubuntu/sdl2-backport](https://launchpad.net/~cybermax-dexter/+archive/ubuntu/sdl2-backport) incase someone on *buntu wanna give it a shot.

**Comment by Tk-Glitch** [comment]
Definitely distro-specific, yes

**Comment by mogorva** [comment]
I'd check if there are broken/missing dependencies in the 32-bit libFaudio.so library:
`ldd -v libFAudio.so`

**Comment by Tk-Glitch** [comment]
I was able to get a log from someone affected:
```
/usr/bin/ld: warning: libvpx.so.5, needed by /usr/lib32/libavcodec.so.58, not found (try using -rpath or -rpath-link)
/usr/bin/ld: /usr/lib32/libavcodec.so.58: undefined reference to `vpx_codec_get_caps'
/usr/bin/ld: /usr/lib32/libavcodec.so.58: undefined reference to `vpx_codec_version_str'
/usr/bin/ld: /usr/lib32/libavcodec.so.58: undefined reference to `vpx_codec_control_'
/usr/bin/ld: /usr/lib32/libavcodec.so.58: undefined reference to `vpx_codec_decode'
/usr/bin/ld: /usr/lib32/libavcodec.so.58: undefined reference to `vpx_codec_vp8_dx_algo'
/usr/bin/ld: /usr/lib32/libavcodec.so.58: undefined reference to `vpx_codec_destroy'
/usr/bin/ld: /usr/lib32/libavcodec.so.58: undefined reference to `vpx_codec_vp9_cx'
/usr/bin/ld: /usr/lib32/libavcodec.so.58: undefined reference to `vpx_codec_error_detail'
/usr/bin/ld: /usr/lib32/libavcodec.so.58: undefined reference to `vpx_codec_enc_config_default'
/usr/bin/ld: /usr/lib32/libavcodec.so.58: undefined reference to `vpx_codec_encode'
/usr/bin/ld: /usr/lib32/libavcodec.so.58: undefined reference to `vpx_codec_error'
/usr/bin/ld: /usr/lib32/libavcodec.so.58: undefined reference to `vpx_codec_get_cx_data'
/usr/bin/ld: /usr/lib32/libavcodec.so.58: undefined reference to `vpx_codec_vp9_dx_algo'
/usr/bin/ld: /usr/lib32/libavcodec.so.58: undefined reference to `vpx_codec_build_config'
/usr/bin/ld: /usr/lib32/libavcodec.so.58: undefined reference to `vpx_codec_err_to_string'
/usr/bin/ld: /usr/lib32/libavcodec.so.58: undefined reference to `vpx_codec_get_frame'
/usr/bin/ld: /usr/lib32/libavcodec.so.58: undefined reference to `vpx_codec_vp8_cx'
/usr/bin/ld: /usr/lib32/libavcodec.so.58: undefined reference to `vpx_codec_dec_init_ver'
/usr/bin/ld: /usr/lib32/libavcodec.so.58: undefined reference to `vpx_img_wrap'
/usr/bin/ld: /usr/lib32/libavcodec.so.58: undefined reference to `vpx_codec_enc_init_ver'
collect2: error: ld returned 1 exit status
```
So something is frogged in the lib32 deps. I'll  try to come up with the best solution for everyone.

**Comment by Tk-Glitch** [comment]
Or not.. It seems rebuilding lib32-ffmpeg against the newest libvpx lib then rebuilding Faudio afterwards fixed it for him. Maybe worth a try for the ones affected ?

**Comment by soredake** [comment]
After lib32-ffmpeg rebuild i built wine two time without errors.

**Comment by Tk-Glitch** [comment]
I'll consider that as fixed upstream. Will reopen if needed :frog:

**Comment by Kerrung** [comment]
@Tk-Glitch Today I first encountered this issue on Arch Linux:
![Screenshot from 2019-03-13 11-59-55](https://user-images.githubusercontent.com/36989404/54259813-c8e79600-4588-11e9-86ec-646cad011384.png)

![Screenshot from 2019-03-13 12-10-24](https://user-images.githubusercontent.com/36989404/54259885-02200600-4589-11e9-9767-e9ddd5e78076.png)

**Comment by Kerrung** [comment]
[customization.zip](https://github.com/Tk-Glitch/PKGBUILDS/files/2960172/customization.zip)

@Tk-Glitch Today I first encountered this issue on Arch Linux:
![Screenshot from 2019-03-13 11-59-55](https://user-images.githubusercontent.com/36989404/54259813-c8e79600-4588-11e9-86ec-646cad011384.png)

![Screenshot from 2019-03-13 12-10-24](https://user-images.githubusercontent.com/36989404/54259885-02200600-4589-11e9-9767-e9ddd5e78076.png)

**Comment by openglfreak** [comment]
Same here.
It looks like an upstream bug, but I haven't tested that theory yet.

**Comment by Tk-Glitch** [comment]
@Kerrung @openglfreak 
If you haven't recompiled lib32-ffmpeg since the 11th of march, then recompiled Faudio (both packages), that's the first thing to do.
If that doesn't fix it, please attach your config.log file found in `PKGBUILDS/wine-tkg-git/src/wine-tkg-*-32-build` after a failed attempt.

**Comment by Kerrung** [comment]
[wine-tkg-git-32-config-log.zip](https://github.com/Tk-Glitch/PKGBUILDS/files/2961350/wine-tkg-git-32-config-log.zip)
I recompiled both 32 and 64 faudio just today, but it did not help.

**Comment by Tk-Glitch** [comment]
@Kerrung 
How fancy..
```
/usr/bin/ld: warning: libvpx.so.5, needed by /usr/lib32/libavcodec.so.58, not found (try using -rpath or -rpath-link)
/usr/bin/ld: /usr/lib32/libavcodec.so.58: undefined reference to `vpx_codec_get_caps'
/usr/bin/ld: /usr/lib32/libavcodec.so.58: undefined reference to `vpx_codec_version_str'
/usr/bin/ld: /usr/lib32/libavcodec.so.58: undefined reference to `vpx_codec_control_'
/usr/bin/ld: /usr/lib32/libavcodec.so.58: undefined reference to `vpx_codec_decode'
/usr/bin/ld: /usr/lib32/libavcodec.so.58: undefined reference to `vpx_codec_vp8_dx_algo'
/usr/bin/ld: /usr/lib32/libavcodec.so.58: undefined reference to `vpx_codec_destroy'
/usr/bin/ld: /usr/lib32/libavcodec.so.58: undefined reference to `vpx_codec_vp9_cx'
/usr/bin/ld: /usr/lib32/libavcodec.so.58: undefined reference to `vpx_codec_error_detail'
/usr/bin/ld: /usr/lib32/libavcodec.so.58: undefined reference to `vpx_codec_enc_config_default'
/usr/bin/ld: /usr/lib32/libavcodec.so.58: undefined reference to `vpx_codec_encode'
/usr/bin/ld: /usr/lib32/libavcodec.so.58: undefined reference to `vpx_codec_error'
/usr/bin/ld: /usr/lib32/libavcodec.so.58: undefined reference to `vpx_codec_get_cx_data'
/usr/bin/ld: /usr/lib32/libavcodec.so.58: undefined reference to `vpx_codec_vp9_dx_algo'
/usr/bin/ld: /usr/lib32/libavcodec.so.58: undefined reference to `vpx_codec_build_config'
/usr/bin/ld: /usr/lib32/libavcodec.so.58: undefined reference to `vpx_codec_err_to_string'
/usr/bin/ld: /usr/lib32/libavcodec.so.58: undefined reference to `vpx_codec_get_frame'
/usr/bin/ld: /usr/lib32/libavcodec.so.58: undefined reference to `vpx_codec_vp8_cx'
/usr/bin/ld: /usr/lib32/libavcodec.so.58: undefined reference to `vpx_codec_dec_init_ver'
/usr/bin/ld: /usr/lib32/libavcodec.so.58: undefined reference to `vpx_img_wrap'
/usr/bin/ld: /usr/lib32/libavcodec.so.58: undefined reference to `vpx_codec_enc_init_ver'
collect2: error: ld returned 1 exit status
```
Exact same error as above. lib32-ffmpeg != faudio

**Comment by Kerrung** [comment]
![Screenshot from 2019-03-13 12-10-24](https://user-images.githubusercontent.com/36989404/54259885-02200600-4589-11e9-9767-e9ddd5e78076.png)


![Screenshot from 2019-03-13 18-56-41](https://user-images.githubusercontent.com/36989404/54284457-c6556280-45c1-11e9-857f-362832523b0a.png)

@Tk-Glitch which package should I install?

**Comment by Tk-Glitch** [comment]
You need to rebuild lib32-ffmpeg

**Comment by Kerrung** [comment]
I recompiled lib32-ffmpeg and it helped me solve this issue. Thank you, now it is fixed.

**Comment by Tk-Glitch** [comment]
Good :)

**Comment by random2324** [comment]
Stumbled about the same problem again. Rebuild lib32-ffmpeg fixed it too but why?

**Comment by Tk-Glitch** [comment]
Some packages got updated, breaking some dependencies (I think it was x265 libs). Rebuilding fixes it because you're building against those updated packages. That's usually the work of maintainers but well.. Since we have to depend on an AUR package for that one we're stuck managing it ourselves unless it makes a comeback in Arch repos.
