### ISSUE TITLE
amdgpu: Failed to allocate a buffer

### ISSUE THREAD

**Issue by ahmed-elsayed2017** [Tk-Glitch/PKGBUILDS#134]
The Walking Dead - Season 1 gives me this error, and loops forever:

amdgpu: Failed to allocate a buffer:
amdgpu:    size      : 1717989376 bytes
amdgpu:    alignment : 4096 bytes
amdgpu:    domains   : 2

I can't report this bug to winehq, because it only happens with Wine-TKG.

This issue didn't happen with Wine-TKG-4.2, it only happenes with Wine-TKG-4.4, and I don't know if it happens with Wine-staging-4.4, because the latest version available on Manjaro is 4.2

**Comment by Laaas** [comment]
What GPU are you using? Something probably just causes wine-tkg to use more VRAM than vanilla wine

**Comment by Tk-Glitch** [comment]
Looks like an upstream regression. You can build a clean wine-staging with wine-tkg-git using `_LOCAL_PRESET="staging"` to see how it goes, but I'm pretty sure you'll have the same behavior.

**Comment by ahmed-elsayed2017** [comment]
> Looks like an upstream regression. You can build a clean wine-staging with wine-tkg-git using `_LOCAL_PRESET="staging"` to see how it goes, but I'm pretty sure you'll have the same behavior.

That will build Wine-staging without Esync, and all the patches?

**Comment by Tk-Glitch** [comment]
Yes, that will build a pure wine-staging build

**Comment by ahmed-elsayed2017** [comment]
It is a regression with Wine. I don't know if it is a regression with Wine 4.3 or 4.4. I will have to test Wine 4.3 also, and do a regression testing which I didn't do before.

**Comment by Tk-Glitch** [comment]
Thanks for the confirmation!

**Comment by ahmed-elsayed2017** [comment]
It is a regression with Wine-staging 4.3, it runs ok with Wine-development 4.4. I reported a bug in Winehq. Sorry for bothering you.

**Comment by Tk-Glitch** [comment]
No problem, that wasn't a bad decision. Wine-tkg can definitely regress just as much as plain or staging would, and independently of them. "Bothering" me with an issue encountered with wine-tkg with no existing bug report on winehq sounds okay to me :smiley:

**Comment by ahmed-elsayed2017** [comment]
Thanks man, you are the best.
