### ISSUE TITLE
[Recomendation/Joke] Icon needs more weeb

### ISSUE THREAD

**Issue by ronoverdrive** [Tk-Glitch/PKGBUILDS#136]
Both Joshua and Doitsujin have anime girl icons. I think its about time you completed the WINE gaming trinity here. Recommend something with a frog like this: https://static.zerochan.net/Moriya.Suwako.full.1849648.jpg

**Comment by doitsujin** [comment]
I approve. That would immediately make this place more welcoming.

**Comment by varris1** [comment]
frogs > weebs

**Comment by rphsoftware** [comment]
I'm highly **against** this suggestion. I feel like TkG is the only remaining glimpse of professionalism in the Wine development area. Y'all filthy weebs should be ashamed :frog:

**Comment by varris1** [comment]
🐸

**Comment by sambow23** [comment]
1+ for the weeb picture

**Comment by ryanmusante** [comment]
I actually live in Japan.

**Comment by Tk-Glitch** [comment]
I have decided to address the issue in a moderate way. What do you think?

**Comment by Laaas** [comment]
This is great. I think you can close this issue now. :frog:

**Comment by Joshua-Ashton** [comment]
frog weebs rise up

**Comment by ronoverdrive** [comment]
The trifecta is complete. ;P

**Comment by clapbr** [comment]
all praise the almighty gamabunta-sama
