### ISSUE TITLE
Fix for Escape from Tarkov launcher, Heartstone Deck Tracker and possibly others

### ISSUE THREAD

**Issue by Faalagorn** [Tk-Glitch/PKGBUILDS#137]
I originally planned to do a proper pull request with the fix and can still do it if needed, as I have that fix running locally, but in the end I thought I'll leave it up to @Tk-Glitch to include or not, including the naming of the fix and content of the comments, as I use it to fix Escape from Tarkov  exclusively (so I named it just `eft.patch` for me) but it originally came from Heartstone Deck Tracker and probably fixes other (.NET) apps as well.

Basically, the patch from [this comment](https://bugs.winehq.org/show_bug.cgi?id=46865#c3), when applied to wine-staging https://github.com/wine-staging/wine-staging/commit/b02bd9c4465d24203d849d1c43def56d6596609c or higher (including most recent https://github.com/wine-staging/wine-staging/commit/8e6af31b99ec5186ad8d272ea2c6c4fcf132b034 as of writing) fixes the issue with black windows and hopefully the auto-update too.

It might be worth including for now, but I guess the proper fix will come to wine-staging soon too, as that was the author of the original patch that created that fix.

**Comment by Tk-Glitch** [comment]
If it's not added in the next staging patch wave, I'll add it. Nice that you found out :)

**Comment by Tk-Glitch** [comment]
As more or less expected, the patch was merged into staging https://github.com/wine-staging/wine-staging/commit/055e049821455efccd4eda554d8a49d09515eedf
Closing :)
