### ISSUE TITLE
Need remove "_update_winevulkan" patch, because Wine has landed the necessary patches for Vulkan 1.1 support.

### ISSUE THREAD

**Issue by Kerrung** [Tk-Glitch/PKGBUILDS#138]
Need remove "_update_winevulkan" patch, because compilation error.
https://www.phoronix.com/scan.php?page=news_item&px=Wine-Vulkan-1.1-Milestone
![Screenshot from 2019-03-21 15-51-00](https://user-images.githubusercontent.com/36989404/54747621-392d9180-4bf1-11e9-9dc8-0aa50cd368ca.png)

**Comment by Tk-Glitch** [comment]
What commit are you building?

**Comment by Kerrung** [comment]
48fdc2f35637585f1e5dcfe6d3852cb267a48a1b

**Comment by Tk-Glitch** [comment]
I was talking about the wine commit, sorry

**Comment by Kerrung** [comment]
The latest git, of course

**Comment by Tk-Glitch** [comment]
That makes no sense then. Not only can't I reproduce it, but the patch will only apply if the commit breaking it is not found in your tree, meaning the patch is ignored on latest master.

**Comment by Tk-Glitch** [comment]
Can you post the content of your last_build_config.log file please?

**Comment by Kerrung** [comment]
[last_build_config.log](https://github.com/Tk-Glitch/PKGBUILDS/files/2991757/last_build_config.log)

**Comment by Tk-Glitch** [comment]
As expected, the patch wasn't applied and your issue is thus unrelated :frog:

**Comment by Kerrung** [comment]
_update_winevulkan="false", but a compilation error happens anyway.

**Comment by Kerrung** [comment]
I will try the newest wine-tkg-git commit and write to you what my result is.

**Comment by Tk-Glitch** [comment]
I would be surprised if it was any different as there has been no change related to this. Make sure you aren't applying a userpatch that would conflict, and maybe nuke the wine-git/wine-staging-git dirs

**Comment by Tk-Glitch** [comment]
I have noticed something weird. Your log mentions that you are building 4.4.r113.g3d0cf846f9 plain with 4.4.r6.gf2b1d2dc staging. But 4.4.r6.gf2b1d2dc staging was rebased against 4.4.r90.g42683dd159 plain, not 4.4.r113.g3d0cf846f9.

**Comment by Tk-Glitch** [comment]
The issue actually happens because of the proton FS hack patch against the current plain wine master. I will push a fix for it shortly, but that doesn't explain why you got the wrong plain base for staging master, unless you have commented the `git checkout "$(../"$_stgsrcdir"/patches/patchinstall.sh --upstream-commit)"` line in the PKGBUILD.

**Comment by Kerrung** [comment]
I have commented the git checkout "$(../"$_stgsrcdir"/patches/patchinstall.sh --upstream-commit)" line in the PKGBUILD.

**Comment by Tk-Glitch** [comment]
Huh, ok. That explains it then.

**Comment by Kerrung** [comment]
Thank you very much!

**Comment by Tk-Glitch** [comment]
:)
