### ISSUE TITLE
Staging patch ddraw-version-check fails to patch on latest git

### ISSUE THREAD

**Issue by ronoverdrive** [Tk-Glitch/PKGBUILDS#140]
```
Applying /home/ronoverdrive/PKGBUILDS/wine-tkg-git/src/wine-staging-git/patches/ddraw-version-check/0001-ddraw-Return-correct-devices-based-off-requested-Dir.patch
error: patch failed: dlls/ddraw/ddraw.c:47
error: dlls/ddraw/ddraw.c: patch does not apply
ERROR: Failed to apply patch, aborting!
==> ERROR: A failure occurred in prepare().
    Aborting...
removed '/home/ronoverdrive/PKGBUILDS/wine-tkg-git/BIG_UGLY_FROGMINER'
  -> exit cleanup done
```
Looks like Staging needs a rebase.

**Comment by Tk-Glitch** [comment]
I have reported the issue : https://github.com/wine-staging/wine-staging/commit/5bc795f9f6a33ef95774b4a282cbf82e035c22df#comments

In the meantime, you can use the attached hotfix patch (to decompress and put in your wine-tkg-userpatches dir).
[staging-4.4.r7.g5bc795f9-hotfix.mypatch.tar.gz](https://github.com/Tk-Glitch/PKGBUILDS/files/2994755/staging-4.4.r7.g5bc795f9-hotfix.mypatch.tar.gz)

Let's keep this open until it's fixed upstream.

**Comment by Tk-Glitch** [comment]
Fixed upstream! :smiley:  https://github.com/wine-staging/wine-staging/commit/dec3f8a3709bd50fa28eabb99c182fc95c6d80ed
