### ISSUE TITLE
Might & Magic VII: Heroes - incorrect resolution in game only when Proton Fullscreen patch is in use.

### ISSUE THREAD

**Issue by Kerrung** [Tk-Glitch/PKGBUILDS#148]
This started to happen after one recent update, but before that it worked fine.
![Screenshot from 2019-03-28 00-56-55](https://user-images.githubusercontent.com/36989404/55108492-892abd80-50f5-11e9-967d-09c9a00d95e6.png)

**Comment by Tk-Glitch** [comment]
This is with wine-tkg-git and not proton-tkg, right?

**Comment by Kerrung** [comment]
wine-tkg-git

**Comment by Tk-Glitch** [comment]
So it's either https://github.com/Tk-Glitch/PKGBUILDS/commit/1752ecf402aae81df0a3f897b550b85c192b67b6#diff-11c43e0c590912399e800f757206cab0 or https://github.com/Tk-Glitch/PKGBUILDS/commit/d82883beeb4d7c519e7bfd5bf9541e89e6c583ea#diff-11c43e0c590912399e800f757206cab0

If you can test both and say which one breaks it that would help tremendously. I don't have that game and so far none of the games I've been playing or testing with have shown anything similar.

**Comment by Kerrung** [comment]
And how can I compile a specific wine-tkg-git commit?

**Comment by Tk-Glitch** [comment]
For such a case, I think the easiest way would be to disable the proton fs hack from your config, and apply the patches with the userpatches feature.

Here is the raw file for the first commit : https://raw.githubusercontent.com/Tk-Glitch/PKGBUILDS/1752ecf402aae81df0a3f897b550b85c192b67b6/wine-tkg-git/wine-tkg-patches/valve_proton_fullscreen_hack-staging.patch

And here the raw file for the second commit (the more recent) : https://raw.githubusercontent.com/Tk-Glitch/PKGBUILDS/d82883beeb4d7c519e7bfd5bf9541e89e6c583ea/wine-tkg-git/wine-tkg-patches/valve_proton_fullscreen_hack-staging.patch

Give them obvious names like "proton_fs_hack_old.mypatch" and "proton_fs_hack_new.mypatch", and drop the first one in the userpatches folder, build with it, test, write down the result, then do the same for the second one.

The process should be pretty smooth that way I guess.

**Comment by Kerrung** [comment]
I tested it with proton_fs_hack_old.mypatch and there is result:
![Screenshot from 2019-03-28 14-44-52](https://user-images.githubusercontent.com/36989404/55148105-6afea500-5169-11e9-81c8-e3b8e61813ea.png)

And then should I test it with proton_fs_hack_new.mypatch ?

**Comment by Kerrung** [comment]
@Tk-Glitch also I tested with proton_fs_hack_new.mypatch and it turned out that if I apply it separately, without proton_fs_hack_old.mypatch, then it works well:
![Screenshot from 2019-03-28 16-11-03](https://user-images.githubusercontent.com/36989404/55153607-b10d3600-5174-11e9-921f-a8f51dc195dc.png)

**Comment by Tk-Glitch** [comment]
Yeah you can't apply them one on each other, it's one or the other. However it makes little sense.. The newer patch literally contains the older one. Were the wine versions the same? Can you still reproduce it while using latest master (without the staging override) and the usual proton fs hack option turned on (so without these .mypatch files) ?

**Comment by Kerrung** [comment]
so, ok, I will try that you said

**Comment by Kerrung** [comment]
@Tk-Glitch I tested that you said, and it works fine with this config:
[last_build_config.zip](https://github.com/Tk-Glitch/PKGBUILDS/files/3019402/last_build_config.zip)

But I don’t know if I understood you completely correctly, what exactly I should have done, because English is not my first language, but I hope that I did exactly what you asked me to do.

**Comment by Tk-Glitch** [comment]
Got access to the game. I can't reproduce your issue on current master :
![Screenshot_20190328_182232](https://user-images.githubusercontent.com/741977/55178876-904ddc00-5186-11e9-83d5-8480f30ece44.png)

So it might have been an upstream regression that's fixed since.

**Comment by Kerrung** [comment]
@Tk-Glitch I tested that you said, and it works fine with this config:
[last_build_config.zip](https://github.com/Tk-Glitch/PKGBUILDS/files/3019402/last_build_config.zip)

But I don’t know if I understood you completely correctly, what exactly I should have done, because English is not my first language, but I hope that I did exactly what you asked me to do.

**Comment by Tk-Glitch** [comment]
English isn't my first language either :frog: 
I think you got it right :wink:

**Comment by Kerrung** [comment]
Thank you!
