### ISSUE TITLE
Extra path segment in PBA317+ patch results in patches not being applied

### ISSUE THREAD

**Issue by neVERberleRfellerER** [Tk-Glitch/PKGBUILDS#15]
Extra path segment here
https://github.com/Tk-Glitch/PKGBUILDS/blob/72d70a089e0a5e883a65f4a629443f743a3f8a02/wine-tkg-git/PBA317%2B.patch#L37
(the /wine-tkjg-git/) together with
https://github.com/Tk-Glitch/PKGBUILDS/blob/accf7d9a801fd6d3c4dc0b8275398856580de894/wine-tkg-git/PKGBUILD#L515
results in patches being extracted into wrong directory that is not globbed by
https://github.com/Tk-Glitch/PKGBUILDS/blob/accf7d9a801fd6d3c4dc0b8275398856580de894/wine-tkg-git/PKGBUILD#L522
and thus patches are not applied.
Even when segment is stripped, patches do not apply due to conflict

**Comment by Tk-Glitch** [comment]
Thanks for the report. I'll fix that asap.

**Comment by neVERberleRfellerER** [comment]
It is indeed fixed. Thank your very much.
