### ISSUE TITLE
64-bit dxvk doesn't build with _NOLIB32="false" and _use_dxvk="true"

### ISSUE THREAD

**Issue by cyro666** [Tk-Glitch/PKGBUILDS#150]
Not sure if this is exactly what's going on, but the PKGBUILDS/wine-tkg-git/src/dxvk/build/dxvk-master/x64/ directory is empty when building everything from scratch (fresh copy/git clone for everything). This then fails the build in the package step:
![build_fail](https://user-images.githubusercontent.com/13151680/55274504-825ca000-52d9-11e9-8f0d-1f47c977f0b3.png)

This is my customization.cfg:
[customization.cfg.zip](https://github.com/Tk-Glitch/PKGBUILDS/files/3025321/customization.cfg.zip)

**Comment by Tk-Glitch** [comment]
Not sure exactly what's going on either. I can't reproduce your issue. It seems DXVK 64-bit fails to build for you. If you could get a shot of the DXVK breakage itself that would be of great help.

**Comment by Tk-Glitch** [comment]
There's this https://github.com/doitsujin/dxvk/issues/970 but 32-bit would also fail I guess..

**Comment by cyro666** [comment]
It does seem to be a problem with compiling dxvk 64-bit. I guess it would be good if there was a check for (un)successful compilation of dxvk. In any case I found the issue: 
![dxvk](https://user-images.githubusercontent.com/13151680/55279045-26fbd380-5314-11e9-8085-b56af47b8d7e.png)

any idea how to fix this?

**Comment by cyro666** [comment]
I have the full vulkan-devel group of packages installed, so not really sure how I could be missing a vulkan library.

**Comment by Tk-Glitch** [comment]
What's your current wine version installed ?

**Comment by cyro666** [comment]
Turns out I had wine-staging-nine-4.1-1, so I installed wine-staging from the official Arch repos. That gave me 4.4... But still the same issue.

**Comment by Tk-Glitch** [comment]
Do `/usr/lib/wine/vulkan-1.dll.so` exists on your system? I'd be surprised if you needed `vulkan-icd-loader` but I think I have added that deps anyway for runtime.

**Comment by cyro666** [comment]
/usr/lib/wine/fakedlls/winevulkan.dll
/usr/lib/wine/fakedlls/vulkan-1.dll
/usr/lib/wine/libwinevulkan.def
/usr/lib/wine/vulkan-1.dll.so
/usr/lib/wine/libvulkan-1.def
/usr/lib/wine/winevulkan.dll.so

This is the result of find /usr/lib/wine -iname '*vulkan*'

I've also just started another makepkg -s, but with _update_winevulkan="false", just in case

**Comment by cyro666** [comment]
And... Same result.

**Comment by cyro666** [comment]
So, it complains about a missing library, yet it's actually there. Moreover, 32-bit compiles fine. Honestly, I don't really know enough about Meson to figure this one out.

**Comment by Tk-Glitch** [comment]
I'd just downgrade meson to 0.49 at this point

**Comment by openglfreak** [comment]
Upload the build log. Maybe that has some information.

**Comment by cyro666** [comment]
Downgrading meson did it. Just in case, I went with 0.48 and it worked.

**Comment by Tk-Glitch** [comment]
I'm still on 0.49.3 and didn't upgrade to 0.50 after seeing the report on DXVK's issue tracker. The issue needs to be fixed either on the meson side or the DXVK side, but it seems to be simply broken on 0.50, at least when it comes to winelib builds.

**Comment by Tk-Glitch** [comment]
@cyro666 If your logs are similar to what's been posted here : https://github.com/doitsujin/dxvk/issues/970
it's irrelevant to post them, I'm glad you got it fixed though. I should add some kind of warning about meson 0.50 for now.
