### ISSUE TITLE
DXVK Async patches need rebase

### ISSUE THREAD

**Issue by clapbr** [Tk-Glitch/PKGBUILDS#154]
Not applying anymore on latest dxvk, worth a note until someone rebases it :frog:

**Comment by Tk-Glitch** [comment]
Applies fine here since https://github.com/Tk-Glitch/PKGBUILDS/commit/016c72debf62ecfede14207ca410ed52e2833379
Got a log ?

**Comment by Tk-Glitch** [comment]
Oh.
The wine-tkg-git one.
Of course.
