### ISSUE TITLE
linux50 MuQSS compile fail 

### ISSUE THREAD

**Issue by d4vid1** [Tk-Glitch/PKGBUILDS#155]
patching file sound/usb/line6/pcm.c
patching file tools/objtool/Makefile
Hunk #1 FAILED at 31.
1 out of 1 hunk FAILED -- saving rejects to file tools/objtool/Makefile.rej
==> FEHLER: Ein Fehler geschah in prepare().
    Breche ab...
  -> exit cleanup done

**Comment by Tk-Glitch** [comment]
Thanks for your report !
