### ISSUE TITLE
[wine-tkg-git] What about Esync rebase for the latest Wine master?

### ISSUE THREAD

**Issue by Kerrung** [Tk-Glitch/PKGBUILDS#156]
Hi, @Tk-Glitch !
As I understand it, Esync in wine-tkg-git is now disabled for the newest Wine master if it detects a commit that breaks compatibility with Esync. Did I understand this correctly? And if I'm right, then in that case I'm interested to know what about rebase Esync to the latest Wine master?
Thank you.

**Comment by varris1** [comment]
Esync is part of staging now. No need for tkg to rebase it anymore.

**Comment by Tk-Glitch** [comment]
It is already rebased against latest mainline master. It is only disabled for staging as Esync has been merged there.

**Comment by Kerrung** [comment]
Wow! And I did not know about it ... Thank you for telling me about it!
And to enable Wine Staging's Esync I still need to use a variable WINEESYNC=1 for this, or is Esync now just always enabled by default?

**Comment by Tk-Glitch** [comment]
It's not enabled by default, it's virtually the exact same patchset as before, and you need to enable it with WINEESYNC=1 still. I just won't be maintaining that one anymore :frog:

**Comment by Kerrung** [comment]
Thank you
