### ISSUE TITLE
[wine-tkg-git] DXVK winelib build for some reason requests cross build and mingw.

### ISSUE THREAD

**Issue by Kerrung** [Tk-Glitch/PKGBUILDS#158]
Hi, @Tk-Glitch ! Is it a new bug or a new feature? I haven't mingw packages installed because it is not required for winelib build, so the compilation crashed with an error message due to the lack of mingw. What am I doing wrong? Thank you.
I use:
Arch Linux;
wine-tkg-git commit: 359d6ce

![Screenshot from 2019-04-06 17-23-15](https://user-images.githubusercontent.com/36989404/55669518-b44da380-5891-11e9-8f3c-bb68d382c2db.png)

**Comment by Tk-Glitch** [comment]
Ok, it seems there was some breakage upstream that got fixed with that commit, with a possible forced push at some point : https://github.com/doitsujin/dxvk/commit/67446eda47b14113d236272c6b92c8f0dff1777e

Deleting your `./src/dxvk` dir should allow a proper resync.

**Comment by Kerrung** [comment]
> Ok, it seems there was some breakage upstream that got fixed with that commit, with a possible forced push at some point : [doitsujin/dxvk@67446ed](https://github.com/doitsujin/dxvk/commit/67446eda47b14113d236272c6b92c8f0dff1777e)
> 
> Deleting your `./src/dxvk` dir should allow a proper resync.

It helps me. Thank you!
Fixed, so, I close it.

**Comment by Tk-Glitch** [comment]
Good !
