### ISSUE TITLE
typo ?

### ISSUE THREAD

**Issue by yuiiio** [Tk-Glitch/PKGBUILDS#159]
proton-tkg proton

            make_d9vk_link(basedir + "/dist/lib/wine/fakedlls/",
                prefix + "drive_c/windows/system32")
        else:
            #use gl-based wined3d for d3d11 and d3d10 32+64
            make_dxvk_links(basedir + "/dist/lib64/wine/fakedlls/",
                prefix + "drive_c/windows/system32")
            make_dxvk_links(basedir + "/dist/lib/wine/fakedlls/",
                prefix + "drive_c/windows/syswow64")
            #use gl-based wined3d for d39 32+64
            make_d9vk_link(basedir + "/dist/lib64/wine/fakedlls/",
                prefix + "drive_c/windows/system32")
            make_d9vk_link(basedir + "/dist/lib/wine/fakedlls/",

make_d9vk_link => make_d9vk_links

**Comment by Tk-Glitch** [comment]
Oh my... You are absolutely right. Good catch!
