### ISSUE TITLE
rm: cannot remove esync.tgz - No such file or directory

### ISSUE THREAD

**Issue by Enverex** [Tk-Glitch/PKGBUILDS#16]
I always have to set cleanup to no otherwise the build fails at the very end with:

```
removed '/mnt/store/Build/TKG-Builds/wine-tkg-git/BIG_UGLY_COINMINER'
rm: cannot remove '/mnt/store/Build/TKG-Builds/wine-tkg-git/esync.tgz': No such file or directory
```

I assume this is because I have a SRCDEST set in makepkg.conf (so sources aren't downloaded to the PKGBUILD folder). Not sure if you want to make this less of a fatal error or work around the problem somehow in these instances.

**Comment by Tk-Glitch** [comment]
Thank you very much for the report. It should be fixed by 691971b.
