### ISSUE TITLE
Maybe it's about tome for remove the Warfame patch from Wine-tkg-git?

### ISSUE THREAD

**Issue by Kerrung** [Tk-Glitch/PKGBUILDS#160]
@Tk-Glitch , hi! The Warfame patch have landed to the vanilla Wine. Maybe it's about tome for remove the Warfame patch from Wine-tkg-git? Thank you!

https://source.winehq.org/git/wine.git/commit/04ccd995b1aec5eac5874454a320b37676b69c42

**Comment by Kerrung** [comment]
Fixed now, thank you!

**Comment by Tk-Glitch** [comment]
We're not removing stuff here as wine-tkg-git can build older trees. We just needed an additional rule :frog:

**Comment by Kerrung** [comment]
Why we need to build older trees?

**Comment by Tk-Glitch** [comment]
A simple example would be that current master has wined3d regressions preventing some games to run. Another example would be that PBA can't be used anymore since 3.19. It's also very useful for debugging and development.

**Comment by Kerrung** [comment]
thank you
