### ISSUE TITLE
[wine-tkg-git] Allow for no-PIC build in 32bit wine

### ISSUE THREAD

**Issue by llde** [Tk-Glitch/PKGBUILDS#162]
Hi. Some copy protection/DRM mechanism for 32bit application are deeply incompatible with wine default of generating Platform Indipendent Code. 
It should be possible to have a switch to enable building -no-PIC -no-pie code for 32 bit builds?

Relevant bug:https://bugs.winehq.org/show_bug.cgi?id=37540

**Comment by Tk-Glitch** [comment]
Hello llde,
I remember stumbling upon that before, and I was unable to get it to work only on the 32-bit side.
If you or anyone is up for a PR on that matter, I'm up for merging.

**Comment by Tk-Glitch** [comment]
Zebediah will be working on this for wine-staging integration soon-ish.

**Comment by Tk-Glitch** [comment]
Actually, it should land in mainline

**Comment by Riesi** [comment]
The [final patch for -fno-pic builds](https://source.winehq.org/patches/data/163849) landed yesterday and is working without any additional configuration with the pkgbuild.
This fixes Origin for example, which means the temporary fix can be removed.

**Comment by Tk-Glitch** [comment]
Done :frog:
