### ISSUE TITLE
_sched_yield_type="1" doesn't work

### ISSUE THREAD

**Issue by Berobad** [Tk-Glitch/PKGBUILDS#167]
The yield type is set to 0 instead of 1 with _sched_yield_type="1" in the cfg file.

_sched_yield_type="2" does work as expected.

**Comment by Tk-Glitch** [comment]
Nice catch! Thanks.

**Comment by Berobad** [comment]
BMQs single core performance is bad when yield_type is 0 on my Ryzen.
(it moves the process too much between cores preventing them to boost above default clock)

Never would have noticed it without it
