### ISSUE TITLE
[wine-tkg-git] fullscreen hack is broken with wine 4.6 for ddraw games

### ISSUE THREAD

**Issue by neVERberleRfellerER** [Tk-Glitch/PKGBUILDS#169]
Fullscreen hack for Wine 4.6 does not work properly and shows as in screenshot. In 4.5 it works correctly.
![Screenshot_20190423_214125](https://user-images.githubusercontent.com/11160972/56613136-53a2c280-6616-11e9-99c3-627e787f9ea0.jpg)
In case of Sacred, it shows "screen" twice but only bottom left is updated, in case of Fallout Tactics it shows single game screen in bottom left and rest is grey. In case of Stringhold it shows also in bottom left and mouse position is calculated as if game covered whole screen.
With Sacred screen flashes black and the color from screenshot and when game exits, my desktop environment was still getting darger and lighter with same freqency as flashing of Sacred (which is really strange).

**Comment by Tk-Glitch** [comment]
What commit was used ?

**Comment by Tk-Glitch** [comment]
Because that reminds me of https://github.com/Tk-Glitch/PKGBUILDS/issues/148

**Comment by neVERberleRfellerER** [comment]
Wine 9d75caf4e1deea0ec8d5ad3f829e7218bc1e3c16 (current master)
Staging a0708adf427a61acd2f68dda8ccf245d93909f15 (current master - 1)

Works with
Wine 56404595d5c42168d4fd4c1ec3a1b802a6aab5c1
Staging 56404595d5c42168d4fd4c1ec3a1b802a6aab5c1 (two commits after 4.6)

**Comment by Tk-Glitch** [comment]
I have tested a bunch of games today on a0708ad with it enabled and faced zero issue.. Are these games all GDI?

**Comment by neVERberleRfellerER** [comment]
Not sure if GDI, but they all use DDraw , so I went ahead and tested FO: New Vegas (without nine) and it works properly.

**Comment by Tk-Glitch** [comment]
Please test the patch attached by putting it in your userpatch folder, disabling proton FS hack in your config, and accepting patching when prompted during build.
[valve_proton_fullscreen_hack-staging-test.mypatch.zip](https://github.com/Tk-Glitch/PKGBUILDS/files/3109573/valve_proton_fullscreen_hack-staging-test.mypatch.zip)

**Comment by neVERberleRfellerER** [comment]
last_build_config.log says
```
Applied your own patch /some/path/tkg-PKGBUILDS/wine-tkg-git/valve_proton_fullscreen_hack-staging-test.mypatch
```
Now borders of all ddraw games blink, mostly black and white, but scaling still does not work.

**Comment by Tk-Glitch** [comment]
It's not supposed to do that but okay. Grabbed Sacred in the meantime to be more efficient.

**Comment by neVERberleRfellerER** [comment]
Sometimes it shows weird corruption (random patterns or butchered parts of desktop environment) and it's not visible on screenshot. It seems to corrupt kwn in some way and it then retains part of blinking on plasma background after I exit the game... intensity goes down with time and after 1-2 minutes it's only barely visible. So, something very weird is going on here.

**Comment by Tk-Glitch** [comment]
There is a separate issue with mouse clipping that is kinda linked with this though. I'm on it.

**Comment by Tk-Glitch** [comment]
Everything should hopefully be fixed now with https://github.com/Tk-Glitch/PKGBUILDS/commit/2a7bdbd98b382e8a1d8f35436a62c48fb928534a

**Comment by BrianAllred** [comment]
Didn't want to make a new issue just for this, but the PKGBUILD wasn't updated with the new hash, so the patch file failed the hash check during build.

**Comment by neVERberleRfellerER** [comment]
It seems that https://github.com/Tk-Glitch/PKGBUILDS/commit/2a7bdbd98b382e8a1d8f35436a62c48fb928534a introduced clipping in Stronghold HD, which is quite special because --- as said in IP --- mouse there behaved differently from other games. Now mouse is clipped to area of resolution selected in game. Clipping is done from top left corner and mouse position is scaled properly so bottom right corner of accessible rectangle triggers mouse events in bottom right corner of game screen even through mouse itself is somewhere in the middle of physical screen.

**Comment by Tk-Glitch** [comment]
I have decided to stop trying to fix the thing against the problematic staging patch as I'm too stupid for that apparently. The staging patch will now be disabled when the FS hack is enabled. That should fix all your issues with it.
