### ISSUE TITLE
Any wine process hangs indefinitely

### ISSUE THREAD

**Issue by BrianAllred** [Tk-Glitch/PKGBUILDS#170]
Any wine process hangs indefinitely after `start_process`, even on a fresh prefix.

```
$ winecfg
000b:fixme:winediag:start_process Wine Staging 4.6 is a testing version containing experimental patches.
000b:fixme:winediag:start_process Please mention your exact version when filing bug reports on winehq.org.
^C^C
```

This started with the changes today. I'm currently building a previous commit, will update if that works.

**Comment by FrostyGT** [comment]
Hey!

Just finished installing about 5 minutes ago and ran into the same issue (although I might be the only one doing this at nearly 3AM!). Please post an update when possible.

**Comment by varris1** [comment]
Staging is broken atm. You can roll back to an older version until it's fixed upstream.

`_staging_version="a0708adf427a61acd2f68dda8ccf245d93909f15"`
works

**Comment by Tk-Glitch** [comment]
I have added a fix as userpatch in https://github.com/Tk-Glitch/PKGBUILDS/commit/81682beada7b3a6843fcb6a92c05bc28efee0c89 as a workaround in the meantime.

**Comment by Valmar33** [comment]
It fails to apply. :(

**Comment by Kerrung** [comment]
With https://github.com/wine-staging/wine-staging/commit/f883c66e40ada01c4413c5f33912339f88bd8073 this bug was, as I suppose, fixed by upstream.

**Comment by Tk-Glitch** [comment]
Yes it was
