### ISSUE TITLE
AMDGPU-Pro updated to 19.10-785425

### ISSUE THREAD

**Issue by skeevy420** [Tk-Glitch/PKGBUILDS#171]
sha256sums=('a0bd71417d0c0ddd404be8c86653135c4e0190a54bb8dc62eef231d5275f37bd')
I'm lazy too lazy to fork & submit a pull request :p

**Comment by Tk-Glitch** [comment]
Fixed with https://github.com/Tk-Glitch/PKGBUILDS/commit/f4acfa298fa329e3c1595f2a00de68ea6ad862bd
