### ISSUE TITLE
[Froggie Question] Will D9VK support DXVK_ASYNC patchset?

### ISSUE THREAD

**Issue by t14462** [Tk-Glitch/PKGBUILDS#173]
I have noticed that D9VK with low CPU overhead completely get rid of Fallout New Vegas stuttering (wich exist on Gallium-Nine).

Also, D9VK supports DX9 for WPF as Nine

Will be DXVK_ASYNC=1 ported to D9VK?

**Comment by Tk-Glitch** [comment]
I think @Joshua-Ashton is the only one able to answer that question right now.

**Comment by Tk-Glitch** [comment]
Closing as it's not directly related to my projects.
If Josh answers here, fine. Else, forward your question to https://github.com/Joshua-Ashton/d9vk
:frog:
