### ISSUE TITLE
Make FAudio PKGBUILD with ffmpeg

### ISSUE THREAD

**Issue by t14462** [Tk-Glitch/PKGBUILDS#174]
For unknown reasons repos and AUR provide FAudio without FFmpeg, which breaks WMA playing in Fallout 4 and Skyrim SE.

If you can, Please make FAudio PKGBUILD with FFmpeg option.

(frog) https://www.google.com/search?q=african+horned+frog&source=lnms&tbm=isch&sa=X&ved=0ahUKEwjYrJL1gu7hAhXikYsKHQR6CgwQ_AUIDigB&biw=1303&bih=672#imgrc=3xZB6OqDVaYg2M:

**Comment by Tk-Glitch** [comment]
Both https://aur.archlinux.org/packages/faudio-git/ and https://aur.archlinux.org/packages/lib32-faudio-git/ have FFMPEG support enabled.

**Comment by t14462** [comment]
OK, I'll test it right now.

**Comment by Tk-Glitch** [comment]
I've actually made a PKGBUILD at some point, and it was removed thanks to these. I've been using them since and except for some dependency-related issues because of other AUR packages breaking on the 32-bit side (they are fixed now), it's been flawless.

**Comment by t14462** [comment]
Thanks for you work and replys :)
I'll test it, and hope everything OK

**Comment by Tk-Glitch** [comment]
You're welcome :)
