### ISSUE TITLE
Builtin DXVK crashing Bethesda games launchers in configuration

### ISSUE THREAD

**Issue by t14462** [Tk-Glitch/PKGBUILDS#175]
[customization.txt](https://github.com/Tk-Glitch/PKGBUILDS/files/3122351/customization.txt)

Wine built with that options crashing configators of bethesda games: Fallout 4, Skyrim SE (and probably oblivion, I'll test it now)

With Fallout New Vegas and F3 - everything OK.

STEPS TO REPRODUCE:
1. Have Mesa AMD RADV driver
2. Build wine with this options
3. Start game launcher
4. Press SETTINGS
5. See: wine: Unhandled page fault on read access to 0x00000000 at address 0x14000c5c1 (thread 0035), starting debugger...

Problem on memory acces when app wants to get video capabilities from driver.

It's weird, because games itself works perfect.

On standalone DXVK this bug not appear.

**Comment by Tk-Glitch** [comment]
This is a known issue with winelib DXVK/D9VK. Nothing I can do about it.

**Comment by t14462** [comment]
OK. So i will use workarounds:

1.Installing standalone DXVK
2.Configure
3.Then disable it...
4.And play with builtin patched
