### ISSUE TITLE
[Question] Can PE libs support in 4.7 fix hackery problems with builtin DXVK winelib?

### ISSUE THREAD

**Issue by t14462** [Tk-Glitch/PKGBUILDS#176]
If DXVK winelib builds is dirty hackery with problems, and its not officially supported...

... Maybe building D9VK/DXVK as PE libs can fix many problems?

Is it possible to make builtin DXVK as PE lib?

**Comment by t14462** [comment]
@Guy1524 Is it possible? Maybe you know?

**Comment by Tk-Glitch** [comment]
It's not "dirty hackery". Anyway it has nothing to do in my issue tracker. Also, I'm providing https://github.com/Tk-Glitch/PKGBUILDS/tree/master/dxvk-tools already for the usual mingw builds.

**Comment by t14462** [comment]
About hackery doitsujin says, when my game configators crashing.

@Tk-Glitch Thanks, you doing cool things, which makes world happy! :)

**Comment by Tk-Glitch** [comment]
Winelib has issues, but it's not because it's a hack :frog: 
Nonetheless, the mingw builds are working as expected, and are basically what you're asking for.

**Comment by t14462** [comment]
I heard news about support for builtin PE libs in Wine 4.7

I was so worried about this idea... and nobody to ask at night, when everyone sleeping. So I asked everyone xD

PS: Forgive me for killing frogs :(
