### ISSUE TITLE
tkg kernel named with version. Do I need rewrite boot config after update?

### ISSUE THREAD

**Issue by t14462** [Tk-Glitch/PKGBUILDS#178]
[Question]
tkg kernel named with version. Do I need rewrite boot config after update?

Maybe better not including version to name of kernel binary?

Rewriting every time systemd-boot configs sucks.

And on arch-based binary distros its difficult to customize GRUB with custom kernels...

**Comment by Tk-Glitch** [comment]
`grub-mkconfig -o /boot/grub/grub.cfg`
Stock Arch kernel is named with version as well.

**Comment by Tk-Glitch** [comment]
https://aur.archlinux.org/packages/update-grub/ also

**Comment by t14462** [comment]
I'm not using GRUB2 because I want KISS UEFI boot

Also, sorry if I asking stupid questions, I'm just big enthusiast of opensource, and its interesting asking about things which i dont fully understand xD

**Comment by Tk-Glitch** [comment]
I understand, and I know it's exciting, but I can't be everywhere and fix everyone's issues with random software. That's unrealistic :frog: 

Systemd-boot is very limited and has poor multi-kernel handling, yes. I won't make a fork of it to make it better. It could be said for many (most?) software I guess.

But I'm not superhuman. I'm doing my part with the limited resources I have and I'm sorry if it's not enough, but the documentation you seek exists already. Joining Linux-related forums or Discord servers would definitely be more helpful to you as you'd get more help.

If you got an issue with specifics of my projects, you're right to ask here. But in that case it's a general issue with systemd-boot, as my kernel packages are pretty much standard. Too frequent updates? Do you really need the new features? The kernel won't stop working out of nowhere if you skip an update or two :smiley: 

Also you could have put it differently with, for example, a feature request to strip the pkgver out? Maybe make a PR for it?
Linux is a community driven environment, and I'm just a very tiny glitched dot lost in there with also a life outside, bills to pay etc. I have absolutely nothing against getting some help to push things further :wink:

**Comment by t14462** [comment]
I'm just asking. (I'm very nosy) No need to worry about that :)

I'm experimenting with new bleeding-edge stuff, UKSM, schedullers, patchsets, optimization and every single option of my system. I'ts my hobby to learn linux deep.

Ah OK. I will just change number in entries/tkg.conf if i decide to update.

**Comment by Tk-Glitch** [comment]
I'll think about adding an option for it
