### ISSUE TITLE
not enough frog emojis in scripts 🐸 🐸 🐸 🐸 

### ISSUE THREAD

**Issue by Joshua-Ashton** [Tk-Glitch/PKGBUILDS#179]
🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 
please add more 🐸  to the scripts

🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 

hardcore frogging should be in the scripts

🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸

**Comment by varris1** [comment]
🐸

**Comment by clapbr** [comment]
there's the cool giant ascii frog :frog:

**Comment by doitsujin** [comment]
:fr: :frog: :baguette_bread: :fork_and_knife:

**Comment by Joshua-Ashton** [comment]
yummy

bone app the teeth

**Comment by Faalagorn** [comment]
You forgot 🍷. Maybe switch to https://www.emojicode.org/ too?

**Comment by TedsterTech** [comment]
🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸

**Comment by TedsterTech** [comment]
> yummy
> 
> bone app the teeth

Bone apple frog tea
🐸

**Comment by Riesi** [comment]
🐸🐸🐸🐸🐸🐸🐸💛💛💛

**Comment by Joshua-Ashton** [comment]
What's the status on this issue?
I am not seeing progress fast enough.
I demand to speak to developer!

**Comment by Tk-Glitch** [comment]
I think @doitsujin is developer!

**Comment by Joshua-Ashton** [comment]
Dear @Tk-Glitch.
Thank you for the update.
I hope more frogs get added soon.

Maybe a patch to add frog hud to DXVK would be a good starting point?

**Comment by Joshua-Ashton** [comment]
@Tk-Glitch I am not seeing progress on this issue.

** I DEMAND TO SPEAK TO DEVELOPER ** 💢 

grr 🐸

**Comment by BangL** [comment]
+1

**Comment by Joshua-Ashton** [comment]
shut yourself, developer will help me.

**Comment by BangL** [comment]
let's go outside

**Comment by Joshua-Ashton** [comment]
Outside is just a crappy fork of Inside™ with green splattered everywhere and an overheating issue during half of the year. It's really annoying and sometimes there are annoying regressions like earthquakes and such. They really should fix that.

**Comment by openglfreak** [comment]
Earthquakes was already an issue with Inside™, but it was reported to the Outside issue tracker first.

**Comment by Joshua-Ashton** [comment]
Calling @Tk-Glitch

**Comment by Joshua-Ashton** [comment]
🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸

**Comment by Joshua-Ashton** [comment]
This is a good solution, thanks for the update.

**Comment by Tk-Glitch** [comment]
I'm glad you're satisfied.

**Comment by SeppeSoete** [comment]
I approve
