### ISSUE TITLE
Fails to apply wine-staging patches

### ISSUE THREAD

**Issue by ghost-101** [Tk-Glitch/PKGBUILDS#18]
`  -> Applying wine-staging patches...
Applying /home/admin/wine-tkg-git/src/wine-staging-git/patches/Compiler_Warnings/0001-windowscodecs-Avoid-implicit-cast-of-interface-point.patch
/home/admin/wine-tkg-git/src/wine-staging-git/patches/patchinstall.sh: line 1604: /home/admin/wine-tkg-git/src/wine-staging-git/patches/Compiler_Warnings/0001-windowscodecs-Avoid-implicit-cast-of-interface-point.patch: No such file or directory
ERROR: Failed to apply patch, aborting!
==> ERROR: A failure occurred in prepare().
    Aborting...
`

This commit causes the breakage:
https://github.com/wine-staging/wine-staging/commit/aa38c0bbbe85f443663d3e52dd487ac9fc4faf1e

**Comment by Tk-Glitch** [comment]
Thanks for the report.
Yes I'm well aware of this but it is an issue on the staging side, not mine.
Alistair didn't add the `0001-windowscodecs-Avoid-implicit-cast-of-interface-point.patch` file with the commit. As a workaround until it's fixed upstream, you can set `_staging_version=1b1af92` in the customization.cfg file to use the previous commit.

**Comment by ryanmusante** [comment]
Out of curioisity, is steam-play {proton} picking and choosing which patches from staging to use or abandoning staging completely?

**Comment by Tk-Glitch** [comment]
@ryanmusante Proton doesn't use staging, that's what breaks most games that are otherwise working fine on wine-staging.

**Comment by goeiecool9999** [comment]
using the suggested saging commit 1b1af92 makes the windows steam client unable to connect to steam for my system. If you're having the same issue, try dc83f04 which does work for me.

**Comment by Tk-Glitch** [comment]
@goeiecool9999 No problem with steam here using 1b1af92. Can you reproduce it consistently?

**Comment by goeiecool9999** [comment]
I rebuilt wine with staging 1b1af92 and steam no long has issues connecting. However when it tried to login with the credentials from my last login (before I went back to 1b1af92) it crashed after it connected. I tried using a clean wine prefix but it still just crashed after I logged in. I have no clue what could be causing this. Unless other users are experiencing similar issues I'd say just ignore what I've said. I may be screwing something up somewhere...

**Comment by Tk-Glitch** [comment]
The issue has now been fixed upstream.

@goeiecool9999 Weird..

**Comment by ghost-101** [comment]
@goeiecool9999 If Steam refuses to connect, try launching Steam with -tcp, works for me everytime.
As for the crashing, I've had it as well, I recall not having crashing problems before Oct while being on 3.17.

`\src\common\pipes.cpp (750) : CClientPipe::BWriteAndReadResult: BWrite failed
\src\common\pipes.cpp (750) : Fatal assert failed: c:\buildslave\steam_rel_client_win32\build\src\common\pipes.cpp, line 750.  Application exiting.`

wine-staging from the Arch repo runs Steam without crashing, I'll see what patch/commit causes it whenever I can.

**Comment by soredake** [comment]
@goeiecool9999 maybe crashing because of https://source.winehq.org/git/wine.git/commit/b79fd400c05547457bb10e74776b8f312bacae8c

**Comment by goeiecool9999** [comment]
@soredake You just made my day! It worked! I built the latest version of wine-staging with that patch reverted and it's working beautifully!

**Comment by Tk-Glitch** [comment]
I have added an option to revert the commit in the cfg : https://github.com/Tk-Glitch/PKGBUILDS/commit/69abc5dcf32446a76006ea83f144ee4a208b270e#diff-410db0d6d78fed0dbe64a6a4e5025e00

**Comment by ghost-101** [comment]
@soredake @Tk-Glitch Works, thank you! I'm going to close this now so it doesn't go off the rails.
