### ISSUE TITLE
Old exFAT kernel module

### ISSUE THREAD

**Issue by TBK** [Tk-Glitch/PKGBUILDS#180]
I just wanted to inform you that you are using the old Samsung exFAT kernel module which has been replaced by the Samsungs sdfat kernel module. It is available from opensource.samsung.com via the phone src releases or you can find it on GH - https://github.com/cryptomilk/kernel-sdfat

**Comment by Tk-Glitch** [comment]
I am aware and it was a convenience choice at some point. The patchset is custom and has been kept afloat by a colleague. Thanks for the heads up nonetheless, I might give it another look down the road :)
Unless you got a specific issue related to it in its current form?

**Comment by TBK** [comment]
I stumbled upon your repo while setting up my new gaming box. I recently have done some work to make sdfat build with the 5.0 kernel.

It was just meant as a heads up. I think lots of people use the old version because they are not aware of Samsung's newer efforts. It will hopefully get mainlined.

Thanks for all the work you have put maintaining the pkgbuilds.

**Comment by Tk-Glitch** [comment]
Thank you!
