### ISSUE TITLE
A compilation issue (again)

### ISSUE THREAD

**Issue by Kerrung** [Tk-Glitch/PKGBUILDS#184]
Hi!

[last_build_config.log](https://github.com/Tk-Glitch/PKGBUILDS/files/3143501/last_build_config.log)

![Снимок экрана от 2019-05-04 01-36-11](https://user-images.githubusercontent.com/36989404/57164451-97af7780-6e0d-11e9-9701-da9d0e4ca1d5.png)

**Comment by Tk-Glitch** [comment]
The async patch broke. Please disable it for now until resolved. Thanks!

**Comment by Sporif** [comment]
The async patch has been [updated](https://github.com/jomihaka/dxvk-poe-hack/commit/9b557061868a12837f24eb6a13fe02a8c4720e88).

**Comment by Tk-Glitch** [comment]
Fixed with https://github.com/Tk-Glitch/PKGBUILDS/commit/9910eaa363e628e67529870d947006880e4a7412
