### ISSUE TITLE
BUILDDIR=/tmp/makepkg MinGW build fails workaround

### ISSUE THREAD

**Issue by t14462** [Tk-Glitch/PKGBUILDS#188]
1. cd ~/PKGBUILDS/mingw/
2. export BUILDDIR=./
3. ./mingw-on-arch-automator.sh

I use this trick for all failed to build pakages, because i like to make my PKGBUILDs in RAM

I hope it will helpfull

**Comment by Tk-Glitch** [comment]
https://github.com/Tk-Glitch/PKGBUILDS/commit/21fbd8491a157c29f4e0b8fe64a739539393b9be should fix that

**Comment by t14462** [comment]
Thanks for your work and for this good idea with empty variable :)
