### ISSUE TITLE
Can't install Gallium-Nine standalone

### ISSUE THREAD

**Issue by t14462** [Tk-Glitch/PKGBUILDS#189]
Probably wine loader linking d3d9.dll with root attributes
Or something wrong with PKGBUILD... (attrs)
or maybe it is wine regression... I don't know, just giving up.

wine-nine from repos, nor winetricks - nothing works

I've always tried to make clean wineprefix - it didn't help

When I try to enable checkbox, it says this:

wine ninewinecfg              
000b:fixme:winediag:start_process Wine Staging 4.7 is a testing version containing experimental patches.
000b:fixme:winediag:start_process Please mention your exact version when filing bug reports on winehq.org.
000d:err:menubuilder:init_xdg error looking up the desktop directory
Native Direct3D 9 v0.4.0.294-release is active.
For more information visit https://github.com/iXit/wine-nine-standalone
err:ninecfg:nine_get removing dead symlink
err:ninecfg:nine_get removing dead symlink

**Comment by t14462** [comment]
tested with BUILDDIR=/tmp/makepkg and without it - problem not depending on it.

Tried with wine-staging 4.7 from repo - nine works!

Problem is that staging 4.7 incompatible with fresh wine 4.8... or something wrong with PKGBUILD

**Comment by Tk-Glitch** [comment]
Please post the configuration file used and `last_build_config.log`. Thanks!

**Comment by t14462** [comment]
[last_build_config.log](https://github.com/Tk-Glitch/PKGBUILDS/files/3168486/last_build_config.log)

I'm using wine for gaming, so this is my patches... also pulsaudio-staging patches always nuking my system audio sink - so i disabled it too

**Comment by t14462** [comment]
Fixed by this userpatch: https://github.com/Tk-Glitch/PKGBUILDS/commit/833c3851243b99c99fdfc846cb057bd5d0079050#diff-410db0d6d78fed0dbe64a6a4e5025e00

This was a global wine regression
