### ISSUE TITLE
Wrong installer of XDVK-Tools

### ISSUE THREAD

**Issue by t14462** [Tk-Glitch/PKGBUILDS#192]
~/PKGBUILDS/dxvk-tools/DXVKBUILD/setup_dxvk*.sh does nothing because of wrong bin lib path.

~/PKGBUILDS/dxvk-tools/DXVKBUILD/master/latest/win*/setup_dxvk.sh makes symlinks to current path, so if you have deleted bin libs PKGBUILDS then you games will crashing and you must install DXVK allways after rebuild.

SOLUTION: fix path in setup_dxvk*.sh and copy libs to wineprefix, don't do symlinks!

**Comment by Tk-Glitch** [comment]
Solution: don't use these symlink scripts if you don't want to?

**Comment by t14462** [comment]
Thanks for adding setup script! :)

**Comment by Tk-Glitch** [comment]
You're welcome
