### ISSUE TITLE
"Noob guide"

### ISSUE THREAD

**Issue by Jordi234** [Tk-Glitch/PKGBUILDS#198]
Hi!
I'm trying to build a Kernel from this site, and I can't understand a lot of options that the build process ask. I'm searching a " noob guide" to do this process, and trying to understand the options a little bit. I never builded a kernel, and I like to learn a how to make it.
If is not possible to found a "noob guide", if I select the options incorrectly, what happens??
Thanks!

**Comment by skeevy420** [comment]
The file "customization.cfg" located in the various kernel folders have very good descriptions of what the various options do and it lists the default values.  

Here's a quick, down and dirty how-to using the 5.1 kernel as an example

1. cd $PATH/TO/linux51-tkg
2. cp ./configuration.cfg ~/.config/frogminer/linux51-tkg.cfg
3. $EDITOR ~/.config/frogminer/linux51-tkg.cfg
4. Edit it to your liking...when in doubt or unsure, use the default value provided in the description
5. makepkg -sif

Optional: rm ~/.config/frogminer/linux51-tkg.cfg

If you do that right...set every option in your local cfg...it'll just build and won't ask you anything.

Replace $PATH/TO with the location of where you cloned PKGBUILDS
Replace $EDITOR with whatever text editor you prefer.  I like Kate for quick edits.

-s pulls any missing dependencies
-i tells it to install the kernel
-f tells it to force install the kernel (handy when testing options and the pkg name doesn't change)

Even with the great descriptions provided, Google really is your friend when it comes to kernel tweaking.  There are a ton of differing opinions on what tweaks are good, bad, necessary, unnecessary, etc and those opinions change based on what the user plans on doing.  That said, feel free to ask away.  I'm sure anything that comes out of this issue will help others and could possibly result in better descriptions in the configuration files.

**Comment by Jordi234** [comment]
Well, if I need to ask here a lot of things I stop trying to do this. At start I have this problem:
`nvidia_drm config not found!!
nvidia_modeset config not found!!
vboxnetflt config not found!!
nvidia config not found!!
vboxnetadp config not found!!
vboxdrv config not found!!
vboxpci config not found!!
*
* Restart config...
*
*
* PCI GPIO expanders
*
AMD 8111 GPIO driver (GPIO_AMD8111) [N/m/y/?] n
BT8XX GPIO abuser (GPIO_BT8XX) [N/m/y/?] (NEW) 
`
I used modprobed.

**Comment by Tk-Glitch** [comment]
1. Do not use modprobed-db.
2. Defaults are sane, so use them! :frog:  That means you can just spam return until it builds. You'll get a working kernel that way, with defaults settings.

If you select options incorrectly you can end up with broken features or an unbootable kernel.

**Comment by Jordi234** [comment]
My first kernel builded and....is working :P
I see a lot difference of performance between this and the original from Antergos, wonderful! I selected the default options.
Last question, nvidia-tkg drivers runs better or more fast than the nvidia package official??
Thanks for the great help!

**Comment by Tk-Glitch** [comment]
It should indeed give a substantial performance boost over stock.
The nvidia pkgbuild I'm providing won't give higher performance (and there's no way it would as it's proprietary black box).
I'm glad it helped fixing your network issues!

**Comment by Jordi234** [comment]
Thanks!
