### ISSUE TITLE
Disable upstream CSMT not recommended

### ISSUE THREAD

**Issue by ryanmusante** [Tk-Glitch/PKGBUILDS#210]
Is the default checked or not-checked for this setting in tabs? I don't remember which I left it at last. And why is it recommended as such?

![CSMT](https://user-images.githubusercontent.com/26808646/58366661-a1aa2f00-7f10-11e9-82f3-32d3ef12c9e2.png)

```
+ static void csmt_set(BOOL status)
+ {
+-    set_reg_key_dword(config_key, "Direct3D", "csmt", status);
++    if (status)
++    {
++        // TRUE, we disable upstream's csmt by setting dword to 0
++        set_reg_key_dword(config_key, "Direct3D", "csmt", 0);
++    }
++    else
++    {
++        // FALSE, we remove the csmt key letting wine use its default
++        set_reg_key(config_key, "Direct3D", "csmt", NULL);
```

**Comment by skeevy420** [comment]
The default is unchecked.  Checked disables it.

The "upstream" CMST used to be in staging only, now it's in regular Wine and on by default.  IMHO, it should be relabeled as "Disable CMST (not recommended)" to more accurately reflect that.

**Comment by Tk-Glitch** [comment]
Default is unchecked and it should stay unchecked for 99.99% of usecases. The stock toggle is unclear and it's patched in wine-tkg to be clearer (using firerat's PR patch for staging).
See more detailed related PR : https://github.com/wine-staging/wine-staging/pull/59
