### ISSUE TITLE
linux51-tkg: bmq 0.95 has been "rebased" recently

### ISSUE THREAD

**Issue by idprophecy** [Tk-Glitch/PKGBUILDS#211]
Hello,

I just want to point out that the BMQ 0.95 all-in-one patch which is used in there might slightly differ according to [Alfred's blog](http://cchalpha.blogspot.com/2019/05/bmq-095-release.html#comment-form) and might need an update. 

> PS, there was a respined before this official release. Pls re-pull/fetch the git or all-in-one file if you have used the 0.95 before this blog.

**Comment by idprophecy** [comment]
Thank you. :frog:

**Comment by Tk-Glitch** [comment]
Thank you for the heads up !
