### ISSUE TITLE
failed to initialize: RIGIN/lib/wine/ntdll.dll.so

### ISSUE THREAD

**Issue by withoutaface** [Tk-Glitch/PKGBUILDS#212]
Hello, i succesfully build proton-tkg-4.9.r5.g8725e273 with the script on ubuntu 18.04 in arch docker container (default config). Installed it to compatibilitytools.d and trying to use it. But it fails with 
"wine: failed to initialize: RIGIN/lib/wine/ntdll.dll.so: cannot open shared object file: No such file or directory"
Any hint? I don't get why it's searching in "RIGIN"

**Comment by Tk-Glitch** [comment]
The related change above should fix the "RIGIN" thing. Please let me know how it goes. Thank you!

**Comment by withoutaface** [comment]
Thanks!, but sadly it did not work - same error message. The changes from the commit in wine-tkg-git/PKGBUILD is there.

**Comment by withoutaface** [comment]
Replaced the \$ORIGIN with hardcoded path to my ".../compatibilitytools.d/proton_tkg.../dist" and i'm now able to use it with ubuntu disco (bionic sadly has older glibc). Uplay renders without buttons and text but with pictures. However this is okay because it launches the game just fine and i will test it with further builds.
Really appreciate your work!

**Comment by Tk-Glitch** [comment]
I'm pretty sure that one is a 4.9 regression.
I'm glad you got it fixed and that it was all that was needed. Now I'll have to figure out why it fails on *some* systems and not others. Thanks for the feedback!

**Comment by withoutaface** [comment]
I compiled proton_tkg_4.6 and proton_tkg_4.8 today and it worked with the "\$ORIGIN"-patch. I removed the whole folder and cloned the repository again. Very strange, the change was also there yesterday.

**Comment by withoutaface** [comment]
Also compiled proton_tkg_4.10.r1.ge2fa6bd9 without the RIGIN error. You may close this issue if there is nobody else - I'm not able to reproduce it.

**Comment by Tk-Glitch** [comment]
That's great news. I was actually awaiting for potential feedback from you after I pushed https://github.com/Tk-Glitch/PKGBUILDS/commit/0bbdbb286e0b61a06131785f8b47c26e37f860fa
Another related commit will come at some point but it shouldn't affect you while using proton-tkg, as it will target regular wine-tkg only. I'll close for now, and reopen if needed.
