### ISSUE TITLE
add league of legends patch fixes pls

### ISSUE THREAD

**Issue by aligodlike** [Tk-Glitch/PKGBUILDS#215]
https://aur.archlinux.org/packages/wine-lol/
https://aur.archlinux.org/packages/wine-lol-glibc/

**Comment by Guy1524** [comment]
@aligodlike the glibc patch is no longer necessary with w/ the revised wine patch.

**Comment by aligodlike** [comment]
> @aligodlike the glibc patch is no longer necessary with w/ the revised wine patch.

does not matter, i just want lol fixes to be added in wine-tkg

**Comment by Tk-Glitch** [comment]
Added in https://github.com/Tk-Glitch/PKGBUILDS/commit/94f011dd51171e363fcbaa20585a9a6b1ef11f6b
