### ISSUE TITLE
AMDGPU-Pro 19.20 available

### ISSUE THREAD

**Issue by skeevy420** [Tk-Glitch/PKGBUILDS#221]
https://drivers.amd.com/drivers/linux/amdgpu-pro-19.20-812932-ubuntu-18.04.tar.xz

**Comment by red5marauder** [comment]
I tried installing 19.20 on my Ubuntu 18.04 server system but it did not create the sysfs directories that existed in the previous releases.  I have a number of scripts that rely on these entries.  I reverted to 19.10 and the entries returned and everything worked fine.  Have these directories been moved in 19.20?

**Comment by Tk-Glitch** [comment]
At first glance, I can't see anything obvious. That being said it's probably not the best place to ask. Also, 19.20 seems to be a shitshow as far as I'm aware :sweat_smile:
