### ISSUE TITLE
winecfg crashes after clicking on" drives" tab

### ISSUE THREAD

**Issue by aligodlike** [Tk-Glitch/PKGBUILDS#225]
log:
https://gist.github.com/aligodlike/12909619efe01cf95f657996a250422e

**Comment by idprophecy** [comment]
Was discussed in https://github.com/Tk-Glitch/PKGBUILDS/issues/219.

Use the latest revision of Wine, it is fixed there. Bug was probably still in your wine-4.10.r1.ge2fa6bd9.

**Comment by aligodlike** [comment]
> Was discussed in #219.
> 
> Use the latest revision of Wine, it is fixed there. Mentioned bug was probably still in your wine-4.10.r1.ge2fa6bd9.

oh ok thanks but i prefer to just wait for wine-tkg and proton-tkg binaries instead of using makepkg

**Comment by Tk-Glitch** [comment]
I'll push a new release soon. Possibly today.

**Comment by aligodlike** [comment]
> I'll push a new release soon. Possibly today.

awesome
