### ISSUE TITLE
theme now looks broken in tkg-wine 4.11r2

### ISSUE THREAD

**Issue by barfin** [Tk-Glitch/PKGBUILDS#227]
screenshots:
https://ibb.co/6FYB8kq
https://ibb.co/1T6yQrn

and here's the theme:
https://drive.google.com/open?id=1kMjQ3FFdgyCAJvBAyz6aMtDBlmut42Xt

**Comment by Tk-Glitch** [comment]
This is an upstream bug. You may want to try with 4.11r6 (current staging head) and see if it's fixed. I couldn't find an open issue about it on winehq, so if it's still an issue, it might not be acknowledged and deserves a post :frog:

**Comment by aligodlike** [comment]
> This is an upstream bug. You may want to try with 4.11r6 (current staging head) and see if it's fixed. I couldn't find an open issue about it on winehq, so if it's still an issue, it might not be acknowledged and deserves a post

https://bugs.winehq.org/show_bug.cgi?id=47444
i did it and it looks like it's only broken on staging version
https://bugs.winehq.org/attachment.cgi?id=64809

**Comment by Tk-Glitch** [comment]
It seems it somehow fixed itself?

**Comment by Tk-Glitch** [comment]
Is it still an issue?

**Comment by aligodlike** [comment]
> Is it still an issue?

yup
the wine-staging in arch linux repo does not have this problem but wine-tkg does have that

**Comment by Tk-Glitch** [comment]
Ok. Can you please try switching `_CSMT_toggle="true"` to `_CSMT_toggle="false"` in your config and see if that fixes the issue?

**Comment by barfin** [comment]
> Ok. Can you please try switching `_CSMT_toggle="true"` to `_CSMT_toggle="false"` in your config and see if that fixes the issue?

sorry i'm noob i'm not sure how should i do that xd
but i disabled csmt using winetricks and it was still crap

**Comment by Faalagorn** [comment]
> > Ok. Can you please try switching `_CSMT_toggle="true"` to `_CSMT_toggle="false"` in your config and see if that fixes the issue?
> 
> sorry i'm noob i'm not sure how should i do that xd
> but i disabled csmt using winetricks and it was still crap

Nah, you actually need to disable the custom patch for it – the easiest way would probably be directly editing `customization.cfg` file that is included in the PKGBUILD repository in wine-tkg folder (or in `proton.cfg` for proton-tkg) and change it there.

If you don't want to edit the file directly (especially as the saves will be lost on each `git pull` of the repo, you can copy these files to `~/.config/frogminer/wine-tkg.cfg` or `~/.config/frogminer/proton-tkg.cfg` files respectively and edit that option there – assuming that `_EXT_CONFIG_PATH=~/.config/frogminer/proton-tkg.cfg` stays in the original files, then these files would take priority then.` stays in the original files, then these files would take priority then.

**Comment by barfin** [comment]
> > > Ok. Can you please try switching `_CSMT_toggle="true"` to `_CSMT_toggle="false"` in your config and see if that fixes the issue?
> > 
> > 
> > sorry i'm noob i'm not sure how should i do that xd
> > but i disabled csmt using winetricks and it was still crap
> 
> Nah, you actually need to disable the custom patch for it – the easiest way would probably be directly editing `customization.cfg` file that is included in the PKGBUILD repository in wine-tkg folder (or in `proton.cfg` for proton-tkg) and change it there.
> 
> If you don't want to edit the file directly (especially as the saves will be lost on each `git pull` of the repo, you can copy these files to `~/.config/frogminer/wine-tkg.cfg` or `~/.config/frogminer/proton-tkg.cfg` files respectively and edit that option there – assuming that `_EXT_CONFIG_PATH=~/.config/frogminer/proton-tkg.cfg` stays in the original files, then these files would take priority then.` stays in the original files, then these files would take priority then.

oh my god my internet speed is so bad
isn't it possible to enable or disable these patches after installation?

**Comment by Faalagorn** [comment]
Not really. Some might be (such as some related to DXVK and I guess things like mime association), but some patch wine sources directly to the point you'd have to recompile/replace the file(s) that got patched beforehand.

**Comment by Tk-Glitch** [comment]
Yeah you can't disable that at runtime sadly. To be frank, there's no other patch touching that panel by default, so that's probably the culprit.

**Comment by barfin** [comment]
> Not really. Some might be (such as some related to DXVK and I guess things like mime association), but some patch wine sources directly to the point you'd have to recompile/replace the file(s) that got patched beforehand.

> Yeah you can't disable that at runtime sadly. To be frank, there's no other patch touching that panel by default, so that's probably the culprit.

alright
i can't test it because my git clone and single connection download speed is super low
if you want you can close this issue because i can just download binary packages with download manager

**Comment by Tk-Glitch** [comment]
Why would you want to clone again? Did you delete your initial clone? What theme were you using when you encountered the issue?

**Comment by barfin** [comment]
> Why would you want to clone again? Did you delete your initial clone? What theme were you using when you encountered the issue?

i finally did it after 2 days and nothing changed but setting that to false

**Comment by barfin** [comment]
apparently it's almost fixed in wine 4.14 so i guess i should close this issue
