### ISSUE TITLE
zapcc usage request information

### ISSUE THREAD

**Issue by ryanmusante** [Tk-Glitch/PKGBUILDS#23]
Do you recommend zapcc or is it just an option for testing? If so, how do you make it default selection? It uses -O3 by default which has known to cause issues with some builds including kernel.

_wine-tkg-git:_
```
	elif [ $_COMPILEWITH == 'zapcc' ]; then
	  export CC="zapcc"
	  export CXX="zapcc++"
	  echo "Using zapcc compiler" >> $_where/last_build_config.log
	  if [ $_OPTIMIZED == 'true' ]; then
	    export COMMON_FLAGS="-std=gnu89 -g -march=native -pipe -O3"
	    export LDFLAGS="-O3"
	  fi
```

**Comment by Tk-Glitch** [comment]
I'm not recommending one compiler over another. It *works* and I have used enough wine builds compiled with it to consider this is a valid option to use if you want to.
Default is your distro's GCC. You can change what compiler will be used in the customization.cfg file.

About -O3, clang's (which zapcc is based on) optimization levels can't really be compared to GCC optimization levels.
Clang's -O3 usually generates the most efficient code while -O2 is the sweet spot for GCC. You can't compile a kernel with clang/zapcc (yet) btw.

**Comment by ryanmusante** [comment]
I see, thanks for the notification.
