### ISSUE TITLE
build failure

### ISSUE THREAD

**Issue by SolarAquarion** [Tk-Glitch/PKGBUILDS#230]
-> Building Wine-32...
make: *** No targets specified and no makefile found.  Stop.

**Comment by Tk-Glitch** [comment]
Please pull latest changes, it was fixed in latest commit.
https://github.com/Tk-Glitch/PKGBUILDS/issues/229

**Comment by SolarAquarion** [comment]
gotcha

**Comment by Tk-Glitch** [comment]
:wink:
