### ISSUE TITLE
Cannot build proton-tkg with PBA (wine 3.18 base)

### ISSUE THREAD

**Issue by qdevpl** [Tk-Glitch/PKGBUILDS#231]
Hi. I wanted to build for myself package with PBA patches. I set wine version to 3.18 during build I was greeted by this error - Server cannot be deleted, it's directory.
`rm -f server && ln -s /home/user/PKGBUILDS/wine-tkg-git/src/proton_dist-64-build/server server
rm: nie można usunąć 'server': Jest katalogiem
make: *** [Makefile:1436: server] Błąd 1
`

**Comment by qdevpl** [comment]
@Tk-Glitch I don't think it was it. I have pulled your change and I haven't used Overwatch patch in build configuration to begin with. Now i have the same error, but in another line
 `rm -f server && ln -s /home/user/PKGBUILDS/wine-tkg-git/src/proton_dist-64-build/server server
rm: nie można usunąć 'server': Jest katalogiem
make: *** [Makefile:1652: server] Błąd 1
make: *** Oczekiwanie na niezakończone zadania....
`

**Comment by Tk-Glitch** [comment]
Looks like I got everything this time :frog:
