### ISSUE TITLE
Information request for adding hook for nvidia dev install

### ISSUE THREAD

**Issue by ryanmusante** [Tk-Glitch/PKGBUILDS#24]
/etc/pacman.d/hooks/nvidia.hook

Could these be added or must it be done manually in order to have a hook for mkinitcpio so I don't forget to update afterwards?
```
[Trigger]
Operation=Install
Operation=Upgrade
Operation=Remove
Type=Package
Target=nvidia
Target=linux
# Change the linux part above and in the Exec line if a different kernel is used

[Action]
Description=Update Nvidia module in initcpio
Depends=mkinitcpio
When=PostTransaction
NeedsTargets
Exec=/bin/sh -c 'while read -r trg; do case $trg in linux) exit 0; esac; done; /usr/bin/mkinitcpio -P'
```

**Comment by Tk-Glitch** [comment]
I've been discussing it multiple times with other people and the conclusion was that I should not add it. If the user want it, he can create it.
I have added red colored text to remind you to run mkinitpcio after install as a middle ground solution.

**Comment by ryanmusante** [comment]
Ok, I might add for my own configuration if needed. Thanks!

**Comment by ryanmusante** [comment]
https://github.com/graysky2/modprobed-db/commit/5c5406f575788503f58b4cb58e50c10909e01c14

modprobed-db updated with nvidia modules

**Comment by Tk-Glitch** [comment]
That was unexpected. Nice :smiley:
