### ISSUE TITLE
wine compile error

### ISSUE THREAD

**Issue by d4vid1** [Tk-Glitch/PKGBUILDS#247]
PKGBUILDS/wine-tkg-git/src/wine-staging-git/patches/winedevice-Default_Drivers/0001-win32k.sys-Add-stub-driver.patch
error: Anwendung des Patches fehlgeschlagen: tools/make_specfiles:429
error: tools/make_specfiles: Patch konnte nicht angewendet werden
ERROR: Failed to apply patch, aborting!
==> FEHLER: Ein Fehler geschah in prepare().
    Breche ab...
  -> Removed BIG_UGLY_FROGMINER - Ribbit
  -> Removed Proton-tkg token - Valve Ribbit
  -> exit cleanup done

**Comment by skeevy420** [comment]
You hit No on the first patch.  Say yes.  I get the same error if I say No with the first one.  The 2nd patch you can say yes or no and it'll work.

`error: patch failed: tools/make_specfiles:429
error: tools/make_specfiles: patch does not apply
ERROR: Failed to apply patch, aborting!
==> ERROR: A failure occurred in prepare().
    Aborting...
  -> Removed BIG_UGLY_FROGMINER - Ribbit
  -> Removed Proton-tkg token - Valve Ribbit
  -> exit cleanup done
`

**Comment by Tk-Glitch** [comment]
Wine staging currently can't build. Until this is resolved upstream, you'll have to apply the first hotfix "derp_4.12.1r4.mystagingpatch" when prompted.

**Comment by Tk-Glitch** [comment]
Fixed upstream
