### ISSUE TITLE
grub-quiet package not compatible with recent build

### ISSUE THREAD

**Issue by ryanmusante** [Tk-Glitch/PKGBUILDS#25]
After most recent update to grub-quiet package from philip @ manjaro, errors at boot.
It appears standard grub package is free of this error because I re-installed standard and rebooted. Why would this be conflicting with the kernel?
```
Oct 14 11:30:09 xmg systemd[2384]: Starting Mark boot as successful...
Oct 14 11:30:09 xmg grub-set-bootflag[6638]: Error opening //boot/grub/grubenv for writing: Permission denied
Oct 14 11:30:09 xmg systemd[2384]: grub-boot-success.service: Main process exited, code=exited, status=1/FAILURE
Oct 14 11:30:09 xmg systemd[2384]: grub-boot-success.service: Failed with result 'exit-code'.
Oct 14 11:30:09 xmg systemd[2384]: Failed to start Mark boot as successful.
```
I don't know if it is loading more/less modules. I keep my modorobed database up to date.

**Comment by Tk-Glitch** [comment]
Does it work with manjaro's stock kernel ?
It would help to know what changed with the package/source, but I can't find any current source. At this point I'll just consider that it's a manjaro issue.

**Comment by ryanmusante** [comment]
I posted in the forum. He fixed it and released it into testing branch. It's nothing to do with the kernel, sorry.

![_20181014_224951](https://user-images.githubusercontent.com/26808646/46917570-bb42da00-d003-11e8-98c7-3fa338ca277b.JPG)
