### ISSUE TITLE
Wine Staging using FAudio library now. May be need some changes to the wine-tkg-git PKGBUILD?

### ISSUE THREAD

**Issue by Kerrung** [Tk-Glitch/PKGBUILDS#250]
https://github.com/wine-staging/wine-staging/commit/b95b9109b824d21d98329c76387c3983d6e27cc2

**Comment by Tk-Glitch** [comment]
I was sleeping like a baby. And I'll now proceed and try to get back to it :frog:

**Comment by openglfreak** [comment]
You don't have to get up just to fix (non-)issues like this.

**Comment by Tk-Glitch** [comment]
But, but, Mooooooooooooooom...

**Comment by t14462** [comment]
FAudio conflicting with staging-pulse, and you can not use it together in your games.

So, not yet.
