### ISSUE TITLE
esync description not fully clear

### ISSUE THREAD

**Issue by aufkrawall** [Tk-Glitch/PKGBUILDS#251]
Hello,
would it be possible to add a note that esync support is enabled by default for staging at compile time? It's looks like `_use_esync="true"` is required, but it is not, which is gruesome to autists. Of course the note to enable it via variable at run time is correct regardless.

**Comment by Kerrung** [comment]
esync support is enabled by default by Wine Staging upstream, so, the frogmans not guilty.

**Comment by Kerrung** [comment]
esync support is enabled by default by Wine Staging upstream, so, the frogs not guilty.

**Comment by aufkrawall** [comment]
Never doubted that. ty, Etienne. :+1:
