### ISSUE TITLE
Possible temp patch needed for Linux 5.2.x KVM users

### ISSUE THREAD

**Issue by ronoverdrive** [Tk-Glitch/PKGBUILDS#253]
For [Bug,204209] kernel 5.2.1: "floating point exception" in qemu with kvm enabled

Apparently this is causing Win10 to bluescreen in a KVM and and people on reddit are reporting this has not yet been fixed upstream. Dunno if this affects 5.3. I haven't played with my KVM in a while since currently there's only one game I need it for at the moment, but will confirm whether or not its broken when I get home later tonight.

But report: https://lkml.org/lkml/2019/7/17/758
Kernel Bugzilla: https://bugzilla.kernel.org/show_bug.cgi?id=204209
Patch: https://patchwork.kernel.org/patch/11050587/

**Comment by Tk-Glitch** [comment]
Interestingly I was testing a different patch (successfully). I'll try that one as it's less invasive.
