### ISSUE TITLE
The child window rendering fix produces a black screen with Treasure Adventure Game, newer patch available

### ISSUE THREAD

**Issue by CartoonFan** [Tk-Glitch/PKGBUILDS#255]
Hello! It seems that [Treasure Adventure Game](http://robitgames.com/treasure-adventure-game/) makes use of child window rendering when using D9VK. The patch from this repo seems to only load the "Robit Games" screen before displaying a black screen. However, there seems to be a newer patch using Xcomposite, available [here](https://github.com/felixhaedicke/wine/commit/4cc738f609faff68bf4c67d5618174fa87ab3cdb.patch), which seems to fix the black screen problem. I left a few comments on the [wine bug report](https://bugs.winehq.org/show_bug.cgi?id=45277), but wanted to let you know as well. I'm using Wine-TKG 4.12.1 and the latest master from D9VK. Thanks!

**Comment by Tk-Glitch** [comment]
Hi! I am aware of Felix's pending patch and I'm following that issue closely as the patch still has issues. But if at least something gets fixed with it that wasn't fixed by the earlier hacky patch (that so called "woff_fix") I guess it's time to merge it indeed.
