### ISSUE TITLE
mingw: still needs mingw-w64-pkg-config

### ISSUE THREAD

**Issue by skeevy420** [Tk-Glitch/PKGBUILDS#256]
mingw-w64-cmake depends on it....though the script still isn't finishing because the AUR went down, lol.

**Comment by Tk-Glitch** [comment]
Why did we need this stuff again? :frog:

**Comment by skeevy420** [comment]
Don't know, but if SDLANDCO is set to true it wants mingw-w64-cmake which tries to pull in pkg-config which causes the build script to fail.

According to the AUR page on this, there's a workaround to use the Linux pkg-config via setting an environment variable...but the AUR is down so I can't copy/paste it :smile_cat:
