### ISSUE TITLE
suggestion: add Mesa userpatch to revert performance regression in HotS with Radv

### ISSUE THREAD

**Issue by aufkrawall** [Tk-Glitch/PKGBUILDS#257]
Hello,
there is still this performance regression:
https://github.com/mesa3d/mesa/commit/0a313cc285c2939de9cac07f045b0b699bc208ca

Reverting this commit fixes it and I'm not aware of any practical harm when doing so:
https://github.com/mesa3d/mesa/commit/0a313cc285c2939de9cac07f045b0b699bc208ca

**Comment by Kerrung** [comment]
@aufkrawall Is the bug report already written on the official Mesa bugzilla?

**Comment by aufkrawall** [comment]
It would appear I spectacularly failed when it came to copy and paste:
https://bugs.freedesktop.org/show_bug.cgi?id=110995

**Comment by aufkrawall** [comment]
@Tk-Glitch I noticed that for some reason building radv now fails when having that commit reverted (it still works with mesa-aco master). Though not having it reverted unfortunately still affects performance (~160 vs ~145-150fps).
