### ISSUE TITLE
snd-aloop module is gone

### ISSUE THREAD

**Issue by barfin** [Tk-Glitch/PKGBUILDS#259]
[snow@arch ~]$ sudo modprobe snd-aloop
modprobe: FATAL: Module snd-aloop not found in directory /lib/modules/5.2.5-15-tkg-pds

**Comment by skeevy420** [comment]
It's available on 5.2.5-15-tkg-bmq.  Is this possibly a modprobe-db issue?

**Comment by Tk-Glitch** [comment]
The module is there on my install. Definitely sounds like yet another modprobed-db issue. Your VPN issue might also be related.

**Comment by barfin** [comment]
> The module is there on my install. Definitely sounds like yet another modprobed-db issue. Your VPN issue might also be related.

sooo what can i do about it right now?

**Comment by skeevy420** [comment]
Short answer: rebuild the kernel without modprobe-db.

Long answer: the short answer with a chroot and a live environment.
