### ISSUE TITLE
Add Futex()/fsync to tkg-wine, like in Proton

### ISSUE THREAD

**Issue by t14462** [Tk-Glitch/PKGBUILDS#262]
Add Futex()/fsync to tkg-wine, like in Proton

Now Im building tkg-kernel, and it asks me about fsync esync replacement. And my answer was Yes. I read some articles and comments, and everyone says fsync is better.

And this "fsync" now can use only Valve's Proton? - I wanna use it in tkg-wine!

**Comment by Tk-Glitch** [comment]
It's being worked on but not yet ready.

**Comment by DxCx** [comment]
Is futex/fsync effects perforemce with vulkan (d9vk) as well?

**Comment by tycho** [comment]
d9vk/dxvk are unrelated, but their performance would likely be improved as a side effect.

The fsync and esync patches affect synchronization primitives (mutexes, semaphores, events, basically any waitable object). So fsync affects performance for everything across the board.

**Comment by DxCx** [comment]
Awsome :) thanks. (Thats what i was expected)

**Comment by Faalagorn** [comment]
🎉

**Comment by Tk-Glitch** [comment]
Couple numbers from my own testing on the Hitman: Absolution benchmark (that was pretty receptive to fsync) - These are average framerates:
Fsync: 138 fps
Esync: 126 fps
Stock: 103 fps
