### ISSUE TITLE
linux-tkg: block acpi_cpufreq module for Ryzen profiles?

### ISSUE THREAD

**Issue by aufkrawall** [Tk-Glitch/PKGBUILDS#263]
Hello Etienne,
I recently stumbled over an issue where acpi_cpufreq caused excessive frametime spikes with power saving features on a Ryzen 2600 CPU. Changing the governor to performance didn't improve the situation, only turning off lower pstates in bios or blacklisting the acpi_cpufreq module helped.
It might be related to specific mainboards (in this case Taichi X470) due to possible ACPI shenanigans, but I guess it's not unlikely that other systems are affected as well.
Fortunately, still a lot of power is saved (in complete idle basically same consumption) when blacklisting that module and keeping lower pstates enabled in the bios at the same time.

So, it might be viable to offer blacklisting that module in your tkg-customization?

**Comment by terencode** [comment]
Is there a simple test to know if you are affected?

**Comment by aufkrawall** [comment]
Probably trying some games with vsync which are lightweight on the CPU.
The issue reproducibly occured in Heroes of the Storm with 60Hz vsync on Polaris 10/20 GPU, there was reoccurring heavy stutter every x seconds by not much going on inside the game at the same time.

Btw: Thx @Tk-Glitch for implementing!

**Comment by Tk-Glitch** [comment]
You're welcome @aufkrawall !

**Comment by terencode** [comment]
Any downside to have it disabled?

**Comment by Tk-Glitch** [comment]
Power consumption in non-idle states, basically
