### ISSUE TITLE
Wine-TkG doesnt recognize my gamepad (regression)

### ISSUE THREAD

**Issue by t14462** [Tk-Glitch/PKGBUILDS#265]
Old wine and Proton does recognize my 3rd-party gamepad, but TkG-wine doesnt.

Wine seeing gamepad, but in games it doesnt work

**Comment by ronoverdrive** [comment]
Have you tried this? https://wiki.archlinux.org/index.php/Gamepad#Joystick_not_recognized_by_all_programs

**Comment by Tk-Glitch** [comment]
Also, https://github.com/Tk-Glitch/PKGBUILDS/commit/bd39bf46adc1272a702ec1dcd599db0c841a8700#comments

**Comment by rodrigo21** [comment]
I have the same problem with my DualShock 3. If you update a prefix to wine-staging 4.13 the game stop recognizing the joystick. But if you create a new prefix with 4.13 it works normally. wine-tkg-git with staging and wine-staging 4.13 from the Arch repo have this problem, wine 4.13 from the Arch repo and Proton 4.11 doesn't. Tested with GRID 2 and Trails in the Sky.

**Comment by Tk-Glitch** [comment]
The problematic patchset indeed is part of staging. The solution I have linked above should be enough to get your old prefixes to work though.

**Comment by t14462** [comment]
removing HKLM/System/CurrentControlSet/Enum/ROOT/WINE/WINEBUS key in registry and running wineboot -u - helps me, thanks!

**Comment by Tk-Glitch** [comment]
Great news :)

**Comment by Tk-Glitch** [comment]
Time to get @skeevy420 to give it a try as well

**Comment by skeevy420** [comment]
Thanks for the idea but, unfortunately, that didn't help anything for me.  :frowning_face: 

My issue over at Proton was updated: they're able to reproduce it and there should be a fix coming for that Hitman 2/PS4 controller issue in an upcoming Proton release.  :smiley

**Comment by telans** [comment]
Is this fixed with the recent Proton releases? There are a few things in the patchnotes about PS4 controllers

**Comment by skeevy420** [comment]
Yes, at least for my issues at that time it is.  

AFAICT in regards to controllers, Hitman 2 is now down to just dealing with that pesky amdgpu excessive xscreensaver stay awake calls from joystick input bug now.

**Comment by Tk-Glitch** [comment]
Seems safe to close this now
