### ISSUE TITLE
proton build fails with _LOCAL_OPTIMIZED="false"

### ISSUE THREAD

**Issue by aufkrawall** [Tk-Glitch/PKGBUILDS#269]
Hello,
then this happens:
[error.log](https://github.com/Tk-Glitch/PKGBUILDS/files/3488966/error.log)
It works with the default of `true` (haven't changed the GCC flags in makepkg.conf). I use mingw-gcc from your PKGBUILDs.

**Comment by aufkrawall** [comment]
Thank you, building succeeded. I wonder if this could also be helpful with the precompiled mingw packages available in the AUR.

**Comment by Tk-Glitch** [comment]
Likely. However you'd be missing out on dwarf2 perf boost for 32-bit.

**Comment by aufkrawall** [comment]
I totally forget about this, and it apparently explains why CPU performance was so bad with my D9VK mingw builds. :tropical_drink:
