### ISSUE TITLE
gitignore additions

### ISSUE THREAD

**Issue by mpalermo73** [Tk-Glitch/PKGBUILDS#273]
I was wondering if you'd consider adding these to .gitignore:

- *.tar.gz
- *.old
- *.db
- *.files

These are extensions of files that get created when creating a local pacman repo.  I decided to just make mine right in the PKGBUILDS/wine-tkg-git tree so I didn't have to mv the resultant tarballs of a build out to another directory.

```
Untracked files:
  (use "git add <file>..." to include in what will be committed)

        wine-tk.db
        wine-tk.db.tar.gz
        wine-tk.db.tar.gz.old
        wine-tk.files
        wine-tk.files.tar.gz
        wine-tk.files.tar.gz.old
```

**Comment by telans** [comment]
Why not gitignore all then whitelist files/directories as you need them?

**Comment by skeevy420** [comment]
Or write a script to build and move everything as necessary?

Or use a clean chroot and have its makepkg.conf PKGDEST variable set to use the custom repo?

Or be lazy and do the above without a clean chroot?

**Comment by Tk-Glitch** [comment]
These are looking good to me and will be added shortly
