### ISSUE TITLE
proton-tkg-staging.patch failed in dlls/kernel32/module.c

### ISSUE THREAD

**Issue by telans** [Tk-Glitch/PKGBUILDS#275]
Patch refers to code moved out of `dlls/kernel32/module.c` and into `dlls/kernelbase/loader.c` with commit https://github.com/wine-mirror/wine/commit/05d00276c627753487c571c30fddfc56c02ad37e

`patching file dlls/kernel32/module.c`
`Hunk #1 succeeded at 77 (offset 1 line).`
`Hunk #2 FAILED at 727.`
`Hunk #3 FAILED at 835.`
`Hunk #4 succeeded at 735 (offset -476 lines).`
`Hunk #5 succeeded at 758 with fuzz 2 (offset -467 lines).`
`Hunk #6 succeeded at 943 with fuzz 1 (offset -467 lines).`
`Hunk #7 succeeded at 1000 (offset -461 lines).`
`2 out of 7 hunks FAILED -- saving rejects to file dlls/kernel32/module.c.rej`

[module.c.rej.log](https://github.com/Tk-Glitch/PKGBUILDS/files/3495221/module.c.rej.log)

**Comment by Tk-Glitch** [comment]
Addressed by https://github.com/Tk-Glitch/PKGBUILDS/commit/bf417d6f6506cd5da90a6afd7298e98ef99ec9bf
I'm not sure about Julliard's plans here but that'll do for now :frog:

**Comment by telans** [comment]
Just a question if you wouldn't mind, @Tk-Glitch 

Should the various -git packages in here update automatically when using a package manager that does `Checking development packages...` (i.e. `yay`), or is that just for -git packages from the AUR?

Cheers

**Comment by openglfreak** [comment]
@telans Yay only picks up packages built and installed through yay. Same with other aur package managers.
