### ISSUE TITLE
nvidia-all: unable to satisfy dependency 'nvidia-utils-tkg'

### ISSUE THREAD

**Issue by telans** [Tk-Glitch/PKGBUILDS#276]
I'm updating nvidia to use the new package names you set a few commits ago.

After the prompts for removing old (conflicting) packages, I get the following error:

`error: failed to prepare transaction (could not satisfy dependencies)`
`:: unable to satisfy dependency 'nvidia-utils-tkg>=418.52.20' required by nvidia-dev-dkms-tkg`
`:: unable to satisfy dependency 'nvidia-utils-tkg' required by lib32-nvidia-dev-utils-tkg`
`==> WARNING: Failed to install built package(s).`
`  -> exit cleanup done`

I think depends() needs to be updated in the PKGBUILD to include `nvidia-dev-utils-tkg`?

Cheers

**Comment by Tk-Glitch** [comment]
Oh yeah that makes sense. Fix incoming.
