### ISSUE TITLE
tkg-mwo cannot run MWO past ~4.13.r3

### ISSUE THREAD

**Issue by Gagis** [Tk-Glitch/PKGBUILDS#283]
I use wine-tkg to play MechWarrior Online, but any builds newer than my pkg for 4.13.r3 result in a hard crash of the dotnet based launcher. The 4.13.r3 version still works just fine with dotnet452 installed.

**Comment by Tk-Glitch** [comment]
The hotfix that was pushed with https://github.com/Tk-Glitch/PKGBUILDS/commit/5cd38429a5d5df6b151a4b4efa98724ba193ace1#diff-410db0d6d78fed0dbe64a6a4e5025e00 might fix your issue. Please let me know, thanks :)

**Comment by ronoverdrive** [comment]
If that doesn't work in the mean time you could always use the Steam client either using Lutris's Winesteam or using Proton-tkg with the MWO patch since it doesn't use the .NET launcher.

**Comment by Gagis** [comment]
The hotfix works beautifully. Thank you very much for including it.
