### ISSUE TITLE
Raw input patch combined with fsync patch degrades Battlefield V performance

### ISSUE THREAD

**Issue by Sporif** [Tk-Glitch/PKGBUILDS#284]
With the rawinput patch, Battlefield V's performance seems as expected at first. But after a few matches, the fps drops to around 75-100fps. Decreasing quality settings or resolution has no effect, almost as if there's a CPU bottleneck. But CPU usage doesn't increase, nor does the game start to stutter. Only GPU usage decreases.

Early versions of the rawinput patch severely impacted performance and mouse input handling in Battlefield games, but over time new updates of the patch fixed the input and performance in all of them except BFV. Though the input is now working fine in BFV too, it's just the fps that degrades after a while.

@Guy1524

**Comment by openglfreak** [comment]
What's the polling rate of your mouse?

**Comment by Sporif** [comment]
Currently 500Hz. But that doesn't seem to matter since the still issue occurs when I set it to 100Hz.

**Comment by openglfreak** [comment]
Are you using the fsync patchset? Maybe that's the problem, because I know that that is the problem for me with Overwatch + raw-input.

**Comment by Tk-Glitch** [comment]
Is it still a thing as of https://github.com/Tk-Glitch/PKGBUILDS/commit/2b7439ac70bac94e85bdd63ab8ce081de9097d5a ?

**Comment by Sporif** [comment]
I would test it, but wine-staging 4.15 seems a bit broken, Overwatch shows only a black screen on start and BFV crashes a few seconds after starting. And the patch fails to apply on 4.14.

**Comment by Sporif** [comment]
@openglfreak I tried rawinput without the fsync patchset and that fixed the issue. Enabling the patchset but disabling fsync doesn't fix it though.

**Comment by Tk-Glitch** [comment]
As of https://github.com/Tk-Glitch/PKGBUILDS/commit/bf9759dbbe99551602c35b3f33240fde373cda12, you can choose not to use the staging shipped patchset and either disable it or use the local "fixed" patchset instead.

**Comment by Tk-Glitch** [comment]
I'll close this for now as the raw input patchset the issue was encountered against is deprecated and not part of wine-tkg anymore. The rewrite of that patch is available in community-patches, with various known issues, and will need more work before I merge it again as a builtin option/maintained patchset.
