### ISSUE TITLE
Compile Failed ... Manjaro 64bit

### ISSUE THREAD

**Issue by d4vid1** [Tk-Glitch/PKGBUILDS#285]
error: Anwendung des Patches fehlgeschlagen: dlls/ntoskrnl.exe/tests/driver.c:1712
error: dlls/ntoskrnl.exe/tests/driver.c: Patch konnte nicht angewendet werden
ERROR: Failed to apply patch, aborting!

Thank you!

**Comment by telans** [comment]
Which patch?

**Comment by d4vid1** [comment]
> Which patch?

i dont know... 

thnx

**Comment by mkaito** [comment]
That would be 

```
Applying /tmp/makepkg/wine-tkg-git/src/wine-staging-git/patches/winedevice-Default_Drivers/0004-programs-winedevice-Load-some-common-drivers-and-fix.patch
error: patch failed: dlls/ntoskrnl.exe/tests/driver.c:1712
error: dlls/ntoskrnl.exe/tests/driver.c: patch does not apply
```

**Comment by openglfreak** [comment]
Make sure you use the latest mester of this repo.

**Comment by mkaito** [comment]
Yep, I'm up to date.

**Comment by openglfreak** [comment]
And you are saying yes to applying the hotfix, right?

**Comment by Tk-Glitch** [comment]
Staging is currently broken upstream. You need to either apply the hotfix I have added with https://github.com/Tk-Glitch/PKGBUILDS/commit/e948498a18e105516fc0976fc22b0a0380dcf8d5 or wait for wine-staging maintainers to fix it on their end (likely in a few hours).

**Comment by Tk-Glitch** [comment]
Fixed upstream
