### ISSUE TITLE
Ys Origin crashes with ".exeCreateFile failed. Error: 32" on wine-tkg 4.14

### ISSUE THREAD

**Issue by CartoonFan** [Tk-Glitch/PKGBUILDS#287]
Hello. Ys Origin seems to crash with wine-tkg 4.14 but not with lutris-4.13. I've tried disabling the options that differ individually, but nothing seems to fix it. I'm thinking it's a Wine issue, but I don't know what else to try. Thanks.

**Comment by Tk-Glitch** [comment]
That definitely sounds like an upstream issue since lutris-4.13 is basically wine-tkg 4.13. Interestingly a quick search about that specific error string gets me to some EasyAntiCheat error.. But I can't find anything about that game using it. I'll investigate.

**Comment by CartoonFan** [comment]
I don't know what happened, but it seems to be working as of wine-staging 4.14.r20.g49aafeb1. I think it's safe to close this now. Of course, you're welcome to investigate further if you like :smile: 

Closing #287.

**Comment by soredake** [comment]
I see the same error with gog version of "Corpse Party" with latest wine-tkg

**Comment by CartoonFan** [comment]
I don't have "Corpse Party", so I can't really test that. I could try testing Ys Origin again when I have time, though.

**Comment by CartoonFan** [comment]
Ys Origin seems fine on my end with wine-4.16.r12.g649c35ff ( TkG Staging Esync Fsync Vkd3d ).

**Comment by soredake** [comment]
nothing changed after upgrading to wine-4.17.r0.g9fe5cabf ( TkG Staging Esync Fsync Vkd3d ), maybe my old prefix is frogged

**Comment by CartoonFan** [comment]
I guess it could be also be something that Corpse Party does differently than Ys Origin, although I haven't seen too many issues like that. I also didn't test super thoroughly, but last time it crashed before the title screen, so I assumed it was fine. I'm really curious though, as it seems like a reoccurring issue that gets magically fixed at some point. I guess it's safe to reopen this for now if you're still experiencing this error.

**Comment by Tk-Glitch** [comment]
@soredake Even though the issue might effectively be different here, was Corpse Party fixed since, or is this still an issue? I don't see an open issue for that game on winehq so you may want to report it if it's still frogged.

**Comment by soredake** [comment]
Can't test with latest wine (stuck on 4.18), 4.19 or gcc 9.2.0 (?) has a regression that causes wine to throw "floating point exception" at start with esync or fsync enabled.

**Comment by soredake** [comment]
These commits looks like a fix to my problem, i'll try compiling new version
https://github.com/Tk-Glitch/PKGBUILDS/commit/6c181d78633198e7f60f79039cc69869a07e032b
https://github.com/Tk-Glitch/PKGBUILDS/commit/b134995280895cff36d8af9780064bed3c24c2df

**Comment by soredake** [comment]
It works now with d9vk (otherwise it will display black screen), error is gone, black screen log, if needed:
```
0009:fixme:win:WINNLSEnableIME hwnd 0x30066 enable 0: stub!
0009:fixme:ddraw:ddraw7_WaitForVerticalBlank iface 001E0380, flags 0x1, event 00000000 stub!
0095:err:d3d:resource_unload Resource 0x21ee00 is being unloaded while mapped.
0095:err:d3d:resource_unload Resource 0x21f010 is being unloaded while mapped.
0095:err:d3d:resource_unload Resource 0x21ee00 is being unloaded while mapped.
0095:fixme:d3d:state_fillmode Unrecognized fill mode 0.
0095:fixme:d3d:state_linepattern_w Setting line patterns is not supported in OpenGL core contexts.
0095:fixme:d3d_shader:glsl_vertex_pointsprite_core Non-point sprite points not supported in core profile.
```

**Comment by CartoonFan** [comment]
Glad to hear your problem's solved. For now, I'm planning to close this again. If the issue reappears, I'll reopen it, I guess.
