### ISSUE TITLE
zswap on kernel-tkg (systemd-swap)

### ISSUE THREAD

**Issue by t14462** [Tk-Glitch/PKGBUILDS#291]
Something wrong with zswap subsystem on TkG-kernels. systemd-swap shouting on boot "Can't enable zswap, no pool configured"

➜  ~ grep -R . /sys/module/zswap/parameters
/sys/module/zswap/parameters/same_filled_pages_enabled:Y
/sys/module/zswap/parameters/enabled:N  <=== This
/sys/module/zswap/parameters/max_pool_percent:25
/sys/module/zswap/parameters/compressor:zstd
/sys/module/zswap/parameters/zpool:z3fold

On stock Manjaro kernels everything is OK

Maybe zswap on TkG compiles as module? So on stock kernel it compiled inside

**Comment by Tk-Glitch** [comment]
I can't reproduce your issue on Arch.
```
~ journalctl -b | grep zswap
Aug 31 01:04:39 glitcher kernel: zswap: loaded using pool lz4/zbud
```
```
~ grep -R . /sys/module/zswap/parameters
/sys/module/zswap/parameters/same_filled_pages_enabled:Y
/sys/module/zswap/parameters/enabled:Y
/sys/module/zswap/parameters/max_pool_percent:20
/sys/module/zswap/parameters/compressor:lz4
/sys/module/zswap/parameters/zpool:zbud
```
And no the config is a stock Archlinux one, zswap is builtin:
```
CONFIG_ZSWAP=y
CONFIG_ZPOOL=y
CONFIG_ZBUD=y
CONFIG_Z3FOLD=y
```

**Comment by t14462** [comment]
it happens with that script "systemd-swap", maybe a better idea say them about it...

**Comment by telans** [comment]
Related?

`[telans@desktop ~]$ sudo journalctl -b | grep zswap`
`Aug 31 desktop kernel: zswap: default compressor lz4 not available`
`Aug 31 desktop kernel: zswap: pool creation failed`
`[telans@desktop ~]$ grep -R . /sys/module/zswap/parameters`
`/sys/module/zswap/parameters/same_filled_pages_enabled:Y`
`/sys/module/zswap/parameters/enabled:N`
`/sys/module/zswap/parameters/max_pool_percent:20`
`/sys/module/zswap/parameters/zpool:zbud`

**Comment by Tk-Glitch** [comment]
I just did a comparison between manjaro current stable kernel config against the stock archlinux current stable kernel config and they are exactly the same regarding our matter here. The couple lines that are different in the whole config are unrelated. Your issue doesn't seem to have anything to do with the kernel itself, assuming you're using the shipped default  config, not using modprobed-db and that you're using the same command line options on both kernels.

@telans Nope. That one is completely normal/expected unless you add `lz4` and `lz4_compress` to your ramdisk : https://wiki.archlinux.org/index.php/Zswap

**Comment by t14462** [comment]
Ahh... I don't want to mess with system, so I just added kernel options for zswap and everything works OK.

I don't know where problem is. If it's no kernel - I don't know where...

**Comment by skeevy420** [comment]
Ran a few tests on Manjaro with two tkg kernels.

```
4.19-tkg
[fluffycat@blackhole ~]$ journalctl -b | grep zswap
Aug 31 06:32:47 blackhole kernel: Command line: BOOT_IMAGE=/@/boot/vmlinuz-linux419-tkg-pds root=UUID=60893d8e-b042-49fb-99b5-fb13d138b6fc rw rootflags=subvol=@ amdgpu.dpm=1 amdgpu.dc=1 amdgpu.ppfeaturemask=0xfffd7fff amdgpu.deep_color=1 amdgpu.exp_hw_support=1 zfs.zfs_arc_max=8589934592 zswap.enabled=1 zswap.compressor=zstd zswap.max_pool_percent=20 zswap.zpool=z3fold
Aug 31 06:32:47 blackhole kernel: Kernel command line: audit=0  BOOT_IMAGE=/@/boot/vmlinuz-linux419-tkg-pds root=UUID=60893d8e-b042-49fb-99b5-fb13d138b6fc rw rootflags=subvol=@ amdgpu.dpm=1 amdgpu.dc=1 amdgpu.ppfeaturemask=0xfffd7fff amdgpu.deep_color=1 amdgpu.exp_hw_support=1 zfs.zfs_arc_max=8589934592 zswap.enabled=1 zswap.compressor=zstd zswap.max_pool_percent=20 zswap.zpool=z3fold
Aug 31 06:32:47 blackhole kernel: zswap: compressor zstd not available, using default lz4
Aug 31 06:32:47 blackhole kernel: zswap: loaded using pool lz4/z3fold
[fluffycat@blackhole ~]$ grep -R . /sys/module/zswap/parameters
/sys/module/zswap/parameters/same_filled_pages_enabled:Y
/sys/module/zswap/parameters/enabled:Y
/sys/module/zswap/parameters/max_pool_percent:20
/sys/module/zswap/parameters/compressor:zstd
/sys/module/zswap/parameters/zpool:z3fold

5.2-tkg
[fluffycat@blackhole ~]$ journalctl -b | grep zswap
Aug 31 06:40:25 blackhole kernel: Command line: BOOT_IMAGE=/@/boot/vmlinuz-linux52-tkg-pds root=UUID=60893d8e-b042-49fb-99b5-fb13d138b6fc rw rootflags=subvol=@ amdgpu.dpm=1 amdgpu.dc=1 amdgpu.ppfeaturemask=0xfffd7fff amdgpu.deep_color=1 amdgpu.exp_hw_support=1 zfs.zfs_arc_max=8589934592 zswap.enabled=1 zswap.compressor=zstd zswap.max_pool_percent=20 zswap.zpool=z3fold
Aug 31 06:40:25 blackhole kernel: Kernel command line: BOOT_IMAGE=/@/boot/vmlinuz-linux52-tkg-pds root=UUID=60893d8e-b042-49fb-99b5-fb13d138b6fc rw rootflags=subvol=@ amdgpu.dpm=1 amdgpu.dc=1 amdgpu.ppfeaturemask=0xfffd7fff amdgpu.deep_color=1 amdgpu.exp_hw_support=1 zfs.zfs_arc_max=8589934592 zswap.enabled=1 zswap.compressor=zstd zswap.max_pool_percent=20 zswap.zpool=z3fold
Aug 31 06:40:25 blackhole kernel: zswap: loaded using pool zstd/z3fold
[fluffycat@blackhole ~]$ grep -R . /sys/module/zswap/parameters
/sys/module/zswap/parameters/same_filled_pages_enabled:Y
/sys/module/zswap/parameters/enabled:Y
/sys/module/zswap/parameters/max_pool_percent:20
/sys/module/zswap/parameters/compressor:zstd
/sys/module/zswap/parameters/zpool:z3fold```

The gist is that zstd may or may not be the culprit.  Using it throws errors on boot with 4.19 in journalctl and yet shows working with grep while it works just fine with 5.2.  If you're using the 4.19 kernel, just switch over to lzo or lz4 and see if that helps.  

systemd-swap works just fine on Manjaro with tkg kernels.  The issue is likely something else.

@t14462 You do have a backing swap drive, partition, or file, right? zswap doesn't work without one.  If you don't, either use the swap file option of systemd-swap or change to the zram option right below.  Luckily, I played the game Adventures With Tumbleweed yesterday so I just happen to have a swap partition available to test because I'm normally swapless and using zram from this script on Manjaro (I have 48gb of ram so I can safely run w/o a physical swap).

Here's my zswap line for the times I do use zswap...updated with zstd.  If z3fold isn't set during boot then the zswap will use zbud up until the script switches it to z3fold provided you set it to z3fold in swap.conf.  z3fold should be better and help give more compression.

`zswap.enabled=1 zswap.compressor=zstd zswap.max_pool_percent=20 zswap.zpool=z3fold`

I am glad to know that zstd works with 5.2.  Nice little optimization to learn upon waking up.

**Comment by t14462** [comment]
I have swapfc options in systemd-swap, it's automatic 500MB swap files allocations. I haven't regular swap file or partition.

**Comment by CodingKoopa** [comment]
I've always gotten these two errors with the TkG kernel:
```
Oct 19 13:06:14 archlinux kernel: zswap: default compressor lz4 not available
Oct 19 13:06:14 archlinux kernel: zswap: pool creation failed
```
I don't get these errors on the stock Arch kernel, and I'm just using normal swap; that is, using Zswap at all is undesired behavior in the case of my setup. I don't have the `systemd-swap` package installed, and I don't have the `zswap.enabled` kernel parameter set (and booting with `zswap.enabled=0` produces the same two errors).

**Comment by Tk-Glitch** [comment]
@CodingKoopa I've explained the lz4 part here already, answering to telans : https://github.com/Tk-Glitch/PKGBUILDS/issues/291#issuecomment-526787159
Zswap starts early enough for the lz4 modules not to be loaded at that time. Adding them to your ramdisk is enough to fix it.

**Comment by CodingKoopa** [comment]
Ah yes that did fix the errors, pardon the noise.

**Comment by Tk-Glitch** [comment]
No problem, I'm happy to help

**Comment by Tk-Glitch** [comment]
I have made the lz4 modules zswap is using builtin on current linux54-tkg so the early loading of the modules isn't needed anymore. Unless the systemd-swap script requires a specific algorithm to be used on boot to work it should fix the root issue.
