### ISSUE TITLE
Patching mouse.c Fails

### ISSUE THREAD

**Issue by mpalermo73** [Tk-Glitch/PKGBUILDS#292]
Patching mouse.c fails when trying to build wine-tkg-git

```
patching file dlls/winex11.drv/mouse.c
Hunk #1 succeeded at 380 (offset -4 lines).
Hunk #2 FAILED at 458.
1 out of 2 hunks FAILED -- saving rejects to file dlls/winex11.drv/mouse.c.rej
```

[mouse.c.rej.txt](https://github.com/Tk-Glitch/PKGBUILDS/files/3562408/mouse.c.rej.txt)

git current as of:
commit 752a8b2ef4f36cf0d9e57ff3487a91a53dbfdc9f
Date:   Sat Aug 31 09:49:02 2019 +0200

Manjaro
5.2.8-1-MANJARO

**Comment by Tk-Glitch** [comment]
staging + raw input enabled fixed by https://github.com/Tk-Glitch/PKGBUILDS/commit/752a8b2ef4f36cf0d9e57ff3487a91a53dbfdc9f

staging + raw input disabled fixed by https://github.com/Tk-Glitch/PKGBUILDS/commit/9df95c90ac60f4f1b2123133dc943e3c420078db
