### ISSUE TITLE
Regression: Rawinput and wayland

### ISSUE THREAD

**Issue by A6GibKm** [Tk-Glitch/PKGBUILDS#293]
## Setup
Fedora Silverblue 30
Wayland
DXVK 1.3.3
Lutris 0.5.2
wine-tkg 4.15.r0.ga46b9ff3

## Description 
In Overwatch mouse movement isn't being registered while in-game. This was working in 4.12.1.r0.gf0718137.

While it is probably out ot the scope of this build, it is possible to use libinput instead of xinput?

**Comment by aufkrawall** [comment]
I got issues with TESIV: Oblivion on xwayland fullscreen, mouse look doesn't work freely and instead stops after a short distance. It used to work before.

**Comment by Tk-Glitch** [comment]
The xwayland regressions with the raw input patchset have been acknowledged and the author is working on it.
@Guy1524 if you need more testers, feel free to ping my lovely users.

**Comment by Guy1524** [comment]
I think I know a workaround for the xwayland issues, will post when I get on a pc.

**Comment by A6GibKm** [comment]
@aufkrawall, the mouse somethimes gets locked to the area of another app's window. Alt-tab seems to fix that.

**Comment by Guy1524** [comment]
Try applying this commit on top: https://github.com/Guy1524/wine/commit/1a1288d4456187ac5509df03081a5f311a973100

**Comment by aufkrawall** [comment]
I had to set `_rawinput_fix="true"` in order to apply your patch. Unfortunately, the issue is unchanged. It works with regular Wine non-staging from Arch repo.

**Comment by A6GibKm** [comment]
How do I build this with that patch?

**Comment by Tk-Glitch** [comment]
@A6GibKm Basically https://github.com/Tk-Glitch/PKGBUILDS/tree/master/wine-tkg-git/wine-tkg-userpatches

**Comment by Guy1524** [comment]
I found a workaround: https://github.com/Guy1524/wine/commit/ba66be90b756717ccaf7afa062f53ee5197e4cbb

**Comment by aufkrawall** [comment]
Thanks @Guy1524 , but I can't get this applied to wine-staging-tkg, no matter if `_rawinput_fix="true"` or `false`.

 > patching file dlls/winex11.drv/mouse.c
Hunk #2 succeeded at 1860 (offset 83 lines).
Hunk #3 FAILED at 1804.
Hunk #4 FAILED at 1890.
2 out of 4 hunks FAILED -- saving rejects to file dlls/winex11.drv/mouse.c.rej
 >

Perhaps @Tk-Glitch could make us blind see (or get this to work at least)? :)

**Comment by openglfreak** [comment]
@aufkrawall Set _rawinput_fix to false and do `curl https://github.com/wine-mirror/wine/compare/master...Guy1524:rawinput.patch -o wine-tkg-userpatches/rawinput.mypatch` in the wine-tkg-git directory. That will put the latest version of the rawinput patchset as a userpatch. If you want to update the userpatch just do the same command again.

**Comment by aufkrawall** [comment]
Thank you, but this fails as well:
[error.log](https://github.com/Tk-Glitch/PKGBUILDS/files/3576468/error.log)

**Comment by openglfreak** [comment]
Are you using any other userpatches? (Are there any other files ending in .mypatch in the wine-tkg-userpatches directory?)

**Comment by aufkrawall** [comment]
Nope, all clean. Also tried 4.15 release tag instead of master, doesn't help either.

**Comment by openglfreak** [comment]
Send your config (customization.cfg or wine-tkg.cfg, whichever you use) and a makepkg log.

**Comment by A6GibKm** [comment]
@aufkrawall  I think the patches fails since the files are fundamentally different.

I am not able to test the patch as I am not able to compile this from fedora.

**Comment by openglfreak** [comment]
I think you need to disable the fullscreen hack.
I don't use it so I never had problems, but the fshack and rawinput patches modify the same files, so they probably conflict with each other.

**Comment by aufkrawall** [comment]
Will try that tomorrow, thanks. Yes, I always enable it, as otherwise wine does some useless mode switching, despite of just a single native resolution and refreshrate available.

**Comment by aufkrawall** [comment]
Applying the patch biggie recommended by @openglfreak actually works without fullscreen hack, thanks!
I can also confirm that the fix by @Guy1524 fixes the locking issue on xwayland. :+1: 

I'd be awesome if we could get this to work with the proton fullscreen hack.

**Comment by Tk-Glitch** [comment]
That one will be my job, at least until it gets upstreamed

**Comment by aufkrawall** [comment]
It works now. Thanks, Etienne! Looks like adjusting the fullscreen hack was quite a bunch of work.

**Comment by Tk-Glitch** [comment]
I have pushed https://github.com/Tk-Glitch/PKGBUILDS/commit/2b7439ac70bac94e85bdd63ab8ce081de9097d5a that has updated and re-enabled our local raw input patchset when using the fs hack. The xwayland workaround is in of course :)

**Comment by aufkrawall** [comment]
Well, then I spoke too soon. ;)
Good thing we have ccache now also with mingw.

**Comment by aufkrawall** [comment]
The issue is still gone for me, great.

I wonder if the raw input fix actually makes a difference for me on Plasma? I feel that both Gnome and Xfce probably don't offer truly untouched input with what they offer as "flat", unlike on Plasma Xorg when directly configuring libinput via config file (and also feels the same on Wayland via system settings UI).

**Comment by A6GibKm** [comment]
This fixed my issue, thanks.
