### ISSUE TITLE
Wine 4.15 can't work with some old good apps

### ISSUE THREAD

**Issue by t14462** [Tk-Glitch/PKGBUILDS#296]
Nexus Mod Manager (even old) doesnt work on new wine - subprocess just crashing.

Witcher Script Merger cant find config, or something.

This apps works on wine 4.12, as I remember, but not work on 4.15

**Comment by t14462** [comment]
Upstream - wine from repo doesn't work with this tools too.

**Comment by telans** [comment]
NMM (latest) works fine for me, perhaps this has been fixed?

**Comment by Tk-Glitch** [comment]
Upstream regressions can and will happen. The path issues encountered here should have been fixed by now so I'll close this. I'll make an "always open" issue for future upstream regression related talk.
