### ISSUE TITLE
wine-tkg-git

### ISSUE THREAD

**Issue by JDC2389** [Tk-Glitch/PKGBUILDS#30]
Fails to build.
error: patch failed: libs/port/mbtowc.c:22
error: libs/port/mbtowc.c: patch does not apply
error: patch failed: tools/make_unicode:472
error: tools/make_unicode: patch does not apply
ERROR: Failed to apply patch, aborting!
==> ERROR: A failure occurred in prepare().
    Aborting...
removed '/home/carbon/PKGBUILDS/wine-tkg-git/BIG_UGLY_COINMINER'
  -> exit cleanup done

**Comment by Tk-Glitch** [comment]
The error comes from the last staging commit : https://github.com/wine-staging/wine-staging/commit/2802df41dc0e432f9987b6063b1b33c8ea6746b8
The breakage is weird though..
