### ISSUE TITLE
USVFS patch

### ISSUE THREAD

**Issue by qsniyg** [Tk-Glitch/PKGBUILDS#300]
https://gist.github.com/qsniyg/ec21d68f9407991a1043a71fa6ffd4cf

With these patches, USVFS (Mod Organizer 2's virtual filesystem) mostly works under wine now.

**Comment by nicman23** [comment]
question: with MO2 does anyone else not get the main menu ? (stuck at the empire's logo)

**Comment by qsniyg** [comment]
@nicman23 It works for me, did you check to make sure there are no missing mod dependencies? For me, that happens when some .esps or .esms are missing. You can check the right-hand side (where the "Plugins" list is), there should be a red caution sign.

If there are no missing mod dependencies, could you try unchecking all mods (or creating a new profile), and seeing if that works? If so, try adding mods one by one.

If that still doesn't work, could you send me a debug log for USVFS? (set Tools->Settings->Diagnostics->Log Level to Debug, and restart MO2 before running Skyrim again)

**Comment by nicman23** [comment]
ok ll do that. also this helps a lot if you do not have a case insensitive fs

https://www.reddit.com/r/linux_gaming/comments/d3493y/i_got_mod_organizer_2s_usvfs_running_under_wine/f00hpeu/
