### ISSUE TITLE
proton-tkg: wined3d-zero-inf-shaders patch failed: dlls/wined3d/glsl_shader.c:4304

### ISSUE THREAD

**Issue by telans** [Tk-Glitch/PKGBUILDS#302]
`Applying /home/telans/Documents/coding/PKGBUILDS/wine-tkg-git/src/wine-staging-git/patches/wined3d-zero-inf-shaders/0001-wined3d-Add-a-setting-to-workaround-0-inf-problem-in.patch`
`error: patch failed: dlls/wined3d/glsl_shader.c:4304`
`error: dlls/wined3d/glsl_shader.c: patch does not apply`
`ERROR: Failed to apply patch, aborting!`
`==> ERROR: A failure occurred in prepare().`
`    Aborting...`

https://github.com/wine-staging/wine-staging/commit/8390ba0d9571b67a63c766dc41d667a09d77e2a1
https://github.com/wine-staging/wine-staging/commit/2e4d0f472736529f59bd92dd3863731cd6bab875

Applies fine in wine-tkg, not proton-tkg

**Comment by Tk-Glitch** [comment]
Actually I'm asking myself if the RE4 issue is still there on current HEAD. We *might* not need that patch anymore.

**Comment by telans** [comment]
Staged here:
https://bugs.winehq.org/show_bug.cgi?id=34266
https://github.com/wine-staging/wine-staging/tree/master/patches/wined3d-zero-inf-shaders

I suppose the patch can be disabled when wine_staging is enabled?

**Comment by Tk-Glitch** [comment]
We're already doing that. The patch is ignored when staging is enabled and the commit introducing that patchset is in the tree.

**Comment by telans** [comment]
Whoops, forgot you already did that
