### ISSUE TITLE
Wine-TKG fails to detect Direct3D 9c

### ISSUE THREAD

**Issue by ronoverdrive** [Tk-Glitch/PKGBUILDS#305]
[wow_434_dxgi.log](https://github.com/Tk-Glitch/PKGBUILDS/files/3614309/wow_434_dxgi.log)
[wow_434_d3d11.log](https://github.com/Tk-Glitch/PKGBUILDS/files/3614310/wow_434_d3d11.log)
[customization.cfg.txt](https://github.com/Tk-Glitch/PKGBUILDS/files/3614312/customization.cfg.txt)

Basically for some reason all my D3D9 games fail to load regardless if D9VK or WineD3D is being used. Even some games like older versions of WoW that support D3D11 fail to start because it can't detect DirectX 9.0c, however, they all run just fine with Virtual Desktop Enabled. This issue isn't present in the Lutris 4.16 runner btw so its something with one of the patches.

Note: the d3d11 & dxgi logs are from WoW Cataclysm, but the results are the same with other games that rely on DX9.

**Comment by telans** [comment]
last_build_log?

**Comment by ronoverdrive** [comment]
[last_build_config.log](https://github.com/Tk-Glitch/PKGBUILDS/files/3614423/last_build_config.log)

**Comment by telans** [comment]
Try it without `_mwo_fix="true"`?

**Comment by ronoverdrive** [comment]
Was due to refresh rate patches. Disabling it fixed it.

**Comment by telans** [comment]
I'd leave this open for @Tk-Glitch , until it's fixed
