### ISSUE TITLE
proton-tkg gamepad_additions=true breaks 4.16.1 wine build

### ISSUE THREAD

**Issue by skeevy420** [Tk-Glitch/PKGBUILDS#310]
With Wine 4.16.1, possibly earlier but that's the version I just compiled, won't compile when _gamepad_additons="true" is set in proton-tkg.cfg.

**Comment by Tk-Glitch** [comment]
I can't reproduce the issue. Could you please give more details and eventually post your cfg? Thanks!

**Comment by telans** [comment]
Neither, builds fine for me.

**Comment by skeevy420** [comment]
OMFG....Just realized that I left the Proton patches I was testing from their 4.11.3 pre-release in the userpatches folder.  Removed them and this isn't an actual issue; only me documenting that my attention to detail could be a bit better.
