### ISSUE TITLE
mesa-tkg-git: ACO merged to mesa master branch

### ISSUE THREAD

**Issue by skeevy420** [Tk-Glitch/PKGBUILDS#312]
Not really an issue, we just don't need the _aco= option anymore since ACO has been accepted into Mesa, disabled by default, and enabled with the environment variable "RADV_PERFTEST=aco".

EDIT:  We still do for certain NIR commits that haven't been accepted by Mesa just yet.

**Comment by telans** [comment]
That was a fairly quick merge of Mesa's part

**Comment by skeevy420** [comment]
I agree.

**Comment by skeevy420** [comment]
From Masuha5 at Phoronix -- 

> from the ACO merge request:
> 
> > For full performance, the following MRs are required: !1240 !1239 !1236 !1664 !1893
> 
> which are not merged yet, so you'll want to stick to the aco branch for now.
> 
> Anyways, great to see it upstream. ACO is amazing. 

And a quick glance at Daniel's commit history shows those are in the ACO repository so my excitement jumped the shark here.

**Comment by telans** [comment]
Could possibly just add these merges as patches to tkg mesa until they're merged?

**Comment by telans** [comment]
[!1240](https://gitlab.freedesktop.org/mesa/mesa/merge_requests/1240.patch)
[!1239](https://gitlab.freedesktop.org/mesa/mesa/merge_requests/1239.patch)
[!1236](https://gitlab.freedesktop.org/mesa/mesa/merge_requests/1236.patch)
[!1664](https://gitlab.freedesktop.org/mesa/mesa/merge_requests/1664.patch)
[!1893](https://gitlab.freedesktop.org/mesa/mesa/merge_requests/1893.patch)

**Comment by skeevy420** [comment]
IMHO, they're not ready.  I've been having some odd corruption issues in Hitman 2 lately and I've nailed it down to one of those NIR patches thanks to them not being accepted by mesa-master yet.

To see what I mean, load up Hitman 2 with both mesa-master and mesa-aco and just aim at something and you'll see what I mean (especially cameras, they really trigger NIR issues).

Yesterday I tried both mesa-aco and mesa-master with RADV_PERFTEST=aco and mesa-aco that had all of the bad corruption issues I've been experiencing as of late when I'd go to aim...and those would stop once aiming stoped.  Mesa-master with ACO enabled played the game damn-near perfectly.

It also has some really fast visual bugs. almost imperceptible, when hitting people with A New Bat (all the confetti and whatnot causes it).

In other news, I did all those Clown escalation missions in Paris and unlocked A New Bat.

**Comment by telans** [comment]
Does mesa-master work the same as mesa-aco with this patch?

[aco.patch.txt](https://github.com/Tk-Glitch/PKGBUILDS/files/3638330/aco.patch.txt)

That's just the diff from https://github.com/daniel-schuermann/mesa and https://github.com/mesa3d/mesa. Just thinking it's better to use mesa-master if possible (with patch). I can't test this myself as I don't use and AMD card.

**Comment by skeevy420** [comment]
I'll give it a test sometime in the next 24h and let you know how it goes.

**Comment by skeevy420** [comment]
Sorry, been meaning to get to this but around noon yesterday I started having some issue where any Wine or Proton prefix just gets stuck on the "updating prefix" screen and eventually my system lagging up with up to 5 minutes at a time freezes and needs a reboot.  I have to get that figured out first.

**Comment by skeevy420** [comment]
I feel dumb.  Thought it might have been a bad pull from master so I wiped all my local PKGBUILDS, recloned it all, re-set all my configs, rebuilt everything, and it ended up being spincount that I forgot I set globally....thanks for pointing me in the right direction last night, #320.

You'll get that patch test done by the end of the day, though it'd be a good idea for me to make new patch based on the latest commits.  Already tested standard mesa from git it's working just fine with AMD_DEBUG=sisched,nir with Hitman 2 using LLVM10.

**Comment by skeevy420** [comment]
In the middle of trying to test the patch with Mesa-master and Hitman 2 had an update and it's throwing an error on launch.  So far I've narrowed down that it's not related to Mesa or Mesa-Aco.  There's an issue over at DXVK for those interested/effected by this.

**Comment by skeevy420** [comment]
I'm no longer getting those NIR issues with the ACO branch anymore.  Yay.

AFAICT, the only changes that have occurred are the game update yesterday as well as I had to replace amd_ags_x64.dll with one I compiled from dxvk-ags to work around some bug that update introduced.

@telans 
Out of curiousity, did you use `git diff branchA...branchB` or `branchA..branchB` to make the above patch?  Both make working patches, only the two dots one makes a much bigger patch and I'm not very keen on which branch diff method is better to use.

**Comment by telans** [comment]
Downloading the patch from a PR on GitHub (adding .patch to the end) seems to be the same no matter how many dots. Formatting the patch myself, I usually branch from the patch, squash, and then `git format-patch master *branch*`. This creates a shorter patch file with only one [PATCH] header.

There have been a few more commits to the ACO branch which are currently merge requests on mesa/mesa

**Comment by telans** [comment]
Actually, using github as a patch generator doesn't really work for this as it's still trying to merge commits which were already committed into master. Looks like braching, rebasing against upstream works however.

This just seems to be the difference now: [aco.patch.txt](https://github.com/Tk-Glitch/PKGBUILDS/files/3654783/aco.patch.txt)
Seen [here](https://gitlab.freedesktop.org/daniel-schuermann/mesa/commit/8e6cf04eef467f4a34ea24b7fdaf40a31562e4d0) & [here](https://gitlab.freedesktop.org/daniel-schuermann/mesa/commit/03937d7d7d755a33716f64b25d2bd12eebc8d62f). I assume a MR for these will be started soon

I'd say it's probably alright to get rid of the `_aco=` option now

**Comment by skeevy420** [comment]
If that's what we're down to, I concur; perhaps with a nir.mymesapatch.

I don't have anything better going on right now so I'm gonna try that new patch out with master.

**Comment by skeevy420** [comment]
Well this is annoying:

[meson: re-add incorrect pkg-config files with GLVND for backward compatibility](https://cgit.freedesktop.org/mesa/mesa/commit/?id=93df862b6affb6b8507e40601212a58012bfa873)

Now no matter what is set in the config I get this error

```
mesa-tkg-git: /usr/lib/libGLESv1_CM.so exists in filesystem (owned by libglvnd-glesv2)
mesa-tkg-git: /usr/lib/libGLESv1_CM.so.1 exists in filesystem (owned by libglvnd-glesv2)
mesa-tkg-git: /usr/lib/libGLESv2.so exists in filesystem (owned by libglvnd-glesv2)
mesa-tkg-git: /usr/lib/libGLESv2.so.2 exists in filesystem (owned by libglvnd-glesv2)
mesa-tkg-git: /usr/lib/pkgconfig/glesv1_cm.pc exists in filesystem (owned by libglvnd-glesv2)
lib32-mesa-tkg-git: /usr/lib32/libGLESv1_CM.so exists in filesystem (owned by lib32-libglvnd)
lib32-mesa-tkg-git: /usr/lib32/libGLESv1_CM.so.1 exists in filesystem (owned by lib32-libglvnd)
lib32-mesa-tkg-git: /usr/lib32/libGLESv2.so exists in filesystem (owned by lib32-libglvnd)
lib32-mesa-tkg-git: /usr/lib32/libGLESv2.so.2 exists in filesystem (owned by lib32-libglvnd)
```
...I'm just gonna mymesarevert this crap for now...
