### ISSUE TITLE
fsync not working in wine-tkg ?

### ISSUE THREAD

**Issue by elovin** [Tk-Glitch/PKGBUILDS#313]
I use an fsync enabled kernel ([from the aur](https://aur.archlinux.org/packages/linux-fsync/))
and pass WINEFSYNC=1 as en environment variable to the game when launching it.
The performance however is much worse compared to esync thus I don't think fsync is enabled.

How can I validate that fsync is enabled ?
Since fsync is most likely not enabled what did I do wrong to enable it ?

**Comment by skeevy420** [comment]
Run Steam from a terminal and you should see
`fsync: up and running.`
somewhere in the output if it's working properly.

See [here](https://steamcommunity.com/app/221410/discussions/0/3158631000006906163/) for more details.

**Comment by elovin** [comment]
@skeevy420 okay thanks but what about none steam games ? 
Because I use wine tkg with lutris to run Battlefield 1 and 5.
