### ISSUE TITLE
patching file dlls/winex11.drv/mouse.c fails

### ISSUE THREAD

**Issue by mpalermo73** [Tk-Glitch/PKGBUILDS#314]
```
patching file dlls/winex11.drv/mouse.c
Hunk #1 succeeded at 427 (offset 43 lines).
Hunk #2 FAILED at 458.
1 out of 2 hunks FAILED -- saving rejects to file dlls/winex11.drv/mouse.c.rej
```
git tree current as of:

> commit 2e52b7231ed6c61c9ab99dfd025341eb1acabfcf
> Author: Tk-Glitch <ti3nou@gmail.com>
> Date:   Thu Sep 19 11:08:38 2019 +0200
> 
>     Goodbye, linux51-tkg

[mouse.c.rej.txt](https://github.com/Tk-Glitch/PKGBUILDS/files/3633678/mouse.c.rej.txt)

[wine-tkg.cfg.txt](https://github.com/Tk-Glitch/PKGBUILDS/files/3633679/wine-tkg.cfg.txt)

**Comment by fls2018** [comment]
I think it might be this Staging commit causing the issue:

https://github.com/wine-staging/wine-staging/commit/c0389b04792d93d361e12f53441bcf9f0d6c4fd5

**Comment by skeevy420** [comment]
It should be _proton_fs_hack="true" that's causing that issue.

Set it to false and it'll continue on.  I'll edit this once it actually compiles or not :frog:

**Comment by fls2018** [comment]
> It's _proton_fs_hack="true" that's causing that issue.
> 
> Set it to false and it'll continue on. I'll edit this once it actually compiles or not frog

It's conflicting with the above staging commit, you can still have the fs hack but downgrade staging to a prior one using `_staging_version` in `proton-tkg.cfg`.

**Comment by Tk-Glitch** [comment]
Should be fixed as of https://github.com/Tk-Glitch/PKGBUILDS/commit/016d1895de668bfd1155a3e240576f6d24411e25

**Comment by telans** [comment]
@Tk-Glitch builds fine for me
