### ISSUE TITLE
proton-tkg/wine-tkg proton-gamepad-additions.patch

### ISSUE THREAD

**Issue by skeevy420** [Tk-Glitch/PKGBUILDS#315]
When using _gamepad_additions="true", the first three patches now fail since they were added to wine-master yesterday.

**Comment by Tk-Glitch** [comment]
Should be fixed as of https://github.com/Tk-Glitch/PKGBUILDS/commit/1f1c1467b8a7c43f951ee76729ca49288089b2c1

**Comment by skeevy420** [comment]
Yep, both working as expected.  Thanks.
