### ISSUE TITLE
Unable to get useful crash dumps

### ISSUE THREAD

**Issue by jporterf** [Tk-Glitch/PKGBUILDS#317]
I'm trying to get EverQuest working with D9VK.  It does for a good portion of the game but some zones crash the game when you load them.  Unfortunately, that means, that if I want the game to work, I need to see the dump to know what's going on.  However, it's not presenting me with a crash dump.  Two issues here, one the application has its own crash handler which gives me absolutely no information, and second, when I use winedbg, I get

> Backtrace:
> =>0 0x000000006253070e EntryPoint+0xef3de() in d3d9 (0x0000000000400000)
>   1 0x0000000000000003 (0x0000000000905a4d)
>   2 0x00000000d366c78b (0x0000000066fffffe)
> 0x000000006253070e EntryPoint+0xef3de in d3d9: divl	%ebx,%eax

Now I know this could be a d9vk issue, since it seems to be coming from that file, but since all I have are addresses, I don't know what function in the library is failing.

**Comment by Tk-Glitch** [comment]
There is logging functions in D9VK, like DXVK (also same syntax), that I think would be more useful.
No specific "D9VK" branded variable names for these afaik, so you can use them as is.
https://github.com/doitsujin/dxvk#debugging

**Comment by Tk-Glitch** [comment]
I'll close this here. Hopefully a solution was found with Josh in the meantime.
