### ISSUE TITLE
Linux-tkg: AMD: support mclk switching if monitors are synced

### ISSUE THREAD

**Issue by HengiFettlich** [Tk-Glitch/PKGBUILDS#319]
Hi! 
There's a patch to enable mclk switching if multiple monitors are connected with the same refresh rates. Patch series starts [here](https://lists.freedesktop.org/archives/amd-gfx/2019-August/039006.html).

By default, mclk doesn't switch if multiple monitors are connected. 
This still needs a bit of testing, has to be enabled with `amdgpu.dcfeaturemask=2`.  

Cheers!

**Comment by telans** [comment]
Does this apply and work with `amdgpu.dcfeaturemask=2`?

[amd-mckl-switching.mypatch.txt](https://github.com/Tk-Glitch/PKGBUILDS/files/3644459/amd-mckl-switching.mypatch.txt)

**Comment by HengiFettlich** [comment]
yes, it's the same patch.

It still needs some testing, that's why it uses the kernel parameter to be enabled.
