### ISSUE TITLE
Dang nabbit

### ISSUE THREAD

**Issue by JDC2389** [Tk-Glitch/PKGBUILDS#32]
daww

  -> Applying /home/carbon/PKGBUILDS/wine-tkg-git/src/esync/0064-server-Create-eventfd-descriptors-for-pseudo-fd-obje.patch
Checking patch server/fd.c...
error: while searching for:
    struct completion   *completion;  /* completion object attached to this fd */
    apc_param_t          comp_key;    /* completion key to set in completion events */
    unsigned int         comp_flags;  /* completion flags */
    unsigned int         comp_flags;  /* completion flags */
};

error: patch failed: server/fd.c:194
error: server/fd.c: patch does not apply
Checking patch server/file.h...
Checking patch server/named_pipe.c...
Hunk #1 succeeded at 162 (offset 1 line).
Hunk #2 succeeded at 205 (offset 2 lines).
==> ERROR: A failure occurred in prepare().
    Aborting...
removed '/home/carbon/PKGBUILDS/wine-tkg-git/BIG_UGLY_COINMINER'
  -> exit cleanup done

Love your work btw, extremely helpful.

**Comment by clapbr** [comment]
-> Applying /home/bruno/extras/PKGBUILDS/wine-tkg-git/src/esync/0064-server-Create-eventfd-descriptors-for-pseudo-fd-obje.patch
Checking patch server/fd.c...
error: while searching for:
    struct completion   *completion;  /* completion object attached to this fd */
    apc_param_t          comp_key;    /* completion key to set in completion events */
    unsigned int         comp_flags;  /* completion flags */
    unsigned int         comp_flags;  /* completion flags */
};


error: patch failed: server/fd.c:194
error: server/fd.c: patch does not apply
Checking patch server/file.h...
Checking patch server/named_pipe.c...
Hunk #1 succeeded at 162 (offset 1 line).
Hunk #2 succeeded at 205 (offset 2 lines).
==> ERRO: Uma falha ocorreu em prepare().
    Abortando...
removido '/home/bruno/extras/PKGBUILDS/wine-tkg-git/BIG_UGLY_COINMINER'
  -> exit cleanup done

Same issue! thanks for the great work

**Comment by Tk-Glitch** [comment]
We should be all good now
