### ISSUE TITLE
is  WINEFSYNC_SPINCOUNT working with wine-tkg?

### ISSUE THREAD

**Issue by logan001** [Tk-Glitch/PKGBUILDS#320]
Does WINEFSYNC_SPINCOUNT option works with wine-tkg?
i've tried to use it with guild wars 2 and the game freeze at launcher
this is the only output i can see in terminal

> env WINEFSYNC=1 WINEFSYNC_SPINCOUNT=100 wine64 /media/mint/games/GuildWars2/Gw2-64.exe
fsync: up and running.
000b:fixme:thread:create_user_shared_data_thread Creating user shared data update thread.
000b:fixme:winediag:start_process Wine TkG 4.16 is a testing version containing experimental patches.
000b:fixme:winediag:start_process Please don't report bugs about it on winehq.org and use https://github.com/Tk-Glitch/PKGBUILDS/issues instead.
000f:fixme:thread:create_user_shared_data_thread Creating user shared data update thread.
000d:fixme:thread:create_user_shared_data_thread Creating user shared data update thread.
0012:fixme:thread:create_user_shared_data_thread Creating user shared data update thread.
0014:fixme:thread:create_user_shared_data_thread Creating user shared data update thread.
001b:fixme:thread:create_user_shared_data_thread Creating user shared data update thread.
0022:fixme:thread:create_user_shared_data_thread Creating user shared data update thread.
0009:fixme:thread:create_user_shared_data_thread Creating user shared data update thread.
0009:fixme:heap:RtlSetHeapInformation 0x10000 0 0x22fcb0 4 stub
0009:fixme:heap:RtlSetHeapInformation 0x730000 0 0x22fc90 4 stub
0009:fixme:heap:RtlSetHeapInformation 0x730000 1 (nil) 0 stub
002b:fixme:ver:GetCurrentPackageId (0x131fd80 (nil)): stub
0009:fixme:gameux:GameExplorerImpl_VerifyAccess (0000000000F2BC50, L"Z:\\media\\mint\\games\\GuildWars2\\Gw2-64.exe", 000000000022F120)
0045:fixme:msctf:ThreadMgr_ActivateEx Unimplemented flags 0x4

and nothing else happens. the launcher does not change at all.
i also tried diablo 3 (in lutris)  and i have the same results. the launcher will "minimize" in tray icon after log in and nothing else happens

**Comment by Tk-Glitch** [comment]
That option is buggy right now. Zebediah fixed it in the upcoming fsync update that will be merged in the next Proton release. I will pick the changes when it drops of course.

**Comment by Tk-Glitch** [comment]
Actually I'm late. I'll merge tomorrow.

**Comment by aufkrawall** [comment]
Seems to work now. :)
Though it seems wine is borked currently, as -staging commit 649c35ff92b4fd86b0ecf5d84d80b595a7c919d9 lets lots of 3D applications refuse to start here (also without fsync).
