### ISSUE TITLE
problem with Fontconfig?

### ISSUE THREAD

**Issue by Danilopereira82** [Tk-Glitch/PKGBUILDS#321]
Fontconfig warning: "/etc/fonts/conf.avail/05-reset-dirs-sample.conf", line 6: unknown element "reset-dirs"

**Comment by openglfreak** [comment]
Not TkG's problem.
The fontconfig and lib32-fontconfig versions in the arch repos don't match.

**Comment by bsngardner** [comment]
I got this as well. I'm not sure where to report this upstream, but downgrading fontconfig works fine for now.

**Comment by openglfreak** [comment]
It's just a warning.

**Comment by bsngardner** [comment]
This warning was accompanied by my wine applications crashing on start until I downgraded fontconfig.

**Comment by telans** [comment]
fontconfig & lib32-fontconfig were just updated to the latest & same version. This should be fixed now
