### ISSUE TITLE
"winevulkan.dll" failed to initialize

### ISSUE THREAD

**Issue by Danilopereira82** [Tk-Glitch/PKGBUILDS#324]
0058:err:vulkan:wine_vk_init Failed to load vulkan library
0058:err:vulkan:wine_vk_init Failed to load Wine graphics driver supporting Vulkan.
0058:err:module:LdrInitializeThunk "winevulkan.dll" failed to initialize, aborting

**Comment by telans** [comment]
Do you have 32bit Vulkan packages installed?

**Comment by Danilopereira82** [comment]
yes i do

**Comment by Danilopereira82** [comment]
i can't say much
because this is all i get from the log

it was working 2 days ago

**Comment by telans** [comment]
What programs does this happen with? Any recent system updates? Have you updated wine since it worked?

**Comment by skeevy420** [comment]
Care to list the program effected, used wine config, your GPU, and possibly any other packages that may have been changed recently?  

That isn't very much to go on and Googling the error just comes up with other people who were missing some 32-bit Vulkan packages.

**Comment by Danilopereira82** [comment]
any game using dxvk or d9vk or vulkan 
the same day i got the problem with fontconfig
it started appearing too
i thought it would disappear if i fixed the fontconfig thing

**Comment by skeevy420** [comment]
Have you tried downgrading fontconfig?  [The one is from the archive ](https://archive.archlinux.org/repos/month/extra/os/x86_64/fontconfig-2%3A2.13.1%2B12%2Bg5f5ec56-1-x86_64.pkg.tar.xz) and is the same as Arch's current lib32-fontconfig

**Comment by Danilopereira82** [comment]
i fixed the problem with fontconfig dude
now its just this vulkan things that is not working

**Comment by telans** [comment]
What happens with vkcube?

**Comment by Danilopereira82** [comment]
works just well

**Comment by Danilopereira82** [comment]
lib32-vulkan-icd-loader

**Comment by Tk-Glitch** [comment]
Glad you got that fixed
