### ISSUE TITLE
WoW 8.2.5 freezes on nvidia

### ISSUE THREAD

**Issue by bsngardner** [Tk-Glitch/PKGBUILDS#327]
```
❯ pacman -Q | egrep 'wine|nvidia|spirv|vulkan|vkd3d|dxvk'
dxvk-mingw-git 1.4.r20.g2e6da26f-1
lib32-nvidia-dev-utils-tkg 435.24.02-64
lib32-opencl-nvidia-dev-tkg 435.24.02-64
lib32-spirv-tools-tkg-git 2019.4.r89.g84b19760-1
lib32-vkd3d-tkg-git 1.1.r613.g865fbea-1
lib32-vulkan-icd-loader 1.1.121-1
nvidia-cg-toolkit 3.1-5
nvidia-dev-dkms-tkg 435.24.02-64
nvidia-dev-egl-wayland-tkg 435.24.02-64
nvidia-dev-utils-tkg 435.24.02-64
opencl-nvidia-dev-tkg 435.24.02-64
spirv-headers-git r210.842ec90-1
spirv-tools-tkg-git 2019.4.r89.g84b19760-1
vkd3d-tkg-git 1.1.r613.g865fbea-1
vulkan-headers-git 1.1.123.r1.gba091ba-1
vulkan-icd-loader 1.1.121-1
wine-tkg-staging-fsync-vkd3d-faudio-git 4.16.r18.gced72a6a-203
...
```

I don't have definitive proof this is nvidia-specific, but my AMD machine was working fine 2 days ago. I'll update once I get back to it. I was originally on the main Arch nvidia-dkms driver, and I tried upgrading to the latest vulkan dev driver from here, but it froze just the same. I have been using spirv-tools, wine, and vulkan-headers from TkG fine for months. Today is the first time I tried launching WoW 8.2.5 update on nvidia, and it freezes between immediately and 1 minute of playing. I can report this upstream once I know where to report. It does not appear related to dxvk or vkd3d since it happens with both. 
Anyone else seen this? What debug logs could help find the problem? When I turn on wine logging, I am inundated with thousands of:
`00fa:fixme:rawinput:GetRawInputBuffer data (nil), data_size 0x22f9f0, header_size 24 stub!`
Other than that, I don't see any crash messages.

**Comment by ronoverdrive** [comment]
Can confirm, WoW 8.2.5.x has random frame drops that look like freezing. I've been able to alleviate it a bit with gamemode and lowering the latency of pulseaudio, but it still randomly happens and I don't know what's causing it but I'm pretty sure its something in the 8.2.5.x patch not agreeing with WINE as WoW ran perfectly fine before the patch dropped.

**Comment by Tk-Glitch** [comment]
If you have Fsync enabled, I'd try with it disabled. The last Fsync changes seem to have affected some games negatively, creating such hanging scenarios.

**Comment by ronoverdrive** [comment]
I've tried it both with and without fsync. Symptoms don't change.

**Comment by Tk-Glitch** [comment]
There's a pending issue regarding inputs: https://bugs.winehq.org/show_bug.cgi?id=47764
But I couldn't find one regarding hanging.

I'd try with a stock wine-staging config (using `_LOCAL_PRESET="staging"` in your configuration file) to make sure it's not unique to wine-tkg, then if you can still reproduce the issue, report to winehq.

**Comment by bsngardner** [comment]
With `_LOCAL_PRESET="staging"`, I'm not getting the hanging. @ronoverdrive? 
I guess that narrows it down to esync, faudio, or one of the extra patches.

**Comment by ronoverdrive** [comment]
@bsngardner esync is part of staging so you can rule that out. With the last update last night (4.16.r28-205) it won't even start with Fsync enabled so I had to disable it, however, I still get random pausing during combat and turning in quests. While clean staging it still suffers some pausing when turning in quests so I didn't spend too much time with it to see if I get the random combat freezing.

**Comment by bsngardner** [comment]
Hmm I don't know what's going on anymore. With clean staging, I played for a good hour yesterday. Until I went to the zone Nazjatar; it froze, and I haven't been able to finish loading since. 
I had forgotten esync was merged into staging. Since hangs still happen on clean staging, I guess the next step is to report to winehq.

**Comment by Tk-Glitch** [comment]
Seems related : https://bugs.winehq.org/show_bug.cgi?id=47471

**Comment by bsngardner** [comment]
You're right; switching to dxvk let Nazjatar load. It's strange because vkd3d has worked there in the recent past, so I thought that bug was fixed somehow. I'll try adding features to clean staging to see when it fails for me. @ronoverdrive I'm not getting any hangs or dropped frames with clean staging.

**Comment by Tk-Glitch** [comment]
Judging by other reports, the recently updated and re-enabled raw-input patchset in staging might actually have something to do with it. I have pushed https://github.com/Tk-Glitch/PKGBUILDS/commit/bf9759dbbe99551602c35b3f33240fde373cda12 to give more options/workaround it.
It might not be it, but still worth a shot.

**Comment by Tk-Glitch** [comment]
Is this still an issue?

**Comment by bsngardner** [comment]
No, this appears to be fixed.
