### ISSUE TITLE
And as a result, Wine 3.18 is compiled instead of 3.19. Why is that?

### ISSUE THREAD

**Issue by Kerrung** [Tk-Glitch/PKGBUILDS#33]
Hi.
And as a result, Wine 3.18.218.g13cdcdae1a with Staging 3.18.15.geb630f68 is compiled instead of 3.19.
Why is that?
[Config+PKGBUILD.zip](https://github.com/Tk-Glitch/PKGBUILDS/files/2521629/Config%2BPKGBUILD.zip)

**Comment by Kerrung** [comment]
pkgver() {

    # retrieve current wine-staging version
cd "${srcdir}/${_stgsrcdir}"
local _stagingTag="$(git tag --sort='version:refname' | tail -n1 | sed 's/-/./g;s/^v//;s/.rc/rc/')"
local _stagingVer="$(git describe --long --tags 
| sed 's/([^-]*-g)/\1/;s/-/./g;s/^v//;s/.rc/rc/' 
| sed "s/^latest.release/${_stagingTag}/")"

    # retrieve current wine version
cd "${srcdir}/${_winesrcdir}"
local _wineVer="$(git describe | sed 's/([^-]*-g)/\1/;s/wine//;s/-//;s/-/./;s/-/./;s/^v//;s/.rc/rc/')"

printf '%s.%s' "$_wineVer.wine" "$_stagingVer.staging"
}

**Comment by Tk-Glitch** [comment]
Wine-staging 3.19 doesn't exist yet. If you disable staging in the config file you'll get 3.19 vanilla though. You'll have to wait for wine-staging to be rebased on 3.19. That should be very soon.

**Comment by Kerrung** [comment]
Ok. Thank you. You are right.
