### ISSUE TITLE
dkms wireguard compile problems

### ISSUE THREAD

**Issue by d4vid1** [Tk-Glitch/PKGBUILDS#330]
==> dkms install wireguard/0.0.20190913 -k 5.3.1-6.1-tkg-bmq
Error! Bad return status for module build on kernel: 5.3.1-6.1-tkg-bmq (x86_64)
Consult /var/lib/dkms/wireguard/0.0.20190913/build/make.log for more information.

DKMS make.log for wireguard-0.0.20190913 for kernel 5.3.1-6.1-tkg-bmq (x86_64)
So 29. Sep 10:35:57 CEST 2019
make: Verzeichnis „/usr/lib/modules/5.3.1-6.1-tkg-bmq/build“ wird betreten
  CC [M]  /var/lib/dkms/wireguard/0.0.20190913/build/main.o
  CC [M]  /var/lib/dkms/wireguard/0.0.20190913/build/noise.o
  CC [M]  /var/lib/dkms/wireguard/0.0.20190913/build/device.o
  CC [M]  /var/lib/dkms/wireguard/0.0.20190913/build/peer.o
  CC [M]  /var/lib/dkms/wireguard/0.0.20190913/build/timers.o
  CC [M]  /var/lib/dkms/wireguard/0.0.20190913/build/queueing.o
  CC [M]  /var/lib/dkms/wireguard/0.0.20190913/build/send.o
  CC [M]  /var/lib/dkms/wireguard/0.0.20190913/build/receive.o
  CC [M]  /var/lib/dkms/wireguard/0.0.20190913/build/socket.o
  CC [M]  /var/lib/dkms/wireguard/0.0.20190913/build/peerlookup.o
  CC [M]  /var/lib/dkms/wireguard/0.0.20190913/build/allowedips.o
  CC [M]  /var/lib/dkms/wireguard/0.0.20190913/build/ratelimiter.o
  CC [M]  /var/lib/dkms/wireguard/0.0.20190913/build/cookie.o
  CC [M]  /var/lib/dkms/wireguard/0.0.20190913/build/netlink.o
  CC [M]  /var/lib/dkms/wireguard/0.0.20190913/build/crypto/zinc/chacha20/chacha20.o
  PERLASM /var/lib/dkms/wireguard/0.0.20190913/build/crypto/zinc/chacha20/chacha20-x86_64.S
  CC [M]  /var/lib/dkms/wireguard/0.0.20190913/build/crypto/zinc/poly1305/poly1305.o
  PERLASM /var/lib/dkms/wireguard/0.0.20190913/build/crypto/zinc/poly1305/poly1305-x86_64.S
  CC [M]  /var/lib/dkms/wireguard/0.0.20190913/build/crypto/zinc/chacha20poly1305.o
  CC [M]  /var/lib/dkms/wireguard/0.0.20190913/build/crypto/zinc/blake2s/blake2s.o
  AS [M]  /var/lib/dkms/wireguard/0.0.20190913/build/crypto/zinc/blake2s/blake2s-x86_64.o
  CC [M]  /var/lib/dkms/wireguard/0.0.20190913/build/crypto/zinc/curve25519/curve25519.o
  AS [M]  /var/lib/dkms/wireguard/0.0.20190913/build/crypto/zinc/chacha20/chacha20-x86_64.o
  AS [M]  /var/lib/dkms/wireguard/0.0.20190913/build/crypto/zinc/poly1305/poly1305-x86_64.o
  LD [M]  /var/lib/dkms/wireguard/0.0.20190913/build/wireguard.o
  Building modules, stage 2.
  MODPOST 1 modules
ERROR: "udp_tunnel_xmit_skb" [/var/lib/dkms/wireguard/0.0.20190913/build/wireguard.ko] undefined!
ERROR: "udp_sock_create6" [/var/lib/dkms/wireguard/0.0.20190913/build/wireguard.ko] undefined!
ERROR: "setup_udp_tunnel_sock" [/var/lib/dkms/wireguard/0.0.20190913/build/wireguard.ko] undefined!
ERROR: "udp_tunnel_sock_release" [/var/lib/dkms/wireguard/0.0.20190913/build/wireguard.ko] undefined!
ERROR: "udp_tunnel6_xmit_skb" [/var/lib/dkms/wireguard/0.0.20190913/build/wireguard.ko] undefined!
ERROR: "udp_sock_create4" [/var/lib/dkms/wireguard/0.0.20190913/build/wireguard.ko] undefined!
make[1]: *** [scripts/Makefile.modpost:103: modules-modpost] Fehler 1
make: *** [Makefile:1632: modules] Fehler 2
make: Verzeichnis „/usr/lib/modules/5.3.1-6.1-tkg-bmq/build“ wird verlassen

please fix.. 

big thanks!

**Comment by Tk-Glitch** [comment]
It looks like enabling CONFIG_NET_UDP_TUNNEL would do

**Comment by Tk-Glitch** [comment]
Actually it's enabled already. You'll want to load the related module before building/installing the dkms one.
Try running `sudo modprobe udp_tunnel` first, then install wireguard-dkms and see if that fixes your issue.

**Comment by d4vid1** [comment]
> Actually it's enabled already. You'll want to load the related module before building/installing the dkms one.
> Try running `sudo modprobe udp_tunnel` first, then install wireguard-dkms and see if that fixes your issue.

sudo pacman -S wireguard-dkms
Warnung: wireguard-dkms-0.0.20190913-1 ist aktuell -- Reinstalliere
Löse Abhängigkeiten auf...
Suche nach in Konflikt stehenden Paketen...

Pakete (1) wireguard-dkms-0.0.20190913-1

Gesamtgröße des Downloads:           0,24 MiB
Gesamtgröße der installierten Pakete:  1,58 MiB
Größendifferenz der Aktualisierung:  0,00 MiB

:: Installation fortsetzen? [J/n] 
:: Empfange Pakete...
 wireguard-dkms-0.0.20190913-1-x86_64     246,1 KiB  2,18M/s 00:00 [####################################] 100%
(1/1) Prüfe Schlüssel im Schlüsselring                             [####################################] 100%
(1/1) Überprüfe Paket-Integrität                                   [####################################] 100%
(1/1) Lade Paket-Dateien                                           [####################################] 100%
(1/1) Prüfe auf Dateikonflikte                                     [####################################] 100%
(1/1) Überprüfe verfügbaren Festplattenspeicher                    [####################################] 100%
:: Starte pre-transaction hooks...
(1/1) Remove DKMS modules
==> dkms remove wireguard/0.0.20190913 -k 5.3.1-1-MANJARO
==> dkms remove wireguard/0.0.20190913 -k 4.19.75-1-MANJARO
:: Verarbeite Paketänderungen...
(1/1) Installiere wireguard-dkms                                   [####################################] 100%
:: Starte post-transaction hooks...
(1/3) Install DKMS modules
==> dkms install wireguard/0.0.20190913 -k 5.3.1-1-MANJARO
==> dkms install wireguard/0.0.20190913 -k 4.19.75-1-MANJARO
==> dkms install wireguard/0.0.20190913 -k 5.3.1-6.1-tkg-bmq
Error! Bad return status for module build on kernel: 5.3.1-6.1-tkg-bmq (x86_64)
Consult /var/lib/dkms/wireguard/0.0.20190913/build/make.log for more information.
(2/3) Cleaning pacman cache...
==> no candidate packages found for pruning
(3/3) Arming ConditionNeedsUpdate...

cat /var/lib/dkms/wireguard/0.0.20190913/build/make.log
DKMS make.log for wireguard-0.0.20190913 for kernel 5.3.1-6.1-tkg-bmq (x86_64)
So 29. Sep 11:15:19 CEST 2019
make: Verzeichnis „/usr/lib/modules/5.3.1-6.1-tkg-bmq/build“ wird betreten
  CC [M]  /var/lib/dkms/wireguard/0.0.20190913/build/main.o
  CC [M]  /var/lib/dkms/wireguard/0.0.20190913/build/noise.o
  CC [M]  /var/lib/dkms/wireguard/0.0.20190913/build/device.o
  CC [M]  /var/lib/dkms/wireguard/0.0.20190913/build/peer.o
  CC [M]  /var/lib/dkms/wireguard/0.0.20190913/build/timers.o
  CC [M]  /var/lib/dkms/wireguard/0.0.20190913/build/queueing.o
  CC [M]  /var/lib/dkms/wireguard/0.0.20190913/build/send.o
  CC [M]  /var/lib/dkms/wireguard/0.0.20190913/build/receive.o
  CC [M]  /var/lib/dkms/wireguard/0.0.20190913/build/socket.o
  CC [M]  /var/lib/dkms/wireguard/0.0.20190913/build/peerlookup.o
  CC [M]  /var/lib/dkms/wireguard/0.0.20190913/build/allowedips.o
  CC [M]  /var/lib/dkms/wireguard/0.0.20190913/build/ratelimiter.o
  CC [M]  /var/lib/dkms/wireguard/0.0.20190913/build/cookie.o
  CC [M]  /var/lib/dkms/wireguard/0.0.20190913/build/netlink.o
  CC [M]  /var/lib/dkms/wireguard/0.0.20190913/build/crypto/zinc/chacha20/chacha20.o
  PERLASM /var/lib/dkms/wireguard/0.0.20190913/build/crypto/zinc/chacha20/chacha20-x86_64.S
  CC [M]  /var/lib/dkms/wireguard/0.0.20190913/build/crypto/zinc/poly1305/poly1305.o
  PERLASM /var/lib/dkms/wireguard/0.0.20190913/build/crypto/zinc/poly1305/poly1305-x86_64.S
  CC [M]  /var/lib/dkms/wireguard/0.0.20190913/build/crypto/zinc/chacha20poly1305.o
  CC [M]  /var/lib/dkms/wireguard/0.0.20190913/build/crypto/zinc/blake2s/blake2s.o
  AS [M]  /var/lib/dkms/wireguard/0.0.20190913/build/crypto/zinc/blake2s/blake2s-x86_64.o
  CC [M]  /var/lib/dkms/wireguard/0.0.20190913/build/crypto/zinc/curve25519/curve25519.o
  AS [M]  /var/lib/dkms/wireguard/0.0.20190913/build/crypto/zinc/chacha20/chacha20-x86_64.o
  AS [M]  /var/lib/dkms/wireguard/0.0.20190913/build/crypto/zinc/poly1305/poly1305-x86_64.o
  LD [M]  /var/lib/dkms/wireguard/0.0.20190913/build/wireguard.o
  Building modules, stage 2.
  MODPOST 1 modules
ERROR: "udp_tunnel_xmit_skb" [/var/lib/dkms/wireguard/0.0.20190913/build/wireguard.ko] undefined!
ERROR: "udp_sock_create6" [/var/lib/dkms/wireguard/0.0.20190913/build/wireguard.ko] undefined!
ERROR: "setup_udp_tunnel_sock" [/var/lib/dkms/wireguard/0.0.20190913/build/wireguard.ko] undefined!
ERROR: "udp_tunnel_sock_release" [/var/lib/dkms/wireguard/0.0.20190913/build/wireguard.ko] undefined!
ERROR: "udp_tunnel6_xmit_skb" [/var/lib/dkms/wireguard/0.0.20190913/build/wireguard.ko] undefined!
ERROR: "udp_sock_create4" [/var/lib/dkms/wireguard/0.0.20190913/build/wireguard.ko] undefined!
make[1]: *** [scripts/Makefile.modpost:103: modules-modpost] Fehler 1
make: *** [Makefile:1632: modules] Fehler 2
make: Verzeichnis „/usr/lib/modules/5.3.1-6.1-tkg-bmq/build“ wird verlassen

**Comment by openglfreak** [comment]
What does `zgrep -F CONFIG_NET_UDP_TUNNEL /proc/config.gz` output

**Comment by d4vid1** [comment]
> What does `zgrep -F CONFIG_NET_UDP_TUNNEL /proc/config.gz` output

nothing :(

**Comment by d4vid1** [comment]
Hey Folks i will try to compile kernel without modprobedb, i think that is my problem. 

thanks for ur help.

**Comment by Tk-Glitch** [comment]
Indeed if the module was stripped out by modprobed-db that explains the whole issue. The config is correct so there's no reason for it not to work. You should be all good without using modprobed-db :)
