### ISSUE TITLE
mostlyportable-gcc / linux53: breaks dkms install of nvidia-tkg

### ISSUE THREAD

**Issue by telans** [Tk-Glitch/PKGBUILDS#334]
Using mostlyportable-gcc to build linux53, dkms nvidia fails to install. Results in nvidia drivers failing to load. Using mostlyportable-gcc `9.2.0` fails, system gcc `9.2.0` succeeds.

[linux53-tkg.cfg.txt](https://github.com/Tk-Glitch/PKGBUILDS/files/3675531/linux53-tkg.cfg.txt)
[mostlyportable-gcc.cfg.txt](https://github.com/Tk-Glitch/PKGBUILDS/files/3675536/mostlyportable-gcc.cfg.txt)

[dkms make.log](https://github.com/Tk-Glitch/PKGBUILDS/files/3675551/make.log)

**Comment by Tk-Glitch** [comment]
That's fully expected as DKMS has no idea mostlyportable-gcc exists.

You can get there by exporting `CUSTOM_GCC_PATH="your mostlyportable-gcc absolute path"` and `PATH=${CUSTOM_GCC_PATH}/bin:${CUSTOM_GCC_PATH}/lib:${CUSTOM_GCC_PATH}/include:${PATH}` some way or another:
- Export them globally (`.bashrc` is a good candidate) so your mostlyportable-gcc will always have priority over system GCC. It might not be what you want though, especially if you switch often.
- Add them to DKMS framework (`/etc/dkms/framework.conf`). That file is sourced by DKMS only so it is pretty safe to do it that way.

**Comment by Tk-Glitch** [comment]
You could also export `CUSTOM_GCC_PATH="your mostlyportable-gcc absolute path"` globally through `.bashrc` and only add `PATH=${CUSTOM_GCC_PATH}/bin:${CUSTOM_GCC_PATH}/lib:${CUSTOM_GCC_PATH}/include:${PATH}` to `/etc/dkms/framework.conf` (and/or other stuff you want to use mostlyportable-gcc with), so you only have to change `CUSTOM_GCC_PATH` value to switch versions.

**Comment by telans** [comment]
Yeah that's true, I just thought it was odd as it worked fine with linux52/tkggcc

**Comment by Tk-Glitch** [comment]
Yeah I'm not sure why/how it worked with 5.2 actually.. :frog:
