### ISSUE TITLE
wine-tkg: Proton fullscreen hack failes validity check

### ISSUE THREAD

**Issue by TrueNeutralDesu** [Tk-Glitch/PKGBUILDS#335]
This error comes up when I try to install wine-tkg:

```
Validating source files with md5sums...

...

valve_proton_fullscreen_hack-staging.patch ... FAILED

...
```

Everything else succeeds. Changing related values ('true' or 'false') in the config file doesn't help.

**Comment by skeevy420** [comment]
Run makepkg with the "--skipcheck" flag to work around that until a proper update is pushed.
