### ISSUE TITLE
nvidia compile problems

### ISSUE THREAD

**Issue by d4vid1** [Tk-Glitch/PKGBUILDS#348]
Manjaro 64 bit / 5.3.5-10.5-tkg-bmq

CONFTEST: drm_alpha_blending_available
  CC [M]  /var/lib/dkms/nvidia/440.26/build/nvidia/nv-frontend.o
  CC [M]  /var/lib/dkms/nvidia/440.26/build/nvidia/nv.o
  CC [M]  /var/lib/dkms/nvidia/440.26/build/nvidia/nv-pci.o
  CC [M]  /var/lib/dkms/nvidia/440.26/build/nvidia/nv-acpi.o
In Datei, eingebunden von /var/lib/dkms/nvidia/440.26/build/nvidia/nv.c:14:
/var/lib/dkms/nvidia/440.26/build/common/inc/nv-linux.h:131:10: schwerwiegender Fehler: asm/system.h: Datei oder Verzeichnis nicht gefunden

**Comment by duud** [comment]
Same here

**Comment by Tk-Glitch** [comment]
This was a locale issue. The nvidia script expects english messages only. I have pinged nvidia about it.
The commit above should fix it while we wait for nvidia to do it.

**Comment by duud** [comment]
ty
