### ISSUE TITLE
mesa-git: MESA_WHICH_LLVM issue in clean chroot

### ISSUE THREAD

**Issue by fluffykittyrevenge** [Tk-Glitch/PKGBUILDS#358]
When setting mesa-git to use MESA_WHICH_LLVM=2, the build will fail in a clean chroot  (with aurutils) because the package gets a dependency on aur-llvm-git which Pacman is unable to find since it doesn't exist.

A workaround is to set it to 3, normally for LH, but since it sets the correct dependency names it works.

I'm unsure if updating the instructions to mention setting it to 3 for clean chroots is an acceptable fix or not.

**Comment by Tk-Glitch** [comment]
AUR's `llvm-git` package provides `aur-llvm-git` but indeed you can't have pacman find it in a clean chroot without manually installing it beforehand. That's what the maintainer (Lone_Wolf) decided to do, and I didn't want to break the `MESA_WHICH_LLVM` variable values for people used to his mesa-git and llvm-git packages. I would have made a single option myself that selects `llvm-git` and leave it to the user to use either AUR's or LordHeavy's packages as they prefer.

No solution is satisfying to me except nuking my mesa PKGBUILD. But that wouldn't satisfy my users :frog:

I'll add some fluff to make it clearer in the cfg/readme

**Comment by fluffykittyrevenge** [comment]
Ahh, I see.  That makes sense.  Up until now I've managed AUR stuff with PACAUR so I didn't even notice that.  I had to reinstall my system a few days ago, switched to AURUTILS since the Wiki recommends building in a clean chroot, and it's a learning process to say the least.

**Comment by Tk-Glitch** [comment]
That's half the fun, isn't it? :smile:

**Comment by Tk-Glitch** [comment]
It's a bit hard to swallow but it's there : https://github.com/Tk-Glitch/PKGBUILDS/commit/0c803297734072a66d08b1f087ea22d171b39e89
Hopefully will be enough.
