### ISSUE TITLE
libglvnd issue

### ISSUE THREAD

**Issue by random2324** [Tk-Glitch/PKGBUILDS#362]
Dont know whats going on...
Sometimes they change something in mesa, then something in the package build or with the libglvnd package. Anyway its chaotic. I cant tell mesa to not install this stuff. Setting true or false in customization.cfg makes no difference. Help. :(

mesa-tkg-git: /usr/include/EGL/egl.h existiert im Dateisystem (gehört zu libglvnd)
mesa-tkg-git: /usr/include/EGL/eglext.h existiert im Dateisystem (gehört zu libglvnd)
mesa-tkg-git: /usr/include/EGL/eglplatform.h existiert im Dateisystem (gehört zu libglvnd)
mesa-tkg-git: /usr/include/GL/gl.h existiert im Dateisystem (gehört zu libglvnd)
mesa-tkg-git: /usr/include/GL/glcorearb.h existiert im Dateisystem (gehört zu libglvnd)
mesa-tkg-git: /usr/include/GL/glext.h existiert im Dateisystem (gehört zu libglvnd)
mesa-tkg-git: /usr/include/GL/glx.h existiert im Dateisystem (gehört zu libglvnd)
mesa-tkg-git: /usr/include/GL/glxext.h existiert im Dateisystem (gehört zu libglvnd)
mesa-tkg-git: /usr/include/GLES2/gl2.h existiert im Dateisystem (gehört zu libglvnd)
mesa-tkg-git: /usr/include/GLES2/gl2ext.h existiert im Dateisystem (gehört zu libglvnd)
mesa-tkg-git: /usr/include/GLES2/gl2platform.h existiert im Dateisystem (gehört zu libglvnd)
mesa-tkg-git: /usr/include/GLES3/gl3.h existiert im Dateisystem (gehört zu libglvnd)
mesa-tkg-git: /usr/include/GLES3/gl31.h existiert im Dateisystem (gehört zu libglvnd)
mesa-tkg-git: /usr/include/GLES3/gl32.h existiert im Dateisystem (gehört zu libglvnd)
mesa-tkg-git: /usr/include/GLES3/gl3platform.h existiert im Dateisystem (gehört zu libglvnd)
mesa-tkg-git: /usr/include/KHR/khrplatform.h existiert im Dateisystem (gehört zu libglvnd)
mesa-tkg-git: /usr/lib/libEGL.so existiert im Dateisystem (gehört zu libglvnd)
mesa-tkg-git: /usr/lib/libEGL.so.1 existiert im Dateisystem (gehört zu libglvnd)
mesa-tkg-git: /usr/lib/libGL.so existiert im Dateisystem (gehört zu libglvnd)
mesa-tkg-git: /usr/lib/libGL.so.1 existiert im Dateisystem (gehört zu libglvnd)
mesa-tkg-git: /usr/lib/libGLESv2.so existiert im Dateisystem (gehört zu libglvnd)
mesa-tkg-git: /usr/lib/libGLESv2.so.2 existiert im Dateisystem (gehört zu libglvnd)
mesa-tkg-git: /usr/lib/pkgconfig/egl.pc existiert im Dateisystem (gehört zu libglvnd)
mesa-tkg-git: /usr/lib/pkgconfig/gl.pc existiert im Dateisystem (gehört zu libglvnd)
mesa-tkg-git: /usr/lib/pkgconfig/glesv2.pc existiert im Dateisystem (gehört zu libglvnd)
lib32-mesa-tkg-git: /usr/lib32/libEGL.so existiert im Dateisystem (gehört zu lib32-libglvnd)
lib32-mesa-tkg-git: /usr/lib32/libEGL.so.1 existiert im Dateisystem (gehört zu lib32-libglvnd)
lib32-mesa-tkg-git: /usr/lib32/libGL.so existiert im Dateisystem (gehört zu lib32-libglvnd)
lib32-mesa-tkg-git: /usr/lib32/libGL.so.1 existiert im Dateisystem (gehört zu lib32-libglvnd)
lib32-mesa-tkg-git: /usr/lib32/libGLESv2.so existiert im Dateisystem (gehört zu lib32-libglvnd)
lib32-mesa-tkg-git: /usr/lib32/libGLESv2.so.2 existiert im Dateisystem (gehört zu lib32-libglvnd)
lib32-mesa-tkg-git: /usr/lib32/pkgconfig/egl.pc existiert im Dateisystem (gehört zu lib32-libglvnd)
lib32-mesa-tkg-git: /usr/lib32/pkgconfig/gl.pc existiert im Dateisystem (gehört zu lib32-libglvnd)
lib32-mesa-tkg-git: /usr/lib32/pkgconfig/glesv2.pc existiert im Dateisystem (gehört zu lib32-libglvnd)

**Comment by random2324** [comment]
Ok figured it out. In customization.cfg both options must be false.
In packagebuild glvnd for 32 and 64 bit must be true. Then its working.

**Comment by Tk-Glitch** [comment]
The current `libglvnd`/`lib32-libglvnd` packages in Arch repos are not fully compatible with current mesa-git. Using `libglvnd-git` and `lib32-libglvnd-git` should fix your issue.

**Comment by random2324** [comment]
Saw that you added glvnd true to 64bit builds again. As I noted above, this did the trick for me. Thx!
