### ISSUE TITLE
[wine-tkg] Overwatch "No compatible graphics hardware was found."

### ISSUE THREAD

**Issue by EdLovecraft** [Tk-Glitch/PKGBUILDS#366]
Distro:Arch Linux（64 bit）
Kernel:5.3.8-19-tkg-pds
RAM:32 GB
GPU Driver:NVIDIA 435.27.02
GPU:NVIDIA GeForce GTX 1080 Ti
CPU:Intel Core i7-8700K @ 3.70GHz

Here's the log

> Running /usr/bin/wine /home/orwennes/Games/overwatch/drive_c/Program Files (x86)/Battle.net/Battle.net.exe --exec=launch Pro
> gamemodeauto: 
> fsync: up and running.
> [1104/215444.666:ERROR:network_change_notifier_win.cc(156)] WSALookupServiceBegin failed with: 0
> [1104/215445.103:ERROR:mf_helpers.cc(14)] Error in dxva_video_decode_accelerator_win.cc on line 373
> info:  Game: Battle.net.exe
> info:  DXVK: v1.4.4
> info:  Found config file: /home/orwennes/Games/overwatch/dxvk.conf
> info:  Effective configuration:
> info:    dxgi.nvapiHack = False
> warn:  OpenVR: Failed to locate module
> info:  Enabled instance extensions:
> info:    VK_KHR_get_physical_device_properties2
> info:    VK_KHR_surface
> info:    VK_KHR_win32_surface
> info:  GeForce GTX 1080 Ti:
> info:    Driver: 435.27.2
> info:    Vulkan: 1.1.126
> info:    Memory Heap[0]: 
> info:      Size: 11264 MiB
> info:      Flags: 0x1
> info:      Memory Type[7]: Property Flags = 0x1
> info:      Memory Type[8]: Property Flags = 0x1
> info:    Memory Heap[1]: 
> info:      Size: 24087 MiB
> info:      Flags: 0x0
> info:      Memory Type[0]: Property Flags = 0x0
> info:      Memory Type[1]: Property Flags = 0x0
> info:      Memory Type[2]: Property Flags = 0x0
> info:      Memory Type[3]: Property Flags = 0x0
> info:      Memory Type[4]: Property Flags = 0x0
> info:      Memory Type[5]: Property Flags = 0x0
> info:      Memory Type[6]: Property Flags = 0x0
> info:      Memory Type[9]: Property Flags = 0x6
> info:      Memory Type[10]: Property Flags = 0xe
> info:  GeForce GTX 1080 Ti:
> info:    Driver: 435.27.2
> info:    Vulkan: 1.1.126
> info:    Memory Heap[0]: 
> info:      Size: 11264 MiB
> info:      Flags: 0x1
> info:      Memory Type[7]: Property Flags = 0x1
> info:      Memory Type[8]: Property Flags = 0x1
> info:    Memory Heap[1]: 
> info:      Size: 24087 MiB
> info:      Flags: 0x0
> info:      Memory Type[0]: Property Flags = 0x0
> info:      Memory Type[1]: Property Flags = 0x0
> info:      Memory Type[2]: Property Flags = 0x0
> info:      Memory Type[3]: Property Flags = 0x0
> info:      Memory Type[4]: Property Flags = 0x0
> info:      Memory Type[5]: Property Flags = 0x0
> info:      Memory Type[6]: Property Flags = 0x0
> info:      Memory Type[9]: Property Flags = 0x6
> info:      Memory Type[10]: Property Flags = 0xe
> info:  D3D11CoreCreateDevice: Probing D3D_FEATURE_LEVEL_11_1
> info:  D3D11CoreCreateDevice: Using feature level D3D_FEATURE_LEVEL_11_1
> info:  Device properties:
> info:    Device name:     : GeForce GTX 1080 Ti
> info:    Driver version   : 435.27.2
> info:  Enabled device extensions:
> info:    VK_EXT_conditional_rendering
> info:    VK_EXT_depth_clip_enable
> info:    VK_EXT_host_query_reset
> info:    VK_EXT_shader_demote_to_helper_invocation
> info:    VK_EXT_shader_viewport_index_layer
> info:    VK_EXT_transform_feedback
> info:    VK_EXT_vertex_attribute_divisor
> info:    VK_KHR_create_renderpass2
> info:    VK_KHR_dedicated_allocation
> info:    VK_KHR_depth_stencil_resolve
> info:    VK_KHR_descriptor_update_template
> info:    VK_KHR_draw_indirect_count
> info:    VK_KHR_driver_properties
> info:    VK_KHR_get_memory_requirements2
> info:    VK_KHR_image_format_list
> info:    VK_KHR_maintenance1
> info:    VK_KHR_maintenance2
> info:    VK_KHR_sampler_mirror_clamp_to_edge
> info:    VK_KHR_shader_draw_parameters
> info:    VK_KHR_swapchain
> info:  Device features:
> info:    robustBufferAccess                     : 1
> info:    fullDrawIndexUint32                    : 1
> info:    imageCubeArray                         : 1
> info:    independentBlend                       : 1
> info:    geometryShader                         : 1
> info:    tessellationShader                     : 1
> info:    sampleRateShading                      : 1
> info:    dualSrcBlend                           : 1
> info:    logicOp                                : 1
> info:    multiDrawIndirect                      : 1
> info:    drawIndirectFirstInstance              : 1
> info:    depthClamp                             : 1
> info:    depthBiasClamp                         : 1
> info:    fillModeNonSolid                       : 1
> info:    depthBounds                            : 1
> info:    multiViewport                          : 1
> info:    samplerAnisotropy                      : 1
> info:    textureCompressionBC                   : 1
> info:    occlusionQueryPrecise                  : 1
> info:    pipelineStatisticsQuery                : 1
> info:    vertexPipelineStoresAndAtomics         : 1
> info:    fragmentStoresAndAtomics               : 1
> info:    shaderImageGatherExtended              : 1
> info:    shaderStorageImageExtendedFormats      : 1
> info:    shaderStorageImageReadWithoutFormat    : 1
> info:    shaderStorageImageWriteWithoutFormat   : 1
> info:    shaderClipDistance                     : 1
> info:    shaderCullDistance                     : 1
> info:    shaderFloat64                          : 1
> info:    shaderInt64                            : 1
> info:    variableMultisampleRate                : 1
> info:  VK_EXT_conditional_rendering
> info:    conditionalRendering                   : 1
> info:  VK_EXT_depth_clip_enable
> info:    depthClipEnable                        : 1
> info:  VK_EXT_host_query_reset
> info:    hostQueryReset                         : 1
> info:  VK_EXT_memory_priority
> info:    memoryPriority                         : 0
> info:  VK_EXT_shader_demote_to_helper_invocation
> info:    shaderDemoteToHelperInvocation         : 1
> info:  VK_EXT_transform_feedback
> info:    transformFeedback                      : 1
> info:    geometryStreams                        : 1
> info:  VK_EXT_vertex_attribute_divisor
> info:    vertexAttributeInstanceRateDivisor     : 1
> info:    vertexAttributeInstanceRateZeroDivisor : 1
> info:  Queue families:
> info:    Graphics : 0
> info:    Transfer : 1
> info:  DXVK: Read 30 valid state cache entries
> info:  DXVK: Using 9 compiler threads
> info:  Adapter LUID 0: 0:147b
> err:   D3D11DXGIResource::GetSharedHandle: Stub
> warn:  D3D11Texture2D::QueryInterface: Unknown interface query
> warn:  9d8e1289-d7b3-465f-8126-250e349af85d
> info:  Presenter: Actual swap chain properties:
> info:    Format:       VK_FORMAT_B8G8R8A8_UNORM
> info:    Present mode: VK_PRESENT_MODE_IMMEDIATE_KHR
> info:    Buffer size:  108x1
> info:    Image count:  2
> warn:  DXGI: MakeWindowAssociation: Ignoring flags
> warn:  D3D11Texture2D::QueryInterface: Unknown interface query
> warn:  9d8e1289-d7b3-465f-8126-250e349af85d
> err:   D3D11DXGIResource::GetSharedHandle: Stub
> warn:  D3D11Texture2D::QueryInterface: Unknown interface query
> warn:  9d8e1289-d7b3-465f-8126-250e349af85d
> info:  Presenter: Actual swap chain properties:
> info:    Format:       VK_FORMAT_B8G8R8A8_UNORM
> info:    Present mode: VK_PRESENT_MODE_IMMEDIATE_KHR
> info:    Buffer size:  1200x810
> info:    Image count:  2
> warn:  DXGI: MakeWindowAssociation: Ignoring flags
> warn:  D3D11Texture2D::QueryInterface: Unknown interface query
> warn:  9d8e1289-d7b3-465f-8126-250e349af85d
> warn:  D3D11Texture2D::QueryInterface: Unknown interface query
> warn:  f8fb5c27-c6b3-4f75-a4c8-439af2ef564c
> warn:  D3D11Texture2D::QueryInterface: Unknown interface query
> warn:  f8fb5c27-c6b3-4f75-a4c8-439af2ef564c
> warn:  D3D11Texture2D::QueryInterface: Unknown interface query
> warn:  f8fb5c27-c6b3-4f75-a4c8-439af2ef564c
> warn:  D3D11Texture2D::QueryInterface: Unknown interface query
> warn:  f8fb5c27-c6b3-4f75-a4c8-439af2ef564c
> warn:  D3D11Texture2D::QueryInterface: Unknown interface query
> warn:  f8fb5c27-c6b3-4f75-a4c8-439af2ef564c
> warn:  D3D11Texture2D::QueryInterface: Unknown interface query
> warn:  f8fb5c27-c6b3-4f75-a4c8-439af2ef564c
> warn:  D3D11Texture2D::QueryInterface: Unknown interface query
> warn:  f8fb5c27-c6b3-4f75-a4c8-439af2ef564c
> warn:  D3D11Texture2D::QueryInterface: Unknown interface query
> warn:  f8fb5c27-c6b3-4f75-a4c8-439af2ef564c
> warn:  D3D11Texture2D::QueryInterface: Unknown interface query
> warn:  f8fb5c27-c6b3-4f75-a4c8-439af2ef564c
> warn:  D3D11Texture2D::QueryInterface: Unknown interface query
> warn:  f8fb5c27-c6b3-4f75-a4c8-439af2ef564c
> warn:  D3D11Texture2D::QueryInterface: Unknown interface query
> warn:  f8fb5c27-c6b3-4f75-a4c8-439af2ef564c
> warn:  D3D11Texture2D::QueryInterface: Unknown interface query
> warn:  f8fb5c27-c6b3-4f75-a4c8-439af2ef564c
> warn:  D3D11Texture2D::QueryInterface: Unknown interface query
> warn:  f8fb5c27-c6b3-4f75-a4c8-439af2ef564c
> warn:  D3D11Texture2D::QueryInterface: Unknown interface query
> warn:  f8fb5c27-c6b3-4f75-a4c8-439af2ef564c
> warn:  D3D11Texture2D::QueryInterface: Unknown interface query
> warn:  f8fb5c27-c6b3-4f75-a4c8-439af2ef564c
> warn:  D3D11Texture2D::QueryInterface: Unknown interface query
> warn:  f8fb5c27-c6b3-4f75-a4c8-439af2ef564c
> warn:  D3D11Texture2D::QueryInterface: Unknown interface query
> warn:  f8fb5c27-c6b3-4f75-a4c8-439af2ef564c
> warn:  D3D11Texture2D::QueryInterface: Unknown interface query
> warn:  f8fb5c27-c6b3-4f75-a4c8-439af2ef564c
> warn:  D3D11Texture2D::QueryInterface: Unknown interface query
> warn:  f8fb5c27-c6b3-4f75-a4c8-439af2ef564c
> warn:  D3D11Texture2D::QueryInterface: Unknown interface query
> warn:  f8fb5c27-c6b3-4f75-a4c8-439af2ef564c
> warn:  D3D11Texture2D::QueryInterface: Unknown interface query
> warn:  f8fb5c27-c6b3-4f75-a4c8-439af2ef564c
> warn:  D3D11Texture2D::QueryInterface: Unknown interface query
> warn:  f8fb5c27-c6b3-4f75-a4c8-439af2ef564c
> warn:  D3D11Texture2D::QueryInterface: Unknown interface query
> warn:  f8fb5c27-c6b3-4f75-a4c8-439af2ef564c
> warn:  D3D11Texture2D::QueryInterface: Unknown interface query
> warn:  f8fb5c27-c6b3-4f75-a4c8-439af2ef564c
> warn:  D3D11Texture2D::QueryInterface: Unknown interface query
> warn:  f8fb5c27-c6b3-4f75-a4c8-439af2ef564c
> warn:  D3D11Texture2D::QueryInterface: Unknown interface query
> warn:  f8fb5c27-c6b3-4f75-a4c8-439af2ef564c
> warn:  D3D11Texture2D::QueryInterface: Unknown interface query
> warn:  f8fb5c27-c6b3-4f75-a4c8-439af2ef564c
> warn:  D3D11Texture2D::QueryInterface: Unknown interface query
> warn:  f8fb5c27-c6b3-4f75-a4c8-439af2ef564c
> warn:  D3D11Texture2D::QueryInterface: Unknown interface query
> warn:  f8fb5c27-c6b3-4f75-a4c8-439af2ef564c
> warn:  D3D11Texture2D::QueryInterface: Unknown interface query
> warn:  f8fb5c27-c6b3-4f75-a4c8-439af2ef564c
> warn:  D3D11Texture2D::QueryInterface: Unknown interface query
> warn:  f8fb5c27-c6b3-4f75-a4c8-439af2ef564c
> warn:  D3D11Texture2D::QueryInterface: Unknown interface query
> warn:  f8fb5c27-c6b3-4f75-a4c8-439af2ef564c
> warn:  D3D11Texture2D::QueryInterface: Unknown interface query
> warn:  f8fb5c27-c6b3-4f75-a4c8-439af2ef564c
> warn:  D3D11Texture2D::QueryInterface: Unknown interface query
> warn:  f8fb5c27-c6b3-4f75-a4c8-439af2ef564c
> warn:  D3D11Texture2D::QueryInterface: Unknown interface query
> warn:  f8fb5c27-c6b3-4f75-a4c8-439af2ef564c
> info:  Presenter: Actual swap chain properties:
> info:    Format:       VK_FORMAT_B8G8R8A8_UNORM
> info:    Present mode: VK_PRESENT_MODE_FIFO_KHR
> info:    Buffer size:  1200x810
> info:    Image count:  3
> [1104/215454.823:ERROR:network_change_notifier_win.cc(156)] WSALookupServiceBegin failed with: 0
> warn:  D3D11Texture2D::QueryInterface: Unknown interface query
> warn:  f8fb5c27-c6b3-4f75-a4c8-439af2ef564c
> warn:  D3D11Texture2D::QueryInterface: Unknown interface query
> warn:  f8fb5c27-c6b3-4f75-a4c8-439af2ef564c
> warn:  D3D11Texture2D::QueryInterface: Unknown interface query
> warn:  f8fb5c27-c6b3-4f75-a4c8-439af2ef564c
> warn:  D3D11Texture2D::QueryInterface: Unknown interface query
> warn:  f8fb5c27-c6b3-4f75-a4c8-439af2ef564c
> warn:  D3D11Texture2D::QueryInterface: Unknown interface query
> warn:  f8fb5c27-c6b3-4f75-a4c8-439af2ef564c
> warn:  D3D11Texture2D::QueryInterface: Unknown interface query
> warn:  f8fb5c27-c6b3-4f75-a4c8-439af2ef564c
> warn:  D3D11Texture2D::QueryInterface: Unknown interface query
> warn:  f8fb5c27-c6b3-4f75-a4c8-439af2ef564c
> warn:  D3D11Texture2D::QueryInterface: Unknown interface query
> warn:  f8fb5c27-c6b3-4f75-a4c8-439af2ef564c
> warn:  D3D11Texture2D::QueryInterface: Unknown interface query
> warn:  f8fb5c27-c6b3-4f75-a4c8-439af2ef564c
> warn:  D3D11Texture2D::QueryInterface: Unknown interface query
> warn:  f8fb5c27-c6b3-4f75-a4c8-439af2ef564c
> warn:  D3D11Texture2D::QueryInterface: Unknown interface query
> warn:  f8fb5c27-c6b3-4f75-a4c8-439af2ef564c
> warn:  D3D11Texture2D::QueryInterface: Unknown interface query
> warn:  f8fb5c27-c6b3-4f75-a4c8-439af2ef564c
> warn:  D3D11Texture2D::QueryInterface: Unknown interface query
> warn:  f8fb5c27-c6b3-4f75-a4c8-439af2ef564c
> warn:  D3D11Texture2D::QueryInterface: Unknown interface query
> warn:  f8fb5c27-c6b3-4f75-a4c8-439af2ef564c
> [1104/215615.166:ERROR:browser_process_sub_thread.cc(221)] Waited 10 ms for network service

**Comment by Anti-Ultimate** [comment]
What patches did you use?

**Comment by fluffykittyrevenge** [comment]
Googled your error and came up with this after reading [this reddit thread](https://www.reddit.com/r/wine_gaming/comments/dggsp9/lutris_battlenet_crash_after_newest_update/):

The fix for now:
- Start "Wine Configuration"
- Go in the "Libraries" tab.
- Add the following (may vary but worked for me):
api-ms-win-crt-heap-l1-1-0.dll
api-ms-win-crt-locale-l1-1-0.dll
api-ms-win-crt-runtime-l1-1-0.dll
api-ms-win-crt-stdio-l1-1-0.dll
ucrtbase
vcruntime140
- Apply

You will also need to install Core TTF Fonts from Microsoft
I do that using winetricks:

`winetricks corefonts`

Now Battle.net should work.

**Comment by Tk-Glitch** [comment]
@EdLovecraft Were you able to fix your issue?
