### ISSUE TITLE
World of Warcraft 8.2.5 crashes

### ISSUE THREAD

**Issue by SveSop** [Tk-Glitch/PKGBUILDS#368]
I have been using TKG patches with the "fshack" set for WoW a while now, but upon pulling GIT today and recompiling 4.19 with some changed/added fshack patches like https://github.com/Tk-Glitch/PKGBUILDS/commit/21a7d06fa2bfb9ec66f4d8047bca7a20717fe8bf#diff-410db0d6d78fed0dbe64a6a4e5025e00 it broke for me.

I cannot pinpoint what patch 100%, and cant really be bothered to do a bisect now.. I set `_proton_fs_hack="false"` and WoW works again. If this is of interest of anyone, feel free to test.. if it is of no importance to run WoW with the fshack patches, feel free to close this issue :)

Afaik lutris builds without the fshack patches anyway...

**Comment by Tk-Glitch** [comment]
Can you please describe what breaks exactly?

**Comment by SveSop** [comment]
I have not captured any logs, but when pressing "PLAY" on the Battle.net app to start WoW, it takes 4-5 seconds, and the "Error 132" box pops up and it closes.

I can come back with more details if it is something you are not aware of, and want to troubleshoot?

I am somewhat unfamiliar with the PKGBUILD method of patching wine, so i might have done something wrong with my config... but when i pulled this after 4.19 was releases - i think this sunday - i built with the fshack patches as i have done a while now, and everything was oki. Then without changing the config, i pulled PKGBUILD git yesterday with some updated patches and rebuilt without changing my customization.cfg at all, and no more WoW :) I guess something can have changed with the customization.cfg file too, and there is a option there that could break things.

I'm at work atm, so can't send you the conf, but from memory i have mostly used defaults exept changing:

`_staging_version="v4.19"`
`_use_pba="false"`
`_use_vkd3d="true"`
`_childwindow_fix="true"`
`_FS_bypass_compositor="true"`
`_proton_fs_hack="true"`
`_nvidia_hate="true"`
`_steam_fix="false"`

I think it was some option for `_rawinput_fix="true"` , but i see this option is now gone... and that introduced the same problem regular wine-staging had for me in WoW with 4.16 - That when i mouselook WHILE also using keyboard to move, i need to doubleclick. I have not used regular wine-staging for a couple of rev's now, but i posted a bug report here that was solved after stagaing-4.17: https://bugs.winehq.org/show_bug.cgi?id=47764

I will redo my customization.cfg file when i get home, in case some option there makes PKGBUILD pull some old patches that mess things up?

**Comment by Tk-Glitch** [comment]
Looks like it might have something to do with vkd3d in some ways. I'll try to get a consistent repro.

Initial launch: error 132 as you described.
Using `-d3d11` as startup argument in bnet launcher for WoW (to enforce DXVK), the game starts and seemingly works just fine on my end.

![Screenshot_20191106_115654](https://user-images.githubusercontent.com/741977/68293210-cbee4400-008d-11ea-94d3-8a97bb28f4f2.png)
![Screenshot_20191106_120332](https://user-images.githubusercontent.com/741977/68293220-d0b2f800-008d-11ea-8979-9a818c843215.png)

**Comment by SveSop** [comment]
If you use regular GIT of vkd3d, it does not work with WoW atm. I have patches for WoW that fixes this + fixes zoning into Nazjatar.
However, launching WoW with -d3d11 with the customization.cfg i mentioned above did not work for me.

I will report back when i redo my .cfg file and try again.

PS. If you are interested in the patches used to get vkd3d to work with WoW (atleast for nVidia.. i have not tested with AMD) i can provide a patchset for you on my git, or you can extract the patches from the .deb package here : [https://launchpad.net/~cybermax-dexter/+archive/ubuntu/vkd3d/+sourcefiles/vkd3d/1.1git20191101-3~bionic1/vkd3d_1.1git20191101-3~bionic1.debian.tar.xz](https://launchpad.net/~cybermax-dexter/+archive/ubuntu/vkd3d/+sourcefiles/vkd3d/1.1git20191101-3~bionic1/vkd3d_1.1git20191101-3~bionic1.debian.tar.xz)

**Comment by Tk-Glitch** [comment]
Reviewing your settings:
`_staging_version="v4.19"` That'll target the point release, I suppose that's what you wanted
`_use_pba="false"` That's not needed, the patchset is force-disabled on anything past wine 3.19
`_use_vkd3d="true"` All good
`_childwindow_fix="true"` Even though there's a (yet to be verified) possible regression case with this, it's unlikely to be an issue here (I'm using it also)
`_FS_bypass_compositor="true"` a priori harmless
`_proton_fs_hack="true"`
`_nvidia_hate="true"` Overkill in the vast majority of cases, and can even create issues
`_steam_fix="false"` Harmless and possibly deprecated with the new library

So except for possibly `_nvidia_hate="true"` it should be okay.

I'll have a look at the VKD3D patches for further testing, thanks.

**Comment by Tk-Glitch** [comment]
Okay, so I was able to get functional vkd3d libs for wow and the result is.... It works fine as well.
![Screenshot_20191106_145437](https://user-images.githubusercontent.com/741977/68304217-9ead9000-00a5-11ea-99d6-2724f7557617.png)

At this stage I'll suggest trying with `_nvidia_hate="false"` and giving `_kernelbase_reverts="true"` a try.

**Comment by SveSop** [comment]
> Reviewing your settings:
> _staging_version="v4.19" That'll target the point release, I suppose that's what you wanted

Yes

> _use_pba="false" That's not needed, the patchset is force-disabled on anything past wine 3.19
> _use_vkd3d="true" All good
> _childwindow_fix="true" Even though there's a (yet to be verified) possible regression case with this, it's unlikely to be an issue here (I'm using it also)
> _FS_bypass_compositor="true" a priori harmless
> _proton_fs_hack="true"

Ok

> _nvidia_hate="true" Overkill in the vast majority of cases, and can even create issues

For WoW this is no problem, since WoW does not do any nvAPI calls ref. logs: 
`11/6 15:34:24.635  Wine detected, skipping NvAPI/ADL loading`

> _steam_fix="false" Harmless and possibly deprecated with the new library

Ok

> So except for possibly _nvidia_hate="true" it should be okay.

If i use a game that uses some nvapi calls, i use my in-testing nvapi implementation here: [https://github.com/SveSop/nvapi_standalone/tree/lite](https://github.com/SveSop/nvapi_standalone/tree/lite) It pulls driver version and things from Linux libraries + adds support for `SetDepthBoundsTest` with DXVK. This library is meant for usage with DXVK tho, and probably will fail if used with wined3d. (This is kinda off-topic anyways)

> I'll have a look at the VKD3D patches for further testing, thanks. Your link doesn't work for me btw.

It seems you figured it out. Those patches are picked from the wine-devel list, and will probably be committed over time. Atleast these patches fixes 2 bugs with WoW with D3D12. (Flashing textures, and crashing when zoning into Nazjatar).

> At this stage I'll suggest trying with _nvidia_hate="false" and giving _kernelbase_reverts="true" a try.

I redid my customization.cfg removing a couple of lines no longer in use, and adding `_kernelbase_reverts="true"` and that seemed to fix things. FS hack enabled, and no more mouselook problems so far. Thanks :)

**Comment by Tk-Glitch** [comment]
Yet again the `kernelbase_reverts` patchset to the rescue! Happy you got it fixed :)
