### ISSUE TITLE
[Wine] Patches applying errors

### ISSUE THREAD

**Issue by Kerrung** [Tk-Glitch/PKGBUILDS#37]
![screenshot from 2018-10-30 14-40-03](https://user-images.githubusercontent.com/36989404/47709293-c166c680-dc51-11e8-8169-d1b18734f479.png)

[Wine_(Config+PKGBUILD).zip](https://github.com/Tk-Glitch/PKGBUILDS/files/2528959/Wine_.Config%2BPKGBUILD.zip)

**Comment by Tk-Glitch** [comment]
PBA at it again :D

**Comment by ryanmusante** [comment]
I'm a bit confused with the current plans for wine devs (including proton). PBA will or won't be pulled upstream / staging? It is or isn't necessary if DXVK is enabled and running?

**Comment by Tk-Glitch** [comment]
@ryanmusante Valve has expressed the will to mainline it, so that should happen at some point. It isn't redundant with DXVK as not everyone has Vulkan capable hardware to begin with, and DXVK doesn't support D3D9 & lower. Of course, if you got Vulkan capable hardware, PBA serves no purpose anymore on D3D10 & D3D11 games.

**Comment by clapbr** [comment]
> @ryanmusante Valve has expressed the will to mainline it, so that should happen at some point. It isn't redundant with DXVK as not everyone has Vulkan capable hardware to begin with, and DXVK doesn't support D3D9 & lower. Of course, if you got Vulkan capable hardware, PBA serves no purpose anymore on (most) D3D10 & D3D11 games.

Do you know if Gallium9 is benefited from PBA? Or only wined3d?

**Comment by Tk-Glitch** [comment]
@clapbr Only wined3d

**Comment by Kerrung** [comment]
The fixes is here:
https://github.com/bobwya/gentoo-wine-pba/commits/master

**Comment by Kerrung** [comment]
@Tk-Glitch  the PBA fixes is here:
https://github.com/bobwya/gentoo-wine-pba/commits/master
Maybe you should change a source of the PBA patches to this? This repo do PBA rebases every Wine commit.

**Comment by Kerrung** [comment]
@Tk-Glitch  the PBA fixes are here:
https://github.com/bobwya/gentoo-wine-pba/commits/master
Maybe you should change a source of the PBA patches to this? This repo do PBA rebases every Wine commit.

**Comment by Tk-Glitch** [comment]
@Kerrung Did you actually tried it? I bet you didn't. Also, there's no source as the patches are standalone and locally stored. So, please, stop with that. Thank you.
