### ISSUE TITLE
mingw builds fail on fresh install

### ISSUE THREAD

**Issue by ganthore** [Tk-Glitch/PKGBUILDS#372]
Normally I compile all of these deps manually by hand, but with my new Arch install, I decided to be lazy and use your automated script =3.

I discovered that many parts of the test suite fail (builds started failing after the installation of cloog), so to workaround the problem I added a the --nocheck flag to your makepkg lines along with some others (--skippgpcheck --skipchecksums) to help avoid any further errors. Otherwise, things are building and installing without further issues.

```
   if [[ "$1" == "-f" ]] || [[ "$1" == "--force" ]]; then
-    makepkg -csi --noconfirm --force
+    makepkg -csi --noconfirm --force --skippgpcheck --skipchecksums --nocheck
   else
-    makepkg -csi --noconfirm
+    makepkg -csi --noconfirm --skippgpcheck --skipchecksums --nocheck
   fi
   if [ "$_AURPKGNAME" == "mingw-w64-winpthreads" ]; then
     libtool --finish /usr/x86_64-w64-mingw32/lib
```

**Comment by Tk-Glitch** [comment]
I just ran the script to check and it didn't hit any roadblock. Are you sure it wasn't a simple timeout on the gpg keys import process? It's happening quite often.

**Comment by ganthore** [comment]
@Tk-Glitch it very well could be, since I added --skippgpcheck I guess we'll never know until I redo everything. On the next try, should I just back out my changes and maybe switch _pgp_auto off?

**Comment by Tk-Glitch** [comment]
Yes please try with an unmodified script and if you set `_pgp_auto` to disabled, try and import the keys manually beforehand to make sure you won't get blocked later on.
The first package that gets built after cloog is `mingw-w64-binutils` and the PKGBUILD definitely checks for a PGP key:
```
validpgpkeys=('3A24BC1E8FB409FA9F14371813FCEF89DD9E3C4F')  # Nick Clifton (Chief Binutils Maintainer) <nickc@redhat.com>
```
This is the first one (`13FCEF89DD9E3C4F`) that the script imports. The timeout idea definitely seems plausible.

**Comment by ganthore** [comment]
Thanks. I'll give that a shot. 

Maybe a good idea to append that to the README.md as a pre-installation step?

**Comment by Tk-Glitch** [comment]
Absolutely. I'll add a note.

**Comment by reno138** [comment]
I'm running into this exact issue currently. I have one machine - my laptop (intel proc, manjaro) and my desktop (Ryzen, manjaro). Both fresh installs. The laptop worked after I forced a key refresh. The desktop just will not add those keys. I'm wondering if it's just a problem with the key servers. System time is set correctly (both sync to pool.ntp.org) so it's not a clock skew problem. Is there anything else, something like secureboot, etc, that can get in the way of this?

**Comment by reno138** [comment]
Both machines are failing the import of the keys now, so I'm guessing it's a problem with the key servers. I'll give it some time and try again.

**Comment by Tk-Glitch** [comment]
It seems to be pretty common (it definitely is for me) that you need to insist quite a bit until it finally passes.

Alternatively, you can also use https://github.com/Tk-Glitch/PKGBUILDS/tree/master/mostlyportable-gcc instead to build a portable build that won't randomly break due to partial mingw package updates.
Both wine-tkg-git/proton-tkg/dxvk-tools have built-in support for it (you simply have to set the path in your .cfg files).

**Comment by reno138** [comment]
it was definitely the key servers. all working now.
