### ISSUE TITLE
[wine-tkg-git] fsync: Floating point exception (core dumped), when run wineboot -u or winecfg

### ISSUE THREAD

**Issue by Kerrung** [Tk-Glitch/PKGBUILDS#375]
wineboot -u or winecfg can't be run on Arch Linux only if fsync patches was applied.

[last_build_config.log](https://github.com/Tk-Glitch/PKGBUILDS/files/3824623/last_build_config.log)

![Screenshot from 2019-11-08 17-43-23](https://user-images.githubusercontent.com/36989404/68477721-f556cd80-024f-11ea-9d90-d277964c5581.png)

**Comment by soredake** [comment]
I have the same problem https://github.com/Tk-Glitch/PKGBUILDS/issues/287#issuecomment-551839661

**Comment by Tk-Glitch** [comment]
Staging is currently borked

**Comment by Tk-Glitch** [comment]
You can try `_kernelbase_reverts="true"` in combination with `_staging_version="e1ac8f20fe17e9282dbeaff9fbadadf53b722b1d"` and answering "y" to the hotfix prompt. That should fix it while we wait for an upstream fix.

**Comment by soredake** [comment]
@Tk-Glitch it works, big thanks!

**Comment by llde** [comment]
If it's of interest, valgridn give this:

**Comment by llde** [comment]
Issue is resolved with  commit 0d5afe0ba9375c85847d5c54e311531c8570b815

This issue can be closed.

**Comment by Kerrung** [comment]
Thank you!
