### ISSUE TITLE
Updated LAA patch fails to patch

### ISSUE THREAD

**Issue by ronoverdrive** [Tk-Glitch/PKGBUILDS#377]
-> Applying LAA-staging-608d086.patch
patching file dlls/kernel32/heap.c
Hunk #2 succeeded at 826 (offset -551 lines).
Hunk #3 succeeded at 870 (offset -551 lines).
patching file dlls/ntdll/loader.c
Hunk #1 succeeded at 2495 with fuzz 1 (offset 510 lines).
Hunk #2 succeeded at 4623 (offset 952 lines).
patching file dlls/ntdll/ntdll.spec
Hunk #1 succeeded at 1559 with fuzz 2 (offset 52 lines).
patching file dlls/ntdll/ntdll_misc.h
Hunk #1 succeeded at 198 (offset 9 lines).
patching file dlls/ntdll/virtual.c
Hunk #1 FAILED at 2442.
1 out of 1 hunk FAILED -- saving rejects to file dlls/ntdll/virtual.c.rej
==> ERROR: A failure occurred in prepare().
    Aborting...
  -> Removed BIG_UGLY_FROGMINER - Ribbit
  -> Removed Proton-tkg token - Valve Ribbit
  -> exit cleanup done

**Comment by Tk-Glitch** [comment]
Wine version?

**Comment by ronoverdrive** [comment]
WINE-TKG-GIT 4.19.r9

**Comment by Tk-Glitch** [comment]
I can't reproduce the issue :/
For some reason the wrong patch gets selected on your end. Can you please post the content of your `last_build_config.log`?

**Comment by ronoverdrive** [comment]
`# Last wine-tkg-staging-fsync-vkd3d-git configuration - Fri 08 Nov 2019 02:39:35 PM EST :

Wine (plain) version: 4.19.r85.g7f469b689a
Using wine-staging patchset (version 4.19.r7.ge1ac8f20)
Disabled the local Esync patchset to use Staging impl instead.
Using VKD3D for d3d12 translation

Applied clock_monotonic patch
Applied clock_monotonic addon patch for 13e11d3
Applied Fullscreen compositor bypass patch
Applied MTGA crashfix
Applied Mechwarrior Online fix
Applied child window for vk patch
Applied steam crossover hack
Applied CSMT toggle logic patch
Staging overrides, if any: 
Applied Mortal Kombat 11 fix
Applied fsync, an experimental replacement for esync (staging <608d086)
Added no_alloc_handle object method to fsync
Applied winevulkan 1.1.113 patch
Applied proton mf hacks patch`

**Comment by Tk-Glitch** [comment]
Thanks. Found the culprit. Fix incoming.

**Comment by Tk-Glitch** [comment]
Should be fixed as of https://github.com/Tk-Glitch/PKGBUILDS/commit/fda38193df8d7a052f597e2d204529d1101cbb44
Please confirm if it's all good on your end as well :)

**Comment by ronoverdrive** [comment]
Successfully patched and compiling now.
