### ISSUE TITLE
winex11-fs-no_above_state.mypatch fails to patch

### ISSUE THREAD

**Issue by ronoverdrive** [Tk-Glitch/PKGBUILDS#378]
error:
  -> ######################################################
  -> 
  -> Applying your own plain-wine patch /home/ronoverdrive/PKGBUILDS/wine-tkg-git/winex11-fs-no_above_state.mypatch
  -> 
  -> ######################################################
patching file dlls/winex11.drv/window.c
Hunk #1 FAILED at 1078.
1 out of 1 hunk FAILED -- saving rejects to file dlls/winex11.drv/window.c.rej

```
#Last wine-tkg-staging-fsync-vkd3d-git configuration - Fri 08 Nov 2019 09:15:56 PM EST :

last_build_config.log:
Wine (plain) version: 4.19.r85.g7f469b689a
Using wine-staging patchset (version 4.19.r7.ge1ac8f20)
Disabled the local Esync patchset to use Staging impl instead.
Using VKD3D for d3d12 translation

Kernelbase reverts clean reverts applied
Applied clock_monotonic patch
Applied clock_monotonic addon patch for 13e11d3
Applied Fullscreen compositor bypass patch
Applied MTGA crashfix
Applied Mechwarrior Online fix
Applied child window for vk patch
Applied steam crossover hack
Applied CSMT toggle logic patch
Staging overrides, if any: 
Applied Mortal Kombat 11 fix
Applied fsync, an experimental replacement for esync (staging <608d086)
Added no_alloc_handle object method to fsync
Applied winevulkan 1.1.113 patch
Applied proton mf hacks patch
Using kernelbase reverts patch (staging)
Applied large address aware override support
Applied your own patch /home/ronoverdrive/PKGBUILDS/wine-tkg-git/rem-rawinput.mypatch
```

**Comment by Tk-Glitch** [comment]
Oh yeah sorry, that patch depends on the fs hack patchset. I'll add a note.

**Comment by ronoverdrive** [comment]
Ah so that means it can't be used with the raw input patch which requires you not use the FS hack.

**Comment by Tk-Glitch** [comment]
Indeed. It will require a rebase of the raw input patchset against the fs hack.

**Comment by Tk-Glitch** [comment]
I'm closing this now that I have added the note to the community-patches readme.
