### ISSUE TITLE
[wine-tkg] Question about NtContinue patchset revert

### ISSUE THREAD

**Issue by llde** [Tk-Glitch/PKGBUILDS#379]
Hi,
It's stated that the "ntdll-NtContinue: Also use NtContinue() to continue after an exception on x86_64."
is causing some games and application to crash/malfunction.
As I skipped to apply the revert in my current wine-staging-tkg what are know affected applications, and it's possible to identify if a bug is caused by this patchset (without doing a bisection everytime)?
I'm asking becouse no-one still reported these issues to the bug report where the patchset originated, and no-one reported in wine staging bucktracker or here about broken applications (except maybe a may be related overwatch error, and clear this patchset was added in staging repo 3 days ago ), and as this patch seems to be required by some nasty copy protection schemes, it may be important  to resolve an undelying and still undetected issue  with the patchset

**Comment by Tk-Glitch** [comment]
The patch notably hangs The Witcher 3 (the process stops allocating memory during launch and stays frozen) and prevents some Blizzard games to run (supposedly World of Warcraft and Overwatch at the very least, crashing early on and triggering their crash reporting tool).

**Comment by Tk-Glitch** [comment]
The regression was fixed with https://github.com/wine-staging/wine-staging/commit/ca018c8079002030e8224988dc5752e9796d5b7c
I guess I can close :)
