### ISSUE TITLE
wine-tkg [wineserver] crashing upon loading steam

### ISSUE THREAD

**Issue by ryanmusante** [Tk-Glitch/PKGBUILDS#38]
Since the 3.19 wine staging releases, _wine-steam_ is crashing and will not load. 
I did following troubleshooting:
1. Uninstall and Re-compile wine from tkg source
2. Re-install Steam
2. Delete ~/.wine prefix
3. Install wine from chaotic-aur / wine-tkg-staging-esync-git 
4. Use all defaults and try again
```
[Thu Nov  1 17:34:11 2018] Code: 71 3e 00 00 48 89 c3 48 85 db 74 7c 48 8b 43 08 48 89 df ff 50 48 49 89 c7 48 89 df e8 84 ba 00 00 4d 85 ff 74 62 49 8d 55 10 <41> 8b b7 e8 00 00 00 4c 89 ff e8 ac ed fe ff 49 89 c4 4d 85 e4 74
[Thu Nov  1 17:36:14 2018] wineserver[12318]: segfault at 5e4 ip 0000000000415105 sp 00007ffdccb6afc0 error 4 in wineserver[403000+5a000]
```

**Comment by Tk-Glitch** [comment]
I can reproduce it. Not sure I have anything to do with it though. I'm going to investigate.

**Comment by Tk-Glitch** [comment]
Ok, this is esync-related. Had a quick talk with @zfigura about it and he'll be working on a fix. You can simply disable esync or use 5a85ab0 staging commit in the meantime. Please don't close the issue until this is resolved so other people can see it.
