### ISSUE TITLE
[wine-tkg-git] FAILED during patching file patches/ntdll-NtContinue/0002-Use-NtContinue-to-continue-execution-after-exception.patch

### ISSUE THREAD

**Issue by Kerrung** [Tk-Glitch/PKGBUILDS#380]
[customization.cfg.zip](https://github.com/Tk-Glitch/PKGBUILDS/files/3830180/customization.cfg.zip)

![Screenshot from 2019-11-11 12-50-16](https://user-images.githubusercontent.com/36989404/68570203-e3f50780-0481-11ea-89e4-da1631790749.png)

**Comment by telans** [comment]
Don't apply the hotfix, or use an earlier staging commit

I belive this is why: https://github.com/wine-staging/wine-staging/commit/ca018c8079002030e8224988dc5752e9796d5b7c

**Comment by Kerrung** [comment]
> Don't apply the hotfix, or use an earlier staging commit
> 
> I belive this is why: [wine-staging/wine-staging@ca018c8](https://github.com/wine-staging/wine-staging/commit/ca018c8079002030e8224988dc5752e9796d5b7c)

How can I disable the application of this hotfix?

**Comment by telans** [comment]
Does it not give you a prompt?

**Comment by Kerrung** [comment]
> prompt

I disabled all prompts in configuration.cfg.
_NOINITIALPROMPT="true"
_user_patches="true"
_user_patches_no_confirm="true"

**Comment by telans** [comment]
Revert no_confirm and don't apply the hotfix

**Comment by Kerrung** [comment]
> Revert no_confirm and don't apply the hotfix

Thank you! Now it compiles fine!
But, nevertheless, I will not close this issue for now, until it is fully fixed here.
