### ISSUE TITLE
[wine-tkg-git] Wine upstream now supports Vulkan 1.1.126. So, wine-tkg-git with your Vulkan-update patches failed to compile.

### ISSUE THREAD

**Issue by Kerrung** [Tk-Glitch/PKGBUILDS#382]
[last_build_config.log](https://github.com/Tk-Glitch/PKGBUILDS/files/3835734/last_build_config.log)

https://source.winehq.org/git/wine.git/shortlog/refs/heads/master

![Screenshot from 2019-11-12 15-51-35](https://user-images.githubusercontent.com/36989404/68666016-ebd9a800-0564-11ea-8349-28ea0eafcc6d.png)

**Comment by Tk-Glitch** [comment]
Fixed by https://github.com/Tk-Glitch/PKGBUILDS/commit/fc2aa3c32c25d6b2684c4ff84d0e424d9e117516
