### ISSUE TITLE
[wine-tkg-git] don't compile anymore with _steam_fix="true"

### ISSUE THREAD

**Issue by Kerrung** [Tk-Glitch/PKGBUILDS#388]
[last_build_config.log](https://github.com/Tk-Glitch/PKGBUILDS/files/3840948/last_build_config.log)
![Screenshot from 2019-11-13 17-00-35](https://user-images.githubusercontent.com/36989404/68762170-78ed3180-0637-11ea-8ab2-0efe448bdb58.png)

**Comment by robzombie91** [comment]
+1 Confirmed. Turning off steam fix in customization.cfg temporarily fixes this issue until the real fix happens

**Comment by Tk-Glitch** [comment]
Fixed by https://github.com/Tk-Glitch/PKGBUILDS/commit/28e50e027262a667b970de0b26e2ee4fcde4a3a4
