### ISSUE TITLE
Wine build fails

### ISSUE THREAD

**Issue by ErdeFB** [Tk-Glitch/PKGBUILDS#389]
At the time of writing, a change to pushed to master that was related to steam.patch (broke builds utilizing said legacy patch before it) and now building Wine fails consistently on a fresh clone with the following rather vague error:

```
r -Wvla \
  -Wwrite-strings -Wpointer-arith -Wlogical-op -Wno-format -D_FORTIFY_SOURCE=2 -pipe -O3 -ftree-vectorize
../../tools/winegcc/winegcc -o mciwave.dll --wine-objdir ../.. -b x86_64-w64-mingw32 --lib-suffix=.cross.a \
  -Wl,--wine-builtin -shared ../../../wine-mirror-git/dlls/mciwave/mciwave.spec -mno-cygwin \
  mciwave.cross.o ../../dlls/winmm/libwinmm.cross.a ../../dlls/user32/libuser32.cross.a \
  -pipe -O3 -ftree-vectorize
make[1]: Leaving directory '/tmp/makepkg/wine-tkg-staging-fsync-vkd3d-git/src/wine-tkg-staging-fsync-vkd3d-git-64-build/dlls/mciwave'
make[1]: Leaving directory '/tmp/makepkg/wine-tkg-staging-fsync-vkd3d-git/src/wine-tkg-staging-fsync-vkd3d-git-64-build/dlls/kernel32'
../../tools/winegcc/winegcc -o dwrite.dll.so --wine-objdir ../.. -m64 -fPIC -fasynchronous-unwind-tables \
  -shared ../../../wine-mirror-git/dlls/dwrite/dwrite.spec analyzer.o bidi.o bracket.o direction.o \
  font.o freetype.o gdiinterop.o layout.o linebreak.o main.o mirror.o opentype.o scripts.o shape.o \
  -luser32 -lgdi32 -ladvapi32 ../../libs/port/libwine_port.a -pipe -O3 -ftree-vectorize
../../tools/winegcc/winegcc -o dwrite.dll.fake --wine-objdir ../.. -m64 -fPIC -fasynchronous-unwind-tables \
  -shared ../../../wine-mirror-git/dlls/dwrite/dwrite.spec analyzer.o bidi.o bracket.o direction.o \
  font.o freetype.o gdiinterop.o layout.o linebreak.o main.o mirror.o opentype.o scripts.o shape.o \
  -luser32 -lgdi32 -ladvapi32 ../../libs/port/libwine_port.a -pipe -O3 -ftree-vectorize
make[1]: Leaving directory '/tmp/makepkg/wine-tkg-staging-fsync-vkd3d-git/src/wine-tkg-staging-fsync-vkd3d-git-64-build/dlls/dwrite'
==> ERROR: A failure occurred in build().
    Aborting...
  -> Removed BIG_UGLY_FROGMINER - Ribbit
  -> Removed Proton-tkg token - Valve Ribbit
  -> exit cleanup done
  -> Compilation time for 64-bit wine: 

real	0m53.778s
user	1m24.164s
sys	0m37.550s
```
Not sure if an upstream issue, but the timing was convenient enough to at least merit mentioning it here especially since there were no build errors if steam.patch was not enabled prior the update.

**Comment by Tk-Glitch** [comment]
The updated patch needs adjustments so please keep it disabled for now. I'll fix it later today.

**Comment by ErdeFB** [comment]
Fair enough. Any way to disable it for proton builds? Earlier due to said patch file proton failed to build, but I didn't find the setting for it in the proton build cfg file even if I did in the regular Wine one (where it was disabled) so is it named differently?

**Comment by Tk-Glitch** [comment]
I'll answer now even though this is fixed, but you can add the option to proton-tkg.cfg (or your external config) if needed. The option was considered as non-useful for a proton build so the option is not there for simplicity but since the proton-tkg script is a wrapper for the wine-tkg building process, it will respond to the same options (+ its own specific ones).
