### ISSUE TITLE
proton-tkg-4.19.r16: GTA IV fails to launch

### ISSUE THREAD

**Issue by telans** [Tk-Glitch/PKGBUILDS#393]
Worked with 4.19-r8, same results with & without fsync, as well as D9VK. Also removed launch arguments, same result.
Can't see why it's failing to launch, but this seems awfully unspecific

 `wine: Unhandled page fault on execute access to 00000000 at address 00000000 (thread 0009), starting debugger...`

[last_build_config.log](https://github.com/Tk-Glitch/PKGBUILDS/files/3844535/last_build_config.log)

**Comment by Tk-Glitch** [comment]
Steamclient lib failing. This is known and will happen on 4.19r2 and up currently (you could actually run a newer build but you would hit another bug requiring the hotfix that's now gone). Guy1524 has promised to fix it so I would expect an update soon-ish.

**Comment by Tk-Glitch** [comment]
I have reopened https://github.com/Tk-Glitch/PKGBUILDS/issues/384 while we wait

**Comment by Tk-Glitch** [comment]
Please confirm it's been fixed with the commit above, just to be sure :)

**Comment by Tk-Glitch** [comment]
False alarm. Many cases are fixed, but not all of them.

**Comment by telans** [comment]
This can probably be closed. Turns out the issue was due to unset `CROSSCFLAGS` & `CROSSLDFLAGS`. As to why that was causing an issue with 32bit wine, not sure.
