### ISSUE TITLE
Applying linux-hardened patch set with non-CFS schedulers (linux53-tkg)

### ISSUE THREAD

**Issue by Ryujinra** [Tk-Glitch/PKGBUILDS#395]
Hi, thanks for your work. I had some questions about the linux-hardened patch set for linux53-tkg kernel. Is there any method of applying the hardened patch set while a non-CFS scheduler is being used?

What exactly blocks this patch when another scheduler is selected (e.g. PDS)?

If it is not able to be done programatically, could you perhaps point me to what would need to be done to the patch to enable it to be applied successfully?

Thanks for any help.

**Comment by Tk-Glitch** [comment]
The linux-hardened patchset is built against CFS CPU scheduler and that's the main blocker. The patch won't apply on a source that's using a different CPU scheduler. Removing the parts targeting CFS shouldn't be too hard but you'll then end up with a less secure patchset, obviously.

If you're not too concerned about the CPU scheduler hardening bits, you can enforce the patch application by putting your modified linux-hardened patchset next to the PKGBUILD with a .mypatch extension. You'll still need to set `_configfile="config_hardened.x86_64"` in your .cfg before building.

**Comment by Ryujinra** [comment]
I gave it a shot and it turns out there wasn't many blockers (at least for PDS scheduler). Just commented out two hunks in sysctl.c (scheduler-related granularity settings were set to read-only by the hardened patch), and two hunks in ps.c (realtek wifi driver related, oddly enough), and it's good to go.

I'm not sure if there are other potential conflicts with the other schedulers, but this seems to work well for now.

Thanks for the tips and for generating the hardened patch to begin with. I'll close this now since it's solved.

**Comment by Ryujinra** [comment]
Hmm, may have spoked too soon. I can patch successfully but right at the end of the build I get the following errors:

```
...
LD      vmlinux.o
MODPOST vmlinux.o
WARNING: modpost: Found 5845 writable function pointers.
To see full details build your kernel with:
make CONFIG_DEBUG_WRITABLE_FUNCTION_POINTERS_VERBOSE=y'
  MODINFO modules.builtin.modinfo
ld: fs/open.o: in function `vfs_fallocate':
open.c:(.text+0x7cd): undefined reference to `device_sidechannel_restrict'
ld: fs/read_write.o: in function `do_clone_file_range':
read_write.c:(.text+0xaaf): undefined reference to `device_sidechannel_restrict'
ld: read_write.c:(.text+0xb80): undefined reference to `device_sidechannel_restrict'
ld: fs/read_write.o: in function `do_iter_write.part.0':
read_write.c:(.text+0x173b): undefined reference to `device_sidechannel_restrict'
ld: fs/read_write.o: in function `__kernel_write':
read_write.c:(.text+0x18e5): undefined reference to `device_sidechannel_restrict'
ld: fs/read_write.o:read_write.c:(.text+0x214c): more undefined references to `device_sidechannel_restrict' follow
make: *** [Makefile:1073: vmlinux] Error 1
==> ERROR: A failure occurred in build().
```

Any idea what could be causing this issue?

**Comment by Tk-Glitch** [comment]
Looks like an upstream breakage. I'll have a look asap.

**Comment by Tk-Glitch** [comment]
Should be resolved as of https://github.com/Tk-Glitch/PKGBUILDS/commit/29e1f0028080335ae1ba4aa553a5d576402299f4

**Comment by Ryujinra** [comment]
Well the `ps.c` conflict was fixed, but unfortunately there is a merge conflict in `slub.c` hunk #6 now. Commenting out the hunk in `0012-linux-hardened.patch` fixes the issue again.

**Comment by Tk-Glitch** [comment]
Timing wasn't the best :frog:
Should be all good now.

**Comment by Ryujinra** [comment]
Yep, builds fine again. Thanks again.
