### ISSUE TITLE
wine regression without CROSSCFLAGS & CROSSLDFLAGS

### ISSUE THREAD

**Issue by telans** [Tk-Glitch/PKGBUILDS#399]
With recent wine versions (~4.19), compiling with `_LOCAL_OPTIMIZED="false"` and without `CROSSCFLAGS` & `CROSSLDFLAGS` set in makepkg.conf, wine would fail to create a new prefix and run certain 32-bit applications. There would be an error similar to:
```
0009:err:seh:raise_exception Unhandled exception code c0000005 flags 0 addr (nil)
```

@xDShot and derandark (discord) have also come across this issue.

I have done a bisect on wine-staging, and it appears the following commit is the first bad one: https://github.com/wine-staging/wine-staging/commit/ef0e88407ea60c9feed923431aee4bcc8ae71f95

I built normal wine against the rebase the commit above was based on. This also had the issue, so whatever caused it is somewhere in here: https://github.com/wine-mirror/wine/compare/070cfc358c8ed67ba08a49ae78c20205ab4e2d00...34ed1e37da1e1c1cfd641f1f16b0e00030cbb357, but I haven't bisected this yet

Whether this is classed as an actual issue or not (maybe the flags should have been set all along?), I think it might be important to add a note about the two make options having to match `CFLAGS` (from what I can tell this is correct, it works for me & others).

**Comment by Tk-Glitch** [comment]
Let's add a litte reference to the related report https://github.com/Tk-Glitch/PKGBUILDS/issues/397 :frog:
