### ISSUE TITLE
.Net Framework 4.0+ won't install correctly

### ISSUE THREAD

**Issue by Eracktor** [Tk-Glitch/PKGBUILDS#4]
I'm trying to install  .Net Framework on a prefix using the esync PKGbuild. For some reason, the .Net Framework fails to install. There's a method that reportedly works to get 4.0+ dotnet prefixes installed: 

export WINEPREFIX= ???
winetricks remove_mono winxp
cd ~/Downloads
wget 'http://download.microsoft.com/download/9/5/A/95A9616B-7A37-4AF6-BC36-D6EA96C8DAAE/dotNetFx40_Full_x86_x64.exe'
wine dotNetFx40_Full_x86_x64.exe /q && wineserver -k
winetricks win7 mscoree=native
wget 'http://download.microsoft.com/download/9/E/6/9E63300C-0941-4B45-A0EC-0008F96DD480/NDP471-KB4033342-x86-x64-AllOS-ENU.exe'
wine NDP471-KB4033342-x86-x64-AllOS-ENU.exe /q && wineserver -k

This method is reported to work. I have wine prefixes from other wine builds that install dotnet 4.0+ using this method.

https://blogs.msdn.microsoft.com/astebner/2008/10/13/net-framework-setup-verification-tool-users-guide/

This tool can verify if dotnet is installed correctly. On a working prefix, dotnet 4.0+ is verified as installed without any issues.

If I use a graphical install, via winetricks, dotnet 4.0 simply throws out a installation failure during install process.

**Comment by Tk-Glitch** [comment]
Well, I have written this method. I did integrate it to my winetricks-git pkgbuild here also : https://github.com/Tk-Glitch/PKGBUILDS/tree/master/winetricks-git
You can use it with "winetricks dotnet471".

Wine-esync is very experimental and won't succeed at installing dotnet 4.0 and up atm. I've been using staging 3.11 myself to do it and that will work (95% of the time or so).

**Comment by Eracktor** [comment]
Ok. Thanks. I didn't notice the Winetricks-git folder since I already had a git ver. from Arch. 
Nice PKGBUILDS

**Comment by Tk-Glitch** [comment]
Thanks :) I'm still interested to know if that will fix your issue. It definitely should though.
