### ISSUE TITLE
non-makepkg-build.sh does nothing

### ISSUE THREAD

**Issue by Alkaris** [Tk-Glitch/PKGBUILDS#400]
The script included for wine-tkg-git doesn't work, it doesn't do anything, its not creating the non-makepkg-build directory like it should be, it just executes nothing in the script. It gives me the whole introduction spiel, Press enter to continue, blah blah stuff, does nothing at all.

done for Ubuntu 18.04. Why would you include a script that doesn't execute anything?

**Comment by Tk-Glitch** [comment]
You're definitely doing it wrong. If you have only downloaded the script that can't work.

**Comment by Alkaris** [comment]
Something can only be wrong when downloaded the entire archive and extracted it went into the fucking folder, ran the script only for it to do fuck all. Perhaps you're just bad at coding scripts.

**Comment by Tk-Glitch** [comment]
And you're great at being an absolute dick. No log provided and giving as little detail as possible. You never wanted to help fixing the issue nor finding out what the problem was. Ciao.

**Comment by Joshua-Ashton** [comment]
> Something can only be wrong when downloaded the entire archive and extracted it went into the fucking folder, ran the script only for it to do fuck all.

What a martyr, do you want a medal? 🙃

> Perhaps you're just bad at coding scripts.

Why not maintain your own set of build scripts and patches for a large number of high-profile projects  this exensible? Might be slightly more useful all your empty forks. 🍴

**Comment by Tk-Glitch** [comment]
Diagnosed thanks to **nobody** and fixed by https://github.com/Tk-Glitch/PKGBUILDS/commit/f66f4370f60ed680009afec2712af44fffa6b845
