### ISSUE TITLE
kernel config prompts when using modprobeddb

### ISSUE THREAD

**Issue by aufkrawall** [Tk-Glitch/PKGBUILDS#404]
I'm always getting these prompts, would be nice if they were covered by the default config:

BT8XX GPIO abuser (GPIO_BT8XX) [N/m/y/?] (NEW)
Studio Evolution SE6X (SND_SE6X) [N/m/?] (NEW)

Thanks!

**Comment by Tk-Glitch** [comment]
This only happens with modprobed-db and adding both entries to config doesn't change anything (I have tried that in the past, multiple times, in multiple ways). No idea why it happens tbh, but modprobed-db has given hell to many others already, sooooo. Frog, I guess.

Related, and stalled: https://bbs.archlinux.org/viewtopic.php?id=249769

**Comment by aufkrawall** [comment]
#404, solution not found. :frog: 
Well, at least apart from that, modprobeddb isn't giving me any headaches with my current hardware.

**Comment by Tk-Glitch** [comment]
This being #404 really is amusing. Long live #404!

**Comment by aufkrawall** [comment]
Fixed, thanks @CodingKoopa .
