### ISSUE TITLE
Problems with some games

### ISSUE THREAD

**Issue by weter11** [Tk-Glitch/PKGBUILDS#405]
Hi! There are some problems on my system and I'm not understand some of them.
Ubuntu 19.10, Lutris launcher. glibc 2.30, proton-tk installed.
If I am correct understand I install builds by simply unpacking proton_tkg...release.zip to ~/.local/share/lutris/runners/wine/ and other stuff is on the side of Lutris (winetricks with installed mf dlls).
The problem is that different versions of tkg behave differently. 
For example tkg_proton_4.6 work with DS4(with rumble), load saves and game preferences in DMC5, but can't work in fullscreen in Nier:Automata. In Driver:San Francisco this version can't load game preferences and saves and crash on any gamepad button press.
Tkg_protonified_4.6 inside Lutris launcher work with DS4(with rumble), load saves and game preferences and work in fullscreen in Nier:Automata and Driver:San Francisco.
But in Resident evil 2 remake tkg_proton_4.6 and  tkg_proton_4.20 don't work with DS4 at all and crash immediately after level loading, but in menu all is ok (except DS4). Versions 4.10-4.16 crash even w/o any menu loading). Tkg_protonified_4.6 inside Lutris launcher work with DS4, but crash immediately after level loading or after intro video with trucker, if you start a new game.
For what reason it crash in this situations? I don't see anything about problem in logs. Tried different options in Lutris, but w/o lucky.

**Comment by Tk-Glitch** [comment]
You should never use a proton build outside of Steam. It's not meant to be used that way and won't work correctly. The "protonified" builds are not proton builds, they are custom wine builds with the key features of proton but without the Steam specific stuff, making them suitable for use outside of Steam.

I have stopped providing builds to lutris myself a while ago but to this day the "lutris" wine builds are still made with wine-tkg. If you're not compiling your own builds with your own feature sets, you should use those builds lutris offers to get updated wine. Or you can use proton-tkg with the Linux Steam client (but in that case you don't want to use lutris).

Wine regressions are pretty common and bound to happen, so you can't 100% expect your experience to be flawless between major updates. Things can break, get fixed, and break again on next update.

All of that being said, your RE2 issue sounds familiar. I'm pretty sure it was linked to a specific option in the graphics settings. Possibly shadow caching. It might also happen if you run out of VRAM. You can probably give it a try with all settings on low and see if the issue persists.

**Comment by weter11** [comment]
Ok, I'm understand, so only with Steam launcher it would work as it should.
And I download latest tkg wine(not proton version) as you said and... RE2 can't load saves and game preferences, but work with DS4 and now I can go to first level. For example system proton from Steam 4.11.9 load saves and I can play first level, but DS4 don't work at all and I really can't play such games w/o rumble feature and gamepad, this is not online shooter, where you need a good mouse and 144 Hz monitor.
May you say is it possible to solve the problem with loading settings and saves?

**Comment by weter11** [comment]
For testing purposes I tried replacing xinput dlls from pure wine to proton build. And this trick didn't work. Also after replacing dlls from proton to wine library gamepad input became broken. After replacing dlls to original all is ok. Or in a such manner this trick not working?

**Comment by Tk-Glitch** [comment]
RE2 has some pretty weird save integrity checks in place. If you make a new save (backup if needed before doing anything of the sort) with that version, can you then load it? Proton will save as "steamuser" user, while wine will save as your linux user. It might be just that.
Regarding dll swapping, you could try with dinput instead of xinput. I don't think the DS4 is a xinput device.

**Comment by weter11** [comment]
Ok. I tried to delete save, but newer one is not loaded.
But when I replace as you wrote 64bit dinput.dll.so & dinput8.dll.so from  wine-tkg-staging to proton_tkg my DS4 magically became working. Really big thanks.
Maybe its better to replace dinput dlls from wine-tkg-staging to proton_tkg or another people have problems with wine dinput in proton builds?

**Comment by Tk-Glitch** [comment]
It seems the DS4 is correctly handled on current wine versions and the proton specific patches are doing more harm than good. I have now disabled them by default so the behavior will be similar to wine-tkg-git. Thanks!
