### ISSUE TITLE
I want to play Dark Souls, please fix this

### ISSUE THREAD

**Issue by Danilopereira82** [Tk-Glitch/PKGBUILDS#408]
frikin after weeks i installed wine and the game again
but still not working AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
let me play pleeeeeease

[danilo@danilo DarkSouls]$ wine DARKSOULS.exe 
000b:fixme:winediag:start_process Wine TkG 4.21 is a testing version containing experimental patches.
000b:fixme:winediag:start_process Please don't report bugs about it on winehq.org and use https://github.com/Tk-Glitch/PKGBUILDS/issues instead.
0019:err:winediag:schan_imp_init Failed to load libgnutls, secure connections will not be available.
0019:err:winediag:load_gssapi_krb5 Failed to load libgssapi_krb5, Kerberos SSP support will not be available.
0019:fixme:ntdll:EtwRegisterTraceGuidsW (0x100778a, 0x100a060, {485e7de8-0a80-11d8-ad15-505054503030}, 1, 0x32fe90, (null), (null), 0x100a068): stub
0019:fixme:ntdll:EtwRegisterTraceGuidsW   register trace class {485e7de8-0a80-11d8-ad15-505054503030}
0019:fixme:ntdll:EtwRegisterTraceGuidsW (0x100778a, 0x100a080, {485e7de9-0a80-11d8-ad15-505054503030}, 1, 0x32fe90, (null), (null), 0x100a088): stub
0019:fixme:ntdll:EtwRegisterTraceGuidsW   register trace class {485e7de9-0a80-11d8-ad15-505054503030}
0019:fixme:ntdll:EtwRegisterTraceGuidsW (0x100778a, 0x100a0a0, {485e7dea-0a80-11d8-ad15-505054503030}, 1, 0x32fe90, (null), (null), 0x100a0a8): stub
0019:fixme:ntdll:EtwRegisterTraceGuidsW   register trace class {485e7dea-0a80-11d8-ad15-505054503030}
0019:fixme:ntdll:EtwRegisterTraceGuidsW (0x100778a, 0x100a0c0, {485e7deb-0a80-11d8-ad15-505054503030}, 1, 0x32fe90, (null), (null), 0x100a0c8): stub
0019:fixme:ntdll:EtwRegisterTraceGuidsW   register trace class {485e7deb-0a80-11d8-ad15-505054503030}
0019:fixme:ntdll:EtwRegisterTraceGuidsW (0x100778a, 0x100a0e0, {485e7dec-0a80-11d8-ad15-505054503030}, 1, 0x32fe90, (null), (null), 0x100a0e8): stub
0019:fixme:ntdll:EtwRegisterTraceGuidsW   register trace class {485e7dec-0a80-11d8-ad15-505054503030}
0019:fixme:ntdll:EtwRegisterTraceGuidsW (0x100778a, 0x100a100, {485e7ded-0a80-11d8-ad15-505054503030}, 1, 0x32fe90, (null), (null), 0x100a108): stub
0019:fixme:ntdll:EtwRegisterTraceGuidsW   register trace class {485e7ded-0a80-11d8-ad15-505054503030}
001e:fixme:win:RegisterDeviceNotificationW (hwnd=0x147998, filter=0x64fe1c,flags=0x00000001) returns a fake device notification handle!
002a:err:winediag:gnutls_initialize failed to load libgnutls, no support for encryption
002a:err:winediag:gnutls_initialize failed to load libgnutls, no support for pfx import/export
002a:fixme:ntdll:EtwRegisterTraceGuidsW (0x6cd15f38, 0x6cd20180, {e2821408-c59d-418f-ad3f-aa4e792aeb79}, 1, 0x32e700, (null), (null), 0x6cd20188): stub
002a:fixme:ntdll:EtwRegisterTraceGuidsW   register trace class {e2821408-c59d-418f-ad3f-aa4e792aeb79}
002a:err:winediag:schan_imp_init Failed to load libgnutls, secure connections will not be available.
002a:err:winediag:load_gssapi_krb5 Failed to load libgssapi_krb5, Kerberos SSP support will not be available.
002a:fixme:heap:RtlSetHeapInformation 0x110000 1 (nil) 0 stub
0030:fixme:ole:CoInitializeSecurity (001A3310,-1,00000000,00000000,4,2,00000000,0,00000000) - stub!
0030:fixme:ole:CoResumeClassObjects stub
003b:fixme:crypt:Collection_release Unimplemented flags 1
003b:fixme:crypt:ProvStore_release Unimplemented flags 1
003b:fixme:crypt:CRYPT_RegCloseStore Unimplemented flags: 00000001
003b:fixme:crypt:MemStore_release Unimplemented flags 1
0009:fixme:heap:RtlSetHeapInformation (nil) 1 (nil) 0 stub
0009:fixme:exec:SHELL_execute flags ignored: 0x00000100
[danilo@danilo DarkSouls]$ 0040:err:winediag:gnutls_initialize failed to load libgnutls, no support for encryption
0040:err:winediag:gnutls_initialize failed to load libgnutls, no support for pfx import/export
0040:fixme:heap:RtlSetHeapInformation (nil) 1 (nil) 0 stub
003b:fixme:advapi:ParseStringSidToSid String constant not supported: L".D"
003b:fixme:iphlpapi:NotifyAddrChange (Handle 0xe9fba8, overlapped 0x1162f88): stub
003b:fixme:wtsapi:WTSEnumerateSessionsW Stub 00000000 0x00000000 0x00000001 00E9FBB0 00E9FBA8
0044:fixme:heap:RtlSetHeapInformation 0x110000 1 (nil) 0 stub
0044:fixme:ole:NdrCorrelationInitialize (0019ADC0, 0019A9C0, 1024, 0x0): semi-stub
003b:fixme:ole:NdrCorrelationInitialize (00E9F834, 00E9F910, 1024, 0x0): semi-stub
003b:fixme:ole:NdrCorrelationFree (00E9F834): stub
0044:fixme:ole:NdrCorrelationFree (0019ADC0): stub

**Comment by Tk-Glitch** [comment]
```
0019:err:winediag:schan_imp_init Failed to load libgnutls, secure connections will not be available.
0019:err:winediag:load_gssapi_krb5 Failed to load libgssapi_krb5, Kerberos SSP support will not be available.
```
You don't have `gnutls`/`lib32-gnutls` package installed. That's the main issue here. That game is 32-bit afaik but make sure to install both.
Then you don't have `krb5`/`lib32-krb5` (same story about 32-bit), which is probably not absolutely required here, but that won't hurt.

**Comment by Danilopereira82** [comment]
done, but now this

[danilo@danilo DarkSouls]$ wine DARKSOULS.exe 
000b:fixme:winediag:start_process Wine TkG 4.21 is a testing version containing experimental patches.
000b:fixme:winediag:start_process Please don't report bugs about it on winehq.org and use https://github.com/Tk-Glitch/PKGBUILDS/issues instead.
001b:fixme:ntdll:EtwRegisterTraceGuidsW (0x100778a, 0x100a060, {485e7de8-0a80-11d8-ad15-505054503030}, 1, 0x32fe90, (null), (null), 0x100a068): stub
001b:fixme:ntdll:EtwRegisterTraceGuidsW   register trace class {485e7de8-0a80-11d8-ad15-505054503030}
001b:fixme:ntdll:EtwRegisterTraceGuidsW (0x100778a, 0x100a080, {485e7de9-0a80-11d8-ad15-505054503030}, 1, 0x32fe90, (null), (null), 0x100a088): stub
001b:fixme:ntdll:EtwRegisterTraceGuidsW   register trace class {485e7de9-0a80-11d8-ad15-505054503030}
001b:fixme:ntdll:EtwRegisterTraceGuidsW (0x100778a, 0x100a0a0, {485e7dea-0a80-11d8-ad15-505054503030}, 1, 0x32fe90, (null), (null), 0x100a0a8): stub
001b:fixme:ntdll:EtwRegisterTraceGuidsW   register trace class {485e7dea-0a80-11d8-ad15-505054503030}
001b:fixme:ntdll:EtwRegisterTraceGuidsW (0x100778a, 0x100a0c0, {485e7deb-0a80-11d8-ad15-505054503030}, 1, 0x32fe90, (null), (null), 0x100a0c8): stub
001b:fixme:ntdll:EtwRegisterTraceGuidsW   register trace class {485e7deb-0a80-11d8-ad15-505054503030}
001b:fixme:ntdll:EtwRegisterTraceGuidsW (0x100778a, 0x100a0e0, {485e7dec-0a80-11d8-ad15-505054503030}, 1, 0x32fe90, (null), (null), 0x100a0e8): stub
001b:fixme:ntdll:EtwRegisterTraceGuidsW   register trace class {485e7dec-0a80-11d8-ad15-505054503030}
001b:fixme:ntdll:EtwRegisterTraceGuidsW (0x100778a, 0x100a100, {485e7ded-0a80-11d8-ad15-505054503030}, 1, 0x32fe90, (null), (null), 0x100a108): stub
001b:fixme:ntdll:EtwRegisterTraceGuidsW   register trace class {485e7ded-0a80-11d8-ad15-505054503030}
001e:fixme:win:RegisterDeviceNotificationW (hwnd=0x147e48, filter=0x64fe1c,flags=0x00000001) returns a fake device notification handle!
002a:fixme:ntdll:EtwRegisterTraceGuidsW (0x6cd15f38, 0x6cd20180, {e2821408-c59d-418f-ad3f-aa4e792aeb79}, 1, 0x32e700, (null), (null), 0x6cd20188): stub
002a:fixme:ntdll:EtwRegisterTraceGuidsW   register trace class {e2821408-c59d-418f-ad3f-aa4e792aeb79}
002a:fixme:heap:RtlSetHeapInformation 0x110000 1 (nil) 0 stub
0030:fixme:ole:CoInitializeSecurity (001A37C0,-1,00000000,00000000,4,2,00000000,0,00000000) - stub!
0030:fixme:ole:CoResumeClassObjects stub
0037:fixme:crypt:Collection_release Unimplemented flags 1
0037:fixme:crypt:ProvStore_release Unimplemented flags 1
0037:fixme:crypt:CRYPT_RegCloseStore Unimplemented flags: 00000001
0037:fixme:crypt:MemStore_release Unimplemented flags 1
0009:fixme:heap:RtlSetHeapInformation (nil) 1 (nil) 0 stub
0009:fixme:exec:SHELL_execute flags ignored: 0x00000100
[danilo@danilo DarkSouls]$ 003f:fixme:heap:RtlSetHeapInformation (nil) 1 (nil) 0 stub
0037:fixme:advapi:ParseStringSidToSid String constant not supported: L".D"
0037:fixme:iphlpapi:NotifyAddrChange (Handle 0xe9fba8, overlapped 0x1162f88): stub
0037:fixme:wtsapi:WTSEnumerateSessionsW Stub 00000000 0x00000000 0x00000001 00E9FBB0 00E9FBA8
0043:fixme:heap:RtlSetHeapInformation 0x110000 1 (nil) 0 stub
0043:fixme:ole:NdrCorrelationInitialize (0019ADC0, 0019A9C0, 1024, 0x0): semi-stub
0037:fixme:ole:NdrCorrelationInitialize (00E9F834, 00E9F910, 1024, 0x0): semi-stub
0037:fixme:ole:NdrCorrelationFree (00E9F834): stub
0043:fixme:ole:NdrCorrelationFree (0019ADC0): stub

**Comment by Tk-Glitch** [comment]
I notice you're running the game directly. That can't work. You want to run it from windows Steam installed in a wine prefix or through proton with Linux Steam.

**Comment by Danilopereira82** [comment]
🏴‍☠️ from where the setup from the iso installed the files

this was working very well before
why this doesn't work now?

**Comment by Tk-Glitch** [comment]
Meaning you're using modified game files that are the likely cause of your issue, and for which I can't provide support for. Your logs aren't explicitly revealing a blocking issue to me anyway so it would require more verbosity. If it worked on an earlier version of wine, then you should use that I suppose?

Be aware that the game works fine on my end as well as for everyone else I know who still plays it (with a legit copy, that is), be it with wined3d or D9VK as well as esync/fsync and LAA enabled.
