### ISSUE TITLE
linux53-tkg kernel package missing pkgbase

### ISSUE THREAD

**Issue by bsngardner** [Tk-Glitch/PKGBUILDS#409]
Other Arch kernel packages include the file
`/usr/lib/modules/<version>/pkgbase`
This is missing in linux53-tkg; I haven't tried building the others. I don't know a lot about kernel pkgbuilds, but do you know why this is missing? It only came up because I use sbupdate to sign my kernel images, and it reads that file to get the naming scheme of a given kernel.

**Comment by Tk-Glitch** [comment]
That pkgbase file only contains `linux` as a string. Nothing more. I didn't know that some tool was relying on that, it sounds weird. I'll add that.

**Comment by bsngardner** [comment]
Well the linux-lts package has 'linux-lts' in that file, so I would expect it to contain 'linux-tkg' or 'linux-tkg-pds' or something for your packages.

**Comment by Tk-Glitch** [comment]
Yup that's what I did.
