### ISSUE TITLE
Linux54-tkg failes to patch

### ISSUE THREAD

**Issue by ronoverdrive** [Tk-Glitch/PKGBUILDS#410]
`patching file drivers/crypto/inside-secure/safexcel.c
Hunk #6 FAILED at 233.
1 out of 37 hunks FAILED -- saving rejects to file drivers/crypto/inside-secure/safexcel.c.rej`

This is where it fails at every time. Here is my customization.cfg. I was sure to try it with and without any community patches to rule them out, even without I still fail to patch. 

[customization.txt](https://github.com/Tk-Glitch/PKGBUILDS/files/3930376/customization.txt)

**Comment by Tk-Glitch** [comment]
This comes from the wireguard community patch. There simply isn't any other patch touching that file. I think I know why removing it from the community patches array didn't work though. The link gets recreated outside of the loop. More pacman workarounds incoming.

**Comment by Tk-Glitch** [comment]
I have fixed the patch itself as of https://github.com/Tk-Glitch/PKGBUILDS/commit/4223a2d5460693af088e7d95497198e069c6f65f and the other changes mentioned above should fix community patches handling.

**Comment by ronoverdrive** [comment]
Builds just fine now.
