### ISSUE TITLE
Proton fullscreen hack upscaling causes screen borders not to be properly recognized after minimizing

### ISSUE THREAD

**Issue by aufkrawall** [Tk-Glitch/PKGBUILDS#413]
Hello,
when I use an upscaling resolution like 720p for my 1440p screen, minimize Heroes of the Storm and open the fullscreen window again, moving the hardware cursor to a screen border to scroll the game's map is not correctly recognized anymore.
E.g. I move the cursor to the top border, then move it along the top border to the right border and then along the right border to the bottom border: The bottom border scroll event is not triggered and the game instead continues scrolling to the right.

**Comment by Tk-Glitch** [comment]
Is it still an issue on current master (staging)?
Specifically since https://github.com/wine-staging/wine-staging/commit/d44f4885f2866d9f2e10b04d687819e7b37beb93

**Comment by aufkrawall** [comment]
Unfortunately not fixed.

**Comment by aufkrawall** [comment]
It seems chances are it might only occur after at least one application restart + minimizing/maximizing and disappears again after switching resolutions without minimizing after.
So it's not unusable, just really ugly. :)

**Comment by Tk-Glitch** [comment]
With Proton 5.0 out now, updating our FS hack patchset will *hopefully* fix this. Next week's evenings sure will be busy 🐸

**Comment by aufkrawall** [comment]
It seems I can't test this anymore, as with Nvidia (no more AMD card), there aren't any upscaling resolutions available for my display setup.

But should it actually be like this with the fullscreen hack? Shouldn't it offer upscaling resolutions, independent from the driver?

**Comment by Tk-Glitch** [comment]
It should.. It did on my 980ti. Is it true on all games or is it limited to Heroes of the Storm?

**Comment by aufkrawall** [comment]
Seems to be general, in vkquake wine only my native resolution is offered too.

**Comment by aufkrawall** [comment]
One more note: I have a display with special needs, it doesn't have a scaler integrated and thus doesn't offer any display upscaling resolutions. The Nvidia driver also doesn't offer any upsaling resolutions via xrandr, only in a sucky way via nvidia-settings.

But still there is the point of expecting the fullscreen hack being able to "emulate" the resolutions, despite of the circumstances.

**Comment by aufkrawall** [comment]
Hm, regular Proton in Steam offers me upscaling resolutions.

**Comment by Tk-Glitch** [comment]
I have tried with 6 different displays at this point:
1440x900 16:10 75Hz
1600x900 16:9 60Hz
1680x1050 16:10 60Hz
1920x1080 16:9 120Hz
2560x1440 16:9 144Hz
3840x2160 16:9 60Hz

And I got all the expected upscaling res available with all of them, on both Nvidia (980ti), AMD(5700XT) and Intel(UHD630) on a panel of 10 games from early 2000s to 2019. I'm clueless and I can't reproduce the issue so far.

**Comment by aufkrawall** [comment]
Wow, thanks for your efforts.
Well, then I'll have to live with that.

**Comment by Tk-Glitch** [comment]
Oh it wasn't that bad thanks to a KVM switch 🐸 The problem is still very frustrating. Do you have your .cfg at hand maybe?

**Comment by aufkrawall** [comment]
[customization.cfg.log](https://github.com/Tk-Glitch/PKGBUILDS/files/4224892/customization.cfg.log)

**Comment by Tk-Glitch** [comment]
Thank you. Was the regular proton test done with proton 5.0-x or was it a different revision?

**Comment by aufkrawall** [comment]
Yes, Proton 5. Reconfirmed this today with 5.0-3.

There is a change with recent patches for wine-tkg: Now some upscaling resolutions are offered, but common ones like 1920x1080 are still missing.

**Comment by Tk-Glitch** [comment]
As of which commit? Because I haven't touched anything related in the patchset since https://github.com/Tk-Glitch/PKGBUILDS/commit/0b8137e171194f9d10396e6eccb35f9c52620dd1 which was 12 days ago.

**Comment by aufkrawall** [comment]
I'm not really building wine on a regular basis anymore, I really can't tell. I'm not really interested anymore in gaming on Linux, so I don't know if I'll get to it. Anyhow, thanks for your support!

**Comment by Tk-Glitch** [comment]
I'd like to be able to fix it if it's broken, but without any way to reproduce it so far I'm at a loss. If it's not something that matters to you anymore that's okay, I suppose someone else will add to this issue if need be. And you're welcome, as always.

**Comment by aufkrawall** [comment]
The good news: It seems I'm not able anymore to reproduce the screen edge ignored issue with a fresh staging 5.11 build of today + fullscreen hack.

The slightly less good news: It still doesn't offer me 1920x1080 as upscaling resolution, just some non 16:9 resolutions and 720p.

**Comment by aufkrawall** [comment]
Hm, it really seems to work fine with Steam Proton. Every game in Steam offers lots of upscaling resolutions (including 1080p) and can switch to them. For whatever reason this is not the case with wine-tkg and Proton fullscreen hack.

**Comment by Tk-Glitch** [comment]
The weirdest part being that I have the exact same available resolutions on vanilla and tkg on 4 different displays, independently of the GPU driver in use. I honestly have no idea why/how it can end up being different for you.

> It seems I'm not able anymore to reproduce the screen edge ignored issue with a fresh staging 5.11 build of today

Good news indeed. That'll cheer me up a bit.

**Comment by aufkrawall** [comment]
Hm, wasn't it possible to add multiple fake refresh rates for the Proton fullscreen hack, e.g. "60 85"? It successfully applies the patches with these values specified, but building  fails later.

Vanilla Proton always offers me 60Hz, despite of just having 85Hz as the sole available real refresh rate. But I guess it won't aid the missing upscaling resolutions issue, as they are also missing without my custom EDID and just 60Hz. :)

**Comment by aufkrawall** [comment]
With a display connected that has its own scaler and not some weirdo edid, as expected, 1080p upscaling resolution is available. I guess there is no need for me bothering you with this any further. Grateful for your efforts though!
