### ISSUE TITLE
linux54-tkg missing dependancies

### ISSUE THREAD

**Issue by robzombie91** [Tk-Glitch/PKGBUILDS#418]
https://paste.ubuntu.com/p/CvKrKgs6cR/

**Comment by XHDR** [comment]
Looking at the log, I see that pacman complains about conflicting files, then stops the "upgrade."

```
...
(24/24) checking for file conflicts
error: failed to commit transaction (conflicting files)
python-snowballstemmer: /usr/lib/python3.8/site-packages/snowballstemmer/__init__.py exists in filesystem
python-snowballstemmer: /usr/lib/python3.8/site-packages/snowballstemmer/__pycache__/__init__.cpython-38.pyc exists in filesystem
python-snowballstemmer: /usr/lib/python3.8/site-packages/snowballstemmer/__pycache__/among.cpython-38.pyc exists in filesystem
...
```

You've got, for some reason, unowned files from the `python-snowballstemmer` package. Manually remove/move the files before continuing.

`$ sudo mv -t /opt /usr/lib/python3.8/site-packages/snowballstemmer`

Run that, then retry the operation.
