### ISSUE TITLE
[wine-tkg-git] What is "Gandalf" in the PKGBUILD? Why we need it? Seems like the compilation  SHALL_NOT_PASS?

### ISSUE THREAD

**Issue by Kerrung** [Tk-Glitch/PKGBUILDS#419]
[last_build_config.log](https://github.com/Tk-Glitch/PKGBUILDS/files/3955173/last_build_config.log)
![Screenshot from 2019-12-12 15-12-28](https://user-images.githubusercontent.com/36989404/70703679-61ff3500-1cf2-11ea-9a89-31c3e0ec34f7.png)

**Comment by HengiFettlich** [comment]
make sure you didn't set NOCOMPILE to true.
https://github.com/Tk-Glitch/PKGBUILDS/blob/1577f79172618478428e978ae5159d80f0263ed2/wine-tkg-git/customization.cfg#L61

**Comment by Kerrung** [comment]
> make sure you didn't set NOCOMPILE to true.
> https://github.com/Tk-Glitch/PKGBUILDS/blob/1577f79172618478428e978ae5159d80f0263ed2/wine-tkg-git/customization.cfg#L61

I applied a log file here...

**Comment by Kerrung** [comment]
> make sure you didn't set NOCOMPILE to true.
> https://github.com/Tk-Glitch/PKGBUILDS/blob/1577f79172618478428e978ae5159d80f0263ed2/wine-tkg-git/customization.cfg#L61

You turned out to be right. It helps me!
