### ISSUE TITLE
Some games is freezed, after press any key on keyboard

### ISSUE THREAD

**Issue by sr-tream** [Tk-Glitch/PKGBUILDS#42]
Some games is freezed after press any key on keyboard. When I pressed keys on mouse, game not freezed.
If I kill freezed game, I lose mouse point - cursor not showed, and programs do not respond to mouse movement and mouse clicks. 

#### Software information
Witcher 3 and Fallout 4

- Driver: mesa 19, llvm 7

https://dl.prime-hack.net/wine-tkg.cfg.zip

**Comment by Tk-Glitch** [comment]
Doesn't look like my bug. Your issues are possibly linked to this commit from staging : https://github.com/wine-staging/wine-staging/commit/e4a3b5fc9d5ed7c102b1618270e26a1fcac2d53e

You can try to use a previous staging version, for example `ac5710e`, and see how it goes.

**Comment by sr-tream** [comment]
Thx

**Comment by Tk-Glitch** [comment]
I can confirm I was able to reproduce your issue on master, and using `ac5710e` fixed it. Might have something to do with esync, I will investigate.
