### ISSUE TITLE
World of Warcraft 8.2.5 - D3D12

### ISSUE THREAD

**Issue by SveSop** [Tk-Glitch/PKGBUILDS#421]
Since a lot of ppl uses this PKGBUILD repo to build custom wine versions with various fixes, I thought i'd share the World of Warcraft patches that you need to run WoW with D3D12. You decide if you wanna toss them in the game-specific and custom folders.

All these patches have been posted on the wine-dev mailing list, but are not for various reasons included upstream. Basically from what i gathered from the answers there is that the Wine patches i post here would require vkd3d to increase API version, and so far vkd3d sits at vkd3d_1.1, and the devs say it requires more work to bump this to vkd3d_1.2, so they will not implement this Wine patch, since that would basically require unreleased libvkd3d_1.2... 

The first one is for vkd3d to get WoW to work in the Nazjatar zone without crashing (Works with atleast vkd3d GIT a59f1982adeca99b64d28fd89fa7118a246558c0: 
[Support_RS_1.0_Volatile.patch.gz](https://github.com/Tk-Glitch/PKGBUILDS/files/3964078/Support_RS_1.0_Volatile.patch.gz)

This is 2 patches for Wine-staging (REQUIRES libvkd3d-GIT - see note below). Tested with wine-staging-4.20->5.0-rc1: 
[D3D12CreateVersionedRootSignatureDeserializer.patch.gz](https://github.com/Tk-Glitch/PKGBUILDS/files/3964082/D3D12CreateVersionedRootSignatureDeserializer.patch.gz)
[D3D12SerializeVersionedRootSignature.patch.gz](https://github.com/Tk-Glitch/PKGBUILDS/files/3964083/D3D12SerializeVersionedRootSignature.patch.gz)

Now, the wee bit tricky part is that if you add these wine patches and NOT use libvkd3d-GIT, you will get an error.. so if a uses adds this patch while using the default libvkd3d (1.1) that comes with the distro, the compile will fail. 

I have only rebased these, and tweaked them to recent GIT. Reference to the original patches on the dev-mailing list:
[https://www.winehq.org/pipermail/wine-devel/2019-November/153658.html](https://www.winehq.org/pipermail/wine-devel/2019-November/153658.html)
[https://www.winehq.org/pipermail/wine-devel/2019-October/152356.html](https://www.winehq.org/pipermail/wine-devel/2019-October/152356.html)
[https://www.winehq.org/pipermail/wine-devel/2019-October/152357.html](https://www.winehq.org/pipermail/wine-devel/2019-October/152357.html)

**Comment by Tk-Glitch** [comment]
I think it's a good candidate for community-patches, what do you think?
Please let me know if you want to PR or if you want me to add the patches :)

**Comment by SveSop** [comment]
I am fine with you just picking the patches and adding them. Saves me from fiddling with the right spot to put them :)

**Comment by Tk-Glitch** [comment]
Gotcha!

**Comment by SveSop** [comment]
I might not have been too good at explaining how stuff connects, as it is a while back since this Nazjatar crash happened, and the same with the "wow flashing textures", so to reiterate how it connects as far as i think.

The wine D3D12 patches does not really need the RS_1.0_Volatile patch, but it needs libvkd3d GIT that provides vkd3d_serialize_root_sign from git [https://source.winehq.org/git/vkd3d.git/commitdiff/3b83ccc67e2a695b61fb374bf6f8d5b9cf605b47](https://source.winehq.org/git/vkd3d.git/commitdiff/3b83ccc67e2a695b61fb374bf6f8d5b9cf605b47)
Now this commit is newer than vkd3d_1.1 release, so for those that DO pull from GIT, this is no problem (as you do with libvkd3d pkgbuild) to build wine with those patches as long as you do that and not use the default distro libvkd3d_1.1 only.

And as long as you pull libvkd3d from GIT + build wine with those two D3D12 patches, wine will utilize D3D12 root signature 1.1 that is needed to make World of Warcraft work with Nazjatar. The RS 1.0 Volatile patch is for the flashing textures and would need recent GIT of libvkd3d to work. I see you have the "wow flicker patch" there, but i think this RS 1.0 Volatile patch is what actually fixes this in a more proper manner.

Afaik the "wow flicker patch" you have there is the old one, but it might still be that it fixes the flickering too.. I had not seen this tbh.

Since i do a fair bit of WoW testing regarding this, i can give you an update to what the wow-flicker-patch does vs. the RS 1.0 Volatile patch and get back to you on this. Just for clarification :)

**Comment by SveSop** [comment]
### Testcase 1 - World of Warcraft
Wine: wine-staging-5.0-rc1 (Plain no patches)
vkd3d: Git a59f1982adeca99b64d28fd89fa7118a246558c0 (Plain no patches)
Result: Wow crashes with `Error # 132`

### Testcase 2 - World of Warcraft
Wine: wine-staging-5.0-rc1 w/D3D12 patches (the two submitted)
vkd3d: Git a59f1982adeca99b64d28fd89fa7118a246558c0 (Plain no patches)
Result: Wow launches, but textures flickering. Nazjatar also works (with flickering)

### Testcase 3 - World of Warcraft
Wine: wine-staging-5.0-rc1 w/D3D12 patches (the two submitted)
vkd3d: Git a59f1982adeca99b64d28fd89fa7118a246558c0 + wow-flicker-fix.myvkd3dpatch
Result: WoW lauches and flickering gone. Same in Nazjatar. 

### Testcase 4 - World of Warcraft
Wine: wine-staging-5.0-rc1 w/D3D12 patches (the two submitted)
vkd3d: Git a59f1982adeca99b64d28fd89fa7118a246558c0 + RS 1.0 Volatile patch
Result: WoW lauches and flickering gone. Same in Nazjatar. 

### Testcase 5 - World of warcraft
Wine: wine-staging-5.0-rc1 w/D3D12 patches (the two submitted)
vkd3d: Git a59f1982adeca99b64d28fd89fa7118a246558c0 + RS 1.0 Volatile patch + wow-flicker-fix.myvkd3dpatch
Result: WoW lauches and flickering gone. Same in Nazjatar. 

### Conclusion:
I do not know if having BOTH "flicker patches" have any problems down the line, but from initial testing, they both do the same although i think the Support RS 1.0 Volatile patch is a bit less "hacky" than the other one posted way back. It does not seem to be any impact on having both tho.

The thing that happened with World of warcraft was when vkd3d had this commit: [https://source.winehq.org/git/vkd3d.git/commitdiff/c002aee119b638d30eeb7cdc91099449ccafeafc](https://source.winehq.org/git/vkd3d.git/commitdiff/c002aee119b638d30eeb7cdc91099449ccafeafc)
This means that vkd3d would enable root_signature_1.1 for d3d12 apps that required it (i believe), but since the D3D12 patches i posted is NOT included in wine upstream (due to former explanation of needing a libvkd3d API update) WoW will crash. 
It was providing d3d12_root_signature_1.1 that actually fixed Nazjatar, and not the RS 1.0 Volatile patch.

1. The wine D3D12 patches requires libvkd3d GIT c002aee119b638d30eeb7cdc91099449ccafeafc or newer to get World of Warcraft working in Nazjatar. 
2. If you are using libvkd3d GIT c002aee119b638d30eeb7cdc91099449ccafeafc or newer, WoW does not lauch at all without the wine D3D12 patches.
3. If you use libvkd3d GIT 769dd2b68c813324a00af8e6b1f99159f403863a or older, WoW will work with D3D12 without wine patches, but will crash when entering Nazjatar.
4. The Support RS 1.0 Volatile patch fixes the same thing as 01-wow-flicker-fix.myvkd3dpatch and you probably do not need both.

Sorry for the long winded explanation, but i kinda felt your commit message based on my earlier explanation was not correct, and i should have been a bit more concise in my reporting. (But quite frankly, did not have all this info before i dug into it...)

**Comment by Tk-Glitch** [comment]
Nice input, thanks for that! The hacky patch was needed on nvidia at least, not too long ago. I have not tried current nor AMD but it's possible it's no more needed.

**Comment by SveSop** [comment]
Actually this hack-patch first surfaced over a year ago, and has been rebased/updated a couple of times after that. The oldest i found atm - [https://bugs.winehq.org/attachment.cgi?id=63022&action=diff](https://bugs.winehq.org/attachment.cgi?id=63022&action=diff) and was kinda posted as just a "hack fix". I do not know if it has any effect or is needed for AMD.

Anyway, from my testing they both have the same effect, but i have used the Support RS_1.0 Volatile patch quite a while without any issues, so I know that atleast works fine with my nVidia RTX2070 :) None of the patches are upstreamed, but the Support RS 1.0 Volatile patch has been posted on the devel mailing list vs the "hack patch" that have not. I cannot determine if one or the other is "more correct".

I can however give a little chirp if i find something that fixes this issue gets upstreamed so that you can update that.
