### ISSUE TITLE
Benchmarks for performance comparison?

### ISSUE THREAD

**Issue by xRiot** [Tk-Glitch/PKGBUILDS#424]
Would there happen to be any benchmarks for direct performance comparison of all the tweaks provided here versus stock?

It would be very interesting to see how these optimizations stacks up against Clear Linux considering it's coming in at the first place in most [distribution benchmarks](https://www.phoronix.com/scan.php?page=article&item=10980xe-intel-linux&num=7).

**Comment by ronoverdrive** [comment]
All the tweaks for what specifically? Linux-TKG vs stock?

**Comment by Tk-Glitch** [comment]
Clear Linux performance comes from all packages having tight optimizations. The actual kernel doesn't do much. You can install Clear Linux kernel on a different distro as a test, you'll see there's basically no performance gain. Similarly to installing for example a game on Clear that hasn't received their optimization treatment: virtually no gain.

In our case the situation is a bit more invasive as most of the performance difference comes from replacing the CPU scheduler altogether, changing the stock behavior. The performance is not expected to be higher for all tasks as it's not the goal. The aim is better interactivity and gaming experience. You could also use terms such as "reactivity", "low-latency", "smoothness" to define what we're after.

It can lead to quite significant raw performance gains in some situations but the actual numbers will vary widely depending on hardware. The common benefit in most cases is very improved frametimes and minimum framerates.

**Comment by xRiot** [comment]
Thanks for clearing this up @Tk-Glitch and @ronoverdrive, you can even observe the same behavior with the Liquorix kernel according to the [Phoronix benchmarks](https://www.phoronix.com/scan.php?page=article&item=radeon-gaming-liquorix54&num=1).
