### ISSUE TITLE
[wine-tkg] MTGA patchset: separate calculate_install_state patch from get_thread_context patch

### ISSUE THREAD

**Issue by llde** [Tk-Glitch/PKGBUILDS#426]
Hi. It's clear then activate the MTGA patch in customization.cfg cause some installer (notable some dotnet versions) to fail in msi.
There are actually two patch merged in one:
the first is fondamental to let the game works  (most of the times) and it's the get_thread_context patch. (without it the game ceash in the in initial internal update).
Then there is the calculate_install_state where a return is putted uncoditionally on the top of the function. This is potentially terribly incorrect and I belive it may be the culprit of disturbed installers. 
The patch was done to avoid recreating the prefix when using  the msi installer directly. 
However with wine 5.0 rc1 the installer actually succeed allowing MTGA updates throught the MTGA Launcher.exe provided dotnet 452 is installed (maybe also dotnet45 is required, I tested with both installed).
So I suggest to split the patch in two, allowing users to select just one if them.  (At least for wine at elastsa 5.0 rc1). 
ALso is clear that the installing with direct msi files failure is a wine deficency, this can allow to easily  discuss and provide a better patch for calculate_install_state functions better and indipendently.
Thanks.

**Comment by Tk-Glitch** [comment]
Thank you for your suggestion and qualitative input!
