### ISSUE TITLE
Add ESO-specific patch

### ISSUE THREAD

**Issue by Saroufim** [Tk-Glitch/PKGBUILDS#43]
It would be nice if this game-specific patch can be added: https://bugs.winehq.org/attachment.cgi?id=62452&action=diff

**Comment by Tk-Glitch** [comment]
This patch doesn't seem to apply cleanly to master. I'll see what I can do.

**Comment by Tk-Glitch** [comment]
Is that still an issue on wine 4.0rc2 ?

**Comment by Saroufim** [comment]
I have the game installed through Steam+Proton now. Redownloading the game to test it via regular wine would take a lot of time and space (The game is humongous). I'll retest this when Proton gets rebased on a newer version of wine.

**Comment by Tk-Glitch** [comment]
This is only for wined3d indeed. And it seems nobody cares, and nobody will care in the future (I definitely don't and won't).
