### ISSUE TITLE
[wine-tkg] Can't build wine, ERROR: could not set PID 39904 to nice 1 - Permission denied

### ISSUE THREAD

**Issue by llde** [Tk-Glitch/PKGBUILDS#430]
Hi, in current git it seems unable to build wine.tkg, 

It is failing with :
ERROR: could not set PID 39904 to nice 1 - Permission denied
when invoking make after the wine 64bit configure.
customization.cfg:https://gist.github.com/llde/5f3d3b568faba848ecf9f68573f73ccc

**Comment by llde** [comment]
solved setting 'cap_sys_nice=eip' capability on schedtool executable.

**Comment by Tk-Glitch** [comment]
Never faced such an issue. #linux-problems 🐸

**Comment by llde** [comment]
@Tk-Glitch 
strange enough seems that just one PC was having this issue.
My notebook didn't have any issue. 
Both ArchLinux, both testing repo.

Boh.
Workaround still stand
