### ISSUE TITLE
[linux5*-tkg] ERROR: A failure occurred in build().

### ISSUE THREAD

**Issue by Faalagorn** [Tk-Glitch/PKGBUILDS#433]
It seems that for me and at least one other person on Discord, recent kernels (linux55-rc for me, 5.4.2 for franky) fails to build at various stages ending with `ERROR: A failure occurred in build().`

**Comment by Faalagorn** [comment]
According to recent discussion in Discord, it seems on linux5.4 it's caused by a slab patch, not sure what's causing it in 5.5

**Comment by XHDR** [comment]
Can't say I'm very informed on all the various optional patches and stages of these packages, but without a single piece of log it'll likely be hard to pinpoint the error. A copy of (possible modifications to) `customization.cfg`, and the output of `makepkg` being run, would help.

One way of capturing the entirety of the build is by running something like: `makepkg 2>&1|tee output.log`

As a side note: Leaving mostly everything as defaults, with the exception of the ZFS patch and selecting MuQSS as the scheduler, I successfully built the `linux55-rc-tkg` package without any errors.

**Comment by Faalagorn** [comment]
As mentioned on Discord, it turned out it was the -O3 optimization – for me switching to -O2 helped  even with keeping all the community patches – I always used O3 without issues so I ruled it out. For franky on Discord, it was one patch that broke it, so I guess it's "fixed" :)
