### ISSUE TITLE
[linux55-tkg] Zen or Zen2 optimizations for Zen+?

### ISSUE THREAD

**Issue by gardotd426** [Tk-Glitch/PKGBUILDS#444]
Trying to clear up some confusion on my part on customization for the linux55-tkg kernel. During optimization steps, when you're able to choose your processor, there's an option for Zen processors, along with Zen2. If I'm using a Zen+ cpu, namely a Ryzen 5 2600X, should I choose Zen? Or conversely, since I plan to move to a 3600 eventually, would there be anything wrong with choosing Zen2?

**Comment by XHDR** [comment]
As far as I can see, Zen+ uses pretty much the exact same instruction set as Zen1. Selecting the Zen 2 option enables the `-march=znver2` compiler option. That would result in code (potentially) incompatible with anything other than a Zen 2 processor.
So, if you're currently running a 2600X, and plan on using the built kernel on there, then using `-march=znver1` would be correct -- as in, plain Zen.

**Comment by gardotd426** [comment]
Okay, I wasn't sure since all 3 are on different processes (14, 12 and 7
nm), and I know that's not entirely related to instructions but I didn't
know if Zen+ was specifically different in that regard to Zen or Zen2.

**Comment by Tk-Glitch** [comment]
XHDR is absolutely right :)
