### ISSUE TITLE
proton-tkg: Fullscreen hack unavailable without staging

### ISSUE THREAD

**Issue by jarrard** [Tk-Glitch/PKGBUILDS#447]
I have been testing proton-tkg with wine5 rc4 and staging patches DISABLED (they cause issues for MO2) and noticed that when the game is set to fullscreen mode it will change my displays settings and cause it to go into 30hz. 

I couldn't figure this out for quite a while until I realised that the packager seems to have not built steams fullscreen hack correctly or something. Is there something special that is needed to be done? I was to understand if its enabled in the cfg file then it should just work but clearly its not.

**Comment by jarrard** [comment]
_proton_fs_hack="true"  this is set in the cfg, the only thing I can think of is that it doesn't work with staging disabled? if that is true then its a odd thing to do.

**Comment by Tk-Glitch** [comment]
I'm very aware, and as you found out it's explicitly stated. The rebased patchset provided is **not** compatible with mainline and targets staging because 99% of users are using staging, and nobody ever asked for a mainline patch before yourself. It was on my todo list with a "maybe, at some point" note attached. I'll consider it more seriously.

**Comment by jarrard** [comment]
Ok, well there is a custom patch that 'maybe' fixes the issue with staging I had. Basically I was using mod organizer 2 which wine-staging currently breaks. 

Guess I will just need to find out howto tag on a patch at the end of the staging patches and see how it goes. (this patch has not been tested yet). 

Thanks for the reply. And yes it would still be nice if fullscreen worked on non-staging build, I know as a end user nobody cares, but for testers who are trying to track down bugs and such it can be of help.

**Comment by gardotd426** [comment]
@jarrard the very message you pasted from the .cfg says "Requires staging."
