### ISSUE TITLE
[wine-tkg-community-patches] winex11-fs-no_above_state.mypatch doesn't apply

### ISSUE THREAD

**Issue by llde** [Tk-Glitch/PKGBUILDS#448]
-> ######################################################
  -> 
  -> Applying your own plain-wine patch /home/<redacted>/PKGBUILDS/wine-tkg-git/winex11-fs-no_above_state.mypatch
  -> 
  -> ######################################################
patching file dlls/winex11.drv/window.c
Hunk #1 FAILED at 1078.
1 out of 1 hunk FAILED -- saving rejects to file dlls/winex11.drv/window.c.rej

**Comment by Tk-Glitch** [comment]
Got your config at hand? It applies fine on my end with the dependencies (staging and _proton_fs_hack) enabled.

**Comment by llde** [comment]
@Tk-Glitch  Can't reproduce anymore after having nuked and recloned the repo, with the same config. 
MAybe a mismerge during pulling updates.
