### ISSUE TITLE
wine 3.20 update

### ISSUE THREAD

**Issue by yokiraamato** [Tk-Glitch/PKGBUILDS#45]
needs update

**Comment by openglfreak** [comment]
-git packages usually don't need updates for new versions, unless the build process changes.

**Comment by neVERberleRfellerER** [comment]
@openglfreak is right. Just rebuild the package - you will even get 3.20 in package version automagically.

**Comment by Tk-Glitch** [comment]
As @openglfreak and @neVERberleRfellerER already explained, you don't need a pkgver bump to get the latest version. The PKGBUILD will always compile from latest git master available, either from staging or plain trees depending on your configuration (default will use staging, that may be available a few hours up to a few days after plain wine release).
