### ISSUE TITLE
[proton-tkg] outdated vkd3d

### ISSUE THREAD

**Issue by 5paceToast** [Tk-Glitch/PKGBUILDS#450]
Log file:
> 8292.986:002a:002f:err:module:load_so_dll failed to load .so lib "/home/toast/.local/share/Steam/compatibilitytools.d/proton_tkg_5.0rc4.r0.ga1bf11e3.release/dist/bin/../lib64/wine/d3d12.dll.so": /home/toast/.local/share/Steam/compatibilitytools.d/proton_tkg_5.0rc4.r0.ga1bf11e3.release/dist/bin/../lib64/wine/d3d12.dll.so: undefined symbol: vkd3d_serialize_versioned_root_signature, version VKD3D_1_0

This is because VKD3D 1.1 is out and present in the arch repositories:
`$ pacman -Q vkd3d # -> vkd3d 1.1-1`

**Comment by Tk-Glitch** [comment]
This is actually the other way around. `proton_tkg_5.0rc4.r0.ga1bf11e3` was built against vkd3d master (6th of December). Arch repos vkd3d packages are a year old at this point and deprecated.

**Comment by 5paceToast** [comment]
Would it make sense to potentially mention that in the wiki (or anywhere, really)?
The only mention I've seen was to just install vkd3d libs to have it work.

**Comment by Tk-Glitch** [comment]
Absolutely. I wasn't aware about the Arch packages being outdated before your report 🐸

**Comment by Tk-Glitch** [comment]
Since it only affects the prebuilts, I have added a note in the VKD3D lines of the last few releases. Hopefully that'll be enough. I really need to refactor readmes and make the wiki actually useful. Right now it's lacking on one front, and is overwhelming on the other 🐸 

I guess I can close this :)
