### ISSUE TITLE
Default answer no for installing mingw during setup

### ISSUE THREAD

**Issue by danger89** [Tk-Glitch/PKGBUILDS#452]
I got this error: `mingw-w64-gcc was not found on your system`. At the end of the package installs & git clones.

```
Do you want to launch mingw installation script now?
     > N/y : y
```

Why is the default answer N (no)?

I think since we are missing mingw, maybe its better to have the default answer yes here?

Regards,
Melroy van den Berg

**Comment by Tk-Glitch** [comment]
It's not a hard requirement so no reason to enforce it. In the future, anticheats will likely require it, but right now you can completely ignore mingw and build with only pure GCC.

**Comment by danger89** [comment]
OK, in that case. You may want to change the output text, saying it was a hard requirement in order to build it.

**Comment by Tk-Glitch** [comment]
```
	    error 'mingw-w64-gcc was not found on your system.'
	    msg2 'It is not a hard requirement but is recommended to build current versions of wine.'
	    msg2 'Do you want to launch mingw installation script now?'
```
Unless you're talking about something else it says that it isn't a hard requirement but recommended. I could tweak it a bit to make it's usefulness clearer I suppose.

**Comment by danger89** [comment]
Oops sorry by bad.. Was late yesterday :\. Excuse me.

**Comment by Tk-Glitch** [comment]
No worries :)
