### ISSUE TITLE
[wine-tkg-git] Wine binary is searching in the wrong lib folder

### ISSUE THREAD

**Issue by danger89** [Tk-Glitch/PKGBUILDS#453]
Hi,

I'm using the Arch docker container to build Wine and use the binaries under Linux Mint (Ubuntu Bionic based): [see more details on the Docker Hub](https://hub.docker.com/repository/docker/danger89/wine-pkgbuilds).

The changed I made in the config are: `_EXTERNAL_INSTALL` to "true", `_EXTERNAL_NOVER` to "true" and `_PKGNAME_OVERRIDE` to "none". Meaning the Wine roll-out directory will become: `/opt/wine-tkg-opt-git/`.

I copied the build files to the correct location in my host PC (see again the Docker hub page).

So I change the PATH:
```
$ export PATH=/opt/wine-tkg-opt-git/bin:$PATH

$ which wine
/opt/wine-tkg-opt-git/bin/wine

$ wine --version
wine-5.0rc5.r0.g23960d98 ( TkG Staging Esync Fsync )
```

So far so good. Until I try do to something with my Wine:

```
$ WINEPREFIX=~/.wine wine wineboot
wine: failed to initialize: /opt/wine-tkg-opt-git-5.0rc5.r0.g23960d98/lib/wine/ntdll.dll.so: cannot open shared object file: No such file or directory
```

So the wine binary is hard-coded to look to this other path, while this is not the path mentioned during the build (`Remember to use /opt/wine-tkg-opt-git/bin/wine instead of just wine (same for winecfg etc.)`).

The dlls files are actually located in `/opt/wine-tkg-opt-git/lib/wine` as expected. So what is going wrong here?

I think something is wrong with the build scripts. I think I did everything correctly in my customization.cfg file.

Thanks!

Regards,
Melroy van den Berg

**Comment by Tk-Glitch** [comment]
Feel free to confirm if that indeed fixed the issue :)

**Comment by danger89** [comment]
I will, thanks.
