### ISSUE TITLE
Wine build error - Undefined reference to __stack_chk_fail / guard 

### ISSUE THREAD

**Issue by reno138** [Tk-Glitch/PKGBUILDS#455]
Hey there - first off, thanks for maintaining this repo. It has been life saver for time and making games more playable -

Now on the for negative part - I've run into this the last couple of days. First on arch (fresh install, ran the migw arch builder in the repo) and now on Manjaro (18.1.5, stable and testing bransh Cinnamon, 5.4.8 and 5.4.11 stock kernels,  and then the wine build fails with the errors below. I read on another thread where there is an issue with the first gen zen architecture, so I thought that is what it was, but then I tried to build on my laptop, which is intel. I'm sure I'm just missing something, but I have NO idea what it is. Any ideas off the top of your head?
The customization.cfg is default except for vkd3d and local optimization. 

GCC 9.2.0
x86_64-w64-mingw32-gcc (GCC) 9.2.0
5.4.11-1-MANJARO
Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz

../../tools/winegcc/winegcc -o actxprxy.dll --wine-objdir ../.. -b x86_64-w64-mingw32 --lib-suffix=.cross.a \
  -Wl,--wine-builtin -shared ../../../wine-mirror-git/dlls/actxprxy/actxprxy.spec -mno-cygwin \
  usrmarshal.cross.o dlldata.cross.o actxprxy_activscp_p.cross.o actxprxy_comcat_p.cross.o \
  actxprxy_docobj_p.cross.o actxprxy_hlink_p.cross.o actxprxy_htiface_p.cross.o \
  actxprxy_htiframe_p.cross.o actxprxy_objsafe_p.cross.o actxprxy_ocmm_p.cross.o \
  actxprxy_servprov_p.cross.o actxprxy_shldisp_p.cross.o actxprxy_shobjidl_p.cross.o \
  actxprxy_urlhist_p.cross.o actxprxy_activscp_r.res actxprxy_comcat_r.res actxprxy_docobj_r.res \
  actxprxy_hlink_r.res actxprxy_htiface_r.res actxprxy_htiframe_r.res actxprxy_objsafe_r.res \
  actxprxy_ocmm_r.res actxprxy_servprov_r.res actxprxy_shldisp_r.res actxprxy_shobjidl_r.res \
  actxprxy_urlhist_r.res ../../dlls/uuid/libuuid.cross.a ../../dlls/oleaut32/liboleaut32.cross.a \
  ../../dlls/ole32/libole32.cross.a ../../dlls/rpcrt4/librpcrt4.cross.a -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong 
/usr/lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld: usrmarshal.cross.o:usrmarshal.c:(.text+0x79): undefined reference to `__stack_chk_fail'
/usr/lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld: usrmarshal.cross.o:usrmarshal.c:(.text+0x116): undefined reference to `__stack_chk_fail'
/usr/lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld: usrmarshal.cross.o:usrmarshal.c:(.text+0xa0d): undefined reference to `__stack_chk_fail'
/usr/lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld: usrmarshal.cross.o:usrmarshal.c:(.rdata$.refptr.__stack_chk_guard[.refptr.__stack_chk_guard]+0x0): undefined reference to `__stack_chk_guard'
/usr/lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld: actxprxy_activscp_p.cross.o:actxprxy_activscp_p.c:(.text+0x64e): undefined reference to `__stack_chk_fail'
/usr/lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld: actxprxy_activscp_p.cross.o:actxprxy_activscp_p.c:(.text+0x9dd): undefined reference to `__stack_chk_fail'
/usr/lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld: actxprxy_activscp_p.cross.o:actxprxy_activscp_p.c:(.text+0xcc8): undefined reference to `__stack_chk_fail'
/usr/lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld: actxprxy_activscp_p.cross.o:actxprxy_activscp_p.c:(.text+0xf42): undefined reference to `__stack_chk_fail'
/usr/lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld: actxprxy_activscp_p.cross.o:actxprxy_activscp_p.c:(.text+0x11c2): undefined reference to `__stack_chk_fail'
/usr/lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld: actxprxy_activscp_p.cross.o:actxprxy_activscp_p.c:(.text+0x149a): more undefined references to `__stack_chk_fail' follow
collect2: error: ld returned 1 exit status
winegcc: x86_64-w64-mingw32-gcc failed
make[1]: *** [Makefile:1047: actxprxy.dll] Error 2
make[1]: Leaving directory '/home/reno/aur/PKGBUILDS/wine-tkg-git/src/wine-tkg-staging-fsync-vkd3d-git-64-build/dlls/actxprxy'
make: *** [Makefile:9118: dlls/actxprxy] Error 2
==> ERROR: A failure occurred in build().

**Comment by Tk-Glitch** [comment]
Pretty sure that one has to do with Manjaro using `-fstack-protector-strong` by default, which is known to break wine since 4.20 or so. Arch doesn't pass that flag and doesn't hit the issue.
Enabling `_LOCAL_OPTIMIZED` will fix it, else you'll have to remove the offending flag from your `/etc/makepkg.conf`.

**Comment by reno138** [comment]
I actually did remove that flag from makepkg.conf. But, mingw was built with it. Could that have been the cause?

**Comment by Tk-Glitch** [comment]
You can test that by setting `_NOMINGW="true"` in your .cfg. If the error vanishes then yes, mingw will have to be rebuilt without the flag. If it fails on a similar error it's something else. But I'm pretty sure that's indeed the issue.

**Comment by reno138** [comment]
Great! I figured it was going to be something simple, and that flag caught my attention, but after I disabled it, I didn't think to rebuild mingw without it. 

Thanks for the quick answer and all the work you put in on this repo! It's very much appreciated!

**Comment by Tk-Glitch** [comment]
You're welcome :)
