### ISSUE TITLE
Several issues with faudio-git

### ISSUE THREAD

**Issue by robzombie91** [Tk-Glitch/PKGBUILDS#458]
1. lib32-ffmpeg is broken due to its dependancy lib32-x264 being out of date/broken
2. Cant compile faudio-git without lib32-ffmpeg due to the issues above

**Comment by Tk-Glitch** [comment]
It breaks once a week or so 🐸 . You can disable the lib32 part with the switch inside the PKGBUILD and use Arch's provided lib32-faudio package as a workaround until this is fixed. Be aware that there's no FFMPEG support in Arch's lib32-faudio package though, meaning quite a few 32-bit games will have broken/missing sounds.

Is the lib32-x264 maintainer aware of the breakage?

**Comment by robzombie91** [comment]
not sure, it hasnt been updated since 4/2019 so i dont think so

**Comment by robzombie91** [comment]
but it was flagged out of date so that should probably get someone's attention

**Comment by robzombie91** [comment]
so just make this false?

if [ "$_lib32" == "true" ]; then
  pkgname=("${pkgname[@]}" "lib32-${_pkgname}-git")
fi

**Comment by telans** [comment]
It might be worth submitting an orphan request for lib32-x264

**Comment by telans** [comment]
Just updated lib32-x264

**Comment by telans** [comment]
can be closed @Tk-Glitch

**Comment by robzombie91** [comment]
Closed due to @telans request
