### ISSUE TITLE
[Question] SMT_NICE on Zen(2)

### ISSUE THREAD

**Issue by Devorlon** [Tk-Glitch/PKGBUILDS#459]
When building linux55-rc-tkg the process asks if you want to enable smt_nice. After entering '?' the reasoning doesn't mention AMD, only Intel. So should it be enabled for Amd / Zen or is it an Intel only thing?

> Enabling Hyperthreading on Intel CPUs decreases the effectiveness
of the use of 'nice' levels and different scheduling policies
(e.g. realtime) due to sharing of CPU power between hyperthreads.

Then later

> If unsure say Y here.

**Comment by Tk-Glitch** [comment]
The note is a bit old, but it'll affect any SMT-enabled CPU. So yes it works for Zen/Zen+/Zen2 as well as Hyperthreaded Intel Core CPUs. It enhances load balancing quite a bit in low/mid load scenarios often encountered while gaming. The "real cores" get the highest priority so you're less likely to end up with a logical core being overloaded.

**Comment by Devorlon** [comment]
Thanks for the answer, as well as all the work you've done for Linux.

**Comment by Tk-Glitch** [comment]
You're welcome!

There's been weird stuff happening since pacman 5.2 release.. Does it work any better with `_force_all_threads="true"` in .cfg?
Another thing to try would be to install the `schedtool` package, possibly combined with `_force_all_threads="true"`.

**Comment by Devorlon** [comment]
While I haven't tested it without it installed, schedtool + _force_all_threads="true" works like a charm. It cuts compilation from ~2h to ~ 25min. Again, thanks for all the help. 🐸
