### ISSUE TITLE
configure: error: Couldn't load Gallium Nine

### ISSUE THREAD

**Issue by ltsdw** [Tk-Glitch/PKGBUILDS#46]
getting this:

configure: error: Couldn't load Gallium nine module at '/usr/lib32/d3d/d3dadapter9.so.1' (found by pkg-config)

**Comment by Tk-Glitch** [comment]
Looks like you're missing the lib32-mesa package.

**Comment by ltsdw** [comment]
it's odd, i'm using mesa-git and lib32-mesa-git, I'll recompile them and try again.

**Comment by ltsdw** [comment]
After recompiling both mesa-git and lib32-mesa-git, it compiled.
