### ISSUE TITLE
Write Wine deps into a package

### ISSUE THREAD

**Issue by t14462** [Tk-Glitch/PKGBUILDS#461]
Write Wine deps into a package, because "yay -Yc" deleting it and some games doesn't play music.

PS: I use ZSTD for packages on Manjaro.

**Comment by telans** [comment]
You could always move the packages you want out of [optdepends](https://github.com/Tk-Glitch/PKGBUILDS/blob/master/wine-tkg-git/PKGBUILD#L128) and into depends if you wanted to keep them around

**Comment by t14462** [comment]
THANKS!!!

**Comment by telans** [comment]
can be closed @Tk-Glitch
