### ISSUE TITLE
[wine-tkg-git] Patch winevulkan

### ISSUE THREAD

**Issue by IroAlexis** [Tk-Glitch/PKGBUILDS#466]
Hello Frogs,

I think that the patch (winevulkan) is out of date if we use the last wine-git. The description of the patch should be modified to make it more clearer.

Indeed, there was a [commit](https://github.com/wine-mirror/wine/commit/1fa427f2d09ed466bf72521c7db2ca7768bcd6c1) updating the Vulkan specs (1.1.130).

_NB : Sorry for my poor english ^^'_

**Comment by ebiroud** [comment]
If you mean "_update_winevulkan patch" included in there, I think it doesn't apply if it isn't necessary. Therefore we're going along with the latest wine-git.

**Comment by telans** [comment]
```
if [ "$_update_winevulkan" == "true" ] {...} && ! git merge-base --is-ancestor 7e736b5903d3d078bbf7bb6a509536a942f6b9a0 HEAD; then
```
The patch isn't applied anyways if you're building wine with [7e736b](https://source.winehq.org/git/wine.git/commit/7e736b5903d3d078bbf7bb6a509536a942f6b9a0), so any time after 11th Nov 2019

**Comment by IroAlexis** [comment]
> ```
> if [ "$_update_winevulkan" == "true" ] {...} && ! git merge-base --is-ancestor 7e736b5903d3d078bbf7bb6a509536a942f6b9a0 HEAD; then
> ```
> 
> The patch isn't applied anyways if you're building wine with [7e736b](https://source.winehq.org/git/wine.git/commit/7e736b5903d3d078bbf7bb6a509536a942f6b9a0), so any time after 11th Nov 2019

Oh mb I haven't check this so i close this issue
