### ISSUE TITLE
gamescope-git: Conflicting with wlroots

### ISSUE THREAD

**Issue by rodrigo21** [Tk-Glitch/PKGBUILDS#468]
gamescope-git is conflicting with wlroots during installation. 

Pacman log:

`error: failed to commit transaction (conflicting files)
gamescope-git: /usr/include/wlr/backend.h exists in filesystem (owned by wlroots)
gamescope-git: /usr/include/wlr/backend/drm.h exists in filesystem (owned by wlroots)
gamescope-git: /usr/include/wlr/backend/headless.h exists in filesystem (owned by wlroots)
gamescope-git: /usr/include/wlr/backend/interface.h exists in filesystem (owned by wlroots)
gamescope-git: /usr/include/wlr/backend/libinput.h exists in filesystem (owned by wlroots)
gamescope-git: /usr/include/wlr/backend/multi.h exists in filesystem (owned by wlroots)
gamescope-git: /usr/include/wlr/backend/noop.h exists in filesystem (owned by wlroots)
gamescope-git: /usr/include/wlr/backend/session.h exists in filesystem (owned by wlroots)
gamescope-git: /usr/include/wlr/backend/session/interface.h exists in filesystem (owned by wlroots)
gamescope-git: /usr/include/wlr/backend/wayland.h exists in filesystem (owned by wlroots)
gamescope-git: /usr/include/wlr/backend/x11.h exists in filesystem (owned by wlroots)
gamescope-git: /usr/include/wlr/config.h exists in filesystem (owned by wlroots)
gamescope-git: /usr/include/wlr/interfaces/wlr_input_device.h exists in filesystem (owned by wlroots)
gamescope-git: /usr/include/wlr/interfaces/wlr_keyboard.h exists in filesystem (owned by wlroots)
gamescope-git: /usr/include/wlr/interfaces/wlr_output.h exists in filesystem (owned by wlroots)
gamescope-git: /usr/include/wlr/interfaces/wlr_pointer.h exists in filesystem (owned by wlroots)
gamescope-git: /usr/include/wlr/interfaces/wlr_switch.h exists in filesystem (owned by wlroots)
gamescope-git: /usr/include/wlr/interfaces/wlr_tablet_pad.h exists in filesystem (owned by wlroots)
gamescope-git: /usr/include/wlr/interfaces/wlr_tablet_tool.h exists in filesystem (owned by wlroots)
gamescope-git: /usr/include/wlr/interfaces/wlr_touch.h exists in filesystem (owned by wlroots)
gamescope-git: /usr/include/wlr/render/dmabuf.h exists in filesystem (owned by wlroots)
gamescope-git: /usr/include/wlr/render/drm_format_set.h exists in filesystem (owned by wlroots)
gamescope-git: /usr/include/wlr/render/egl.h exists in filesystem (owned by wlroots)
gamescope-git: /usr/include/wlr/render/gles2.h exists in filesystem (owned by wlroots)
gamescope-git: /usr/include/wlr/render/interface.h exists in filesystem (owned by wlroots)
gamescope-git: /usr/include/wlr/render/wlr_renderer.h exists in filesystem (owned by wlroots)
gamescope-git: /usr/include/wlr/render/wlr_texture.h exists in filesystem (owned by wlroots)
gamescope-git: /usr/include/wlr/types/wlr_box.h exists in filesystem (owned by wlroots)
gamescope-git: /usr/include/wlr/types/wlr_buffer.h exists in filesystem (owned by wlroots)
gamescope-git: /usr/include/wlr/types/wlr_compositor.h exists in filesystem (owned by wlroots)
gamescope-git: /usr/include/wlr/types/wlr_cursor.h exists in filesystem (owned by wlroots)
gamescope-git: /usr/include/wlr/types/wlr_data_control_v1.h exists in filesystem (owned by wlroots)
gamescope-git: /usr/include/wlr/types/wlr_data_device.h exists in filesystem (owned by wlroots)
gamescope-git: /usr/include/wlr/types/wlr_export_dmabuf_v1.h exists in filesystem (owned by wlroots)
gamescope-git: /usr/include/wlr/types/wlr_foreign_toplevel_management_v1.h exists in filesystem (owned by wlroots)
gamescope-git: /usr/include/wlr/types/wlr_fullscreen_shell_v1.h exists in filesystem (owned by wlroots)
gamescope-git: /usr/include/wlr/types/wlr_gamma_control_v1.h exists in filesystem (owned by wlroots)
gamescope-git: /usr/include/wlr/types/wlr_gtk_primary_selection.h exists in filesystem (owned by wlroots)
gamescope-git: /usr/include/wlr/types/wlr_idle.h exists in filesystem (owned by wlroots)
gamescope-git: /usr/include/wlr/types/wlr_idle_inhibit_v1.h exists in filesystem (owned by wlroots)
gamescope-git: /usr/include/wlr/types/wlr_input_device.h exists in filesystem (owned by wlroots)
gamescope-git: /usr/include/wlr/types/wlr_input_inhibitor.h exists in filesystem (owned by wlroots)
gamescope-git: /usr/include/wlr/types/wlr_input_method_v2.h exists in filesystem (owned by wlroots)
gamescope-git: /usr/include/wlr/types/wlr_keyboard.h exists in filesystem (owned by wlroots)
gamescope-git: /usr/include/wlr/types/wlr_layer_shell_v1.h exists in filesystem (owned by wlroots)
gamescope-git: /usr/include/wlr/types/wlr_linux_dmabuf_v1.h exists in filesystem (owned by wlroots)
gamescope-git: /usr/include/wlr/types/wlr_list.h exists in filesystem (owned by wlroots)
gamescope-git: /usr/include/wlr/types/wlr_matrix.h exists in filesystem (owned by wlroots)
gamescope-git: /usr/include/wlr/types/wlr_output.h exists in filesystem (owned by wlroots)
gamescope-git: /usr/include/wlr/types/wlr_output_damage.h exists in filesystem (owned by wlroots)
gamescope-git: /usr/include/wlr/types/wlr_output_layout.h exists in filesystem (owned by wlroots)
gamescope-git: /usr/include/wlr/types/wlr_output_management_v1.h exists in filesystem (owned by wlroots)
gamescope-git: /usr/include/wlr/types/wlr_pointer.h exists in filesystem (owned by wlroots)
gamescope-git: /usr/include/wlr/types/wlr_pointer_constraints_v1.h exists in filesystem (owned by wlroots)
gamescope-git: /usr/include/wlr/types/wlr_pointer_gestures_v1.h exists in filesystem (owned by wlroots)
gamescope-git: /usr/include/wlr/types/wlr_presentation_time.h exists in filesystem (owned by wlroots)
gamescope-git: /usr/include/wlr/types/wlr_primary_selection.h exists in filesystem (owned by wlroots)
gamescope-git: /usr/include/wlr/types/wlr_primary_selection_v1.h exists in filesystem (owned by wlroots)
gamescope-git: /usr/include/wlr/types/wlr_region.h exists in filesystem (owned by wlroots)
gamescope-git: /usr/include/wlr/types/wlr_relative_pointer_v1.h exists in filesystem (owned by wlroots)
gamescope-git: /usr/include/wlr/types/wlr_screencopy_v1.h exists in filesystem (owned by wlroots)
gamescope-git: /usr/include/wlr/types/wlr_seat.h exists in filesystem (owned by wlroots)
gamescope-git: /usr/include/wlr/types/wlr_server_decoration.h exists in filesystem (owned by wlroots)
gamescope-git: /usr/include/wlr/types/wlr_surface.h exists in filesystem (owned by wlroots)
gamescope-git: /usr/include/wlr/types/wlr_switch.h exists in filesystem (owned by wlroots)
gamescope-git: /usr/include/wlr/types/wlr_tablet_pad.h exists in filesystem (owned by wlroots)
gamescope-git: /usr/include/wlr/types/wlr_tablet_tool.h exists in filesystem (owned by wlroots)
gamescope-git: /usr/include/wlr/types/wlr_tablet_v2.h exists in filesystem (owned by wlroots)
gamescope-git: /usr/include/wlr/types/wlr_text_input_v3.h exists in filesystem (owned by wlroots)
gamescope-git: /usr/include/wlr/types/wlr_touch.h exists in filesystem (owned by wlroots)
gamescope-git: /usr/include/wlr/types/wlr_virtual_keyboard_v1.h exists in filesystem (owned by wlroots)
gamescope-git: /usr/include/wlr/types/wlr_xcursor_manager.h exists in filesystem (owned by wlroots)
gamescope-git: /usr/include/wlr/types/wlr_xdg_decoration_v1.h exists in filesystem (owned by wlroots)
gamescope-git: /usr/include/wlr/types/wlr_xdg_output_v1.h exists in filesystem (owned by wlroots)
gamescope-git: /usr/include/wlr/types/wlr_xdg_shell.h exists in filesystem (owned by wlroots)
gamescope-git: /usr/include/wlr/types/wlr_xdg_shell_v6.h exists in filesystem (owned by wlroots)
gamescope-git: /usr/include/wlr/util/edges.h exists in filesystem (owned by wlroots)
gamescope-git: /usr/include/wlr/util/log.h exists in filesystem (owned by wlroots)
gamescope-git: /usr/include/wlr/util/region.h exists in filesystem (owned by wlroots)
gamescope-git: /usr/include/wlr/version.h exists in filesystem (owned by wlroots)
gamescope-git: /usr/include/wlr/xcursor.h exists in filesystem (owned by wlroots)
gamescope-git: /usr/include/wlr/xwayland.h exists in filesystem (owned by wlroots)
gamescope-git: /usr/lib/libwlroots.so exists in filesystem (owned by wlroots)
gamescope-git: /usr/lib/pkgconfig/wlroots.pc exists in filesystem (owned by wlroots)
Errors occurred, no packages were upgraded.`

**Comment by Tk-Glitch** [comment]
Thank you. I am aware and will push a fix later today :)

**Comment by Valmar33** [comment]
For reference, I made a bug report here: https://github.com/Plagman/gamescope/issues/26
