### ISSUE TITLE
Steam (Windows) crashes with  Wine-TKG

### ISSUE THREAD

**Issue by leillo1975** [Tk-Glitch/PKGBUILDS#470]
First I want to clarify that I am completely newbie in using self-compiling wine versions. 
I'm trying to use wine-tkg to avoid the hud problems with Assetto Corsa. To configure the installation I use Lutris.

After a lot of problems, finally I could compile Wine-Tkg, and I used it as a custom executable in Lutris. The problem is taht when I execute Steam, it starts to load, show my login name and then crash. This is the Lutris Log:
```
Running /home/leo/.local/share/lutris/runners/wine/wine-tkg-staging-fsync-git-5.0.r16.gd83b9f53/bin/wine /home/leo/.local/share/lutris/runners/winesteam/prefix64/drive_c/Program Files (x86)/Steam/Steam.exe -no-cef-sandbox -console steam://open/games/details
wine: Read access denied for device L"\\??\\Z:\\", FS volume label and serial are not available.
info:  Game: Steam.exe
info:  DXVK: v1.5.2
info:  Built-in extension providers:
info:    Win32 WSI
info:    OpenVR
warn:  OpenVR: Failed to initialize OpenVR
wine: Call from 0x7bca46b9 to unimplemented function vulkan-1.dll.vkGetInstanceProcAddr, aborting
Waiting on children
Waiting on children
2020-01-29 11:21:32,072: Unable to read stat for process 15715
2020-01-29 11:21:32,073: Unable to read stat for process 15715
All children gone
Exit with returncode 1
```
Changing the wine executable to system, or another Lutris version, I don't have this problems. I'd like to know if I forgot anything to get Steam started. Can anyone help me?

NOTE: I found that if I deactivate DXVK, steam loads. I don't have this problem with other Lutris Wine versions

**Comment by Tk-Glitch** [comment]
It looks like your wine build lacks vulkan support. On what distro did you build wine-tkg?

**Comment by leillo1975** [comment]
Ubuntu 19.10.  I found that if I deactivate DXVK, steam loads. I don't have this problem with other Lutris Wine versions

**Comment by Tk-Glitch** [comment]
Yeah since your wine build lacks vulkan support, DXVK can't work. You'll need to rebuild and make sure you got `libvulkan-dev` and `libvulkan-dev:i386` packages installed beforehand.

https://github.com/Tk-Glitch/PKGBUILDS/wiki/wine-tkg-git#dependencies might help, even though I need to review the Debian/buntu part it should still be valid for the most part.

**Comment by leillo1975** [comment]
Thanks a lot, I will try it again.
In another term, Some days ago [I ask on Lutris forums for a TKG compilaton](https://forums.lutris.net/t/please-include-a-wine-tkg-with-assetto-corsa-fix-activated/8108) with the Assetto Corsa fix enabled, but nobody answered.

**Comment by Tk-Glitch** [comment]
I see. Ubuntu 19.10 should come with glibc 2.30 so I *guess* I can make a build on Arch that will work for you. Let's give it a try.

**Comment by Tk-Glitch** [comment]
https://drive.google.com/open?id=1vnwvBRBSMxOkSBWcIIT8xm5LFSqMExQz

Here you go. Not 100% sure it'll work on buntu but I think the chances are high.

**Comment by leillo1975** [comment]
> https://drive.google.com/open?id=1vnwvBRBSMxOkSBWcIIT8xm5LFSqMExQz
> 
> Here you go. Not 100% sure it'll work on buntu but I think the chances are high.

Thanks again. I will try it in a moment. 
About the lutris compilation, my intention was to modify the installer to use a Assetto Corsa patched version of TKG to avoid the hud problems, to facilitate the installation to game Linux users.

**Comment by Tk-Glitch** [comment]
I guess you could ask for the patch to be enabled by default. I'm not aware of a regression caused by it.
Assetto Corsa is still played by a good amount of people so @tannisroot might want to think about it.

**Comment by leillo1975** [comment]
I don't know if this is the bug that your Wine compilation fix or is another:
https://bugs.winehq.org/show_bug.cgi?id=46955

**Comment by Tk-Glitch** [comment]
It does look a lot like the issue the patch I'm providing fixes (by reverting the problematic commit). The last time I ran the game I got ~150fps @ 1080p max settings but that was with DXVK. Maybe there's a different regression case affecting wined3d here.

**Comment by Tk-Glitch** [comment]
Just ran it to check on 5.0r16. 113fps maxed out at 1440p on the pit screen, a bit more in race. Seems to be in line with the expected perf.
![Screenshot_20200129_123305](https://user-images.githubusercontent.com/741977/73353400-8f4c7600-4293-11ea-8317-3a5c71d501a3.png)

**Comment by leillo1975** [comment]
> https://drive.google.com/open?id=1vnwvBRBSMxOkSBWcIIT8xm5LFSqMExQz
> 
> Here you go. Not 100% sure it'll work on buntu but I think the chances are high.

Works great! Thanks a lot

As you say , this problem is probably related to Wined3d. I still waiting for your tests

**Comment by Tk-Glitch** [comment]
That new patch seems to perform similarly (ever so slightly slower) to reverting the offending commit. It's between 1 and 5 fps slower on my machine at first glance. Still much better than the current broken state upstream.

**Comment by leillo1975** [comment]
Ouch.... I made a mistake. This morning I told you that my system is 19.10 (in the PC that I was using in that moment was true).... but I didn't remember that my main computer has 18.04.3 .... Now I'm trying to build in this PC, because your build don't work here.

**Comment by Tk-Glitch** [comment]
Yeah that's expected sadly since 18.04.x has vastly outdated packages. One of my users was able to successfully build on 18.04 and they would be of much better help here than myself. I'll ping on our Discord.

**Comment by leillo1975** [comment]
Don't worry. Finally, after a lot of work , I could build it in my Ubuntu 18.04.3. If someone need it here it is:
https://mega.nz/#!9BRCUYrZ!iVe_bDR-9sQ8w0o0tQctPTBRJl5MWauO2f39u8sDMDg

Cheers!

**Comment by Tk-Glitch** [comment]
I'm glad! Tannisroot is definitely the one, and since I've pinged him above I'm pretty sure he'll get the message. Anyway, have fun! :)
