### ISSUE TITLE
Proton-TKG unimplemented function vcruntime140

### ISSUE THREAD

**Issue by jarrard** [Tk-Glitch/PKGBUILDS#473]
When building this new version for steam and using it to launch mod oganizer 2 I get the below repeating error. I'm not sure why it happens but its exclusive to proton-tkg.

wine: Call from 0x7b00fc1e to unimplemented function vcruntime140_1.dll.__CxxFrameHandler4, aborting

Here is my proton cfg file, I've turned some things on but have no idea why this would be occurring. Did a patch break something?

[proton-tkg.cfg.log](https://github.com/Tk-Glitch/PKGBUILDS/files/4137037/proton-tkg.cfg.log)

I built a RC4 previously without issue.

**Comment by Tk-Glitch** [comment]
You can try setting `_msvcrt_nativebuiltin="true"` in your .cfg, it'll probably fix it.

**Comment by jarrard** [comment]
I'll give it a shot.,

**Comment by Tk-Glitch** [comment]
@jarrard Did it actually fix your issue?

**Comment by jarrard** [comment]
I believe so, but also you can do this yourself easily with apps like lutris. Not a huge issue I guess.

**Comment by Bumbadawg** [comment]
Got this issue with lutris-5.2, which is supposed to include TKG patch. Cfg to native,builtin for msvcrt and vcruntime140 didn't solve this issue.

**Comment by Bumbadawg** [comment]
@Tk-Glitch Got this issue with lutris-5.2, which is supposed to include TKG patch. Cfg to native,builtin for msvcrt and vcruntime140 didn't solve this issue.

**Comment by Tk-Glitch** [comment]
@Bumbadawg You need to have Visual C++ 2015 redist (or 2017) installed in the prefix for this to have any effect. You can use winetricks to do so.
