### ISSUE TITLE
AC 4 Black Flag black screen

### ISSUE THREAD

**Issue by nicman23** [Tk-Glitch/PKGBUILDS#474]
I am that reddit user and i found it was not for borderless skyrim but for black flag !

https://bugs.winehq.org/show_bug.cgi?id=39731

works with:

```
diff --git a/dlls/user32/winpos.c b/dlls/user32/winpos.c
index 4b39d0aa393..6a283d6e5ae 100644
--- a/dlls/user32/winpos.c
+++ b/dlls/user32/winpos.c
@@ -1266,6 +1266,9 @@ BOOL WINAPI ShowWindow( HWND hwnd, INT cmd )
     if ((cmd == SW_HIDE) && !(GetWindowLongW( hwnd, GWL_STYLE ) & WS_VISIBLE))
         return FALSE;
 
+    if ((cmd == SW_SHOW) && (GetWindowLongW( hwnd, GWL_STYLE ) & WS_VISIBLE))
+        return TRUE;
+
     return SendMessageW( hwnd, WM_WINE_SHOWWINDOW, cmd, 0 );
 }
```

I think bf also requires the res4 patch but i am not sure

**Comment by Tk-Glitch** [comment]
Thanks to others noticing, that patch has been staged ages ago already.

**Comment by nicman23** [comment]
does that mean that it was in wine-staging?

**Comment by Tk-Glitch** [comment]
Yes, has been for three years 🐸 
https://github.com/wine-staging/wine-staging/blob/master/patches/user32-ShowWindow/0001-user32-ShowWindow-should-not-send-message-when-windo.patch

**Comment by nicman23** [comment]
huh i though default cfg was with staging, guess not

**Comment by Tk-Glitch** [comment]
It is, on both proton-tkg and wine-tkg-git.
