### ISSUE TITLE
[linux55-tkg] Is mc-llc supported on other schedulers than MuQSS?

### ISSUE THREAD

**Issue by ebiroud** [Tk-Glitch/PKGBUILDS#476]
Hello,

I've been thinking about recommendation of choosing mc-llc runqueue sharing for zen processors in customization.cfg. Short description in the customization.cfg (I mean "mc-llc"(for zen)) implies, at least for me, that it should work on any scheduler I pick, but isn't it supposed to work with MuQSS only? I'd like to clarify it since I haven't been using MuQSS and if it is still option for me on any other schedulers.

Thank you!

**Comment by Tk-Glitch** [comment]
BMQ has some kinda similar feature built-in, and PDS is usually faster than MuQSS in cases where mc-llc would make sense (at least as far as I was able to test), so I'm not sure what to think about that feature, but well it's there!

I have added a few notes that'll hopefully make it less confusing: https://github.com/Tk-Glitch/PKGBUILDS/commit/d878354b963ed03ec81c3ee8e6ab32ed02ed5324

**Comment by ebiroud** [comment]
Alfred implemented something to deal with Ryzens in the previous versions of BMQ, so I was a little confused if this setting actually has any effect and if it would affect it somehow. Well, now I know it doesn't at all. And yeah, my results of testings were quite the same.

Okay, those notes should do just fine, I think it is clear now. Closing. Thank you!
