### ISSUE TITLE
Can't build last 4.19 kernel commit

### ISSUE THREAD

**Issue by JDC2389** [Tk-Glitch/PKGBUILDS#48]
==> Starting build()...
make: *** empty string invalid as file name.  Stop.
==> ERROR: A failure occurred in build().
    Aborting...

real	0m0.041s
user	0m0.002s
sys	0m0.002s
removed '/home/carbon/PKGBUILDS/linux419-tkg/cpuschedset'
removed '/home/carbon/PKGBUILDS/linux419-tkg/src/cpuschedset'
  -> exit cleanup done

**Comment by Tk-Glitch** [comment]
Ok, so you're not having the MAKEFLAGS env var set. I didn't even know some people did that on Arch. Fix on its way.
