### ISSUE TITLE
wine-tkg-git, community-patches, error when applying patches:

### ISSUE THREAD

**Issue by ViNi-Arco** [Tk-Glitch/PKGBUILDS#484]
This is the error I have when applying these patches:

winex11-fs-no_above_state.mypatch:
![oie_CZC31wWeTgrg](https://user-images.githubusercontent.com/57958460/73999230-da752180-4942-11ea-8058-37c0d3983c78.png)

0001-wined3d-Support-SRGB-read-for-B5G6R5-textures.mypatch:
![oie_F96r7dlXKeNn](https://user-images.githubusercontent.com/57958460/73999242-dfd26c00-4942-11ea-9a74-58a276e6b16b.png)

**Comment by Tk-Glitch** [comment]
The Warhammer patch was merged upstream, and thus removed by the commit above.

Regarding `winex11-fs-no_above_state`, it applies fine as long as you respect its dependencies. It needs `_proton_fs_hack="true"`, which currently needs `_use_staging="true"`.

**Comment by ViNi-Arco** [comment]
Oh great, thanks Etienne  :heart:
