### ISSUE TITLE
[wine-tkg] osu! is crashing when starting beatmap

### ISSUE THREAD

**Issue by exstrim401** [Tk-Glitch/PKGBUILDS#487]
https://hastebin.com/teyojaraha

**Comment by Tk-Glitch** [comment]
I can't reproduce your issue. It works fine here. I installed it that way, keeping the default path:
`wget https://m1.ppy.sh/r/osu\!install.exe`
`WINEPREFIX="$HOME/.osu" wine 'osu!install.exe'`
`WINEPREFIX="$HOME/.osu" winetricks -q dotnet472`
`WINEPREFIX="$HOME/.osu" wine '$HOME/.osu/drive_c/users/tkg/Local Settings/Application Data/osu!/osu!.exe'`

If you haven't installed dotnet472 through winetricks (what I assume from your log), that should fix it.

**Comment by openglfreak** [comment]
Wait, osu! starts with Mono?

**Comment by exstrim401** [comment]
Works with dotnet472. Previously I was playing fine with dotnet45

**Comment by exstrim401** [comment]
It crashing even with dotnet472 if using custom skin

**Comment by exstrim401** [comment]
When starting logged in high chance to get another crash at start
Log from osu! window: https://pastebin.com/WaAUACTX
Terminal log: https://pastebin.com/XuY1Yg4K

**Comment by openglfreak** [comment]
Are you on the latest wine-staging?

**Comment by exstrim401** [comment]
> Are you on the latest wine-staging?

Just compiled latest wine-tkg. Crashes are still here

**Comment by openglfreak** [comment]
Could you try again with commit b9307cfa61e9884b01d34c2310ec1ffbb1868728 reverted?

**Comment by exstrim401** [comment]
> Could you try again with commit b9307cfa61e9884b01d34c2310ec1ffbb1868728 reverted?

Crashes on start are disappeared but not when starting beatmap with custom skin

**Comment by openglfreak** [comment]
Can you get a new log with a custom skin?

**Comment by exstrim401** [comment]
> Can you get a new log with a custom skin?

https://pastebin.com/xdE3YNAm

**Comment by Tk-Glitch** [comment]
You could try installing native gdiplus and corefonts through winetricks, and maybe give the `WINE_LARGE_ADDRESS_AWARE=1` env var a try.

**Comment by openglfreak** [comment]
You could also try with a 64-bit wineprefix.
For some reason everyone thinks you need a 32-bit prefix even though that hasn't been the case for years.

**Comment by exstrim401** [comment]
> You could try installing native gdiplus and corefonts through winetricks, and maybe give the `WINE_LARGE_ADDRESS_AWARE=1` env var a try.

Same with native gdiplus and corefonts. With `WINE_LARGE_ADDRESS_AWARE=1` osu! is not crashing but in infinite loading with same error

**Comment by exstrim401** [comment]
> You could also try with a 64-bit wineprefix.
> For some reason everyone thinks you need a 32-bit prefix even though that hasn't been the case for years.

Same with 64 bit prefix

**Comment by exstrim401** [comment]
Works with wine from arch repo without staging patches

**Comment by Tk-Glitch** [comment]
inb4 mingw bug
