### ISSUE TITLE
Proton-TKG fails to build after Proton 5.0 update

### ISSUE THREAD

**Issue by ronoverdrive** [Tk-Glitch/PKGBUILDS#488]
==> Starting pkgver()...
==> Removing existing $pkgdir/ directory...
==> Starting build()...
  -> Building Wine-64...
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking whether make sets $(MAKE)... yes
checking for gcc... gcc
checking whether the C compiler works... no
configure: error: in /home/ronoverdrive/PKGBUILDS/wine-tkg-git/src/proton_dist-64-build:
configure: error: C compiler cannot create executables
See config.log for more details
==> ERROR: A failure occurred in build().
    Aborting...
  -> Removed BIG_UGLY_FROGMINER - Ribbit
  -> Removed Proton-tkg token - Valve Ribbit
  -> exit cleanup done
The required initial proton_dist build is missing! Wine-tkg-git compilation may have failed.

[proton-tkg.cfg.txt](https://github.com/Tk-Glitch/PKGBUILDS/files/4174697/proton-tkg.cfg.txt)

[config.log](https://github.com/Tk-Glitch/PKGBUILDS/files/4174710/config.log)

The config.log is from the directory it claims is missing too which is empty aside from the log.

**Comment by Tk-Glitch** [comment]
`_GCC_FLAGS="-march=native -mtune=native-pipe -O2 -ftree-vectorize"` is incorrect.
I assume you want `-march=native -mtune=native -pipe -O2 -ftree-vectorize`

**Comment by ronoverdrive** [comment]
*face palms* god I feel stupid to not notice that, I need more coffee xD
