### ISSUE TITLE
Nvidia with _PRIME_render_offload="true" can't build

### ISSUE THREAD

**Issue by ANISANi** [Tk-Glitch/PKGBUILDS#492]
if I set _PRIME_render_offload="true" in customization.cfg and get this error:
[...]
==> Starting package_nvidia-utils-tkg()...
sed: -e expression #1, char 29: unterminated `s' command
==> ERROR: A failure occurred in package_nvidia-utils-tkg().
    Aborting...
[...]
I try with: 440.59, dkms.

**Comment by ANISANi** [comment]
It don't help me:

==> Starting package_nvidia-utils-tkg()...
sed: -e expression #1, char 30: unknown option to `s'
==> ERROR: A failure occurred in package_nvidia-utils-tkg().

But I find how fix it. In PKGBUILD I change:
from :  sed -i '**s**/Option "PrimaryGPU" "yes"**/**/d' "$srcdir"/10-nvidia-drm-outputclass.conf
to: sed -i '/Option "PrimaryGPU" "yes"/d' "$srcdir"/10-nvidia-drm-outputclass.conf 

And all wolked (tested with benchmark Sadow of tomb raider (gtx 1060 (mobile)) ).

**Comment by Tk-Glitch** [comment]
Sorry, I shouldn't try to fix stuff when I'm distracted 🐸
