### ISSUE TITLE
Can't compile nvidia-all

### ISSUE THREAD

**Issue by ANISANi** [Tk-Glitch/PKGBUILDS#495]
I get 
[...]
  -> Selected driver integrity check behavior (md5sum or SKIP): d342eb15715551cdd48c615026dca045
/home/anisan/compile/PKGBUILDS/nvidia-all/PKGBUILD: line 262: syntax error near unexpected token `fi'
/home/anisan/compile/PKGBUILDS/nvidia-all/PKGBUILD: line 262: `    fi'
==> ERROR: Failed to source /home/anisan/compile/PKGBUILDS/nvidia-all/PKGBUILD
[...]

in line 260 after then need space:
from:   if [[ $pkgver = 440.58.01 ]]; the**n#** 440.58.01 Unfrogging
to:   if [[ $pkgver = 440.58.01 ]]; then # 440.58.01 Unfrogging

**Comment by ViNi-Arco** [comment]
Hi, The same thing happens to me:

![oie_dXnr9gwz8wr5](https://user-images.githubusercontent.com/57958460/74612158-8e17a780-50e1-11ea-9a2c-26a6a935eb6f.png)

**Comment by ViNi-Arco** [comment]
There is no such problem here:

https://github.com/Tk-Glitch/PKGBUILDS/tree/9eadc734f288ae601e0651dd60a391fea79f1874
