### ISSUE TITLE
MostlyPortable-GCC: unable to complete, error occurs, using Mingw/GCC git

### ISSUE THREAD

**Issue by ViNi-Arco** [Tk-Glitch/PKGBUILDS#496]
Hello Etienne, good afternoon, The only modification I made was to change: _use_gcc_git to "true" and _gcc_version = to "gcc-8" in "mostlyportable-mingw.cfg", and these errors occur:

![oie_Phm8x44eu2ag](https://user-images.githubusercontent.com/57958460/74611417-6bce5b80-50da-11ea-9c37-b8f5cc121bba.png)

I tried to change the _valve_patches = to "false", hoping to be able to solve the previous problem and get this:

![oie_2rWkxojY3kPa](https://user-images.githubusercontent.com/57958460/74611462-d41d3d00-50da-11ea-817d-7e915b47d50f.png)

I tried downloading "binutils-0001.patch" and "binutils-0002.patch", placing them inside "mostlyportable-gcc / build / proton_binutils", and an error occurs as well :disappointed:

**Comment by Tk-Glitch** [comment]
Hello ViNi-Arco,
From those logs, configure can't find your system-wide GCC install. Is GCC installed? Yes you need GCC (or a compatible C compiler, at least) to compile GCC 🐸 
The valve patch error is non critical and can be ignored (I guess I should silence that).

Also, for GCC8 the actual branch name is `releases/gcc-8` and not just `gcc-8`.

**Comment by ViNi-Arco** [comment]
Hmm, I don't have gcc installed :grimacing: :, that was the reason for the error :confused:, I will use releases/gcc-8 now and install GCC, thank you very much Etienne :relaxed: have a good night.

**Comment by ViNi-Arco** [comment]
Hi Etienne, so... in parts installing GCC and using the branch name correctly solved the initial problem, but this is happening now:

![oie_2GD99W6avF8o](https://user-images.githubusercontent.com/57958460/74646157-0de05900-5158-11ea-8a25-68f9d9cbf979.png)

![oie_M5dTpncIWJHd](https://user-images.githubusercontent.com/57958460/74646170-146ed080-5158-11ea-91ef-2d8354519466.png)

Strange, he is accusing "There is no space available on the device", more free space on the PC :confused:

**Comment by ViNi-Arco** [comment]
So I managed to solve the problem with "There is no space available on the device" by changing _dstdir = to another directory, but this happens:

![oie_AUIAuI7GTVEp](https://user-images.githubusercontent.com/57958460/74679942-fb890e00-519d-11ea-97ca-ce28807706cb.png)

I don't know what else to do :disappointed:

**Comment by Tk-Glitch** [comment]
Please give it another try with the recent changes I made. I'll try to reproduce your issue on my end with GCC 8 tomorrow.

**Comment by ViNi-Arco** [comment]
Etienne had a breakthrough here, I used 'MostlyPortable' with his latest modifications, and he is now able to download and apply the patches, "proton_binutils1.binutilspatch" "proton_binutils2.binutilspatch", which I couldn't before, but errors still occur:

![oie_vgevlK7Gr8g4](https://user-images.githubusercontent.com/57958460/74754608-a2c67d80-5250-11ea-9a73-7db506261b64.png)

![oie_7kESSdlVZDP0](https://user-images.githubusercontent.com/57958460/74754619-a8bc5e80-5250-11ea-936a-77a37a091f77.png)

**Comment by Tk-Glitch** [comment]
I was able to reproduce the issue with GCC 8.3. I think it's libc related. Using older mingw or binutils doesn't help. Is there a specific reason for you to want 8.3? Bringing a local libc would be a real pita.

**Comment by ViNi-Arco** [comment]
Good morning Etienne, sorry for the delay I was very busy and didn't have time to work on the PC, so the problem is with GCC8 and the possible culprit is libc? what a complicated case, the reason I want to use GCC8 is because of its stability and I had good results when I used it to compile my Kernels in the past, I don’t even know how to thank you for taking some of your time to test this problem that I’m going through with GCC8, thank you very much, I will try the Master branch if there is no way to use GCC8 for now, I hope that the Master branch is as good as GCC8.

**Comment by Tk-Glitch** [comment]
No worries!
Master branch might still be in a bit of a rough shape. If you got a Ryzen CPU, 9.1.0 or 9.2.1 should be fine (9.2.0 has a zen specific bug).
I'm still exploring ways that could allow us to workaround the issue.

**Comment by ViNi-Arco** [comment]
Great, I will try GCC9, if it works I will inform you, it is good to be able to count on you.

**Comment by ViNi-Arco** [comment]
It worked Etienne !! using MostlyPortable with its latest modifications with GCC9 it was possible to conclude, I even tested it by compiling DXVK and compiled it perfectly, you are the greatest.

Here I copied from the terminal, for you to follow how the finalization process took place:
[GccMingw.txt](https://github.com/Tk-Glitch/PKGBUILDS/files/4231554/GccMingw.txt)

**Comment by Tk-Glitch** [comment]
Would still be cool to be able to build GCC8 again, but it seems it'll be pretty annoying to fix 🐸

**Comment by ViNi-Arco** [comment]
Good night Etienne, how are you ?, it's sad that GCC8 doesn't work, I tested GCC10 and it works perfect, look at me compiling DXVK with GCC10:

![oie_KgCRZeIRIl15](https://user-images.githubusercontent.com/57958460/75123602-ab231c00-5687-11ea-8ef3-358e5d067e92.png)

I hope that GCC8 will work in the future, as it is a version that works very well. I'm using GCC9.2.1 to compile the Kernel and GCC10 to compile everything, it has been proving very stable.

**Comment by Tk-Glitch** [comment]
GCC10 still has a few issues but as long as you're not using it to build your kernel it should be fine. I have a couple ideas to bring GCC8 back but it'll take time.

**Comment by ViNi-Arco** [comment]
Great news :heart_eyes:, but don't feel pressured, do everything in your time, have a good time Etienne :wink:
