### ISSUE TITLE
[mesa-tkg-git] 32bit radeonsi library causes crashes on multiple applications 

### ISSUE THREAD

**Issue by BlazeKl** [Tk-Glitch/PKGBUILDS#499]
When using mesa-tkg-git's lib32 package, most 32bit OpenGL applications stop working

Steam
`Program received signal SIGILL, Illegal instruction.`
`0xf5f8ce30 in ?? () from /usr/lib32/dri/radeonsi_dri.so`

PCSX2
`[1]    98273 illegal hardware instruction (core dumped)`

lib32-mesa-git from AUR doesn't have this issue

[customization.cfg](https://gist.github.com/BlazeKl/d0f67e9ebdc604422d19f7cd6e400579)

EDIT: using default customization.cfg doesn't seem to make a difference

**Comment by Tk-Glitch** [comment]
https://gitlab.freedesktop.org/mesa/mesa/issues/2526

**Comment by BlazeKl** [comment]
removing swr gallium drivers from the customization.cfg fixed the 32 bit libraries

**Comment by Tk-Glitch** [comment]
No such issue on my system, I don't know what to tell you 🤷‍

**Comment by BlazeKl** [comment]
I don't know why it makes a difference but it's very consistent here

**Comment by Tk-Glitch** [comment]
This seems related: https://gitlab.freedesktop.org/mesa/mesa/-/commit/382b902a6db87a2b0409b760c320555d1f4eadca

Using some exotic LLVM package maybe?

**Comment by BlazeKl** [comment]
using stable LLVM from arch packages, compiling with swr still broke 32bit libs tho, maybe I'm missing some dependency

**Comment by Tk-Glitch** [comment]
Is it still an issue? We have hundreds other users with no issue, including myself. Since this is/was an upstream problem, it's worth a recheck.

**Comment by BlazeKl** [comment]
srry for not looking into this earlier, tested it again now and it is working properly

**Comment by Tk-Glitch** [comment]
Thank you!
