### ISSUE TITLE
The elder scrolls online steam launcher crash

### ISSUE THREAD

**Issue by shpinog** [Tk-Glitch/PKGBUILDS#5]
How I`m can run this? Work on lutris + wine (3.12\3.13), but if compiling with this pkbuild steam work fine .Teso launcher crash without any errors or launcher work but "Play"button does not launch the game.

**Comment by Tk-Glitch** [comment]
I don't have TESO so I probably won't be able to help much without logs, but you can try a few things.

Did you modify the customization.cfg file or did you use the default config?
TESO launcher might require one of the staging patch that needs to be disabled for esync to work. You can try to set "use_esync" to false and rebuild. If that works, TESO is probably not yet functional with esync.

**Comment by shpinog** [comment]
I`m try switch gcc to clang(not effect) and off "GAME-SPECIFIC" patches(not effect). 
Now I'm trying to compile without esync. But if um set "WINEESYNC" env to 0 it does not help either

**Comment by shpinog** [comment]
https://youtu.be/z0EFO6vJHDk

**Comment by Tk-Glitch** [comment]
Currently WINEESYNC env variable value actually doesn't have an effect. "WINEESYNC=0" enables esync like "WINEESYNC=1". To disable esync you need to remove the variable altogether.

That video doesn't help. If you can get me wine output from command prompt I may be able to help more.

**Comment by shpinog** [comment]
I`m build this without esync, and this work for me. But only when use gcc, if use clang this does not working. Sorry for my english.

**Comment by Tk-Glitch** [comment]
GCC is the recommended compiler anyway :D

**Comment by Tk-Glitch** [comment]
@shpinog Your issue with esync enabled should now be resolved.
