### ISSUE TITLE
Can't compile wine-tkg-git

### ISSUE THREAD

**Issue by steamp0rt** [Tk-Glitch/PKGBUILDS#502]
Using the mostlyportable MinGW, latest master as of now (https://github.com/Tk-Glitch/PKGBUILDS/commit/16269feb6e610aaa7e1cb5a3f7c71a939a288d29) , latest packages on Arch Linux as of now.

Personal config:
```
_plasma_systray_fix="true"
CUSTOM_MINGW_PATH="/home/dragon/Code/AUR/PKGBUILDS/mostlyportable-gcc/mingw-mostlyportable-9.2.0"

```

Output log (of `makepkg -si`): https://paste.ee/p/pZ1ZO

**Comment by Tk-Glitch** [comment]
Thanks, interesting output for sure.

**Comment by ronoverdrive** [comment]
I've encountered this same bug, the work around I've found is to also have mostlyportable-gcc built and set to the CUSTOM_GCC_PATH as well as the MinGW.

**Comment by steamp0rt** [comment]
@ronoverdrive Didn't seem to work. I even tried clearing `pkg`/`src`.

**Comment by Tk-Glitch** [comment]
https://github.com/Tk-Glitch/PKGBUILDS/commit/74711b1d54860e7f934ee404710825fffb06e78c should have fixed this
