### ISSUE TITLE
nvidia-dkms with updated 5.6 rc3 PKGBUILD fails to compile on 5.6 rc3 kernel

### ISSUE THREAD

**Issue by muncrief** [Tk-Glitch/PKGBUILDS#504]
I just pulled the latest git and saw a nvidia-all PKGBUILD change for kernel 5.6 rc3, so I went ahead and compiled Kernel 5.6 rc3, and then then did a clean build of nvidia-all with the dkms and driver 440.58.02 options. Unfortunately the dkms module fails to build for kernel 5.6 rc3. I've attached the failed build log below.

[nvidia-dkms.bad.log](https://github.com/Tk-Glitch/PKGBUILDS/files/4243083/nvidia-dkms.bad.log)

**Comment by Tk-Glitch** [comment]
The nvidia-all PKGBUILD wasn't yet updated for rc3, only up to rc2 as of yet. Thanks for your feedback.
