### ISSUE TITLE
Kvm device passthrough with avic broken on 5.6 rc1 through rc3. Here's the patch.

### ISSUE THREAD

**Issue by muncrief** [Tk-Glitch/PKGBUILDS#507]
I just wanted to let you know that kvm avic with passthrough has been broken on AMD systems in kernel 5.6. I worked with the developers over the last few days and we came up with a simple patch that fixes it. You can find it at https://bugzilla.kernel.org/show_bug.cgi?id=206579.

And thank you for all your hard work. Your packages are awesome!
Mitch Muncrief

**Comment by Tk-Glitch** [comment]
Thank you for the heads up and kind words! I'm glad you like them :)
