### ISSUE TITLE
Wine location in menus is wrong

### ISSUE THREAD

**Issue by andrebadaia** [Tk-Glitch/PKGBUILDS#510]
Hi Tk! I am trying to compile wine-tkg on Linux Mint 19.3 and put the files in "/opt/wine-tkg-git" directory, with /opt/wine-stable, /opt/wine-staging and /opt/wine-devel. However, when I install some application, the path does not seem correctly, and the executable does not open. Take a look:

env WINEPREFIX="/media/GAMES/winetest" /home/wineuser/PKGBUILDS/wine-tkg-git/wine-tkg-staging-fsync-git-5.3.r5.g59fe96c1/bin/wine C:\\windows\\command\\start.exe /Unix /media/GAMES/winetest/dosdevices/c:/ProgramData/Microsoft/Windows/Start\ Menu/Programs/nGlide/nGlide\ Configurator.lnk

I set the variables in customization.cfg:

_EXTERNAL_INSTALL="true"
_DEFAULT_EXTERNAL_PATH="/opt"
_EXTERNAL_NOVER="true"

How to fix that? Thanks for helping!!!

**Comment by Tk-Glitch** [comment]
Hello andrebadaia,

Builds not made with makepkg won't make use of that specific path option. You'll want to look at `_nomakepkg_prefix_path` instead.
```
# Set to the desired installation path for your build(s). A versioned dir containing your build will be created inside that target.
# Example: _nomakepkg_prefix_path="/home/frog" will install your build in /home/frog/wine-tkg-********
_nomakepkg_prefix_path=""
```

That being said, your command doesn't look right.
`/home/wineuser/PKGBUILDS/wine-tkg-git/wine-tkg-staging-fsync-git-5.3.r5.g59fe96c1/bin/wine` is unlikely to be the wine path you want to use since you said you put your builds in `/opt/wine*`

That `C:\windows\command\start.exe /Unix /media/GAMES/winetest/dosdevices/c:/ProgramData/Microsoft/Windows/Start\ Menu/Programs/nGlide/nGlide\ Configurator.lnk` path also looks weird, but if that usually works, well 🐸 

Anyway thank you for pointing that out as it's not really obvious that part of these options are only working for makepkg builds.

**Comment by andrebadaia** [comment]
Hi! Yes, your suggestion worked, but it's not ideal yet. I set _nomakepkg_prefix_path="/opt", but I want to personalize this path, to use /opt/wine-tkg (or /opt/wine-tkg-git as I mentioned before), without "versioning". A variable that sets this path would be interesting.
 I also had to run non.makepkg-build.sh as root to access /opt. 

I'am trying that because I want to create a deb package of it, to make the installation easily. For the compilation, it would be easier to make that if you put a flag to non-installation and choose a destination directory. So I can copy the compiled files to correct path.

env WINEPREFIX="/media/GAMES/winetest" /opt/wine-tkg-staging-fsync-git-5.3.r5.g59fe96c1/bin/wine C:\\windows\\command\\start.exe /Unix /media/GAMES/winetest/dosdevices/c:/ProgramData/Microsoft/Windows/Start\ Menu/Programs/nGlide/nGlide\ Configurator.lnk

So, I will check the source code to find these issues, and then, helping you to support non-arch users.

Thanks for helping!

**Comment by Tk-Glitch** [comment]
We have a similar "no-install" option for proton-tkg so yeah I guess that would make sense especially for non-makepkg builds. I'll also have a look at the naming. I don't remember exactly why the `_EXTERNAL_NOVER` option was ignored for non-makepkg, I'll also look into it.

Thanks!

**Comment by andrebadaia** [comment]
I have checked the code, and I found the variable "_PKGNAME_OVERRIDE", that is controllable on customization.cfg file. When I put "none" on it, the installation folder comes to "/opt/wine-tkg-git-5.3.r5.g59fe96c1/". 

It takes the variable "pkgname" and add the "pkgver" on line 180 of non-makepkg-build.sh, and sets the destination folder in the local variable "_prefix". It's also set in "build.sh" on the same way, on line 125 (function _package_nomakepkg()). 

The EXTERNAL_INSTALL is always false in no-proton builds, because the line 68 of non-makepkg-build.sh. Maybe is a good place to change the behavior.

I suggest an option to set pkgname directly (as a static constant, not changeable). What do you think?

**Comment by andrebadaia** [comment]
I had tested here, and it works, just avoiding the pkgver variable.

**Comment by Tk-Glitch** [comment]
I suppose that should cover your needs.

**Comment by andrebadaia** [comment]
Sorry, I was not following the conversation lately... Thanks for the effort! Is it already working?

**Comment by Tk-Glitch** [comment]
Supposedly for the last 27 days, yeah :D

**Comment by andrebadaia** [comment]
Yes, I had to change all my schedule because the coronavirus... I just didn't have time to work with wine-tkg... Anyway, when I downloaded the last version of that, I realize that is different... The folder changes (now is wine-tkg/wine-tkg) and the configuration file is shorter than the last one. I couldn't find the nomakepkg_nover variable that you mentioned...

**Comment by Tk-Glitch** [comment]
Yeah, the configuration file has been split since the last time. You'll now found that option in `wine-tkg-profiles/advanced-customization.cfg` :)
```
##
##   This config file contain the basic settings of your build.
##   For deeper configuration, see wine-tkg-profiles/advanced-customization.cfg
##
```

**Comment by Tk-Glitch** [comment]
Just noticed a typo while copy/pasting 🐸

**Comment by andrebadaia** [comment]
Ok, I will check! Thanks a lot!

**Comment by Tk-Glitch** [comment]
I guess we're all good here by now :)

**Comment by andrebadaia** [comment]
Thanks a lot! :)
