### ISSUE TITLE
[proton-tkg] Build fails with "fatal error: wine/list.h: No such file or directory"

### ISSUE THREAD

**Issue by Nocifer** [Tk-Glitch/PKGBUILDS#513]
Title says all, here is the complete error:

```
steamclient_main.c:13:10: fatal error: wine/list.h: No such file or directory
   13 | #include "wine/list.h"
      |          ^~~~~~~~~~~~~
compilation terminated.
```

**Comment by Tk-Glitch** [comment]
I'll need more detail than that, since that error means your wine source tree either doesn't contain the file (unlikely), or isn't found at the expected emplacement.

Wine version? PKGBUILD or proton-tkg.sh? If it's with the PKGBUILD, do you have any non-standard makepkg.conf settings?

**Comment by Nocifer** [comment]
Yeah, sorry, I considered those as a given. Wine version is the latest commit, along with wine-staging, both downloaded automatically through proton-tkg.sh. Some options in proton-tkg.cfg have been changed from their defaults, though the exact same changes haven't been a problem up until today (last time I built the package was some 4-5 days ago). But just in case, I tried to build with the default configuration and it failed again.

Here's a build log: [build.tar.gz](https://github.com/Tk-Glitch/PKGBUILDS/files/4302196/build.tar.gz)

**Comment by Tk-Glitch** [comment]
Thanks!

**Comment by Tk-Glitch** [comment]
Please check if that change fixes it. Thanks!

**Comment by Nocifer** [comment]
Yep, this fixes the issue. Thanks!

And since I got your attention, a quick but completely irrelevant question: has the option for building and bundling dxvk along with wine been removed from wine-tkg-git's configuration options, or am I missing something?

**Comment by Tk-Glitch** [comment]
Yes it has. The winelib DXVK/D9VK builds were broken enough and unsupported enough for me to stop offering them as an option. People were posting issues on Philip and Josh's trackers that were only due to winelib, creating undesirable and time consuming noise.

**Comment by Nocifer** [comment]
Ah, I see. Alright then, I'll stick to using the symlinked dll's. Thanks again!

**Comment by Tk-Glitch** [comment]
You're welcome, have fun! :)
