### ISSUE TITLE
[Feature Request - Proton-tkg] Add Userpatch to Fix NieR:Automata Crash

### ISSUE THREAD

**Issue by sonic2kk** [Tk-Glitch/PKGBUILDS#519]
Hi there,

I was hoping we could add a patch from a PR made by `yuiiio` [here](https://github.com/ValveSoftware/wine/pull/83). It fixes a crash with "NieR:Automata" that has been present since 4.11-9 for me, and from 4.2-9 and up for a handful of users. It originated from [this issue](https://github.com/ValveSoftware/Proton/issues/2929) which I've been following for quite some time, and allegedly also fixes "Sekiro: Shadows Die Twice" and "DARK SOULS III". I can't personally vouch for these games, but I know it fixes NieR:Automata.

I tested with Proton-tkg based on Wine 5.4 and it fixes the issue. If it can't be brought in that's okay,but I thought I should bring it to the attention of more people.

Thanks!

**Comment by Tk-Glitch** [comment]
Thanks for the suggestion, I'll add the patch.
