### ISSUE TITLE
Make mkinitcpio or dracut dependencies

### ISSUE THREAD

**Issue by Bl4cKn1gh7** [Tk-Glitch/PKGBUILDS#523]
According to the arch [mailing list](https://lists.archlinux.org/pipermail/arch-dev-public/2019-May/029570.html), mkinitcpio will eventually be replaced with dracut. In the meantime, while testing and installing linux55-tkg using dracut, it still depends on mkinitcpio, even though it works fine with dracut.

Actually, upon looking at other kernel packages on the AUR, making initramfs a dependency should fix the issue.

**Comment by Valmar33** [comment]
Um.... you do realize that post is from May 21st 2019?

No progress has been made, since then... seemingly.

**Comment by Bl4cKn1gh7** [comment]
Yeah, that's true. it was just a little odd on how all the other kernel packages don't care if you use mkinitcpio or not but this one required it is all.
