### ISSUE TITLE
Josh's VK patches no longer apply to mesa git

### ISSUE THREAD

**Issue by random2324** [Tk-Glitch/PKGBUILDS#525]
VK_JOSH_depth_bias_info_header.mymesapatch
VK_JOSH_depth_bias_info_radv.mymesapatch
Do you want to install it/them? - Be careful with that ;)
> N/y : y
  -> ######################################################
  -> 
  -> Applying your own mesa patch /home/greg/Source/debug_builds/PKGBUILDS/mesa-git/VK_JOSH_depth_bias_info_header.mymesapatch
  -> 
  -> ######################################################
patching file include/vulkan/vulkan_core.h
Hunk #1 succeeded at 560 (offset 49 lines).
Hunk #2 succeeded at 10723 with fuzz 2 (offset 1165 lines).
patching file src/vulkan/registry/vk.xml
Hunk #1 succeeded at 12461 with fuzz 1 (offset 1275 lines).
  -> ######################################################
  -> 
  -> Applying your own mesa patch /home/greg/Source/debug_builds/PKGBUILDS/mesa-git/VK_JOSH_depth_bias_info_radv.mymesapatch
  -> 
  -> ######################################################
patching file src/amd/vulkan/radv_cmd_buffer.c
Hunk #1 succeeded at 1321 (offset 97 lines).
Hunk #2 succeeded at 1593 with fuzz 2 (offset 117 lines).
patching file src/amd/vulkan/radv_device.c
Hunk #1 succeeded at 1298 with fuzz 1 (offset 310 lines).
patching file src/amd/vulkan/radv_extensions.py
Hunk #1 FAILED at 145.
1 out of 1 hunk FAILED -- saving rejects to file src/amd/vulkan/radv_extensions.py.rej
patching file src/amd/vulkan/radv_pipeline.c
Hunk #1 succeeded at 5090 (offset 775 lines).
patching file src/amd/vulkan/radv_private.h
Hunk #1 succeeded at 1631 with fuzz 1 (offset 179 lines).

**Comment by random2324** [comment]
Thank you for your fantastic work!

**Comment by Tk-Glitch** [comment]
You're welcome!
