### ISSUE TITLE
[linux56-rc-tkg] Newest release-candidate (rc7) is broken (kernel panic)

### ISSUE THREAD

**Issue by gardotd426** [Tk-Glitch/PKGBUILDS#526]
I've installed every single release candidate of kernel 5.6 with your PKGBUILD, and until today they all worked perfectly fine. However now, after updating to the 5.6-rc7 release candidate, it's broken and fails to boot:
![IMG_20200323_070335805](https://user-images.githubusercontent.com/54234607/77311081-db38fb80-6cd5-11ea-88cf-853389bbc014.jpg)

I've tried this with other rc7 builds, and with a clean `git clone`. I've not done anything funky to the options, and not added any weird patches or anything. Happy to provide anything you need.

**Comment by Tk-Glitch** [comment]
Well, no init is definitely going to break 🐸 
I'm surprised you weren't triggered by some unusual installation failure. No modprobed-db? A log of the package installation might tell more.

![Screenshot_20200323_122553](https://user-images.githubusercontent.com/741977/77312053-86ab7580-6d01-11ea-8663-93afb2c61967.png)

**Comment by gardotd426** [comment]
No, I don't use modprobed-db. Super weird. How should I get a log? Just
makepkg > tkglog.txt?

**Comment by Tk-Glitch** [comment]
The initramfs building is triggered on installation, so you can either do `makepkg -i` or `pacman -U package.name.tar.xz`. `> tkglog.txt` would be enough, yeah.

**Comment by Tk-Glitch** [comment]
Also, have you tried running `sudo mkinitcpio -P` directly?

**Comment by gardotd426** [comment]
I have no idea what's going on. I did a fresh install of ArcoLinux on an
extra partition, booted into it, updated, installed all my stuffs, then
installed the new tkg kernel, and it booted right the hell up. I'm
currently trying to figure out why it might not be working on Manjaro. I've
already checked to make sure I didn't unknowingly run out of space on
anything (as that was the first solution I came across whilst searching),
and that's not it, I'm like 3 percent full on /boot/efi and only about 35
percent full on /. I'll try manually running mkinitcpio and then get you a
log.

**Comment by ronoverdrive** [comment]
The problem is probably Manjaro. Of all the Arch-likes, Manjaro always gave me the most headaches when installing anything 3rd party kernel related because of how they package things relating to drivers. Arco is like what Antergos used to be: Arch with an easy installer and an extra repo or two with some packages normally you'd have to get from the AUR. Personally I recommend sticking to Arco.

**Comment by gardotd426** [comment]
I usually run two distros, that way I can just hop over to the other one if whichever one I'm using at the time gives me trouble, without having to drop everything and spend all day troubleshooting or restoring snapshots or reinstalling, etc. I usually just run vanilla Arch and Manjaro, but the past month or so I've been running Arco with Manjaro, which I'd run Arco before on my laptop, but yeah that's exactly why I like Arco, it's Arch with an easy installer and their own "community repository" like chaotic-aur. 

I do love Manjaro's tools though, like MHWD, the chroot shell, bauh (which yeah, you can get on Arco and Arch, but still), etc. But yeah, I've just been using Arco since this issue came up, I restored a snapshot on Manjaro from a couple days ago (but from within Arco, so I haven't like booted into Manjaro again since I did that) so I plan to try and reinstall the kernel on the restored Manjaro just to see if something got frogged with my install for some reason, and I'll try and figure out (or if nothing else, help you figure out lol) what's going on in case anyone else has this issue. It's just weird because I've always used your kernels (with the same configs and stuff) with Manjaro and never had an issue. But yeah, they do customize Arch a lot over at Manjaro. Which I think is great, it's a fantastic distribution and (IMHO) the first truly great gaming desktop Linux distro for average users or beginners, but I guess I'm starting to get to where I want to do things that either vanilla Arch or Arco is better suited for.

**Comment by gardotd426** [comment]
Yeah it works with after restoring a snapshot and then reinstalling the
kernel (that had already been built, I have a separate /home partition
where I built it so that was unaffected by restoring said snapshot). Seems
something had been frogged in my Manjaro installation. Now if I could only
get AMD to fix these damn Navi crashes that are still terrible for me I'd
be all set! I'm replying via email but you can go ahead and close this
issue if you like.

**Comment by Tk-Glitch** [comment]
I admit it's a bit worrying. Let's hope it'll stay a rare case.
