### ISSUE TITLE
WINE-TkG fails to patch

### ISSUE THREAD

**Issue by ronoverdrive** [Tk-Glitch/PKGBUILDS#528]
`patching file dlls/kernel32/tests/process.c
Hunk #1 FAILED at 2543.
Hunk #2 succeeded at 2763 (offset 116 lines).
1 out of 2 hunks FAILED -- saving rejects to file dlls/kernel32/tests/process.c.rej
`

This is where it fails and does so before any community patches get applied. Most likely something got upstreamed.

**Comment by Tk-Glitch** [comment]
Fixed by https://github.com/Tk-Glitch/PKGBUILDS/commit/3ec721dc0d47a008de87b7848c00b3a4f98029b7
