### ISSUE TITLE
SW_JFO_steam.mypatch broken

### ISSUE THREAD

**Issue by ronoverdrive** [Tk-Glitch/PKGBUILDS#529]
Its either been up-streamed or needs a rebase. Fails to patch against latest git.

**Comment by Tk-Glitch** [comment]
Oh yeah that's part of the _protonify switch now, I'll nuke it from community patches.

**Comment by Tk-Glitch** [comment]
It's gone 🐸 
https://github.com/Tk-Glitch/PKGBUILDS/commit/992dd771d823896a6fce20c8a0650755a2803828
