### ISSUE TITLE
Patch suggestion for WIne systray bug (affects at least steam on kde)

### ISSUE THREAD

**Issue by clapbr** [Tk-Glitch/PKGBUILDS#53]
Discussion: https://www.reddit.com/r/wine_gaming/comments/9y3lpk/wine_steam_on_kde_plasma_no_systray_menu/
A kind soul on reddit (bobywya) provided a neat rebased patch that fixes the issue. https://bugs.winehq.org/attachment.cgi?id=62815
I tested the patch and it fixes the issue to a great extent altough not perfectly (it shows the systray menu but not in the right place, it shows somewhere inside steam window) but still better than no menu at all and having to kill wine every time. 

If it somehow breaks things for other cases than kde put it behind an optional flag.

**Comment by Tk-Glitch** [comment]
Built, tested, added. Thanks for the suggestion :)
