### ISSUE TITLE
Patch for supporting certain code protection systems

### ISSUE THREAD

**Issue by qsniyg** [Tk-Glitch/PKGBUILDS#532]
Due to a patch apply failure (because of my darned email server stripping whitespaces - and of course it force-inlines the attached patch file and subsequently strips its whitespace because why would it not...) it got rejected. I'm sending this in here then for the moment, but it'll (hopefully) get in in the next release upstream haha :)

https://source.winehq.org/patches/data/182063

It's needed for a number of DLL mods for games. As far as I can tell, it shouldn't cause any harm to existing programs, it matches windows 10's behavior.

**Comment by Tk-Glitch** [comment]
I have nothing against it :) Would you have examples of such protection schemes?

**Comment by qsniyg** [comment]
Codex uses it as a protection scheme against debuggers, for example with sunset overdrive.

Here's the patch without (hopefully) the whitespace issue: https://gist.github.com/qsniyg/b0c2f3f91c3924cc952112e3796655b5, it _should_ apply cleanly :) Although manual rebasing is needed for staging.

**Comment by Tk-Glitch** [comment]
Thanks! I'll add back your header.

**Comment by Tk-Glitch** [comment]
Please let me know if you need some feedback about the patch. Thanks again :)

**Comment by GloriousEggroll** [comment]
Thanks for the updated patch, this one works great. I also ran Sunset Overdrive yesterday and can confirm the patch works great!
