### ISSUE TITLE
proton-tkg makepkg problem

### ISSUE THREAD

**Issue by soredake** [Tk-Glitch/PKGBUILDS#535]
```
❯ WINEFSYNC=1 /usr/share/steam/compatibilitytools.d/proton_tkg_makepkg/dist/bin/wine winepath -w "/home/mannyf/.local/share/Steam/steamapps/common/Steamworks Shared"
fsync: up and running.
0009:err:environ:run_wineboot failed to create wineboot event, expect trouble
0009:err:module:import_dll Loading library kernelbase.dll (which is needed by L"C:\\windows\\system32\\kernel32.dll") failed (error c0000008).
wine: could not load kernel32.dll, status c0000135
```
[problem.log](https://github.com/Tk-Glitch/PKGBUILDS/files/4397524/problem.log)

**Comment by Tk-Glitch** [comment]
Hmm meh

**Comment by Tk-Glitch** [comment]
I couldn't repro with the few games I tried. I also tried running wineboot and winecfg directly - with no issue. It looks like a permission issue tbh, but those should be correct already so... Meh again.

**Comment by soredake** [comment]
It fail with any game, i'm using proton-tkg from https://lonewolf.pedrohlc.com/chaotic-aur/

**Comment by Tk-Glitch** [comment]
I just grabbed the latest build from chaotic-aur and... It works fine here. Third meh in a row. I don't like this.

**Comment by soredake** [comment]
I use systemd-homed with fscrypt, nothing interesting aside of that.

**Comment by soredake** [comment]
![image](https://user-images.githubusercontent.com/5204968/77831620-f45c0500-7138-11ea-8663-dc8f5a7dc514.png)
prefix is not actually created, and creating prefix with system wine before running command does not help

**Comment by soredake** [comment]
https://github.com/Tk-Glitch/PKGBUILDS/issues/233

**Comment by soredake** [comment]
![image](https://user-images.githubusercontent.com/5204968/77832120-5d914780-713c-11ea-99eb-1b5943291e92.png)
My user is not 1000, problem solved after doing
```
sudo chown -R root:root /usr/share/steam/compatibilitytools.d/proton_tkg_makepkg
sudo chmod 755 -R /usr/share/steam/compatibilitytools.d/proton_tkg_makepkg
```

**Comment by soredake** [comment]
For some reason, dist folder ends up owned with different user
![image](https://user-images.githubusercontent.com/5204968/77832328-e066d200-713d-11ea-8c25-a5d836b51171.png)

**Comment by PedroHLC** [comment]
@soredake @Tk-Glitch that's the chaotic-aur's container user! (1000:1000) the one who calls makepkg.

**Comment by Tk-Glitch** [comment]
Could you guys please check if the following PKGBUILD fixes it? (remove the trailing .txt)
[PKGBUILD.txt](https://github.com/Tk-Glitch/PKGBUILDS/files/4397982/PKGBUILD.txt)

**Comment by soredake** [comment]
Yes, files are now owned by root.

**Comment by Tk-Glitch** [comment]
Thanks! Merging.
