### ISSUE TITLE
can't start battle.net with anything newer than > wine-tkg-staging-fsync-vkd3d-git-5.4.r3.gcd7d77fe-252

### ISSUE THREAD

**Issue by OneOfOne** [Tk-Glitch/PKGBUILDS#536]
```
fsync: up and running.
000b:fixme:winediag:__wine_start_process Wine TkG 5.5 is a testing version containing experimental patches.
000b:fixme:winediag:__wine_start_process Please don't report bugs about it on winehq.org and use https://github.com/Tk-Glitch/PKGBUILDS/issues instead.
000d:err:module:__wine_process_init L"C:\\windows\\system32\\winemenubuilder.exe" not found
000b:err:wineboot:process_run_key Error running cmd L"C:\\windows\\system32\\winemenubuilder.exe -r" (126).
0009:err:module:LdrInitializeThunk "kernelbase.dll" failed to initialize, aborting
0009:err:module:LdrInitializeThunk Initializing dlls for L"C:\\Program Files (x86)\\Battle.net\\Battle.net Launcher.exe" failed, status c0000005
```

I tried several builds  since then with different options, `_kernelbase_reverts="true"` doesn't change it.

```
grep '^_' ~/.config/frogminer/wine-tkg.cfg 
_nomakepkg_prefix_path=""
_nomakepkg_midbuild_prompt="false"
_EXTERNAL_INSTALL="false"
_plain_version=""
_use_staging="true"
_staging_version="v5.5"
_use_esync="true"
_use_fsync="true"
_use_vkd3d="true"
_dxvk_dxgi="true"
_mtga_fix="false"
_mwo_fix="false"
_re4_fix="false"
_childwindow_fix="true"
_lol920_fix="false"
_assettocorsa_hudperf_fix="false"
_mk11_fix="false"
_ffxivlauncher_fix="false"
_launch_with_dedicated_gpu="false"
_plasma_systray_fix="true"
_FS_bypass_compositor="true"
_proton_fs_hack="true"
_proton_mf_hacks="true"
_proton_rawinput="true"
_msvcrt_nativebuiltin="false"
_win10_default="true"
_protonify="true"
_community_patches="D3D12SerializeVersionedRootSignature.mypatch D3D12CreateVersionedRootSignatureDeserializer.mypatch winex11-fs-no_above_state.mypatch Do_not_fail_if_LDR_MODULE.Flags_is_modified.mypatch"
_kernelbase_reverts="true"
```

**Comment by xavatar** [comment]
No problem for me with the last build.

![Capture d’écran_2020-03-29_07-34-56](https://user-images.githubusercontent.com/11721867/77842222-0a48e480-7190-11ea-842d-454d8bed2cdc.png)

**Comment by Tk-Glitch** [comment]
There are quite a few reports of similar issues with the 5.5 release starting to hit distros and two "straightforward" things to try:
 - Make a new prefix and see if the issue persists.
 - If you're building with mingw, especially if you're using the AUR packages, try to either disable it through the .cfg or to switch to mostlyportable. See https://github.com/Tk-Glitch/PKGBUILDS/issues/501.

**Comment by ronoverdrive** [comment]
My Battlenet screen is just a blank white screen with the latest WINE-TkG 5.5.r1.

![Screenshot_2020-03-29_16-29-42](https://user-images.githubusercontent.com/160574/77860209-e7442200-71db-11ea-8f7d-81c1d2423edc.png)

**Comment by Tk-Glitch** [comment]
Reportedly, `Do_not_fail_if_LDR_MODULE.Flags_is_modified.mypatch` is responsible for that one. I'm not experiencing it on my end for whatever reason.

**Comment by ronoverdrive** [comment]
@Tk-Glitch well maybe @OneOfOne 's problem is the same patch then? They have it listed in their user patches in their config.

**Comment by Tk-Glitch** [comment]
Possibly

**Comment by OneOfOne** [comment]
> @Tk-Glitch well maybe @OneOfOne 's problem is the same patch then? They have it listed in their user patches in their config.

No, I've had that problem before the patch was added to the repo and even with multiple versions of 5.4.x.

I'm trying a clean prefix right now and I'll report back

**Comment by xavatar** [comment]
Test now with a fresh compilation (5.5.r1), i have no problem.
Nvidia : 440.66.4 ; Vulkan : 1.2.135

![battlenet-5 5 r1](https://user-images.githubusercontent.com/11721867/77860758-2b054e80-7211-11ea-920b-758e367d31c8.png)

**Comment by OneOfOne** [comment]
It works on a fresh prefix but I got the white screen with and without `Do_not_fail_if_LDR_MODULE.Flags_is_modified.mypatch`, only thing that fixed it was installing dxvk, so that seems like a regression in wine's dx11.

I'm closing this, thanks for the help.
