### ISSUE TITLE
[wine-tkg] Can't play Overwatch

### ISSUE THREAD

**Issue by EdLovecraft** [Tk-Glitch/PKGBUILDS#537]
![Screenshot_20200330_131521](https://user-images.githubusercontent.com/40231164/77877575-b241d900-7288-11ea-85cf-5131324aa18f.png)
The screen was completely frozen, and i could not do anything but reboot my computer

Here's the log

```
[0330/131516.585:ERROR:browser_process_sub_thread.cc(221)] Waited 4 ms for network service
Initial process has exited.
wineserver: ../../wine-mirror-git/server/thread.c:1311: copy_context: Assertion `to->cpu == from->cpu' failed.

```

[customization.txt](https://github.com/Tk-Glitch/PKGBUILDS/files/4400911/customization.txt)
[advanced-customization.txt](https://github.com/Tk-Glitch/PKGBUILDS/files/4400912/advanced-customization.txt)

**Comment by Tk-Glitch** [comment]
It looks familiar. Someone bisected it down to Proton's GTA V patches. However, I have removed them yesterday with https://github.com/Frogging-Family/wine-tkg-git/commit/07927c3d366eaabd2217b7e155f90e5bb92cef52. Is your build susceptible to be older than that change?

**Comment by xavatar** [comment]
Hello, I just tested right now and overwatch starts correctly.

End of my log :
```
info:  Presenter: Actual swap chain properties:
info:    Format:       VK_FORMAT_B8G8R8A8_UNORM
info:    Present mode: VK_PRESENT_MODE_FIFO_KHR
info:    Buffer size:  1200x750
info:    Image count:  3
info:    Exclusive FS: 2
[0330/102001.186:ERROR:network_change_notifier_win.cc(156)] WSALookupServiceBegin failed with: 0
warn:  D3D11Texture2D::QueryInterface: Unknown interface query
warn:  f8fb5c27-c6b3-4f75-a4c8-439af2ef564c
warn:  D3D11Texture2D::QueryInterface: Unknown interface query
warn:  f8fb5c27-c6b3-4f75-a4c8-439af2ef564c
warn:  D3D11Texture2D::QueryInterface: Unknown interface query
warn:  f8fb5c27-c6b3-4f75-a4c8-439af2ef564c
warn:  D3D11Texture2D::QueryInterface: Unknown interface query
warn:  f8fb5c27-c6b3-4f75-a4c8-439af2ef564c
warn:  D3D11Texture2D::QueryInterface: Unknown interface query
warn:  f8fb5c27-c6b3-4f75-a4c8-439af2ef564c
warn:  D3D11Texture2D::QueryInterface: Unknown interface query
warn:  f8fb5c27-c6b3-4f75-a4c8-439af2ef564c
```

Same log as you but you have this extra line :
`[0330/131516.585:ERROR:browser_process_sub_thread.cc(221)] Waited 4 ms for network service`

Maybe a network problem ?

**Comment by EdLovecraft** [comment]
> Hello, I just tested right now and overwatch starts correctly.
> 
> End of my log :
> 
> ```
> info:  Presenter: Actual swap chain properties:
> info:    Format:       VK_FORMAT_B8G8R8A8_UNORM
> info:    Present mode: VK_PRESENT_MODE_FIFO_KHR
> info:    Buffer size:  1200x750
> info:    Image count:  3
> info:    Exclusive FS: 2
> [0330/102001.186:ERROR:network_change_notifier_win.cc(156)] WSALookupServiceBegin failed with: 0
> warn:  D3D11Texture2D::QueryInterface: Unknown interface query
> warn:  f8fb5c27-c6b3-4f75-a4c8-439af2ef564c
> warn:  D3D11Texture2D::QueryInterface: Unknown interface query
> warn:  f8fb5c27-c6b3-4f75-a4c8-439af2ef564c
> warn:  D3D11Texture2D::QueryInterface: Unknown interface query
> warn:  f8fb5c27-c6b3-4f75-a4c8-439af2ef564c
> warn:  D3D11Texture2D::QueryInterface: Unknown interface query
> warn:  f8fb5c27-c6b3-4f75-a4c8-439af2ef564c
> warn:  D3D11Texture2D::QueryInterface: Unknown interface query
> warn:  f8fb5c27-c6b3-4f75-a4c8-439af2ef564c
> warn:  D3D11Texture2D::QueryInterface: Unknown interface query
> warn:  f8fb5c27-c6b3-4f75-a4c8-439af2ef564c
> ```
> 
> Same log as you but you have this extra line :
> `[0330/131516.585:ERROR:browser_process_sub_thread.cc(221)] Waited 4 ms for network service`
> 
> Maybe a network problem ?

not network problem i think, the game just frozen, alt+f4,alt+enter or whatever

> Hello, I just tested right now and overwatch starts correctly.
> 
> End of my log :
> 
> ```
> info:  Presenter: Actual swap chain properties:
> info:    Format:       VK_FORMAT_B8G8R8A8_UNORM
> info:    Present mode: VK_PRESENT_MODE_FIFO_KHR
> info:    Buffer size:  1200x750
> info:    Image count:  3
> info:    Exclusive FS: 2
> [0330/102001.186:ERROR:network_change_notifier_win.cc(156)] WSALookupServiceBegin failed with: 0
> warn:  D3D11Texture2D::QueryInterface: Unknown interface query
> warn:  f8fb5c27-c6b3-4f75-a4c8-439af2ef564c
> warn:  D3D11Texture2D::QueryInterface: Unknown interface query
> warn:  f8fb5c27-c6b3-4f75-a4c8-439af2ef564c
> warn:  D3D11Texture2D::QueryInterface: Unknown interface query
> warn:  f8fb5c27-c6b3-4f75-a4c8-439af2ef564c
> warn:  D3D11Texture2D::QueryInterface: Unknown interface query
> warn:  f8fb5c27-c6b3-4f75-a4c8-439af2ef564c
> warn:  D3D11Texture2D::QueryInterface: Unknown interface query
> warn:  f8fb5c27-c6b3-4f75-a4c8-439af2ef564c
> warn:  D3D11Texture2D::QueryInterface: Unknown interface query
> warn:  f8fb5c27-c6b3-4f75-a4c8-439af2ef564c
> ```
> 
> Same log as you but you have this extra line :
> `[0330/131516.585:ERROR:browser_process_sub_thread.cc(221)] Waited 4 ms for network service`
> 
> Maybe a network problem ?

I don’t think it’s a network problem, the screen was completely frozen, and I couldn't do anything but reboot my computer

**Comment by EdLovecraft** [comment]
> Hello, I just tested right now and overwatch starts correctly.
> 
> End of my log :
> 
> ```
> info:  Presenter: Actual swap chain properties:
> info:    Format:       VK_FORMAT_B8G8R8A8_UNORM
> info:    Present mode: VK_PRESENT_MODE_FIFO_KHR
> info:    Buffer size:  1200x750
> info:    Image count:  3
> info:    Exclusive FS: 2
> [0330/102001.186:ERROR:network_change_notifier_win.cc(156)] WSALookupServiceBegin failed with: 0
> warn:  D3D11Texture2D::QueryInterface: Unknown interface query
> warn:  f8fb5c27-c6b3-4f75-a4c8-439af2ef564c
> warn:  D3D11Texture2D::QueryInterface: Unknown interface query
> warn:  f8fb5c27-c6b3-4f75-a4c8-439af2ef564c
> warn:  D3D11Texture2D::QueryInterface: Unknown interface query
> warn:  f8fb5c27-c6b3-4f75-a4c8-439af2ef564c
> warn:  D3D11Texture2D::QueryInterface: Unknown interface query
> warn:  f8fb5c27-c6b3-4f75-a4c8-439af2ef564c
> warn:  D3D11Texture2D::QueryInterface: Unknown interface query
> warn:  f8fb5c27-c6b3-4f75-a4c8-439af2ef564c
> warn:  D3D11Texture2D::QueryInterface: Unknown interface query
> warn:  f8fb5c27-c6b3-4f75-a4c8-439af2ef564c
> ```
> 
> Same log as you but you have this extra line :
> `[0330/131516.585:ERROR:browser_process_sub_thread.cc(221)] Waited 4 ms for network service`
> 
> Maybe a network problem ?

I don’t think it’s a network problem, the screen was completely frozen, and I couldn't do anything but reboot my computer

**Comment by xavatar** [comment]
I use no custom patch and i have the last build : 5.5.r2.g7fe7d87f-257.
Are you using the latest build of wine-tkg-staging ?

**Comment by EdLovecraft** [comment]
> I use no custom patch and i have the last build : 5.5.r2.g7fe7d87f-257.
> Are you using the latest build of wine-tkg-staging ?

yes, wine-tkg-staging-fsync-vkd3d-git-5.5.r2.g7fe7d87f-257-x86_64

**Comment by EdLovecraft** [comment]
> It looks familiar. Someone bisected it down to Proton's GTA V patches. However, I have removed them yesterday with [Frogging-Family/wine-tkg-git@07927c3](https://github.com/Frogging-Family/wine-tkg-git/commit/07927c3d366eaabd2217b7e155f90e5bb92cef52). Is your build susceptible to be older than that change?

i rebuilt with the same settings just now, still cannot get Overwatch work

**Comment by Tk-Glitch** [comment]
Please try a rebuild with these changes.

**Comment by EdLovecraft** [comment]
> Please try a rebuild with these changes.

it's working now, thank you

**Comment by Tk-Glitch** [comment]
Noice :) Enjoy
