### ISSUE TITLE
[nvidia-all] linux-tkg-pds 5.6.0

### ISSUE THREAD

**Issue by IroAlexis** [Tk-Glitch/PKGBUILDS#538]
Hello,

I just received the update linux-tkg-pds 5.6 (via chaotic-aur) but i don't build correctly the initcpio because he foundn't the nvidia module.
So I edit my mkinitcpio.conf and remove nvidia moudule. The initcpio built themselves up properly and i reinstall nvidia-dkms-tkg but there is an error :
```
(2/2) Install DKMS modules
==> dkms install nvidia/440.66.04 -k 5.6.0-2-tkg-pds
Error! Bad return status for module build on kernel: 5.6.0-2-tkg-pds (x86_64)
Consult /var/lib/dkms/nvidia/440.66.04/build/make.log for more information.
``` 
[make.log](https://github.com/Tk-Glitch/PKGBUILDS/files/4407329/make.log)

Thank you for the amazing work @Tk-Glitch 

PS : Sorry for my poor english

**Comment by openglfreak** [comment]
Rebuild the nvidia-tkg packages.

**Comment by IroAlexis** [comment]
Ah I see... I go through Chaotic-aur so I need wait the rebuild the nvidia-tkg package.

**Comment by openglfreak** [comment]
You can just build it yourself, takes like 2 minutes not counting download.

**Comment by Tk-Glitch** [comment]
It's even made simpler by my recent switch to submodules:

`git clone https://github.com/Frogging-Family/nvidia-all`
`cd nvidia-all`
`makepkg -si`

**Comment by IroAlexis** [comment]
Yes it is true so I clone the nvidia git and no issues. I didn't want to use the git, I just wanted to go through Chaotic Aur but I followed your suggestion.

Thanks you guys

**Comment by IroAlexis** [comment]
Yes it is true so I clone the nvidia git and no issues. I didn't want to use the git, I just wanted to go through Chaotic Aur but I followed your suggestion.

Thanks you guys

**Comment by Tk-Glitch** [comment]
Major kernel releases transitions are always more involved when it comes to Nvidia, similarly to GCC updates for everyone. After all, Nvidia doesn't yet offer a 5.6 compatible driver 🐸

**Comment by PedroHLC** [comment]
Please involved, when those things occur, please feel free to open an issue in https://github.com/PedroHLC/chaotic-aur/issues
Other may also benefit from it :smile:

**Comment by IroAlexis** [comment]
Oh @PedroHLC, I completely forgot there was a git repository... My bad, would you like me to open a issue ?

**Comment by PedroHLC** [comment]
It's okay, I rebuilt it and put it to try hourly with https://github.com/PedroHLC/chaotic-aur/commit/4a97128a0268b94d8812d5828558effb95e70f30 .
Now as long as @Tk-Glitch dumps pkgrel, it should rebuild too.
