### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by Kerrung** [Tk-Glitch/PKGBUILDS#54]
### [customization.zip](https://github.com/Tk-Glitch/PKGBUILDS/files/2606811/customization.zip)
PBA=false in customization.cfg, but:
![screenshot from 2018-11-22 11-31-46](https://user-images.githubusercontent.com/36989404/48885674-f4643a80-ee4a-11e8-945f-69ef451eefd5.png)

**Comment by Tk-Glitch** [comment]
The error is in kernelbase, so this is not PBA indeed. Some other patch broke. Working on it.

**Comment by Tk-Glitch** [comment]
Should be fixed by https://github.com/Tk-Glitch/PKGBUILDS/commit/

**Comment by Kerrung** [comment]
### [customization.cfg.zip](https://github.com/Tk-Glitch/PKGBUILDS/files/2609306/customization.cfg.zip)

I tried f546023 but it did not help:
![screenshot from 2018-11-23 02-39-10](https://user-images.githubusercontent.com/36989404/48922599-a0e50180-eec9-11e8-90fd-371a409a8326.png)

**Comment by Tk-Glitch** [comment]
That is a completely different error here. It's happening in wined3d this time. Looks like pba again.

**Comment by Kerrung** [comment]
What means "BIG_UGLY_COINMINER"? Why do we need it?

**Comment by Tk-Glitch** [comment]
This is the (jokingly named) state tracker file that prevents the initial prompt to come back during building. It's empty, only its presence is checked.

**Comment by Tk-Glitch** [comment]
@Kerrung I have fixed the PBA patch so it builds again on master ( https://github.com/Tk-Glitch/PKGBUILDS/commit/855fabc69e4a334d65f7aaed6e01ada08f9796c8 ). PBA is still broken though, and I can't recommend anyone to use it except for debugging purposes.

**Comment by Kerrung** [comment]
f546023
### [customization.zip](https://github.com/Tk-Glitch/PKGBUILDS/files/2609372/customization.zip)
_use_pba="false"
_use_dxvk="true"
_dxvk_winelib_fix="true"
![screenshot from 2018-11-23 03-55-31](https://user-images.githubusercontent.com/36989404/48923861-0fc75800-eed4-11e8-9702-e2cab9953a0a.png)

**Comment by Tk-Glitch** [comment]
#works4me

**Comment by Tk-Glitch** [comment]
Oh, I think I know what your issue is. You need to have an actually fixed build running for DXVK to be able to build. So you need to first make a build without DXVK with the fix enabled, then you'll be able to build DXVK again.
