### ISSUE TITLE
Kernel 5.6 is requiring nvidia-dkms-tkg-440.64-102-x86_64 patch 

### ISSUE THREAD

**Issue by lavacano** [Tk-Glitch/PKGBUILDS#541]
I'm having to apply this patch to the package named https://gitlab.com/snippets/1945940

**Comment by Tk-Glitch** [comment]
nvidia-all comes with its own set of patches for kernel compat. You don't need any additional patch for 5.6. Just run `makepkg -si` and select your driver. Everything will be done automagically.

**Comment by Tk-Glitch** [comment]
```
git clone https://github.com/Frogging-Family/nvidia-all.git
cd nvidia-all
makepkg -si
```

**Comment by lavacano** [comment]
I installed it from chaos-aur... I'm getting used to this package manager paradigm its different.

**Comment by Tk-Glitch** [comment]
We've been discussing about the best way to offer patched up nvidia packages with the chaotic-aur maintainer to make things as smooth as possible in the future considering Nvidia's limitations. The transition to major kernel releases that are not supported by Nvidia can be quite problematic. Using my scripts directly should hopefully only be needed as a fallback for chaotic-aur users pretty soon.
