### ISSUE TITLE
BCrypt patch fails to apply

### ISSUE THREAD

**Issue by ronoverdrive** [Tk-Glitch/PKGBUILDS#542]
```
patching file dlls/bcrypt/gnutls.c
patching file dlls/mfreadwrite/reader.c
Hunk #1 FAILED at 565.
1 out of 1 hunk FAILED -- saving rejects to file dlls/mfreadwrite/reader.c.rej
```
Possibly upstreamed or needs a rebase?

**Comment by VictorRogers** [comment]
Literally just ran into the same problem

**Comment by MrTheElk** [comment]
Ran into the same problem as well.
Although from the error message it seems to be the mfreadwrite patch that fails.

**Comment by Riesi** [comment]
the `last_build_config.log` would be nice
and it fails in something mfplat related not bcrypt

**Comment by MrTheElk** [comment]
Here.

[last_build_config.log](https://github.com/Tk-Glitch/PKGBUILDS/files/4430348/last_build_config.log)
