### ISSUE TITLE
[suggestion] PKGBUILD for vkBasalt

### ISSUE THREAD

**Issue by OneOfOne** [Tk-Glitch/PKGBUILDS#543]
It kinda fits with vkd3d and dxvk and the other vulkan packages.

- https://github.com/DadSchoorse/vkBasalt

**Comment by ronoverdrive** [comment]
There's already one in the AUR.

**Comment by OneOfOne** [comment]
it's been broken it seems.

**Comment by ronoverdrive** [comment]
Builds just fine for me.
