### ISSUE TITLE
[proton-tkg] "DX11 feature level 10.0 is required to run the engine" with every VR game

### ISSUE THREAD

**Issue by frostworx** [Tk-Glitch/PKGBUILDS#548]
built proton-tkg earlier today, in oder to apply some patches where required.
I only enabled _steamvr_support and disabled _proton_winetricks
everything else is default.
looks like all games work fine as expected, but all VR games I tried (not very many tbh) exit with
"DX11 feature level 10.0 is required to run the engine"
Is this a known issue? Do you need any logs?

edit: I'm on up2date arch linux with nvidia-440.82-6 running a rtx2080 btw
edit2: looks like it also affects some pancake games. I'll try to get more information within the next days when I find the time.

**Comment by frostworx** [comment]
looks like I nailed the issue down to the following reproducable example:
https://store.steampowered.com/app/1098490/Explore_Fushimi_Inari/
has both a pancake version and a (chargeable) VR dlc
seperate executables, but same wineprefix.

1) when I start the pancake version with SteamVR disabled(!) the game works fine!
2) when I start the pancake version with SteamVR enabled it also crashes with "DX11 feature level 10.0 is required to run the engine"

3) when I start the VR version with SteamVR disabled(!) the game starts fine in pancake window (because VR is disabled) (it goes black after some seconds, but this is a different issue, also happening with vanilla proton)
4) when I start the VR version with SteamVR enabled it crashes with "DX11 feature level 10.0 is required to run the engine"

5) when I start the pancake version with SteamVR disabled(!) and PROTON_USE_WINED3D=1 set the game works fine!
6) when I start the pancake version with SteamVR enabled(!) and PROTON_USE_WINED3D=1 set the game works (slow)!

7) when I start the VR version with SteamVR disabled(!) and PROTON_USE_WINED3D=1 set the game 
starts fine in pancake window (because VR is disabled) (it also goes black after some seconds - see 3))
8) when I start the VR version with SteamVR enabled(!) and PROTON_USE_WINED3D=1 set the game crashes with "Fatal Error"

Would be great if you could take a look, maybe this would fix other VR related problems as well.
Please tell me which logs you need if you're interested in debugging this!

**Comment by Tk-Glitch** [comment]
Thanks for the feedback. I'll investigate tomorrow, it seems pretty weird. So I assume you're not building DXVK yourself at this point (since that's not default). That might be something to try.

**Comment by frostworx** [comment]
thanks for the response!
I in fact did so as well, but haven't tested it very much. only replaced the dlls in 
compatibilitytools.d/proton_tkg_5.6.1.r8.g0d8d1f04/dist/lib/wine/dxvk/
but haven't cleaned the prefix or checked logs if the dlls were used.
checking that later today :)

**Comment by frostworx** [comment]
Hi again,
just tried the pancake version with VR on/off with both dxvk builds.
the issue is reproducable with both the prebuilt binaries and with the self rolled dlls (from dxvk-mingw AUR)
the dxvk logfiles for both d3d11 and dxgi all have the same size and md5 for the prebuild and selfrolled dxvk versions.
the PROTON_LOG=1 files are identical for the prebuild and selfrolled dxvk versions when VR is on
but are a little bit different when VR is off.
I attached both logs maybe they are helpful.
especially the
`1108.020:0016:0019:err:setupapi:SetupDiSelectBestCompatDrv No compatible drivers were enumerated for device L"USB\\VID_28DE&PID_2400\\0".`
lines look suspicious imho in the "custom rolled log".

[steam-1098490-NOVR-BIN.log](https://github.com/Tk-Glitch/PKGBUILDS/files/4523087/steam-1098490-NOVR-BIN.log)
[steam-1098490-NOVR-CUST.log](https://github.com/Tk-Glitch/PKGBUILDS/files/4523088/steam-1098490-NOVR-CUST.log)

**Comment by frostworx** [comment]
just tried randomly some VR games. Looks like every VR game is affected (not all have that "DX11 feature level" requester though, probably comes from UE4) and crashes while loading.
tried Boneworks, BeatSaber, cyubeVR, Half Live Alyx, InDeath - all crash with proton-tkg but work with proton 5.0-6.
Not all pancake games  are affected though with VR enabled - f.e. "Cat Quest" works normally.

**Comment by frostworx** [comment]
looks like proton-ge has exactly the same problem.

**Comment by Tk-Glitch** [comment]
The issue seems deeper than initially thought. I'm still trying to figure it out.

**Comment by frostworx** [comment]
no worries! thanks for the reply and for even trying!
if there's anything I can do to help just tell me.

**Comment by frostworx** [comment]
just tried a game with proton_tkg_5.8.r0.g7d92cd31 and WINEDEBUG="+steam,+vrclient,+msvcrt,+ntdll"
and found the bug:
`00c4:warn:ntdll:FILE_CreateFile L"\\??\\Z:\\home\\frostwork\\.local\\share\\Steam\\compatibilitytools.d\\proton_tkg_5.8.r0.g7d92cd31\\dist\\lib64\\wine\\vrclient_x64.dll" not found (c0000034)`

and indeed the file is installed as vrclient_x64.dll.so
renaming the file fixed the error (but unfortunately proton-tk not the game with the bug ;))

**Comment by tuxfoo** [comment]
I have observed the same behavior. Might try some debugging tomorrow.

**Comment by mrxz** [comment]
I looked into this issue a bit and it seems that it fails in dxvk when trying to create the Vulkan instance (`vkCreateInstance`), with a `VK_ERROR_EXTENSION_NOT_PRESENT`. Comparing the logs with Proton-5.0.9, the exact same extensions are requested, so not sure why it fails.

Replacing winevulkan with the one from Proton-5.0.9 resolves the issue. So either Proton contains some custom changes to winevulkan or upstream changes caused this regression. I'll see if I can bisect winevulkan.

**Comment by mrxz** [comment]
I can confirm that 5e2cf6c fixes the issue, thanks. :smile: 
One issue is that now `valve_proton_fullscreen_hack.patch` and `proton-vr.patch` contain the same change to `vulkan.c` (a5e8fd142327229b03205e57c1827376ed643b7f).

**Comment by frostworx** [comment]
Great, thanks a lot!

**Comment by Tk-Glitch** [comment]
@mrxz Thanks for the heads up, I have removed the duplicated hunk from the patchset with https://github.com/Frogging-Family/wine-tkg-git/commit/c9ea2c20cebbf67f4d2906b74860cf9eeffa6d71. I guess I can close :smiley:

**Comment by Patola** [comment]
This bug is back. Latest build 6.17 doesn't work at all for VR.

**Comment by frostworx** [comment]
`proton_tkg_6.17.r0.g5f19a815` doesn't have any `vrclient` libs bundled.

**Comment by Tk-Glitch** [comment]
We have disabled VR support altogether until further notice as it doesn't seem to work anyway. It'll be looked after again when a rebase drops on the valve side.
