### ISSUE TITLE
Winegcc can't build DXVK

### ISSUE THREAD

**Issue by ssorgatem** [Tk-Glitch/PKGBUILDS#55]
Since yesterday (at least), I am unable to build DXVK as a winelib if using Wine built from this package (compiler = gcc).

If I install wine-staging from the repos, I can build DXVK just fine.

Just to clarify, I'm not building DXVK as part of this wine, but separately (the AUR winelib packages).

Here's my customization.cfg:

> _COMPILEWITH="gcc"
_LOCAL_OPTIMIZED="true"
_NUKR="true"
_NOCOMPILE="false"
_NOINITIALPROMPT="true"
_PKGNAME_OVERRIDE=""
_INSTALL_TO_OPT="false"
_plain_version=""
_use_esync="true"
_esync_version="ce79346"
_use_staging="true"
_staging_version=""
_use_pba="false"
_use_vkd3d="true"
_use_dxvk="false"
_dxvk_version=""
_use_gallium_nine="true"
_poe_fix="true"
_fallout4dsound_fix="false"
_f4skyrimse_fix="false"
_fortnite_fix="false"
_sims2_fix="false"
_sims4_fix="true"
_mtga_fix="true"
_staging_pulse_disable="false"
_use_faudio="true"
_CSMT_toggle="true"
_steam_fix="true"
_lowlatency_audio="false"
_launch_with_dedicated_gpu="false"
_clock_monotonic="true"
_FS_bypass_compositor="true"
_proton_fs_hack="true"
_plasma_systray_fix="true"`

**Comment by Tk-Glitch** [comment]
Indeed, someone reported that to me an hour ago or so. I'm investigating.

**Comment by Tk-Glitch** [comment]
The culprit seems to be this commit : https://github.com/wine-mirror/wine/commit/2dfff7e63c4fc6f97e83df448a2c2b8c4b9eedd5
