### ISSUE TITLE
[wine-tkg-git] Can't to compile ada6f9f1b957e665c6c9ee44add9a39862f2460d

### ISSUE THREAD

**Issue by Kerrung** [Tk-Glitch/PKGBUILDS#551]
Commit: https://github.com/Tk-Glitch/PKGBUILDS/commit/ada6f9f1b957e665c6c9ee44add9a39862f2460d
[last_build_config.log](https://github.com/Tk-Glitch/PKGBUILDS/files/4548461/last_build_config.log)

![Screenshot from 2020-04-29 02-03-59](https://user-images.githubusercontent.com/36989404/80537711-ef030c00-89bd-11ea-9e16-c17257390e53.png)

**Comment by Tk-Glitch** [comment]
Sync'd with https://github.com/Tk-Glitch/PKGBUILDS/commit/655f3a3b7a322e3f0f16211cc17d36d1ddf7e21d

**Comment by Kerrung** [comment]
> Sync'd with [655f3a3](https://github.com/Tk-Glitch/PKGBUILDS/commit/655f3a3b7a322e3f0f16211cc17d36d1ddf7e21d)

Tnx!
