### ISSUE TITLE
[wine-tkg-git] Can't to compile with _update_winevulkan="true" (655f3a3b7a322e3f0f16211cc17d36d1ddf7e21d)

### ISSUE THREAD

**Issue by Kerrung** [Tk-Glitch/PKGBUILDS#552]
Commit: https://github.com/Tk-Glitch/PKGBUILDS/commit/655f3a3b7a322e3f0f16211cc17d36d1ddf7e21d
[last_build_config.log](https://github.com/Tk-Glitch/PKGBUILDS/files/4548701/last_build_config.log)
![Screenshot from 2020-04-29 02-44-07](https://user-images.githubusercontent.com/36989404/80540870-90409100-89c3-11ea-9f65-7fb361273758.png)

**Comment by Tk-Glitch** [comment]
1 - Not my bug
2 - Can't repro

**Comment by Kerrung** [comment]
Works fine now. Tnx.
