### ISSUE TITLE
Game: Kerbal Space Program

### ISSUE THREAD

**Issue by CMHash** [Tk-Glitch/PKGBUILDS#555]
[Logs.zip](https://github.com/Tk-Glitch/PKGBUILDS/files/4573592/Logs.zip)
Greetings, 

I am attempting to run KSP 18.1 through wine, the game loads its resources and then proceeds to crash. 

included is all needed files and logs.

Thanks

**Comment by ronoverdrive** [comment]
Isn't KSP a native linux game?

**Comment by CMHash** [comment]
Well lets just look at it as a technical exercise.

**Comment by Tk-Glitch** [comment]
Are we talking about the EA version 0.18.1 or the release version 1.8.1?
I ran my 1.9.1 version (Steam) and it runs OOTB, even on my current Wine 5.8 based build.

I noticed your log pointed to DXVK not being used, so I then tried without DXVK to see if wined3d might be at fault here. But nope, worked fine too. Then everything got clearer when I saw the hardware used.
A Intel(R) Celeron(R) CPU  N2807  @ 1.58GHz with its accompanying iGPU and a maximum of 4GB RAM supported (which is shared with the iGPU, of course).

The game - in d3d11 mode - uses ~4.2GB RAM and ~1.5GB VRAM on the main menu with minimum settings and 1024x768 res.
I don't think this is a Wine issue. It could be a mesa issue, or Pop_OS! being stupid as it always is, but ultimately I doubt that hardware is enough for the game to run in d3d11 mode with Wine. You could try to force opengl mode or something, but the native version is definitely your best bet.
