### ISSUE TITLE
[wine-tkg] Wine-mono (installed on Arch Linux) is not detected

### ISSUE THREAD

**Issue by iWeaker4you** [Tk-Glitch/PKGBUILDS#557]
The latest versions I have noticed that it does not detect Wine-mono that is installed on the system, but Wine-gecko is detected without problems, does this in any way affect the compatibility of the applications?

![image](https://user-images.githubusercontent.com/49424816/81064955-77d2e980-8e8f-11ea-9a16-8011005cacd2.png)

**Comment by Tk-Glitch** [comment]
https://bugs.archlinux.org/task/66428?project=5&string=wine-mono

It'll just download mono everytime if you click install. No change in compat.

**Comment by Tk-Glitch** [comment]
For proton-tkg, latest mono is now included in the dist as of https://github.com/Frogging-Family/wine-tkg-git/commit/9b65540e316d650a152b35c9b885282afb9d98fe so you don't need mono installed anymore. The issue persists for wine-tkg of course, and needs to be fixed upstream.

**Comment by iWeaker4you** [comment]
@Tk-Glitch Thanks, Then I will close the problem.
