### ISSUE TITLE
[wine-tkg]Interlocked functions

### ISSUE THREAD

**Issue by edisionnano** [Tk-Glitch/PKGBUILDS#558]
Wine got rid of interlocked functions on this commit https://github.com/wine-mirror/wine/commit/7eef40d444b3325f9580ff557afb6bc19c811f5e causing the build to fail with 
`fsync.c:(.text+0x19e): undefined reference to `interlocked_cmpxchg_ptr'
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:1330: wineserver] Error 1
make[1]: Leaving directory '/home/spiros/Downloads/PKGBUILDS-master/wine-tkg-git/src/wine-tkg-staging-fsync-vkd3d-git-64-build/server'
make: *** [Makefile:9733: server] Error 2`

**Comment by Tk-Glitch** [comment]
Your tree isn't up to date.
https://github.com/Frogging-Family/wine-tkg-git/commit/17d0c282d8f16c98cb99b1fc61abba08cea3c460
