### ISSUE TITLE
[nvidia-all] patch nvidia 418 FAILED

### ISSUE THREAD

**Issue by AlvinZhu** [Tk-Glitch/PKGBUILDS#567]
-> Applying kernel-5.6.patch for 5.6.15-arch1-1...
patching file nvidia/nvidia.Kbuild
Hunk #1 FAILED at 150.
1 out of 1 hunk FAILED -- saving rejects to file nvidia/nvidia.Kbuild.rej
patching file common/inc/nv-procfs.h
Hunk #1 succeeded at 52 with fuzz 2 (offset 24 lines).
Hunk #2 succeeded at 75 with fuzz 1 (offset 25 lines).
Hunk #3 FAILED at 90.
Hunk #4 succeeded at 134 with fuzz 2 (offset 7 lines).
1 out of 4 hunks FAILED -- saving rejects to file common/inc/nv-procfs.h.rej
patching file conftest.sh
Hunk #1 succeeded at 930 with fuzz 1 (offset 124 lines).
patching file nvidia/nv-procfs.c
Hunk #1 succeeded at 436 (offset -16 lines).
Hunk #2 succeeded at 453 with fuzz 2 (offset -16 lines).
Hunk #3 FAILED at 541.
Hunk #4 succeeded at 555 with fuzz 2 (offset 6 lines).
Hunk #5 FAILED at 624.
Hunk #6 succeeded at 772 with fuzz 2 (offset 139 lines).
Hunk #7 FAILED at 736.
Hunk #8 FAILED at 863.
Hunk #9 succeeded at 1007 with fuzz 2 (offset 136 lines).
Hunk #10 FAILED at 1200.
Hunk #11 succeeded at 1016 (offset -200 lines).
5 out of 11 hunks FAILED -- saving rejects to file nvidia/nv-procfs.c.rej
patching file nvidia/os-interface.c
Hunk #1 succeeded at 445 (offset -32 lines).
patching file common/inc/56rc3uglyhack.h
patching file common/inc/nv-time.h
patching file nvidia/linux_nvswitch.c
Hunk #1 FAILED at 26.
1 out of 1 hunk FAILED -- saving rejects to file nvidia/linux_nvswitch.c.rej

**Comment by Tk-Glitch** [comment]
418 is 300% dead on recent kernels in its current form. I'll add a check to make the user aware.
