### ISSUE TITLE
Linux57-tkg & Linux58-tkg fail to compile on Piledriver, Steamroller, and Excavator

### ISSUE THREAD

**Issue by ronoverdrive** [Tk-Glitch/PKGBUILDS#569]
[buildlog.txt](https://github.com/Tk-Glitch/PKGBUILDS/files/4736550/buildlog.txt)

[customization.cfg.txt](https://github.com/Tk-Glitch/PKGBUILDS/files/4736555/customization.cfg.txt)

I've tried without any user patches as well as both native and mostlyportable-gcc, 5.7 just doesn't seem to want to build on my system.

**Comment by Tk-Glitch** [comment]
I can reproduce the issue when selecting piledriver optimizations. I'd try mnative and if that still breaks, fallback to generic x86-64.

**Comment by ronoverdrive** [comment]
Already have. march native fails as well.

**Comment by Tk-Glitch** [comment]
It seems to be a comeback of https://forums.gentoo.org/viewtopic-t-1075862-start-0.html

**Comment by ronoverdrive** [comment]
So basically its an upstream issue.

**Comment by ronoverdrive** [comment]
So looks like one of the Gentoo guys may have found a work around for this problem.

https://github.com/graysky2/kernel_gcc_patch/issues/55

Gonna attempt this patch and see how it goes later.

**Comment by ronoverdrive** [comment]
So confirmed that this is an upstream issue related to changes in Linux 5.7+ and GCC 10.1. The Work around is to disable Trailing Bit Manipulation (a feature only found on these CPUs) by adding -mno-tbm to the CPU cflags for those CPU families in glitched-base.

```
+        cflags-$(CONFIG_MPILEDRIVER) += $(call cc-option,-march=bdver2 -mno-tbm)
+        cflags-$(CONFIG_MSTEAMROLLER) += $(call cc-option,-march=bdver3 -mno-tbm)
+        cflags-$(CONFIG_MEXCAVATOR) += $(call cc-option,-march=bdver4 -mno-tbm)
```

**Comment by Tk-Glitch** [comment]
Thanks for confirming. I'll import Graysky's patchsets tomorrow.
