### ISSUE TITLE
LAA Patch dont work with wine 5.10 vanilla

### ISSUE THREAD

**Issue by mrdeathjr28** [Tk-Glitch/PKGBUILDS#570]
Hi

LAA patch dont work in my case with wine 5.10 vanilla, however with wine 5.9 still works

Thanks

**Comment by Tk-Glitch** [comment]
I have added informative messages about what's going on. The 5.10 dumpster fire *will* affect clean builds due to major refactoring upstream. I might issue a statement to explain where we're at and where I'm heading, at least for (hopefully) short term.

**Comment by Tk-Glitch** [comment]
This should be fixed, closing.
