### ISSUE TITLE
Wine-tkg hotfixes broken

### ISSUE THREAD

**Issue by ronoverdrive** [Tk-Glitch/PKGBUILDS#571]
[prepare.log](https://github.com/Tk-Glitch/PKGBUILDS/files/4768396/prepare.log)

More Wine 5.10 build problems.

**Comment by Tk-Glitch** [comment]
Your tree isn't up to date. Please pull latest changes and give it another try 🐸

**Comment by ronoverdrive** [comment]
Removed and tried a fresh git clone: 
[prepare.log](https://github.com/Tk-Glitch/PKGBUILDS/files/4773676/prepare.log)

More breakage. Wine 5.10 is a real clusterfuck isn't it? :P

**Comment by Tk-Glitch** [comment]
Staging was updated in the meantime. Wine is a clusterfuck since 5.6 btw 🐸

**Comment by ronoverdrive** [comment]
Looks like the mfplat patch broke again xD

**Comment by Tk-Glitch** [comment]
Update your trees.
Both issues were fixed and sync'd: https://github.com/Tk-Glitch/PKGBUILDS/commit/06046e876e7bc521334d67b08aa1b771e5ac1eff

**Comment by ronoverdrive** [comment]
Had to do some fresh trees. Ever since the git switched to submodules it never seems to want to keep syncing correctly for me.

**Comment by Tk-Glitch** [comment]
Yeah it's been pretty annoying for the centralized repo. I'm working on some solutions that'll hopefully be satisfying for everyone.
