### ISSUE TITLE
Intel AC-9650 wireless card broken

### ISSUE THREAD

**Issue by nepnep1111** [Tk-Glitch/PKGBUILDS#577]
Support for the Intel AC-9650 is broken tested on kernel 5.7-tk and 5.8rc4-tk.
error -22 when loading iwlwifi module.
Bluetooth still works properly
![unknown](https://user-images.githubusercontent.com/28652514/87081251-9edecc00-c1ee-11ea-9c8f-f4a2b6fdb4a0.png)
Device Used: MSI GS65
(i7-9750h, 64gb DDR4, RTX 2080 Max-Q, Manjaro 20.0.3 Unstable Branch)

Edit: not working on 5.7 or 5.8 stock

**Comment by Tk-Glitch** [comment]
I have found https://bugzilla.kernel.org/show_bug.cgi?id=208141#c21 that seems to be related, with a possible fix attached, depending on your device id.

**Comment by nepnep1111** [comment]
That patch worked 👍
