### ISSUE TITLE
setting _staging_version in wine-tkg gets ignored

### ISSUE THREAD

**Issue by varris1** [Tk-Glitch/PKGBUILDS#578]
Hello,
I tried to set _staging_version to use wine-staging 5.5 because this is the last Wine version that works with the Star Citizen launcher.
Sadly it gets completely ignored and wine-tkg tries to build master regardless.

```# staging
_use_staging="true"
# staging commit or version tag if you want to use a specific staging version. Can use e.g. "7cfceb7", "v3.16" or "v4.0"
# Leave empty to use latest master - https://github.com/wine-staging/wine-staging/commits/master
_staging_version="v5.5"
```

`=> Making package: wine-tkg-staging-fsync-vkd3d-git 5.14.r10.g46420edc-295 (Sat 15 Aug 2020 03:28:47 PM CEST)`

**Comment by Tk-Glitch** [comment]
Makepkg will output that line way before the actual package name gets defined, so this will output what's in the PKGBUILD at the time, and not the actual version you'll end up with (`pkgver()` is called right after the whole patching step). Check your `last_build_config.log` to have the actual version strings of each trees.

**Comment by varris1** [comment]
ok, it seems to work. Sorry for the noise 🐸

When I tried to build it yesterday with the version set to 5.5, it wanted to use the hotpatcher and failed. I think you fixed it in the meantime.

**Comment by Tk-Glitch** [comment]
Something broke with a recently merged PR. Should be fine now indeed :)

**Comment by Tk-Glitch** [comment]
As a side note, I just updated SC to 3.10 and played for a few with no issue whatsoever on 5.15r1 (hotfixed).
