### ISSUE TITLE
Wine-Tkg failed to compile

### ISSUE THREAD

**Issue by mozo78** [Tk-Glitch/PKGBUILDS#580]
Hello, the latest code fail to compile for me. I compiled Wine-Tkg many times before without any problems but not this time.

Here's the log:

https://pastebin.com/BVk1rzcK

**Comment by Tk-Glitch** [comment]
Should be fixed with https://github.com/Frogging-Family/wine-tkg-git/commit/9b482267a082e23b2f35bf3556f1db083532a1d3

**Comment by mozo78** [comment]
Thank you but now there's a new error:
https://pastebin.com/C0M6dEta
