### ISSUE TITLE
PKGBUILDS are missing

### ISSUE THREAD

**Issue by mozo78** [Tk-Glitch/PKGBUILDS#581]
Hello,
When git clone the repo, the result is empty folders with no PKGBUILD files. The command is as always:

`git clone https://github.com/Tk-Glitch/PKGBUILDS.git`

**Comment by CodingKoopa** [comment]
Yes, the folders are all submodules. You must use the `--recurse-submodules` parameter to `git clone` in order to retrieve them. Since you have already cloned the repo, though, you can retrieve the submodules by running `git submodule update --init`. Cheers.

**Comment by mozo78** [comment]
Yes it's working with --recurse-submodules, thank you :)
I think it should be included in the how to. There's only git clone https://github.com/Tk-Glitch/PKGBUILDS.git and it doesn't work.

**Comment by CodingKoopa** [comment]
The [readme](https://github.com/Tk-Glitch/PKGBUILDS/blob/frogging-family/README.md) should already describe that process ;)

**Comment by mozo78** [comment]
Thanks :)
