### ISSUE TITLE
league of legends crash

### ISSUE THREAD

**Issue by greypeg** [Tk-Glitch/PKGBUILDS#582]
I click play on lutris then client opens i put my credentials and then a small black window pops up for 2-3 minutes and then the game stops.

My lutris logs:

lutris-wrapper: League of Legends
Running /home/greg/.local/share/lutris/runners/wine/lutris-lol-5.5-2-x86_64/bin/wine /home/greg/Games/league-of-legends/drive_c/Riot Games/League of Legends/LeagueClient.exe
Initial process has started with pid 1466
Game is considered started.
esync: up and running.
000b:fixme:winediag:start_process Wine TkG 5.5 is a testing version containing experimental patches.
000b:fixme:winediag:start_process Please don't report bugs about it on winehq.org and use https://github.com/Tk-Glitch/PKGBUILDS/issues instead.
0009:fixme:ntdll:NtQuerySystemInformation info_class SYSTEM_PERFORMANCE_INFORMATION
0009:fixme:ntdll:EtwEventRegister ({2f9efe86-4af7-4f37-a40f-94b909a157d6}, 0x5524e0, 0x18b53a0, 0x1944fc8) stub.
0009:fixme:ntdll:EtwEventRegister ({ea08c559-95a8-4aa2-afa6-18738eec6d37}, 0x5524e0, 0x18b5330, 0x1944f48) stub.
0009:fixme:ntdll:EtwEventRegister ({10f6728c-ef92-4bf1-8397-49e693a6eb74}, 0x5524e0, 0x18b5368, 0x1944f88) stub.
0009:fixme:ntdll:EtwEventRegister ({46dd7f96-60cb-416b-8085-da5cd8f491dd}, 0x5524e0, 0x18b53d8, 0x1945008) stub.
0009:fixme:msvcrt:MSVCRT__stdio_common_vsnprintf_s options 24 not handled
0009:fixme:msvcrt:MSVCRT__stdio_common_vsnprintf_s options 24 not handled
0009:fixme:msvcrt:__stdio_common_vsprintf options 25 not handled
0009:fixme:msvcrt:__stdio_common_vsprintf options 26 not handled
0009:fixme:msvcrt:MSVCRT__stdio_common_vsnprintf_s options 24 not handled

**Comment by Samega7Cattac** [comment]
that's by far not the full log

**Comment by Samega7Cattac** [comment]
it doesn't seem to be a crash since it exists with error code 0
it just doesn't start the launcher when finish loading league

**Comment by greypeg** [comment]
Sorry for not showing all the logs, it was just an infinite loop of "...24,25,26 not handled" and im new to manjaro. I tried every troubleshoot i was able to find but nothing worked.

**Comment by greypeg** [comment]
I got frustrated so I deleted lutris and league as well. I tried one month ago league install with snapd but it was buggy.

**Comment by greypeg** [comment]
the only solution that worked out somehow was the one that you delete the client folder of league, and you sing in with a client of older version, but you cant see your friends and friendlist and they cant see you ether.

**Comment by Samega7Cattac** [comment]
ur not the only one, seems it for happens to everyone some with a bit of luck still launches.
Same thing on https://github.com/Frogging-Family/wine-tkg-git/issues/59 is having issues with that

**Comment by IroAlexis** [comment]
This issue is much better here because we move away from the initial issue that I had opened up :+1:

**Comment by greypeg** [comment]
"Edit 2 : From time to time, the client stops working just after the LoL logo appears. Just restart it (several times ; it is very rare) and it will succeed in starting up. thinking But I have no idea if it's the compilation with mingw that's causing this and anyway I'm not sure" this happens to me with one exception, those restarts that i made never got me in to play just a loop of black little window -> league logo and the "stop" button on lutris turned to "play" automatically.

**Comment by greypeg** [comment]
So this is a new/recent thing for many people with this new particular patch??/

**Comment by IroAlexis** [comment]
> https://github.com/Frogging-Family/wine-tkg-git/issues/59#issuecomment-698482726

I am not sure that this comportement is good if it works

> So this is a new/recent thing for many people with this new particular patch??

it is since yesterday but I'm not sure it's related to the patch (not sure)

**Comment by greypeg** [comment]
i dont know if it matters but after i first installed league with lutris i was able to play for 10 hours. Then after 3 days this error started.

**Comment by IroAlexis** [comment]
Anyway you provided the logs, you just have to be patient to get a wine patch that will "fix" it all :frog:

**Comment by greypeg** [comment]
ok, 1)so how i can get notified for when this patch is coming?? 2)clearing everything and reinstall it do you think might be solution??
3)thanks for the info appreciate it!!

**Comment by Samega7Cattac** [comment]
> > [Frogging-Family/wine-tkg-git#59 (comment)](https://github.com/Frogging-Family/wine-tkg-git/issues/59#issuecomment-698482726)
> 
> I am not sure that this comportement is good if it works
like it's playable, and can be an hint idk this client is weird

**Comment by IroAlexis** [comment]
> so how i can get notified for when this patch is coming?

TkG will indicate that the issue has been solved by mentioning it in a commit

> clearing everything and reinstall it do you think might be solution?

I don't think but with the updates of Riot launcher, maybe we should reinstall everything

> thanks for the info appreciate it!

It is normal :frog:

**Comment by greypeg** [comment]
> > so how i can get notified for when this patch is coming?
> 
> TkG will indicate that the issue has been solved by mentioning it in a commit
> 
> > clearing everything and reinstall it do you think might be solution?
> 
> I don't think but with the updates of Riot launcher, maybe we should reinstall everything
> 
> > thanks for the info appreciate it!
> 
> It is normal frog

do you play or are you having the same issue?

**Comment by IroAlexis** [comment]
I have exactly the same issue. :(

**Comment by greypeg** [comment]
> I have exactly the same issue. :(

pff sad, well  then we are gonna wait. Im going to continue learning node.js and mongo db for the couple of weeks i suppose cause from the time i installed league again i kinda left them behind.

**Comment by Samega7Cattac** [comment]
> > clearing everything and reinstall it do you think might be solution?
> 
> I don't think but with the updates of Riot launcher, maybe we should reinstall everything

it's doesn't solve, already tried

**Comment by greypeg** [comment]
i tried to reinstall it, check my installation logs if that matters:

**Comment by greypeg** [comment]
https://paste.ubuntu.com/p/FHTrXs86kQ/

my installation logs right now..

**Comment by greypeg** [comment]
![Uploading image.png…]()

**Comment by greypeg** [comment]
![Uploading Screenshot_2020-09-30_13-55-07.png…]()

**Comment by greypeg** [comment]
0203:fixme:msvcrt:MSVCRT__stdio_common_vsnprintf_s options 24 not handled this line is spammed so hard

**Comment by greypeg** [comment]
> Apparently it looks like it's fixed [Frogging-Family/wine-tkg-git@9cfa91d](https://github.com/Frogging-Family/wine-tkg-git/commit/9cfa91d187d091d2e5eeb364f6574e7c4d937e09) frog

So what i have to do?
sudo pacman -Sy ??

**Comment by IroAlexis** [comment]
Ah ! I didn't see that you use Lutris. Just wait that Lutris publish an other build basd on this commit

**Comment by greypeg** [comment]
> Ah ! I didn't see that you use Lutris. Just wait that Lutris publish an other build based on this commit
ok I hope it wont take them long. Do you have a link though for me to install league like you did or do you think it is a messy process??

thank you very much by the way you've been very helpful my friend.

**Comment by Samega7Cattac** [comment]
it's not messy
u just need to compile wine-tgk-git from scratch and change ur game config to use that custom wine

**Comment by IroAlexis** [comment]
https://github.com/Frogging-Family/wine-tkg-git/pull/159#issuecomment-702720286
