### ISSUE TITLE
Validating files for linux54-tkg fails

### ISSUE THREAD

**Issue by random2324** [Tk-Glitch/PKGBUILDS#583]
Hello,
today I tried updating my Kernel, but fails to validate some files.

Running 'updpkgsums' resulted in a corrupted PKGBUILD. But removing those corrupted lines solved it.

Anyway here is the log:
`==> Making package: linux54-tkg-pds 5.4.72-91 (Sun Oct 25 16:21:53 2020)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Found linux-5.4.tar.xz
  -> Found patch-5.4.72.xz
  -> Downloading enable_additional_cpu_optimizations_for_gcc_v10.1%2B_kernel_v4.19-v5.4.patch...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 26892  100 26892    0     0   105k      0 --:--:-- --:--:-- --:--:--  105k
  -> Found config.x86_64
  -> Found config_hardened.x86_64
  -> Found 90-cleanup.hook
  -> Found cleanup
  -> Found 0001-add-sysctl-to-disallow-unprivileged-CLONE_NEWUSER-by.patch
  -> Found 0002-clear-patches.patch
  -> Found 0003-glitched-base.patch
  -> Found 0003-glitched-cfs.patch
  -> Found 0004-glitched-ondemand-muqss.patch
  -> Found 0004-glitched-muqss.patch
  -> Found 0004-5.4-ck1.patch
  -> Found 0005-glitched-ondemand-pds.patch
  -> Found 0005-glitched-pds.patch
  -> Found 0005-v5.4_undead-pds099o.patch
  -> Found 0006-add-acs-overrides_iommu.patch
  -> Found 0007-v5.4-fsync.patch
  -> Found 0009-glitched-bmq.patch
  -> Found 0009-bmq_v5.4-r2.patch
  -> Found 0011-ZFS-fix.patch
  -> Found 0012-linux-hardened.patch
==> Validating source files with sha256sums...
    linux-5.4.tar.xz ... Passed
    patch-5.4.72.xz ... Passed
    enable_additional_cpu_optimizations_for_gcc_v10.1%2B_kernel_v4.19-v5.4.patch ... Passed
    config.x86_64 ... FAILED
    config_hardened.x86_64 ... Passed
    90-cleanup.hook ... Passed
    cleanup ... Passed
    0001-add-sysctl-to-disallow-unprivileged-CLONE_NEWUSER-by.patch ... Passed
    0002-clear-patches.patch ... Passed
    0003-glitched-base.patch ... Passed
    0003-glitched-cfs.patch ... Passed
    0004-glitched-ondemand-muqss.patch ... Passed
    0004-glitched-muqss.patch ... Passed
    0004-5.4-ck1.patch ... Passed
    0005-glitched-ondemand-pds.patch ... Passed
    0005-glitched-pds.patch ... Passed
    0005-v5.4_undead-pds099o.patch ... Passed
    0006-add-acs-overrides_iommu.patch ... Passed
    0007-v5.4-fsync.patch ... Passed
    0009-glitched-bmq.patch ... Passed
    0009-bmq_v5.4-r2.patch ... Passed
    0011-ZFS-fix.patch ... Passed
    0012-linux-hardened.patch ... Passed
==> ERROR: One or more files did not pass the validity check!
  -> exit cleanup done
`

**Comment by Tk-Glitch** [comment]
I have just checked. `config.x86_64`'s correct sha256 is `55dd5117c1da17c9ec38d7bc995958958bcc8b7ebcfd81de1d4c7650b85537ab`, which is what's in the PKGBUILD. Either your config is corrupted or it's been tempered with.

**Comment by random2324** [comment]
Yes, sorry for the noise!!! Now that I see its the config file, you're correct, I did something stupid....

**Comment by Tk-Glitch** [comment]
In case you didn't know, you can create custom entries/values in your config by using the fragment system (more details about this in the customization.cfg file, near the end).
