### ISSUE TITLE
Possibility to run clang build of Linux419 kernel

### ISSUE THREAD

**Issue by XeonDead** [Tk-Glitch/PKGBUILDS#59]
Is it possible to you to add the patches to allow kernel to be built with clang?

The guide itself is located at https://github.com/ClangBuiltLinux/linux/wiki/Steps-for-compiling-the-kernel-with-Clang
The guide itself misses a step described in:
https://github.com/ClangBuiltLinux/linux/issues/276
It misses a step about having to bring two patches with us:
https://github.com/ClangBuiltLinux/continuous-integration/tree/master/patches/4.19/x86_64

That should be it, I'm currently running the build. Will tell if it boots ;-)

**Comment by XeonDead** [comment]
Okay, never mind, that did not quite boot.
However, if anyone wants to continue this, feel free to.

**Comment by Tk-Glitch** [comment]
asm goto support missing from clang as of now sounds like x86_64 won't work at this point indeed. This might land in LLVM 8 at some point though.
