### ISSUE TITLE
Add "dxvk-async" patch?!

### ISSUE THREAD

**Issue by tr37ion** [Tk-Glitch/PKGBUILDS#590]
I'm not sure if its already added, but there seems to be a new patch which improves game performance for some games like Guild Wars 2. Maybe you can add it optionally: https://github.com/Sporif/dxvk-async

**Comment by Tk-Glitch** [comment]
It is already available through dxvk-tools: https://github.com/Frogging-Family/dxvk-tools/blob/645c99348e064c792018d78ad4d3bee4b1a23420/updxvk.cfg#L47

**Comment by Tk-Glitch** [comment]
Closing.
