### ISSUE TITLE
nvidia-all - latest arch kernel returns error 10 with tkg 450+ version drivers

### ISSUE THREAD

**Issue by IvoAndonov** [Tk-Glitch/PKGBUILDS#591]
Quite a few people said the new kernel (5.10.x) installs without any problems with 450+ driver version of nvidia. But for me (I'm using 450.57 tkg) no driver newer than that would work with kernel 5.10.3. I know I have to run sudo mkinitcpio -P after driver update but that doesn't help either - after all the modules are loaded, I get only black screen with a quickly blinking underscore cursor and that's it. I tried installing only 5.10.3 kernel - same result. 5.10.3 with the official arch repo nvidia driver (which for the moment is 455.45.01 or something) - same result. Only the official repo driver with my current kernel (5.9.14) - same result.
Any ideas what is going on here and how to fix it? I'm not a programmer, so writing/editing scripts is Greek to me.
I can provide the output of any command, if requested.
If it matters in the case, the video card is GTX 1660 Ti.

**Comment by Tk-Glitch** [comment]
Apparently 5.10.4 has broken nvidia drivers. I believe it's been resolved since, at least for the most part. I'll attempt to get access to some nvidia hardware to test.

**Comment by IvoAndonov** [comment]
> Apparently 5.10.4 has broken nvidia drivers. I believe it's been resolved since, at least for the most part. I'll attempt to get access to some nvidia hardware to test.

Did you manage to test it? Or at least to confirm 5.10.x has been fixed to work with version 450?
