### ISSUE TITLE
cant build proton-tkg

### ISSUE THREAD

**Issue by damachine** [Tk-Glitch/PKGBUILDS#592]
Hello building proton stop. i can put a few last posts: 

...
Installing /EXTRA/TRANSFER/.git-master/tkg-master/wine-tkg-git/proton-tkg/external-ressources/dxvk-tools/dxvk-master/src/dxvk_config/dxvk_config.h to /EXTRA/TRANSFER/.git-master/tkg-master/wine-tkg-git/proton-tkg/external-ressources/dxvk-tools/DXVKBUILD/dxvk-master/include/dxvk
Datei umbenannt '../DXVKBUILD/dxvk-master/x32' -> '../DXVKBUILD/master/0eec95843fd169a3b4bcf85680380d6de305826c-2021-01-08-17:42:44/x32'
Datei umbenannt '../DXVKBUILD/dxvk-master/x64' -> '../DXVKBUILD/master/0eec95843fd169a3b4bcf85680380d6de305826c-2021-01-08-17:42:44/x64'
Your files were built in /EXTRA/TRANSFER/.git-master/tkg-master/wine-tkg-git/proton-tkg/dxvk-tools/DXVKBUILD/master/0eec95843fd169a3b4bcf85680380d6de305826c-2021-01-08-17:42:44

real    5m11,092s
user    32m58,051s
sys     2m44,906s

exit cleanup done
       .---.`               `.---.
    `/syhhhyso-           -osyhhhys/`
   .syNMdhNNhss/``.---.``/sshNNhdMNys.
   +sdMh.`+MNsssssssssssssssNM+`.hMds+
   :syNNdhNNhssssssssssssssshNNhdNNys:
    /ssyhhhysssssssssssssssssyhhhyss/
    .ossssssssssssssssssssssssssssso.
   :sssssssssssssssssssssssssssssssss:
  /sssssssssssssssssssssssssssssssssss/
 :sssssssssssssoosssssssoosssssssssssss:
 osssssssssssssoosssssssoossssssssssssso
 osssssssssssyyyyhhhhhhhyyyyssssssssssso
 /yyyyyyhhdmmmmNNNNNNNNNNNmmmmdhhyyyyyy/
  smmmNNNNNNNNNNNNNNNNNNNNNNNNNNNNNmmms
   /dNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNd/
    `:sdNNNNNNNNNNNNNNNNNNNNNNNNNds:`
       `-+shdNNNNNNNNNNNNNNNdhs+-`
             `.-:///////:-.`

'./DXVKBUILD/master/0eec95843fd169a3b4bcf85680380d6de305826c-2021-01-08-17:42:44/x64/d3d10_1.dll' -> '../dxvk/x64/d3d10_1.dll'
'./DXVKBUILD/master/0eec95843fd169a3b4bcf85680380d6de305826c-2021-01-08-17:42:44/x64/d3d10core.dll' -> '../dxvk/x64/d3d10core.dll'
'./DXVKBUILD/master/0eec95843fd169a3b4bcf85680380d6de305826c-2021-01-08-17:42:44/x64/d3d10.dll' -> '../dxvk/x64/d3d10.dll'
'./DXVKBUILD/master/0eec95843fd169a3b4bcf85680380d6de305826c-2021-01-08-17:42:44/x64/d3d11.dll' -> '../dxvk/x64/d3d11.dll'
'./DXVKBUILD/master/0eec95843fd169a3b4bcf85680380d6de305826c-2021-01-08-17:42:44/x64/d3d9.dll' -> '../dxvk/x64/d3d9.dll'
'./DXVKBUILD/master/0eec95843fd169a3b4bcf85680380d6de305826c-2021-01-08-17:42:44/x64/dxgi.dll' -> '../dxvk/x64/dxgi.dll'
'./DXVKBUILD/master/0eec95843fd169a3b4bcf85680380d6de305826c-2021-01-08-17:42:44/x64/dxvk_config.dll' -> '../dxvk/x64/dxvk_config.dll'
'./DXVKBUILD/master/0eec95843fd169a3b4bcf85680380d6de305826c-2021-01-08-17:42:44/x64/setup_symlink_dxvk.sh' -> '../dxvk/x64/setup_symlink_dxvk.sh'
'./DXVKBUILD/master/0eec95843fd169a3b4bcf85680380d6de305826c-2021-01-08-17:42:44/x32/d3d10_1.dll' -> '../dxvk/x32/d3d10_1.dll'
'./DXVKBUILD/master/0eec95843fd169a3b4bcf85680380d6de305826c-2021-01-08-17:42:44/x32/d3d10core.dll' -> '../dxvk/x32/d3d10core.dll'
'./DXVKBUILD/master/0eec95843fd169a3b4bcf85680380d6de305826c-2021-01-08-17:42:44/x32/d3d10.dll' -> '../dxvk/x32/d3d10.dll'
'./DXVKBUILD/master/0eec95843fd169a3b4bcf85680380d6de305826c-2021-01-08-17:42:44/x32/d3d11.dll' -> '../dxvk/x32/d3d11.dll'
'./DXVKBUILD/master/0eec95843fd169a3b4bcf85680380d6de305826c-2021-01-08-17:42:44/x32/d3d9.dll' -> '../dxvk/x32/d3d9.dll'
'./DXVKBUILD/master/0eec95843fd169a3b4bcf85680380d6de305826c-2021-01-08-17:42:44/x32/dxgi.dll' -> '../dxvk/x32/dxgi.dll'
'./DXVKBUILD/master/0eec95843fd169a3b4bcf85680380d6de305826c-2021-01-08-17:42:44/x32/dxvk_config.dll' -> '../dxvk/x32/dxvk_config.dll'
'./DXVKBUILD/master/0eec95843fd169a3b4bcf85680380d6de305826c-2021-01-08-17:42:44/x32/setup_symlink_dxvk.sh' -> '../dxvk/x32/setup_symlink_dxvk.sh'

###############################################################

This DXVK build will be integrated to your next Proton-tkg build

###############################################################

exit cleanup done
'dxvk/x64/d3d10core.dll' -> 'proton_dist_tmp/lib64/wine/dxvk/d3d10core.dll'
'dxvk/x64/d3d11.dll' -> 'proton_dist_tmp/lib64/wine/dxvk/d3d11.dll'
'dxvk/x64/d3d9.dll' -> 'proton_dist_tmp/lib64/wine/dxvk/d3d9.dll'
'dxvk/x64/dxgi.dll' -> 'proton_dist_tmp/lib64/wine/dxvk/dxgi.dll'
'dxvk/x32/d3d10core.dll' -> 'proton_dist_tmp/lib/wine/dxvk/d3d10core.dll'
'dxvk/x32/d3d11.dll' -> 'proton_dist_tmp/lib/wine/dxvk/d3d11.dll'
'dxvk/x32/d3d9.dll' -> 'proton_dist_tmp/lib/wine/dxvk/d3d9.dll'
'dxvk/x32/dxgi.dll' -> 'proton_dist_tmp/lib/wine/dxvk/dxgi.dll'
'dxvk/x64/dxvk_config.dll' -> 'proton_dist_tmp/lib64/wine/dxvk/dxvk_config.dll'
'dxvk/x32/dxvk_config.dll' -> 'proton_dist_tmp/lib/wine/dxvk/dxvk_config.dll'

and nothing more happens and building stops. in htop i see a wget -qi task when i terminat this task ./proton.sh stop too.
sorry my english hope some can help.

**Comment by Tk-Glitch** [comment]
wget is used at that step to grab gecko. It's possible winehq servers were being slow (they are more often than not) or even timed out at the time you attempted building.
Are you able to download from there? -> https://dl.winehq.org/wine/wine-gecko/2.47.2/

**Comment by damachine** [comment]
Issus can be solved last build works thanks.
