### ISSUE TITLE
[mesa-tkg-git] GTA V through lutris fails using radeon vulkan loader.

### ISSUE THREAD

**Issue by FabioSedia** [Tk-Glitch/PKGBUILDS#593]
I want to play gta v through lutris (rockstar launcher version) When using the radeon icd loader i get the "unable to find dx 11 adapter" error. I'm forced to select the amdvlk icd loader. Performance is fine, but shader compilation is long and causes a lot of stutter. If I want to use the radeon icd loader, i have to uninstall mesa-tkg-git to install mesa and vulkan-radeon. Maybe it's my system's fault, maybe not. Additional informations needed? I would like to play with radeon driver as it's faster when compiling shaders

**Comment by flgx16** [comment]
AMDVLK added a layer which filters out RADV unless explicitely set with their env variable (`DISABLE_LAYER_AMD_SWITCHABLE_GRAPHICS_1=1` I think). Simple solution is to uninstall AMDVLK.

**Comment by FabioSedia** [comment]
> AMDVLK added a layer which filters out RADV unless explicitely set with their env variable (`DISABLE_LAYER_AMD_SWITCHABLE_GRAPHICS_1=1` I think). Simple solution is to uninstall AMDVLK.

This worked. Is this affecting my steam proton games too? Should I expect a different performance now that I deleted amdvlk and radv is "unlocked"?

**Comment by flgx16** [comment]
> Is this affecting my steam proton games too?
Yes

> Should I expect a different performance now that I deleted amdvlk and radv is "unlocked"?
Well, RADV is better & faster in most cases so yes

**Comment by FabioSedia** [comment]
> > Is this affecting my steam proton games too?
> 
> Yes
> 
> > Should I expect a different performance now that I deleted amdvlk and radv is "unlocked"?
> 
> Well, RADV is better & faster in most cases so yes

Just to clarify and learn, and then I'll close the issue. Before the amdvlk uninstallation all my games were using it?

**Comment by flgx16** [comment]
> Just to clarify and learn, and then I'll close the issue. Before the amdvlk uninstallation all my games were using it?

As far as I know, yes, all vulkan games since they added the layer a week ago or so (and I think AMDVLK was the default even without the layer if installed?)
