### ISSUE TITLE
Can't build last 4.19 kernel commit

### ISSUE THREAD

**Issue by JDC2389** [Tk-Glitch/PKGBUILDS#62]
Hunk #1 succeeded at 129 (offset 3 lines).
Hunk #2 succeeded at 302 (offset 3 lines).
Hunk #3 succeeded at 319 (offset 3 lines).
Hunk #4 succeeded at 474 (offset 3 lines).
Hunk #5 succeeded at 1049 (offset 12 lines).
patching file kernel/time/posix-cpu-timers.c
patching file kernel/trace/trace_selftest.c
patching file drivers/cpufreq/cpufreq_ondemand.c
patching file kernel/Kconfig.hz
patching file mm/vmscan.c
patching file kernel/sched/pds.c
Hunk #1 FAILED at 118.
1 out of 1 hunk FAILED -- saving rejects to file kernel/sched/pds.c.rej
==> ERROR: A failure occurred in prepare().
    Aborting...
  -> exit cleanup done
[carbon@carbon-pc linux419-tkg]$

**Comment by Tk-Glitch** [comment]
Thanks for your report. Fixed in https://github.com/Tk-Glitch/PKGBUILDS/commit/2c62cf36cb30789554e1276519c6fbc242e16852

**Comment by JDC2389** [comment]
danke
