### ISSUE TITLE
PDS kernels make games crash w/ Gamemode?

### ISSUE THREAD

**Issue by Sukid** [Tk-Glitch/PKGBUILDS#67]
Hi. I haven't tried the special 4.19 kernel yet, but a while back due to the ext4 corruption bug (or rather, fear of it) I installed the 4.18 kernel with PDS and noticed any games I played with Feral Gamemode injected would either blackscreen, crash, or freeze the entire system. When I didn't inject gamemode it seemed fine for the most part (although alt tabbing out of Doom made it freeze uncrecoverably).

Just wondering if anyone else has had this issue or it makes sense as to why it would happen. I tried making sure I had all the safe settings for the kernel otherwise when prompted.

**Comment by Tk-Glitch** [comment]
I remember I've had issues with the task priority enforced by gamemode, that would reduce performance to a crawl and eventually end up crashing. At the time I simply disabled that part and it worked just fine. Then I noticed after a bunch of benchmarks it was not helping performance in any way or form on my system, but well that's another story. It might be working fine on 4.19, there has been quite a few changes on the scheduler front. Also, 4.19.8 has fixed the ext4 corruption issue (that was only happening with enforced no I/O sched set btw), so you can probably give it a spin :smiley:

**Comment by Sukid** [comment]
Aah I was glad when that happened. Alrighty! Thanks for the info
