### ISSUE TITLE
Linux 4.19.8 Released With BLK-MQ Fix To The Recent Data Corruption Bug

### ISSUE THREAD

**Issue by ryanmusante** [Tk-Glitch/PKGBUILDS#68]
I've been using 4.19 tkg build (PDS) with BLK-MQ deadline  on my drives. Is it correct to say that with that configuration, it was never affected by the bug? 

https://www.phoronix.com/scan.php?page=news_item&px=Linux-4.19.8-Released

**Comment by Tk-Glitch** [comment]
Considering the bug only affected machines using no I/O scheduler, yes indeed you weren't affected.

**Comment by ryanmusante** [comment]
Good to know.
