### ISSUE TITLE
A request for Faudio

### ISSUE THREAD

**Issue by ahmed-elsayed2017** [Tk-Glitch/PKGBUILDS#72]
There is a Wine fork with Faudio included.
https://github.com/flibitijibibo/wine

But this fork doesn't contain Esync. Could you make install scripts for this fork for Arch with Esync and TKG patches?

**Comment by Tk-Glitch** [comment]
I'm already offering Faudio as an option in wine-tkg.

**Comment by ahmed-elsayed2017** [comment]
Great! I will install it now. Thanks man.

**Comment by Tk-Glitch** [comment]
My pleasure :)
