### ISSUE TITLE
[Request] linux420-tkg

### ISSUE THREAD

**Issue by clapbr** [Tk-Glitch/PKGBUILDS#81]
Self explanatory. Now that 4.20 was released I'd be awesome to have it with your awesome optimizations. The frogs are spoiled af :)

**Comment by clapbr** [comment]
MuQSS officially ready for 4.20 http://ck-hack.blogspot.com/2018/12/linux-420-ck1-muqss-version-0185-for.html

**Comment by Tk-Glitch** [comment]
Memory management breaking down slowly up to a panic. Works fine on my C2D laptop and on both Zen and IvyBridge user rigs. It seems to be specific to my Coffeelake setup and I couldn't figure it out so far.
