### ISSUE TITLE
Esync wine-tkg-git nofile settings with systemd 420

### ISSUE THREAD

**Issue by ryanmusante** [Tk-Glitch/PKGBUILDS#82]
_https://github.com/lutris/lutris/wiki/How-to:-Esync_

For recommendations by lutris wiki, it states to set soft and hard limits for nofile.
```
 username soft nofile 1048576
 username hard nofile 1048576
```
_https://github.com/systemd/systemd/blob/master/NEWS_

Systemd 420 states that numbers have been changed,  but is the previous recommendation now nullified?

```
With this systemd release the hard limit
          systemd passes on is increased to 512K, overriding the kernel's
          defaults and substantially increasing the number of simultaneous file
          descriptors unprivileged userspace processes can allocate.
```
There are reports of problems with settings into the 1G limit

```
Note that there are also reports that using very
          high hard limits (e.g. 1G) is problematic: some software allocates
          large arrays with one element for each potential file descriptor
          (Java, …) — a high hard limit thus triggers excessively large memory
          allocations in these applications. Hopefully, the new default of 512K
          is a good middle ground: higher than what real-life applications
          currently need, and low enough for avoid triggering excessively large
          allocations in problematic software.
```

**Comment by neVERberleRfellerER** [comment]
By the way, linked recommendations seem untrustworthy to me. I am on Archlinux and merely seting
username hard nofile 1048576
in
/etc/security/limits.d/50-user-nofile.conf
worked fine:
ulimit -Hn returns 1048576
I have checked that I have nothing but comments in user.conf/system.conf and I am not aware of other ways to set it.  I am using this setup for very long time, starting before esync became a thing, so unless Archlinux changed the limits at exatly the same time I created 50-user-nofile.conf, statements about systemd are wrong.

**Comment by Wuestengecko** [comment]
[ArchWiki](https://wiki.archlinux.org/index.php/Limits.conf) says:
> **Note:** `/etc/security/limits.conf` does not work if systemd exists.

The `limits.conf` is applied by the `pam_limits` module, which is enabled by default on Arch. However - my point of confusion - if you only set the hard limit in `limits.conf`, it will only change the hard limit. I checked with `limit`, and saw 1024 as the (soft) limit on file descriptors, and assumed it didn't work.

**Comment by neVERberleRfellerER** [comment]
Well, that's quite interesting. So to summarize:
- ArchWiki is wrong with "does not work if systemd exists" because pam_limits will actually apply limits.conf,
- Lutris wiki is wrong, because they explicitly mention Arch Linux but what they say does not actually apply to Arch Linux.
- Lutris Wiki is requesting change of global RLIMIT_NOFILE soft limit for no reason because wine will change soft limit by setrlimit call and even official esync readme does not say anything about soft limit (because it's not necessary).

**Comment by ryanmusante** [comment]
Apparently, the best information is stated here in esync's readme.

https://github.com/zfigura/wine/blob/esync/README.esync

**Comment by Wuestengecko** [comment]
Right. The Lutris wiki is missing that bit though.

Everything that's running under Wine is a client to the wineserver, so yes, Steam is a client too.

**Comment by Tk-Glitch** [comment]
As long as you're not trying to run multiple wine instances with different esync parameters you're fine.

**Comment by Tk-Glitch** [comment]
Closing this. The discussion has moved to lutris and documentation was fixed, so I guess it's fine :)
