### ISSUE TITLE
winetricks fails to install vcrun2015 dotnet35

### ISSUE THREAD

**Issue by ryanmusante** [Tk-Glitch/PKGBUILDS#83]
Error on installation of vcrun2015 
. Also failure to install dotnet35. 

Note: attempt was tried first before installing vcrun2017 ultimately. 

![vcrun2015](https://user-images.githubusercontent.com/26808646/50543384-9e896c00-0c1a-11e9-8351-5f52d517d768.png)

However, _vcrun2017_ appears to have the same DLLs so is this a suitable workaround for software that specifically states that it needs _vcrun2015_ in the description?

![selection](https://user-images.githubusercontent.com/26808646/50543385-a34e2000-0c1a-11e9-9915-f7ed77bf5c2e.png)

**Comment by Tk-Glitch** [comment]
Isn't that supposed to be installed in quiet mode though? Vcrun2017 libs may work, but that sounds vastly app dependent.

**Comment by ryanmusante** [comment]
vcrun2017 is a suitable replacement for vcrun2016. However, I still have issues with dotnet35.

```
Note: command load_dotnet35  returned status 67. Aborting.
```
![screenshot from 2018-12-31 09-32-59](https://user-images.githubusercontent.com/26808646/50552833-541df300-0cdf-11e9-96c4-59a3e53251c0.png)

**Comment by Tk-Glitch** [comment]
I don't know about having them both working in the same prefix, sorry. But, again, I have high doubts this is installing correctly from the GUI.

**Comment by ryanmusante** [comment]
Quiet mode worked for vcrun2015. On a clean prefix dotnet35 worked from -q also.
