### ISSUE TITLE
Question about extra modules for custom kernel

### ISSUE THREAD

**Issue by Taraluktus** [Tk-Glitch/PKGBUILDS#85]
Maybe a dumb question, but couldn't find an answer at https://wiki.archlinux.org/index.php/Kernel/Arch_Build_System

How do I add extra modules like 'r8168' (for my Realtek NIC)?
Building and booting the custom linux420-tkg kernel went fine, but /lib/modules/extramodules-4.20-tkg... is empty (except from 'version'), so no network is available.

**Comment by XeonDead** [comment]
You might be good enough with installing the DKMS package of said module (it is available in AUR).
Module will be automatically built against headers you have and you will have it available in the modules dir.

**Comment by Taraluktus** [comment]
Thanks, that worked!
