### ISSUE TITLE
nvidia-persistenced recommendation

### ISSUE THREAD

**Issue by ryanmusante** [Tk-Glitch/PKGBUILDS#9]
On the "nvidia-utils-tkg.install", there is a configuration for nvidia-persistenced. I use Nvidia PRIME SYNC on a laptop with kenel opts: nvidia-drm.modeset=1. 

Is the persistence daemon even necessaary for my case?

**Comment by Tk-Glitch** [comment]
I don't exactly know how prime sync handles the persistence daemon (as nobody around me is using prime nor do I) but unless there's a bug, I don't see why they would interfere.
The daemon should be sleeping, waiting for the nvidia gpu device files to be opened when using the Intel GPU. The "legacy" kernel mode persistence won't be used unless the persistence daemon is broken for some reason.

**Comment by ryanmusante** [comment]
OK, my setup is not typical as I'm using laptop with PRIME SYNC, TLP disabled, OC'd video card, battery removed and power management set to performance.
