### ISSUE TITLE
trying to build kernel 4.20 blazeit

### ISSUE THREAD

**Issue by JDC2389** [Tk-Glitch/PKGBUILDS#97]
![image](https://user-images.githubusercontent.com/2825701/51581701-029bfa80-1e7e-11e9-8d69-b2ada769b740.png)

**Comment by JDC2389** [comment]
I think we really need a mirror system setup, because these official servers are wack asf slow downloads and now they're breaking.

**Comment by Tk-Glitch** [comment]
This is not an error from me though. I'd call your ISP. It took me 6 seconds.
![screenshot_20190123_045405](https://user-images.githubusercontent.com/741977/51582132-02761c00-1ecb-11e9-89d2-43269c6a1f11.png)

**Comment by Tk-Glitch** [comment]
Routing issue maybe?

**Comment by JDC2389** [comment]
Odd, I'm using cloudflare dns, 
![image](https://user-images.githubusercontent.com/2825701/51582385-b1d9d100-1e80-11e9-9d46-b47851a28627.png)  
![image](https://user-images.githubusercontent.com/2825701/51582437-e0f04280-1e80-11e9-8d2c-f4d8d0ba583b.png) I'll try a router restart and report back.

**Comment by Tk-Glitch** [comment]
Definitely odd indeed. Curl frogged again? :frog:

**Comment by Tk-Glitch** [comment]
I'm glad you got that fixed. I know how infuriating such thing can be at times :smile:
