### ISSUE TITLE
Make dependencies aren't removed despite specifying --rmdeps with makepkg

### ISSUE THREAD

**Issue by Sporif** [Tk-Glitch/PKGBUILDS#98]
Because an exit trap is included in certain PKGBUILDs the `clean_up` function inside makepkg ([line 131](https://git.archlinux.org/pacman.git/tree/scripts/makepkg.sh.in?h=release/5.1.x#n131)) is not called. However the function `remove_deps` ([line 315](https://git.archlinux.org/pacman.git/tree/scripts/makepkg.sh.in?h=release/5.1.x#n315)) is called at the [end of `clean_up`](https://git.archlinux.org/pacman.git/tree/scripts/makepkg.sh.in?h=release/5.1.x#n179). So `remove_deps` needs to be added to those PKGBUILDs' exit functions to allow the `--rmdeps` parameter to work. I've tested it out and it does work if you add the function.

Affected packages: 

gst-libav
linux419-tkg
linux420-tkg
nvidia-all
wine-tkg-git

**Comment by Tk-Glitch** [comment]
Good catch! Thanks :+1:
